### ISSUE TITLE
PNG圖示無法正常預覽 部分Adobe檔案無法正常顯示圖示

### ISSUE THREAD

**Issue by aunight** [zhuxb711/RX-Explorer#10]
![image](https://user-images.githubusercontent.com/52199445/89038495-095cd500-d373-11ea-8143-9ad58cbe8186.png)
![image](https://user-images.githubusercontent.com/52199445/89038601-4032eb00-d373-11ea-9896-e6a1c5362ef4.png)
Premiere Pro XD正常
其他部份建議
可使用ctrl+滾輪 更改預覽模式
文件排序除了詳細列表外都無法改動 希望能做優化
shift+刪除可以直接永久刪除
新建文件夾後可以直接重新命名
可以預覽svg文件
可更改需要系統管理員權限的文件夾
大文件背景刪除

**Comment by zhuxb711** [comment]
您截图时看到的图标是默认图标。
那么默认图标什么时候会出现呢？当RX文件管理器无法在规定的时间内获取到缩略图的时候。
因此部分文件显示默认文件仅代表此次无法正确获取到缩略图。

> 可使用ctrl+滾輪 更改預覽模式
> 文件排序除了詳細列表外都無法改動 希望能做優化
> shift+刪除可以直接永久刪除

以上是可以确定正在尝试实现的内容

**Comment by aunight** [comment]
某些圖片跟檔案是無法正常顯示的
但系統的文件管理器是正常的

**Comment by zhuxb711** [comment]
RX的文件缩略图均由UWP的文件系统API提供，因此该问题应该是由于微软的相关API返回“空内容”导致的，目前应该无法缓解...Sorry

**Comment by aunight** [comment]
好吧GG
