### ISSUE TITLE
Install.ps1 安装出错

### ISSUE THREAD

**Issue by blackAzrael** [zhuxb711/RX-Explorer#100]
PS E:\Package_5.9.7.0_SideLoadPackage> .\Install.ps1
找到了捆绑: E:\Package_5.9.7.0_SideLoadPackage\Package_5.9.7.0_x86_x64_ARM.msixbundle

正在安装应用程序...
找到依赖项包:
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x86\Microsoft.UI.Xaml.2.5.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x64\Microsoft.UI.Xaml.2.5.appx
E:\Package_5.9.7.0_SideLoadPackage\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx

Add-AppxPackage: E:\Package_5.9.7.0_SideLoadPackage\Add-AppDevPackage.ps1:487
Line |
 487 |              Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep …
     |              ~~~~~~~~~~~~~~~
     | The 'Add-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For
     | more information, run 'Import-Module Appx'.

错误: 未能安装应用程序。
Press Enter to continue...:

**Comment by zhuxb711** [comment]
此问题可能是由于Appx文件损坏导致的，请重新下载安装包（当然也可能是Add-AppxPackage命令本身有什么问题）

**Comment by blackAzrael** [comment]
PS E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage> .\Install.ps1
找到了捆绑: E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Package_6.0.0.0_x86_x64_ARM.msixbundle

正在安装应用程序...
找到依赖项包:
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x86\Microsoft.UI.Xaml.2.5.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x64\Microsoft.UI.Xaml.2.5.appx
E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx

Add-AppxPackage: E:\RX-Explorer\Package_6.0.0.0_SideLoadPackage\Add-AppDevPackage.ps1:487
Line |
 487 |              Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep …
     |              ~~~~~~~~~~~~~~~
     | The 'Add-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For
     | more information, run 'Import-Module Appx'.

错误: 未能安装应用程序。
Press Enter to continue...:

### 6.0版本安装也有同样的问题

**Comment by zhuxb711** [comment]
那说明不是安装包的问题咯
请通过应用商店下载
