### ISSUE TITLE
【功能请求】请问将来是否考虑加强对onedrive的支持

### ISSUE THREAD

**Issue by HydrogenDeuterium** [zhuxb711/RX-Explorer#101]
在explorer中可以看到在onedrive中的文件和文件夹状态（脱机可用，仅联网可用等等），还可以在右键菜单中设置（调整状态，释放空间等等）。

请问将来是否考虑添加这些功能？

**Comment by Sayor0630** [comment]
Yes, you are right. Pls, Do this!! I also want this!

**Comment by zhuxb711** [comment]
> 在explorer中可以看到在onedrive中的文件和文件夹状态（脱机可用，仅联网可用等等）
在最新版本的属性-详细信息中可以看到，但目前尚未有计划更改文件显示界面以直接展示其状态

> 还可以在右键菜单中设置（调整状态，释放空间等等）
在最新版本中的右键菜单已经支持

**Comment by zhuxb711** [comment]
OneDrive状态图标将于6.5.4版本中提供

**Comment by zhuxb711** [comment]
6.5.5已发布
