### ISSUE TITLE
文件夹右键显示不全

### ISSUE THREAD

**Issue by 1091515459** [zhuxb711/RX-Explorer#102]
![image](https://user-images.githubusercontent.com/33256117/106706471-b833e380-662a-11eb-9eea-836af1c34c69.png)
![image](https://user-images.githubusercontent.com/33256117/106706573-d568b200-662a-11eb-929e-e87778b3773c.png)

**Comment by Sayor0630** [comment]
I didn't understand your problem

**Comment by zhuxb711** [comment]
老问题了，暂时还没有解决方案

**Comment by Sayor0630** [comment]
> Old problem, there is no solution for the time being

Can't you fix it? We are all facing this problem! Please, try to fix this problem!

**Comment by zhuxb711** [comment]
将于下一个版本修复此问题

**Comment by zhuxb711** [comment]
将于下一个版本修复此问题

**Comment by Sayor0630** [comment]
Thank you very very much!
