### ISSUE TITLE
Office快捷方式问题

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#103]
我的office的快捷方式的目标路径是"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"，但在RX中是C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE，这个路径是错的，希望修复。

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/106827916-44deb000-66c4-11eb-9c08-fcf14f7e2812.png)

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/106827929-4b6d2780-66c4-11eb-9608-9514cc55aff1.png)

**Comment by XSH-Hero** [comment]
就像这样

**Comment by zhuxb711** [comment]
此问题由Windows自作聪明导致，X86应用运行于X64系统上时，若访问Program Files，则会自动重定向至Program Files(x86)，快捷方式也是如此，因此它被强制重定向且无法更改。针对此问题，我已取消“首选32位应用程序”来尽可能确保在X64系统上以X64模式运行来解决此问题

**Comment by zhuxb711** [comment]
6.0.1版本已发布
