### ISSUE TITLE
辅助进程(Fulltrustprocess.exe)问题

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#104]
更新最新版本后，进入桌面时图标加载变慢，且后台出现大量的“Fulltrustprocess.exe”的进程

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/107002046-a3d81e00-67c5-11eb-9fac-73227fb7490a.png)

**Comment by zhuxb711** [comment]
辅助进程调度器问题，已于6.0.1中解决。
(你issue提太快我忙不过来的😂)
