### ISSUE TITLE
指向UWP的快捷方式

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#105]
RX在打开指向UWP应用的快捷方式时报错

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/107002347-10531d00-67c6-11eb-9f9f-def60ce13501.png)

**Comment by XSH-Hero** [comment]
打开选中的“哔哩哔哩动画UWP.lnk”时报错

**Comment by zhuxb711** [comment]
UWP 的lnk文件似乎不遵守相关规范，因此无法获取到其所对应的UWP应用

**Comment by XSH-Hero** [comment]
不过我看Files似乎可以打开，可以看看他们怎么做的

**Comment by oxygen-dioxide** [comment]
不仅UWP，从商店安装的win32应用快捷方式也打不开（例如 wiznote lite），edge浏览器创建的pwa快捷方式也打不开（但chrome创建的pwa快捷方式可以打开）

**Comment by zhuxb711** [comment]
看不懂Files~他那个是超级裹蒸粽来的
@silentmoon 有没有兴趣？

**Comment by zhuxb711** [comment]
[看这里](https://github.com/zhuxb711/RX-Explorer/issues/106#issuecomment-775756740)

**Comment by XSH-Hero** [comment]
针不戳，效率挺高
