### ISSUE TITLE
RX-Explorer can't open shortcuts

### ISSUE THREAD

**Issue by Sayor0630** [zhuxb711/RX-Explorer#106]
When I try to open any shortcut(.ink), RX-Explorer shows an error that says "Unable to locate the path: Unknown". Here is a screenshot:-
![image](https://user-images.githubusercontent.com/77576588/107020822-873fe400-67cd-11eb-8ce7-8f8f690b912e.png)

**Comment by zhuxb711** [comment]
Sorry, uwp 's lnk is not supported by RX-Explorer for the time being

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/107311407-41369900-6ac9-11eb-9b7b-f620d4a3e16d.png)
大致看了下,它是在这里专门去查了文件图标的.
然后它打开文件是直接调用win32api打开的.

**Comment by zhuxb711** [comment]
@silentmoooon 它这个不是获取IconOverlay的吗？就是说获取快捷方式上面的小箭头

**Comment by zhuxb711** [comment]
Ok我懂了

**Comment by silentmoooon** [comment]
打开文件要不也改成调用系统方式打开?

**Comment by zhuxb711** [comment]
Haha，搞定了，比Files的还要好。在Files中如果你打开这种文件的属性，切换属性里面的标签页的话，就会崩溃~
RX的实现原理与Files并不同并且相比Files，获取的图标没有底色
![Untitled](https://user-images.githubusercontent.com/42038175/107334940-5116a300-6af2-11eb-8e70-83cb81f327d4.png)

**Comment by silentmoooon** [comment]
666,坐等更新

**Comment by silentmoooon** [comment]
![test11111111111](https://user-images.githubusercontent.com/9210514/107343449-482acf00-6afc-11eb-96fb-18a4d181469a.gif)

奇怪,对于日历和邮件这个应用会打开"文档",其他应用没出现这问题.

**Comment by zhuxb711** [comment]
@silentmoooon 说明启动有点小问题。现在Uwp的启动是调用explorer来启动。但是explorer这个东西呢，你PackageFamilyName稍微有一丁点问题，它就会启动自己而不是你指定的应用

**Comment by Sayor0630** [comment]
is this  possible now?

**Comment by zhuxb711** [comment]
Yes, it will be released in 6.0.6
