### ISSUE TITLE
打开目录不崩溃但是加载不出内容

### ISSUE THREAD

**Issue by srliuhao** [zhuxb711/RX-Explorer#107]
我在5.9.7.0和6.0.0.0上都报过崩溃日志，就是点击任意盘符后进去，加载不出内容，然后再点击其它地方就直接崩了，这次6.0.1.0更新了点击目录崩溃的问题，果然点哪里都不崩了，但是什么都加载不出来┓( ´∀` )┏

**Comment by zhuxb711** [comment]
请在设置中导出 日志文件 看看？

**Comment by zhuxb711** [comment]
Hi能否提供进一步的信息？包括设置当中导出日志文件？

**Comment by zhuxb711** [comment]
考虑是不是有某些驱动器迟迟不能响应导致的？

**Comment by srliuhao** [comment]
今天通过windows应用商店更新了6.0.1版本，使用正常了，目录和文件正常打开。
感谢开发者，新年快乐！

**Comment by zhuxb711** [comment]
新年快乐
