### ISSUE TITLE
我想加入一些快捷键的支持

### ISSUE THREAD

**Issue by lindexi** [zhuxb711/RX-Explorer#108]
- 直接键入，等于文件夹过滤文件。如键入 `哔` 将会只显示文件夹里面所有包含 `哔` 的文件或文件夹（当然，交互方式也可以是高亮啥的）
- 指定命令行绑定快捷键。如将 `F3` 绑定到命令 `Foo.exe $File` 那么此时在选中文件时按下 F3 将会执行 `Foo.exe 文件绝对路径` 
- 支持 Ctrl+Shift+C 复制文件或文件夹绝对路径

感谢大佬，这是我提的一点点建议

**Comment by zhuxb711** [comment]
Ctrl+Shift+C将于下一个版本中到来。
直接输入过滤文件好像不太好搞，但是我在列表头的筛选功能中增加了“正则表达式”筛选。
