### ISSUE TITLE
左边框样式bug

### ISSUE THREAD

**Issue by vercharlin** [zhuxb711/RX-Explorer#109]
1. 初始样式(注意左边框)
![image](https://user-images.githubusercontent.com/63804569/107126510-5d7cdf00-68eb-11eb-818a-fc68b7069ce6.png)
2. 点击安全域后,左边框变粗,样式成为一道明显粗黑线
![image](https://user-images.githubusercontent.com/63804569/107126555-974de580-68eb-11eb-8228-45680d9015a3.png)
3. 拖动窗口或者最大化窗口后消除

环境: 系统win10-21H2,至美化主题:蕾丝Win10主题

**Comment by zhuxb711** [comment]
这个应该是微软UWP框架的一个BUG，我无法修复
