### ISSUE TITLE
建议固定列名

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#111]
![标题栏](https://user-images.githubusercontent.com/41459054/107134440-144d7f00-692d-11eb-8c7e-2cbee73d9036.gif)

**Comment by zhuxb711** [comment]
之前是有固定列表头的，但是固定列表头会导致一个意外偏移滚动的BUG，你右键的时候有概率会导致列表滚动。所以移除掉了，据我所知该问题已经被微软修复了但尚未发布，如果它发布了新版本，我会重新引入固定列表头的功能

**Comment by FlyingDragon0420** [comment]
看6.1.5.0更新日志，此问题已修复，但测试后仍未固定
Windows 10 专业版 Build 19041
RX 6.1.5.0

**Comment by FlyingDragon0420** [comment]
重启 RX后好了

**Comment by zhuxb711** [comment]
已知问题。切换最顶的导航， 比如 回收站 等，会导致固定列名失效。但只要切换一下标签页，固定列名可恢复。
