### ISSUE TITLE
个人的一些建议

### ISSUE THREAD

**Issue by silentmoooon** [zhuxb711/RX-Explorer#113]
个人的一些建议,不知道可不可以哈
1. UI,把这台电脑  回收站 安全域 还有设置按钮都放到标题栏去,标签栏整体上移一行,这台电脑左边那个返回按钮感觉没必要, 地址栏左边的返回按钮改成也能返回主页就好了
2. 主页上的快速启动和热门网站合并成一个快速启动,放到右边的"设备和驱动器"的下方,然后左边改成上面一个类似资源管理器的快速访问和下面一个目录树的形式.
3. 打开文件直接调用系统的打开会不会更好点,内置的文本编辑器感觉可以作为一种预览的方式存在,当没有quicklook的时候.
4.  然后下面那个状态栏文字可不可以和最下面的折叠菜单放在一起

**Comment by zhuxb711** [comment]
1.放到标题栏存在工程问题，首先是区分拖拽窗口动作，你放到标题栏上面去容易出现窗口拖拽的动作覆盖了你点击的动作。左边返回的按钮没有必要是因为你没有正确理解文件夹导航中的后退按钮的作用，如果没有左上角的箭头，你就只能一层层回退才能够回到主界面，如果你跳转了上百个不同的文件夹呢？要一层层后退几百次才能够回到主界面嘛？

2.设备和驱动器 以及 文件夹和库 区域本身空间就不是很充足了，毕竟这些地方动态性太大了，文件夹和库可以添加任意多的文件夹，驱动器也可能有很多，如果移动到这里就三行并排，看来显示器需要换成竖屏使用才可以了~。左边把目录树单拎出来，如果你觉得这个OK的话你太小看这里需要的工作量了，RX的架构现在是不可能简单搞成这样的，必然要整体架构大起底。

3.RX本来对于这种行为就可以自定义，你想指定谁打开都行，也没有限制，别懒得动手，右键-打开方式-选择打开方式-勾选默认使用此应用打开。

4.那个地方塞不进去，是微软官方的控件，它起的作用就是维护UI的一致性观感，并提示你这里有个可以弹出来的东西，并没有设计为可以让你塞额外的东西进去。另外值得注意的是这个浮出菜单是对于触摸屏状态下的一种补充

总之想法美好，但是实现起来巨复杂。不要拿Files的标准来要求RX，毕竟总共就三个PR（算上你的那个😂），我觉得靠我一个人能有些功能超越Files都是奇迹。路要一步一步走，慢慢来吧，如果你有兴趣一起开发的话可以一起，我最近在关注issue里的那些问题

**Comment by silentmoooon** [comment]
1的话,主要是感觉可以多留点空间,类似chrome这样,尽量加大内容区,也不一定要放到那上面,如果有好的放这3个按钮的方式,像chrome直接标签栏放最上面是最好了.
2的话 主要是希望有一个类似chrome的收藏夹或者资源管理器的快速访问.快速启动这些感觉没那么重要,如果右边区域不好看,或者能放到一些折叠的菜单里也行我觉得. 如果有个类似快速访问功能其实返回主界面就方便了,就可以不需要那个箭头了,箭头的话感觉容易和下面的返回混淆.
3 我觉得还是直接用系统的方式更直观一点.
4 那没办法 哈哈.
btw,其实我没用过Files,也没用Files的标准, 都是根据自己的经验或者感觉总结的,毕竟也用过不少explorer的工具了,嘿嘿.
其实我对windows方面的东西都还是有些了解的,包括技术栈也有一定关注.
但毕竟工作上不涉及,对C#的熟悉也仅限于.net 3.5时期,开发上估计没法给你太多的帮助~~
慢慢来吧,总体来说,RX是很优势的.哈哈

**Comment by silentmoooon** [comment]
![test11111111111](https://user-images.githubusercontent.com/9210514/108447524-ff60dc00-729a-11eb-8347-37e152a46ce0.gif)
哈哈,发现标题栏可以做到拖拽和点击互不影响,下面的状态栏也可以重叠在CommandBar上

**Comment by zhuxb711** [comment]
Good，但是这样做是否美观？感觉有点像顶部菜单了

**Comment by silentmoooon** [comment]
emmm~ 美观的话,多少有点影响吧. 暂时也没想到更好的既不浪费空间又不损失美观度的摆放方式了,感觉uwp默认的风格都有点浪费空间.
是有点像顶部菜单了,现在的工具型应用基本上都是这个思路吧,诸如idea   chrome vs  vsc等之类的.

**Comment by zhuxb711** [comment]
其实RX一直都有个问题，ContentDialog弹出时，RX无法被拖拽，有没有兴趣修一下这个BUG？原理其实是ContentDialog是全屏Popup，会盖住顶部的可拖拽区域

**Comment by silentmoooon** [comment]
啊这,这不是feature么,

**Comment by zhuxb711** [comment]
是么？那没事了😀

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/108651627-29193d80-74fd-11eb-9965-6a1448c82635.png)
起码对于ms来说,这是个feature~~
而且同一时间只允许出现一个,如果允许拖拽,那其他操作也允许吧,那如果其他操作又弹出一个ContentDialog咋办,
![image](https://user-images.githubusercontent.com/9210514/108651749-6da4d900-74fd-11eb-91cc-eaaa36ab7655.png)
或者除非另外搞一套
https://www.cnblogs.com/hhchaos/p/9925745.html

**Comment by zhuxb711** [comment]
因为不能同时出现两个ContentDialog，所以RX自己继承了ContentDialog搞了一套QueueContentDialog出来

**Comment by silentmoooon** [comment]
哦哦,已经搞了一个啊,没注意看..😀 那可以在此基础上改成非模态的.

**Comment by zhuxb711** [comment]
另外还有一个问题就是固定详细列表的列头，CommunityTookit里面有现成的实现，但是之前有BUG所以弃用了，有木有原生的方式？

**Comment by silentmoooon** [comment]
我也不知道额..
之前我也发现这问题了,想提issue来着,然后发现有人提了.

**Comment by silentmoooon** [comment]
啊这 不对.. 是我理解错了.
刚刚无意中发现自带UWP应用在有ContentDialog时都是可以拖拽窗口的..
然后发现如果保留默认的标题栏也是可以拖拽的..

**Comment by zhuxb711** [comment]
有木有不保留默认标题栏也可以拖拽的方式？我怀疑是因为系统标题栏不属于UI界面的一部分所以ContentDialog没有覆盖到

**Comment by silentmoooon** [comment]
好像没有.. 除非自己实现一个
估计是的,或者说反过来,给标题栏留了口子,但又忘记给自定义标题栏留了. 要不你去给他们提个issue,哈哈.
