### ISSUE TITLE
Everything search engine not active

### ISSUE THREAD

**Issue by dinirichard** [zhuxb711/RX-Explorer#114]
![image](https://user-images.githubusercontent.com/36500470/107731336-695b0d80-6cfe-11eb-920d-c75fb247a7a7.png)

**windows 10:** 19042.804
**RX Explorer:** 6.0.1.0 (Paid version)
**Everything**: 1.4.1.1005

I have fulfilled the required prerequisites to unlock the feature. What am I missing?

**Comment by XSH-Hero** [comment]
I have the same problem. I have installed Everything, but it just can't let me use.
![image](https://user-images.githubusercontent.com/69738882/107773158-38b7ba00-6d78-11eb-870a-0ee192a6cda9.png)

**Comment by XSH-Hero** [comment]
I have the same problem. I have installed Everything, but it just can't let me use.  :(
![image](https://user-images.githubusercontent.com/69738882/107773329-74528400-6d78-11eb-94bb-0e4dab8e6319.png)

**Comment by zhuxb711** [comment]
Confire that is a bug which only in X64 system
