### ISSUE TITLE
About Enter bug

### ISSUE THREAD

**Issue by Sayor0630** [zhuxb711/RX-Explorer#118]
When I press Enter to open a Local Disk or Folder, nothing appears. It shows Empty. But when I double-click mouse left button, it works properly.
When Double-Clicking mouse left button-
![20210216_11132821-02-16-11-15-20](https://user-images.githubusercontent.com/77576588/108021296-718db280-7048-11eb-8658-20473c7acfae.gif)

When pressing Enter-
![20210216_11172721-02-16-11-18-41](https://user-images.githubusercontent.com/77576588/108021476-d812d080-7048-11eb-808a-feaaf367b9cf.gif)

**Comment by zhuxb711** [comment]
Yes I could confirm this issue.

**Comment by Sayor0630** [comment]
Thank you
