### ISSUE TITLE
建议添加输入文件名直接定位至相应条目的功能

### ISSUE THREAD

**Issue by HakureiKion** [zhuxb711/RX-Explorer#12]
该功能存在于Windows自带资源管理器中，对含有大量文件夹的路径下的快速定位很有帮助。

比如路径A下有：

- Adobe
- Chrome
- CloudSync
- CrystalDiskInfo
- DolbyDriver

这五个文件夹，则在按键输入C时会直接定位至`Chrome`，再次按C会到下一个C开头的文件夹`CloudSync`，直接输入C和R会定位至`CrystalDiskInfo`。

软件真的很棒，已经向身边的人推荐！

**Comment by zhuxb711** [comment]
该功能正在开发，预计将于下一版本中上线

**Comment by zhuxb711** [comment]
更新已发布
