### ISSUE TITLE
Feature Request: Make folder properties like windows explorer

### ISSUE THREAD

**Issue by Sayor0630** [zhuxb711/RX-Explorer#120]
When seeing properties of a file or folder, fewer things are shown. But windows explorer shows everything. Can you make RX like this? Add sharing, security, previous versions, customize tabs in properties of RX.
![ScreenShot_20210216130257](https://user-images.githubusercontent.com/77576588/108029250-54acab80-7057-11eb-9192-3cdfb0d301ea.png)
![ScreenShot_20210216130401](https://user-images.githubusercontent.com/77576588/108029347-76a62e00-7057-11eb-9735-8b98ad1134aa.png)

**Comment by Sayor0630** [comment]
I don't know coding. But can anyone help with coding?

**Comment by silentmoooon** [comment]
要不讨个巧,在属性面板上加个"超链接",点击打开系统的属性面板.

**Comment by zhuxb711** [comment]
这个本身做是可以做的，我没时间做罢了，具体就是参考Files那样，利用UWP的多页面功能来搞

**Comment by silentmoooon** [comment]
是啊 内容还不少. 比较耗时. 所以不如讨个巧先应付下 哈哈.

**Comment by silentmoooon** [comment]
啊这,太难了.涉及的数据挺多的吧.
而且最近工作上事比较多.

**Comment by zhuxb711** [comment]
ok如果我有空我会去看看的 @silentmoooon

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/111562312-f2b7a100-87d0-11eb-8db6-67fbeac5257c.png)
![image](https://user-images.githubusercontent.com/42038175/111562343-02cf8080-87d1-11eb-87da-fb712fe6aa76.png)
![image](https://user-images.githubusercontent.com/42038175/111562388-17137d80-87d1-11eb-8a53-0cf8042c2f3f.png)

That is not an easy job. Here is the screen shot

**Comment by Jerry-Liew** [comment]
The best opensource software author/programmer in the world!
