### ISSUE TITLE
打开方式选择的bug

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#123]
当我打开一个文件，要选择打开方式时，RX无响应，然后崩溃，并且没有崩溃日志，是程序本身的崩溃，希望修复。

**Comment by XSH-Hero** [comment]
![未命名-副本(2)](https://user-images.githubusercontent.com/69738882/108209205-fe2d9300-7164-11eb-84d0-9bac9d305ef4.gif)

**Comment by XSH-Hero** [comment]
就像这样

**Comment by zhuxb711** [comment]
似乎无法复现此问题

**Comment by XSH-Hero** [comment]
您是说您那里没有出现该问题吗？

**Comment by XSH-Hero** [comment]
但反馈建议清单里也有一些人遇到了该问题
![image](https://user-images.githubusercontent.com/69738882/108352898-74dc9600-7222-11eb-9c38-657cb2a8344a.png)

**Comment by Sayor0630** [comment]
Yeah. I am also experiencing this problem from update 6.0.6

**Comment by zhuxb711** [comment]
确认是OpenCV的问题

**Comment by istudy2012** [comment]
Hi @zhuxb711 
看到有一笔patch 似乎已经修复了这个问题
Fixed an issue in CV. Add support for ARM64
https://github.com/zhuxb711/RX-Explorer/commit/6ecb722769509146c49b243d52fa42608524a0c9

是否可以尽快更新版本, 上线呢
目前电脑打开zip文件和右键打开PDF等, 都会出现RX-Explorer闪退

还有, 能不能 用内置打开文件/视频 等是可选的功能 , 而不是强制的

**Comment by zhuxb711** [comment]
@istudy2012  可以，原本是通过右键选择打开方式来调整的，但是现在打开方式卡死了~（这个BUG就很淦了，只在Release模式中会出现，所以开发的时候没有查出来）

**Comment by srliuhao** [comment]
同遇到这样的问题，目前测试只要打开office文档就会这样，txt和pdf没问题，有崩溃日志

﻿Native API could not found the path: "H:\", fall back to UWP storage API
Native API could not found the path: "H:\", fall back to UWP storage API
Native API could not found the path: "H:\", fall back to UWP storage API
------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (5): 拒绝访问。
   at RX_Explorer.Class.WIN_Native_API.CreateDirectoryWatcher(String, Action`1, Action`1, Action`2, Action`1) + 0x242


Message:
        拒绝访问。

StackTrace:
        at RX_Explorer.Class.WIN_Native_API.CreateDirectoryWatcher(String, Action`1, Action`1, Action`2, Action`1) + 0x242

Extra info: 
        CallerMemberName: CreateDirectoryWatcher
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 641
