### ISSUE TITLE
网络驱动器打开为空

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#124]
![image](https://user-images.githubusercontent.com/41459054/108452987-7fd80a80-72a4-11eb-97a3-17ff167a5aba.png)

**Comment by chengl404** [comment]
Duplicate of #97

**Comment by zhuxb711** [comment]
说明Win32 API无法获取到此处的内容，下一个版本我将添加一些Fallback 机制来看看能不能用
