### ISSUE TITLE
[bug]powershell 调用导致终端卡死

### ISSUE THREAD

**Issue by HydrogenDeuterium** [zhuxb711/RX-Explorer#125]
如图。预期结果为打开软件后终端就绪等待下一条语句执行。
实际结果表现为终端卡死。
![image](https://user-images.githubusercontent.com/36532302/108600406-1d7d2800-73d2-11eb-9d48-4cb154a173af.png)

按照[这里](https://github.com/JasonStein/Notepads/issues/768)的说法，使用start-process 调用可以避免这个情况

**Comment by zhuxb711** [comment]
对，start RX-Explorer.exe 也行。但是这并不是RX的问题，RX是被调用方，cmd这边是会等待应用执行完毕的，如果你直接用RX-Explorer打开的话会等待RX运行完毕，你用start的话，本质上是等待start命令返回，所以可以立即返回

**Comment by HydrogenDeuterium** [comment]
一般来说在命令行调用的时候没有必要等待调用完毕，可否将软件的运行调整为：每次运行都开启新进程（特性可关闭）？
若如此做较为复杂，则抱歉打扰

**Comment by zhuxb711** [comment]
不你误解了我的意思，命令行调用的时候等不等被调用方完成，是命令行决定的，不是RX所能够决定的。它确实是每次都开启新的进程，但是它会决定等待这个进程执行完成（这应该是默认行为，你执行命令的时候还可以不等待你就返回？？？）。而且这样输入直接就是启动的RX主进程，，不存在套壳进程：即 命令行→套壳→套壳→套壳→RX，实际上是 命令行→RX，所以RX不退出，命令行不返回，建议在RX前面加start

**Comment by HydrogenDeuterium** [comment]
一般的非命令行应用程序（打开gui窗口界面的程序），除了git commit这种会打开一个文本编辑器读取修改的情况，我个人认为少有命令调用方需要等待要在窗口内的进程执行完毕反馈什么东西的，因此我认为默认情况是新开一个进程打开会比较好。
在命令行里调用其它东西，比如explorer,code或者notepad++之类的软件都不会这样阻塞进程。
嗯，这里提出来只是作为一个建议供作者考虑。

**Comment by silentmoooon** [comment]
你是用windows内置的windows powershell吧,是有这个问题,
可以改用最新的[powershell core](https://github.com/PowerShell/PowerShell),试了是没有这个问题的.
同样的,cmd也没这个问题.
wsl1 wsl2也没这问题(看起来阻塞,实际上可以ctrl+c退出且不结束rx)
