### ISSUE TITLE
FullTrustProcess.exe又炸了:(

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#126]
![image](https://user-images.githubusercontent.com/69738882/108677058-1bc37980-7524-11eb-99cd-0491953d8217.png)
![image](https://user-images.githubusercontent.com/69738882/108677240-5cbb8e00-7524-11eb-9863-c54bccfe494e.png)

**Comment by XSH-Hero** [comment]
#104

**Comment by XSH-Hero** [comment]
再次出现

**Comment by zhuxb711** [comment]
Issue一响，休息凉凉，XSH出现啦啊啊啊啊啊啊~~~~~~~~~滑稽🤪

**Comment by XSH-Hero** [comment]
啊这

**Comment by XSH-Hero** [comment]
非常抱歉，占用了您的休息时间，不过，这确实影响了使用:(

**Comment by zhuxb711** [comment]
没事，RX就是靠着闲暇时间才写出来的，不然根本没有这个软件

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/108988934-fe331300-76cf-11eb-94ba-fda402eaaa40.png)

额 之前没炸,6.1.0反倒炸了

**Comment by zhuxb711** [comment]
正常数量是(标签页数量+1)×运行实例数量

**Comment by silentmoooon** [comment]
打开不动就默认单实例单标签就有这么多进程了.

**Comment by zhuxb711** [comment]
@silentmoooon 打开不动是这么多
![image](https://user-images.githubusercontent.com/42038175/109002953-d351ba80-76e1-11eb-9f4c-08c1f796c995.png)

@XSH-Hero 有遇到？

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/109003618-a225ba00-76e2-11eb-9912-cf766dab7d84.png)
啊这,刚刚那次还是单标签固定到18个trust 20个backtask就不动了, 现在又试了一次,开始无限增长了..
可能是我系统有关? 最新预览版21318,但RX6.1.0之前的时候也是这系统版本 那时还是没有问题的.

**Comment by zhuxb711** [comment]
是不是积累出来的？有一种情况是RX退了但是FullTrustProcess因为意外没有退。所以一直卡在那里。你任务管理器直接结束RX和FullTrustProcess后再启动看看？

**Comment by silentmoooon** [comment]
第一次发的是特意重启了电脑再试的，
这次发的虽然没重启电脑，但也全部结束进程了的，直接taskkill /f /im

**Comment by XSH-Hero** [comment]
> ![image](https://user-images.githubusercontent.com/9210514/109003618-a225ba00-76e2-11eb-9912-cf766dab7d84.png)
> 啊这,刚刚那次还是单标签固定到18个trust 20个backtask就不动了, 现在又试了一次,开始无限增长了..
> 可能是我系统有关? 最新预览版21318,但RX6.1.0之前的时候也是这系统版本 那时还是没有问题的.

巧了，我也是21318

**Comment by XSH-Hero** [comment]
现在我认为应该是系统的锅，因为在build21313时，6.0.6版本辅助进程没有问题，但升级到21318时就有了，因此提交了该issue

**Comment by XSH-Hero** [comment]
如今6.1.0，问题仍然存在

**Comment by XSH-Hero** [comment]
要不然我尝试回滚到21313再试试？

**Comment by silentmoooon** [comment]
@XSH-Hero  握手握手, 放了半个多小时,总共稳定在120个进程了.
不过我在build21318及6.0.6版本的时候看到你发这个issue的时候,我看了下我的,当时是没有问题的.
ps 你前面暴露真名了 哈哈

**Comment by zhuxb711** [comment]
这个版本我又改进了调度机制，理论上是不会出现暴增的情况的，当然也可能是机制有问题，不过我很久没有见过辅助进程暴增的问题了

**Comment by XSH-Hero** [comment]
@zhuxb711 您的Win10是什么版本？

**Comment by zhuxb711** [comment]
最新稳定版20H2

**Comment by XSH-Hero** [comment]
那我回滚到21313试试吧，在21318，Files那边的辅助进程尽管没有暴增，但也不起作用，看看是不是系统的锅 @zhuxb711

**Comment by zhuxb711** [comment]
如果是不起作用的话可能是AppService挂掉了，这样想来的话在这种情况下确实是有可能暴增。

参考以下理论，辅助进程调度逻辑，仅展示启动后什么操作都不做的情况：
1. 有任何代码请求了辅助进程操作（6.1.0中这个一般是检查Quicklook可用性）
2. 辅助进程调度器检查发现CurrentRunningControllerNum=0，于是执行调整逻辑
3. 启动辅助进程，增加一个可调度的对象，此时CurrentRunningControllerNum+1
4. 默认至少两个可调度对象CurrentRunningControllerNum应该=2，超过2的话不会继续启动
5. 注意，如果AppService(负责辅助进程和RX的通信联络中继的任务)启动了退出逻辑，包括但不限于系统节电要求或者其他故障，又或者FullTrustProcess意外崩溃，则会通知RX注销一个可调度对象，此时CurrentRunningControllerNum-1.

如果AppService由于系统问题一启动起来就挂，RX的CurrentRunningControllerNum会一直刚＋了又-，始终达不到目标数量，则有可能一直产生大量辅助进程

**Comment by XSH-Hero** [comment]
已回退21313，RX版本6.1.0没有问题，辅助进程正常，确认为Windows build21318问题导致！

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/109084083-0deb3f80-7742-11eb-8d37-e93864342768.png)

**Comment by WindowsHero64bit** [comment]
啊这，我发现到build21327，AppService还是挂的。。。

**Comment by WindowsHero64bit** [comment]
能否到微软那里反馈一下？@silentmoooon @zhuxb711

**Comment by silentmoooon** [comment]
@zhuxb711 去反馈一下? 我英语不行~
要不代码层面也改一下,如果连不了appservice就不继续创建实例了

**Comment by silentmoooon** [comment]
21343好了  @WindowsHero64bit  @XSH-Hero

**Comment by XSH-Hero** [comment]
> 21343好了 @WindowsHero64bit @XSH-Hero

太棒了！

**Comment by XSH-Hero** [comment]
这就去更新！

**Comment by WindowsHero64bit** [comment]
好耶！针不戳！
