### ISSUE TITLE
Translation to de-DE

### ISSUE THREAD

**Issue by Jon495** [zhuxb711/RX-Explorer#127]
Hello, I could help you translate the app into German if you want.

**Comment by zhuxb711** [comment]
Sure. Thanks @Jon495 
Do you know how to translate in RX ?

**Comment by Jon495** [comment]
Yes. I just need the Multilingual App Toolkit and the .xlf file for de.

**Comment by zhuxb711** [comment]
[Translation.zip](https://github.com/zhuxb711/RX-Explorer/files/6136577/Translation.zip)
Remember mark every item as "Translated" when you done. Thanks.

**Comment by zhuxb711** [comment]
Any progress ?

**Comment by Jon495** [comment]
Here's the translated file. Sorry for the delay, but I've been very busy lately.
[RX_Explorer.de-DE.zip](https://github.com/zhuxb711/RX-Explorer/files/6266550/RX_Explorer.de-DE.zip)

**Comment by zhuxb711** [comment]
[RX_Explorer.zip](https://github.com/zhuxb711/RX-Explorer/files/6277599/RX_Explorer.zip)

Sorry, the translated file has changed a lot in the last 25 days. Could you help update the translation?

Make sure uncheck "Translated" to find out what you need to update
![image](https://user-images.githubusercontent.com/42038175/114002990-fac6a600-988f-11eb-8416-a4cda35b3d37.png)

Thank you very much~~~~~😀

**Comment by Jon495** [comment]
Here's the newest file. I tried to make the expressions/sentences shorter but I couldn't do much but it probably fits anyway.
[RX_Explorer.de-DE.zip](https://github.com/zhuxb711/RX-Explorer/files/6279888/RX_Explorer.de-DE.zip)

**Comment by zhuxb711** [comment]
Thanks a lot @Jon495

**Comment by zhuxb711** [comment]
@Jon495 May I have your name? So that I could thanks to you on RX
![image](https://user-images.githubusercontent.com/42038175/115116061-4c76db00-9fca-11eb-96f5-711309a26ef5.png)

**Comment by Jon495** [comment]
Of course. My name is Jonas Gunkel. Thank you for letting me work on the project.
