### ISSUE TITLE
快捷方式图标刷新慢

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#128]
如题，刷新时间在20s左右
![link_bug](https://user-images.githubusercontent.com/41459054/109263749-c4cce580-783e-11eb-9c0c-26926d3a0708.gif)

**Comment by zhuxb711** [comment]
所有图标都慢还是仅360这个慢？我怀疑是获取Msi应用图标的速度太慢了

**Comment by FlyingDragon0420** [comment]
新建了一个快捷方式试了下，好像就这个慢

**Comment by zhuxb711** [comment]
我在虚拟机里面测试了一下，获取360软件管家的速度也不是很慢，而且不是走获取MSI的应用图标的获取路径。所以应该只是单纯的Win回传缩略图的速度比较慢罢了，你第一次获取过后只要没有清除缩略图缓存，应该后续都很快的
