### ISSUE TITLE
建议：内置视频播放器

### ISSUE THREAD

**Issue by WindowsHero64bit** [zhuxb711/RX-Explorer#129]
希望RX的视频播放器播放视频时，点击视频界面可以暂停

**Comment by WindowsHero64bit** [comment]
最好设置为可选功能，即在设置中可以打开/关闭

**Comment by XSH-Hero** [comment]
我觉得这个可以有

**Comment by FlyingDragon0420** [comment]
其实我倒不建议内置各种播放器，文件管理器就干文件管理器的活比较好

**Comment by zhuxb711** [comment]
@FlyingDragon0420 内不内置与用户用不用没啥关系，本来就可以很容易的替换打开方式。
@WindowsHero64bit 此功能将会包含在下一个版本中，但不会作为设置项，因为已经有太多的设置，我觉得不是每一个操作都要搞个设置去控制或者自定义~，如果都自定义的话设置页面只会让人眼花缭乱找不到重点

**Comment by WindowsHero64bit** [comment]
好的，辛苦了 @zhuxb711

**Comment by WindowsHero64bit** [comment]
> @FlyingDragon0420 内不内置与用户用不用没啥关系，本来就可以很容易的替换打开方式。
> @WindowsHero64bit 此功能将会包含在下一个版本中，但不会作为设置项，因为已经有太多的设置，我觉得不是每一个操作都要搞个设置去控制或者自定义~，如果都自定义的话设置页面只会让人眼花缭乱找不到重点

其实我认为这个可以在播放器页面单独设置，毕竟软件功能越多，设置项必然也越多

**Comment by WindowsHero64bit** [comment]
或者像Files那样，把设置分类，每类一个页面
