### ISSUE TITLE
套用繁體中文仍然是顯示英文

### ISSUE THREAD

**Issue by aunight** [zhuxb711/RX-Explorer#13]
![image](https://user-images.githubusercontent.com/52199445/89555515-b8e9e980-d842-11ea-9c67-62253d3e8233.png)

**Comment by zhuxb711** [comment]
Fine，我调查了一下发现有一些小设置没有做好。

默认状态下，微软为了进一步降低安装包的大小，会在软件分发时自动根据系统语言来分配语言包。换言之就是如果下载的时候你的系统语言不包括“繁体中文”的话，则微软不会分发繁体中文的语言包。

RX通过一系列的技术和标记来强制微软分发所有的语言包，但由于一些疏忽，繁体中文并没有包含在“强制分发”的要求中。(在本地调试时此问题不会出现，仅当上传至微软商店后才会出现)

再次表示歉意，我将于下一个版本中修复此问题。或您可以向系统语言增加繁体中文，然后卸载并重新安装RX，此时相应语言包应当随之一并下载，即可成功切换。

**Comment by aunight** [comment]
我的系統語言原本就是繁體中文 重新安裝後仍然是如此 但還是有某部分內容是繁體

**Comment by zhuxb711** [comment]
似乎是由于繁体中文并未写入RX文件管理器的清单中导致的~

**Comment by zhuxb711** [comment]
进一步的调查显示，由于忘记将繁体中文写入清单，同时繁体中文的标记未能正确加入附带的资源包，故在应用内更改为繁体中文时，显示不正确。

相关问题已得到解决，通过本地验证并将于下一个版本中修复。

**Comment by aunight** [comment]
好的感謝辛苦了

**Comment by zhuxb711** [comment]
@aunight 问题是否已经解决？

**Comment by aunight** [comment]
問題已經解決但有少部分的用語仍然是大陸的用語  最後希望穩定度可以再增強

**Comment by zhuxb711** [comment]
部分用语不太正确是因为增加新功能或者翻译更新的时候，我会用Google Translate去转换成繁体，因此它可能是逐字对译的。鉴于翻译可能会随着每一个版本不断变化，故不敢每次都打扰您让您翻译。

**Comment by aunight** [comment]
建議你可以使用Word內置的翻譯 裡面也有用語的翻譯

**Comment by zhuxb711** [comment]
OK，当前该Issue指向的问题已经解决，我将关闭该Issue.

**Comment by zhuxb711** [comment]
Hi，

由于大陆这边有关一些字词的表述和使用繁体中文的区域不太一致，您能否定期向RX提交一个PR来更正不准确的翻译呢？

即我这里快速翻译→您有空的时候巡查一下是否存在不合适的翻译→提交PR更正（不需要太频繁，一两个月看一下就行下😁）
