### ISSUE TITLE
打开文件提示空异常

### ISSUE THREAD

**Issue by lindexi** [zhuxb711/RX-Explorer#131]
现象：

![图片](https://user-images.githubusercontent.com/16054566/109609290-14c0ea80-7b66-11eb-94a6-fb7f2c8b89ae.png)

步骤：

1. 在系统资源管理器点击映射网络驱动器，添加一个网络驱动器
2. 打开Rx Explorer
3. 在系统资源管理器断开网络驱动器
4. 在 Rx Explorer 进入网络驱动器，此时将会提示错误
5. 点击其他任意盘符，都会提示空异常

![图片](https://user-images.githubusercontent.com/16054566/109609454-4d60c400-7b66-11eb-8cde-5ed6b1dd39fe.png)

**Comment by zhuxb711** [comment]
6.1.7版本中加入了对网络驱动器的添加/移除探测，应当能够避免此问题
