### ISSUE TITLE
建议加入“网络”文件夹

### ISSUE THREAD

**Issue by WindowsHero64bit** [zhuxb711/RX-Explorer#133]
希望RX能够在顶层
![image](https://user-images.githubusercontent.com/79686372/110193295-2825cb80-7e6e-11eb-945e-615bb362ffb9.png)
“这台电脑”、“回收站”、“安全域”那一栏中加入“网络”文件夹的入口

**Comment by WindowsHero64bit** [comment]
这是系统Explorer的“网络”文件夹
![image](https://user-images.githubusercontent.com/79686372/110193350-6327ff00-7e6e-11eb-8334-65ca5c9c4660.png)

**Comment by WindowsHero64bit** [comment]
这是系统Explorer的“网络”文件夹
![image](https://user-images.githubusercontent.com/79686372/110193401-9cf90580-7e6e-11eb-8c69-34271cde0c5e.png)

**Comment by zhuxb711** [comment]
UWP对网络文件夹的支持其实比较一般，So并不是所有网路设备都支持的，对于网络设备还是建议使用Windows Explorer

**Comment by WindowsHero64bit** [comment]
不过files好像已经有了，RX也应该可以

**Comment by zhuxb711** [comment]
很难，Files多少人，这里就我一个

**Comment by WindowsHero64bit** [comment]
emm确实

**Comment by WindowsHero64bit** [comment]
不过慢慢来嘛，这个什么时候弄好都行，也不是什么着急的功能

**Comment by luojunyuan** [comment]
很想吐槽file那么多人为啥还是那么容易卡死，文件夹打开速度也很缓慢。试过好几台win10 20h2电脑都一样我认为不是我环境问题，且files对于触控的支持一塌糊涂。
上面这些问题在rx中完全不存在，感谢作者制作了那么优秀的uwp应用👍

**Comment by zhuxb711** [comment]
@luojunyuan files那边为了MVVM而MVVM，啥东西都是这样的架构，一个过程跳超级多文件和类，对于效率方面来说表现是不够好的。（其实有很多效率上的优化files是搬我的过去的，我有的时候也会看看他们的新功能，感觉启发挺大）
