### ISSUE TITLE
无法打开office文件

### ISSUE THREAD

**Issue by robinzjh** [zhuxb711/RX-Explorer#134]
无法打开.doc   .docx   .xlsx    .vsdx文件

**Comment by zhuxb711** [comment]
右键-打开方式-选择其他应用打开-选择Office系列软件

**Comment by peteryixu** [comment]
> 右键-打开方式-选择其他应用打开-选择Office系列软件

升级到6.0.5了，尝试“右键-打开方式-选择其他应用打开-选择office系列软件”了，还是不行。。。。。。

**Comment by peteryixu** [comment]
> 现已证实，该问题是由于Office自身引起的，请更新Office365至最新版本。例如打开Word，左下角“账户”-右侧 立即检查更新

嗯嗯！问题已解决！感谢！（国内老上不去Github，回复慢了，抱歉。。。）
