### ISSUE TITLE
回收站点击删除后一直显示正在删除

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#135]
![截图20210308111518174](https://user-images.githubusercontent.com/41459054/110269962-c09f8580-7fff-11eb-90ac-2d7f3a1fef87.jpg)
Windows 10 专业版 Build 19041  
RX 6.1.5.0

**Comment by zhuxb711** [comment]
已知问题，目前的话发现是获取exe文件的删除日期数据的时候，不知道是依赖库还是系统本身的行为，会在exe文件上创建一个Handle，这个Handle就类似于占用，导致无法清除回收站的文件，除非RX关闭否则这个Handle不会消失。

如果回收站不存在exe文件，那就没有问题可以清空。此问题仍在调查中。

**Comment by zhuxb711** [comment]
该问题似乎是Windows Shell的行为，但我已经找到办法防止系统创建意外的Handle
