### ISSUE TITLE
Del键无法删除文件

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#136]
键盘Del键 无法删除文件

Windows 10 专业版 Build 19041
RX 6.1.5.0

**Comment by zhuxb711** [comment]
键盘Del键一直都是有支持删除文件的，请提供进一步的信息

**Comment by FlyingDragon0420** [comment]
额，今天好了，昨天不好使，RX内Del无效，其他地方好使

**Comment by FlyingDragon0420** [comment]
确实存在问题，复现条件
点击回收站，再切回目录，Del键就不好使了
![trash_bug](https://user-images.githubusercontent.com/41459054/110937523-7276e300-836d-11eb-982f-bbb70b57abc7.gif)

**Comment by zhuxb711** [comment]
我想这是由于一个微软的BUG引起的，切换最顶上的导航然后切换回来的时候，UWP的页面加载事件激活了一次，但页面卸载事件却意外激活了两次，这直接导致了删除对快捷方式的监听，我将进行一些更改以避免该问题，同时该问题已提交微软。
