### ISSUE TITLE
Enhancement: add Xbox support

### ISSUE THREAD

**Issue by Nun-z** [zhuxb711/RX-Explorer#138]
Currently the app installs to an Xbox and runs, but there are numerous bugs that prevent it from being fully usable.  Official support for Xbox would be helpful to many users.

**Comment by zhuxb711** [comment]
RX-Explorer was not designed for Xbox. It only runs on PC. I don’t know why should RX run on Xbox?

**Comment by Nun-z** [comment]
No file explorer available for Xbox is as full-featured as RX Explorer.  Many use a worse file explorer in order to move around ROMs and BIOS on Xbox for emulation, so there is some demand for it.  RX Explorer would be the best file explorer on the market for Xbox users if it was supported.

**Comment by zhuxb711** [comment]
Could you create a PR to add support for Xbox ?

**Comment by silentmoooon** [comment]
感觉意义不是蛮大 哈哈
xbox类似ios的机制,管理不了啥文件.

**Comment by Nun-z** [comment]
It absolutely can manage files.  See this video: https://streamable.com/r5z7z0

Here's RX Explorer running on Xbox:
https://streamable.com/2qlkdq

**Comment by zhuxb711** [comment]
I think the key component "FullTrsutProcessor" is base on Win32 so it might not be able to use on Xbox

**Comment by Nun-z** [comment]
It sounds like all uses of the fullTrustProcessLauncher class would have to be replaced.  Perhaps that isn't feasible for this project.

**Comment by zhuxb711** [comment]
I think it will be very hard for RX to support Xbox. Because lots of basic function rely on FullTrustProcess
