### ISSUE TITLE
2个小BUG

### ISSUE THREAD

**Issue by silentmoooon** [zhuxb711/RX-Explorer#141]
1. 右键菜单有时候会灰显,暂时没找到触发的规律,有时候半天都不出来,有时候一下就出来了.
![image](https://user-images.githubusercontent.com/9210514/112997587-d556df80-919f-11eb-94d2-6a95e772c490.png)

2. 有时候属性窗口会显示在左上角而不是屏幕中间
![image](https://user-images.githubusercontent.com/9210514/112997944-2666d380-91a0-11eb-996f-c8473f255eda.png)

**Comment by zhuxb711** [comment]
问题1. issue #59 N久之前就报告了
问题2. RX只能是Request而不是Must，以下内容来自官方文档，实际上按不按RX请求的来不是RX所能够决定的
![image](https://user-images.githubusercontent.com/42038175/113088921-3242ac00-9219-11eb-8a0b-de9329bc2de2.png)

**Comment by zhuxb711** [comment]
FYR [AppWindow class](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/windows-apps-src/design/layout/app-window.md)
