### ISSUE TITLE
有没有考虑增加通过Windows Index的方式搜索

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#143]

**Comment by zhuxb711** [comment]
什么叫Windows Index方式搜索？Everything不是嘛？

**Comment by taooceros** [comment]
> 什么叫Windows Index方式搜索？Everything不是嘛？

就是windows自带的index，就不用单独装everything了

**Comment by zhuxb711** [comment]
本身RX也有自带的搜索呀，直接选择“内置搜索引擎”不就可以了

**Comment by taooceros** [comment]
> 本身RX也有自带的搜索呀，直接选择“内置搜索引擎”不就可以了

理论上那个快一点嘛，毕竟windows做了index

顺便问一个问题，我尝试clone了rx的源码然后编译了之后，rx就会变成debug mode的，是否有办法可以让release mode 和debug mode的rx并存？

**Comment by zhuxb711** [comment]
[这里](https://github.com/zhuxb711/RX-Explorer/blob/5162c8033e88848ac390fa8309beab497c8b57d8/RX_Explorer/Class/FileSystemStorageFolder.cs#L256)
展示了RX是如何进行搜索的，在支持的情况下，RX会直接调用Win32 API FindFirstFileEx 进行搜索以达到最大搜索速度，虽然官方文档没有明说，但此函数是文件搜索函数，应当会自动利用索引
[RX利用FindFirstFileEx搜索的实现](https://github.com/zhuxb711/RX-Explorer/blob/5162c8033e88848ac390fa8309beab497c8b57d8/RX_Explorer/Class/WIN_Native_API.cs#L891)
Or在某些网络驱动器上，FindFirstFIleEx无法支持的时候回退到UWP文件API （虽然经过优化但还是很慢）
[RX在此处标明如果存在索引就使用索引，否则直接使用文件系统进行遍历](https://github.com/zhuxb711/RX-Explorer/blob/5162c8033e88848ac390fa8309beab497c8b57d8/RX_Explorer/Class/FileSystemStorageFolder.cs#L282)

[文档在这里](https://docs.microsoft.com/zh-cn/uwp/api/windows.storage.search.indexeroption?view=winrt-19041)
截图以供您参考
![image](https://user-images.githubusercontent.com/42038175/113532366-bfad4400-95fd-11eb-8688-c0b856a41f8c.png)

当然昨天我仔细看过RX的FindFirstFileEx的搜索实现之后发现了一些不足，我会在下次更新时进行改进，尚存在优化空间，可以节省一些遍历的数量(考虑到这个API的速度.....emmmmm大概每秒十几万上下，节省的时间不会特别多)

**Comment by zhuxb711** [comment]
> 顺便问一个问题，我尝试clone了rx的源码然后编译了之后，rx就会变成debug mode的，是否有办法可以让release mode 和debug mode的rx并存？

这个应该是需要更改RX的名称的，比如如果您希望Debug版本与Release共存，需要到Package(此项目是您需要部署的项目/启动项目)项目下的Package.appxmanifest内更改应用名称

1.更改显示名称，如在前面加入[Debug]
![image](https://user-images.githubusercontent.com/42038175/113533783-5e876f80-9601-11eb-8851-aca82ac3ee34.png)

2.请找到“打包”，更改包名，加上任意合法包名后缀，如.Debug。最后，同样修改 包显示名称，如下
![image](https://user-images.githubusercontent.com/42038175/113533878-9ee6ed80-9601-11eb-9e43-5351299de8c5.png)

部署之后可与商店版本共存

**Comment by taooceros** [comment]
感谢！明白了，因为之前项目是单独做了odbc搜索的，所以以为没有单独的win32 api用来调用index
