### ISSUE TITLE
windows的主题颜色似乎有些和rx的主体颜色不太协调

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#144]
![image](https://user-images.githubusercontent.com/45326534/113471486-32e47800-948f-11eb-8d60-2ed50000f1b9.png)

是否可以考虑单独设置一个更协调的淡灰色或者黑色而不是用windows的主题颜色

**Comment by zhuxb711** [comment]
你这个情况是在设置中关闭了“透明效果”，即“亚克力(Acrylic)”效果，因此RX不得不遵顼并使用主题色替换原本是亚克力颜色的部分

**Comment by taooceros** [comment]
我好像使用的是推荐，我查看了自定义模式，即使打开了acrylic效果，还是使用主题色。
![image](https://user-images.githubusercontent.com/45326534/113514444-43851300-95a1-11eb-9d72-8eb366fed22a.png)

![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/45326534/113514477-77603880-95a1-11eb-84af-0e0d794ccc5b.png)

**Comment by zhuxb711** [comment]
系统设置-个性化- 打开 “透明效果” 这个开关
![image](https://user-images.githubusercontent.com/42038175/113514512-ad9db800-95a1-11eb-9bf5-256abd41d4ec.png)

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/113514557-e2aa0a80-95a1-11eb-94cc-d4cfd50f2acd.png)
是开着的

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/113514600-34529500-95a2-11eb-9659-eb693a8bd624.png)
正常应该是这样，可能是其他原因导致了亚克力不生效，比如开启了省电模式，根据微软官方文档，亚克力会在以下场景失效:
![image](https://user-images.githubusercontent.com/42038175/113514630-6b28ab00-95a2-11eb-83df-4923373e67b3.png)

[看这里](https://docs.microsoft.com/zh-cn/windows/uwp/design/style/acrylic#usability-and-adaptability)

**Comment by taooceros** [comment]
但是看设置页面似乎blur生效了，不知道那个是不是也是用的acrylic
![image](https://user-images.githubusercontent.com/45326534/113514792-2d785200-95a3-11eb-88d7-b7919d73d189.png)
另外，这似乎是6.0.0之后出现的
我尝试重置一下

**Comment by taooceros** [comment]
emmm确实好像是我电脑的acrylic有点问题，我研究一下，感谢回复。

**Comment by zhuxb711** [comment]
好的，那我先Close这个issue，如果您有进一步的问题，我会重新打开

**Comment by taooceros** [comment]
谢谢！

**Comment by zhuxb711** [comment]
问一句，是什么问题呀？

**Comment by taooceros** [comment]
> 问一句，是什么问题呀？

我也不是很懂，我就照着google上搜到的一个教程改了注册表然后重启就可以了。可能是2004的某个bug？

**Comment by zhuxb711** [comment]
emmmm行吧~~~~~~
