### ISSUE TITLE
无法启动Word

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#147]
![image](https://user-images.githubusercontent.com/45326534/113676220-c23b9680-96ee-11eb-9643-242705d66088.png)

**Comment by taooceros** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6262955/Export_All_Error_Log.txt)

Log在这，但是好像没有特别有效的信息

**Comment by taooceros** [comment]
说实话我觉得现在启动文件的逻辑有点怪，如果不被识别其实感觉直接让系统api打开就好了，没必要弹出选择程序的窗口（对我来说那个窗口打开要3-4秒），选择程序的窗口应该只有右键的时候打开。
如果你不介意的话我有空可以帮你改一下那一部分

**Comment by zhuxb711** [comment]
Hi，任何PR都欢迎👏~~~~~

这样的设计是因为RX不会探测系统是否已经设置了默认打开方式，所以需要用户自行设置一遍。如果您可以提交PR到这一部分来进行改进，使得RX可以探测是否已经存在默认打开方式，并保存至数据库，然后用户就无需再次设置一遍。若您提交PR，不胜感激！

Tips: 某个版本的Office无法正确打开，请更新Office至最新版即可

**Comment by taooceros** [comment]
> Hi，任何PR都欢迎👏~~~~~
> 
> 这样的设计是因为RX不会探测系统是否已经设置了默认打开方式，所以需要用户自行设置一遍。如果您可以提交PR到这一部分来进行改进，使得RX可以探测是否已经存在默认打开方式，并保存至数据库，然后用户就无需再次设置一遍。若您提交PR，不胜感激！
> 
> Tips: 某个版本的Office无法正确打开，请更新Office至最新版即可

我这是最新版的呀（beta），但是不知道为啥无法打开

**Comment by zhuxb711** [comment]
Emmm之前我也遇到过这个问题，具体表现就是RX怎么启动Word都被拒绝访问，原因不知道，但是我更新Office到最新版之后就可以了，很神奇

**Comment by taooceros** [comment]
那我回头debug看看吧

**Comment by taooceros** [comment]
hmmm怎么样debug FullTrustProcess里的代码啊，我debug的时候显示版本不匹配

**Comment by zhuxb711** [comment]
方法1：在FullTrustProcess的代码里面加Debugger.Launch()，由于RX有重连机制，请勿加在建立连接前的代码中。
方法2：单独启动RX后，待FullTrustProcess启动后，VS点击调试，附加到进程，选中所有FullTrustProcess，点击附加，即可调试FullTrustProcess

**Comment by taooceros** [comment]
ok

**Comment by zhuxb711** [comment]
有任何发现嘛？

**Comment by taooceros** [comment]
似乎所有office软件都打不开，报错是“拒绝访问”，但是不太清楚改怎么解决

**Comment by zhuxb711** [comment]
能否确认6.3.1版本中是否仍然存在此问题？

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/115209141-e60bcd00-a12f-11eb-9c44-d7b32d582079.png)
直接打开word仍然不行，但是我把sqlite的记录删了然后现在可以直接打开docx文件

**Comment by zhuxb711** [comment]
那可能是直接调用UWP的Launch API是可以打开的

**Comment by taooceros** [comment]
> 那可能是直接调用UWP的Launch API是可以打开的

Launch API不是不能打开exe嘛，文件在没有指定打开程序的情况下我记得后来改成了Process.Start

**Comment by zhuxb711** [comment]
Launch API可以打开指定文件的默认关联程序，是不能直接打开exe，所以应该是通过UWP API打开了默认关联程序

**Comment by taooceros** [comment]
> Launch API可以打开指定文件的默认关联程序，是不能直接打开exe，所以应该是通过UWP API打开了默认关联程序

对我记得这个api是可以打开docx的，这个我在当时测试pr的时候试过，不过后来具体实现不是改成了win32的api嘛

**Comment by zhuxb711** [comment]
代码看这里，首先使用UWP API启动，失败后再用Win32API启动
[这里](https://github.com/zhuxb711/RX-Explorer/blob/d9d4338247571098c01cc3a99059d2f6f2a9402a/RX_Explorer/View/FilePresenter.xaml.cs#L2428)

**Comment by taooceros** [comment]
o后面修改过了，那应该没错

**Comment by taooceros** [comment]
> 代码看这里，首先使用UWP API启动，失败后再用Win32API启动
> [这里](https://github.com/zhuxb711/RX-Explorer/blob/d9d4338247571098c01cc3a99059d2f6f2a9402a/RX_Explorer/View/FilePresenter.xaml.cs#L2428)

有点好奇，为什么后面还是改成了默认先用uwp api启动？其实用win32api启动效果是一样的

**Comment by zhuxb711** [comment]
Office就一个经典的例子，Win32 API启动有的时候不太可靠。你看Win32不就报出拒绝访问了嘛......

**Comment by taooceros** [comment]
不过其实我感觉win32api打不开的uwpapi也打不开……
这个权限问题确实挺奇怪的

**Comment by zhuxb711** [comment]
很奇怪，你清除了数据库本质上就是会进到UWP Api启动，你会发现UWP能够启动而Win32启动不了....当然这个问题也是看电脑的，很多电脑没有这个问题

**Comment by taooceros** [comment]
> 很奇怪，你清除了数据库本质上就是会进到UWP Api启动，你会发现UWP能够启动而Win32启动不了....当然这个问题也是看电脑的，很多电脑没有这个问题

不，win32是能启动docx的，只是不能启动word的exe，这就是为什么我要清掉数据库，因为启动不了word的exe也就没办法通过启动word带参数启动文档

**Comment by taooceros** [comment]
这倒是，也有可能是杀软的问题，不是特别清楚。但是我用的另一个wpf的软件可以直接启动word，不会报拒绝访问……

**Comment by zhuxb711** [comment]
[我好像找到点有意思的东西](https://devblogs.microsoft.com/oldnewthing/20101118-00/?p=12253)
你可以尝试一下把FullTrustProcess里处理RunExe命令的那部分用Helper.CreateSTATask()然后让它在STA模式下跑一次，看看能不能启动Word

**Comment by zhuxb711** [comment]
C# Process.Start()方法使用UseShellExecute = true 背后就是使用ShellExecute()执行的

**Comment by taooceros** [comment]
> [我好像找到点有意思的东西](https://devblogs.microsoft.com/oldnewthing/20101118-00/?p=12253)
> 你可以尝试一下把FullTrustProcess里处理RunExe命令的那部分用Helper.CreateSTATask()然后让它在STA模式下跑一次，看看能不能启动Word

我尝试一下

**Comment by taooceros** [comment]
还是不行，估计是权限的问题

**Comment by zhuxb711** [comment]
你能不能测试一下直接使用Shell32下面的ShellExecute API来启动？
在Programs.cs中你可以使用Shell32.ShellExecute()来直接调用此API，看看绕过 C#的Process类可不可以

**Comment by taooceros** [comment]
> 你能不能测试一下直接使用Shell32下面的ShellExecute API来启动？
> 在Programs.cs中你可以使用Shell32.ShellExecute()来直接调用此API，看看绕过 C#的Process类可不可以

ok

**Comment by zhuxb711** [comment]
我提交了一个新的Commit，你可以试一下，我用底层Win32 API 完全替换了 Process 类，现在整个启动过程完全直接交由Win32 API执行

**Comment by taooceros** [comment]
好，我晚一点试一下

我刚刚试了下Shell32.ShellExercute，似乎不行，返回值是5 (0x00000000000005)

**Comment by zhuxb711** [comment]
那就是还是拒绝访问了咯，我查了.Net framwork的源代码，Process.Start()启动的时候如果不是STA模式的话会自动开一个线程切换到STA模式，所以不是STA模式的问题

**Comment by zhuxb711** [comment]
Hi 6.3.5是否解决了这个问题？

**Comment by taooceros** [comment]
> Hi 6.3.5是否解决了这个问题？

尝试了一下，仍然无法打开winword.exe，估计是一些奇怪的权限问题？

**Comment by zhuxb711** [comment]
6.3.5我两个启动的Win32都上了，一个是[ShellExecuteEx](https://github.com/zhuxb711/RX-Explorer/blob/c5d37245a05011191d335f9591ab362840d588ac/FullTrustProcess/Program.cs#L1636)一个是[CreateProcess](https://github.com/zhuxb711/RX-Explorer/blob/c5d37245a05011191d335f9591ab362840d588ac/FullTrustProcess/Program.cs#L1681)，系统内启动exe的总共就这两个函数，再起不起来我也木得办法了。

**Comment by taooceros** [comment]
> 6.3.5我两个启动的Win32都上了，一个是[ShellExecuteEx](https://github.com/zhuxb711/RX-Explorer/blob/c5d37245a05011191d335f9591ab362840d588ac/FullTrustProcess/Program.cs#L1636)一个是[CreateProcess](https://github.com/zhuxb711/RX-Explorer/blob/c5d37245a05011191d335f9591ab362840d588ac/FullTrustProcess/Program.cs#L1681)，系统内启动exe的总共就这两个函数，再起不起来我也木得办法了。

😂😂😂辛苦了，不过是可以直接打开docx文件的，只要不要主动设定打开方式目前貌似是没问题的

**Comment by zhuxb711** [comment]
因为不主动设定打开方式的时候用的微软自己做的库来打开的默认关联.....那我Close这个issue了
