### ISSUE TITLE
win+e错误

### ISSUE THREAD

**Issue by 449134904** [zhuxb711/RX-Explorer#149]
![图片](https://user-images.githubusercontent.com/17736664/114138700-94e62700-9940-11eb-818b-980e2b1d0b55.png)

**Comment by zhuxb711** [comment]
请确认最新版6.3.1中是否还有此问题？

**Comment by 449134904** [comment]
是的也有

**Comment by zhuxb711** [comment]
能否前往设置中，滚动到最底下，导出日志文件然后发出来参考一下？

**Comment by 449134904** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6340590/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
"﻿An unexpected error was threw in InterceptWindowsPlusEAsync, message: Alias file is not exists"
这说明RX未能找到您系统中的WindowsApp文件夹或未在该文件夹内找到RX-Explorer.exe这样一个快捷启动文件，Win+E功能必须依赖于这个文件，因此最终导致无法开启WIN+E

**Comment by 449134904** [comment]
那我要怎么操作呢?我这个是在应用商城下载的,我全局搜索了下是有这2个文件的
![图片](https://user-images.githubusercontent.com/17736664/115521519-d1f5d600-a2bd-11eb-843c-4579b9ad6eb5.png)

**Comment by zhuxb711** [comment]
这样的话应该是环境变量中没有配置此处的WindowsApps路径，环境变量中添加路径之后再次尝试打开Win+E即可

**Comment by zhuxb711** [comment]
Hi 是否已经解决了您的问题？

**Comment by 449134904** [comment]
![图片](https://user-images.githubusercontent.com/17736664/115809310-6d05c180-a41e-11eb-8c50-f3aed882692d.png)
0kb的,我的环境变量中是修改过这个目录的
D:\Users\xia\AppData\Local\Microsoft\WindowsApps
他所在的是D盘 是否是这个原因导致的呢

**Comment by zhuxb711** [comment]
0 kb是正常的，因为这其实是一个伪装成exe的快捷方式，它帮助系统找到真正的RX可执行文件。您不需要复制它。只需要将D:\Users\xia\AppData\Local\Microsoft\WindowsApps添加至环境变量的Path中即可让RX识别到它

**Comment by 449134904** [comment]
![图片](https://user-images.githubusercontent.com/17736664/115809579-f1584480-a41e-11eb-89d5-89017cd242b0.png)
我一直都是添加中的

**Comment by zhuxb711** [comment]
可能是有什么问题....但是您可以通过一下方式来手动操作
https://github.com/zhuxb711/RX-Explorer/issues/27#issuecomment-692418152

**Comment by 449134904** [comment]
操作什么?

**Comment by zhuxb711** [comment]
手动添加Win+E的支持

**Comment by 449134904** [comment]
![图片](https://user-images.githubusercontent.com/17736664/115810352-5eb8a500-a420-11eb-8a1e-bf96eb01ab46.png)

**Comment by zhuxb711** [comment]
啊你这就说明你的WindowsApps路径在环境变量中没配置对，你看Powershell也找不到这个RX-Explorer.exe文件

**Comment by 449134904** [comment]
可以了 我知道怎么操作了

**Comment by zhuxb711** [comment]
Ok，那我关闭此issue了，我已更改RX在这一部分的代码，提供了环境变量缺失时的回退方法来尽可能的保证成功启用Win+E，下一个版本中将包含此改进

**Comment by 449134904** [comment]
不过这个应该算是一个小bug,因为我是重新吧之前的C盘都指定到D盘了,所以找不到我还是需要吧这个在C盘的东西复制到D盘才可以的
