### ISSUE TITLE
部分文件夹打不开/找不到

### ISSUE THREAD

**Issue by lsgbx** [zhuxb711/RX-Explorer#15]
我的用来装下载文件的目录----迅雷下载无法直接在RX中找到，搜索可以找到但是点击无法打开，原因未知
如图按名称排序无此文件夹
![1](https://user-images.githubusercontent.com/36256836/89699859-afed3b00-d95c-11ea-98ab-50ccd98aa626.jpg)
驱动器内搜索可得到：
![2](https://user-images.githubusercontent.com/36256836/89699927-2f7b0a00-d95d-11ea-9c97-6b0c64dc6abc.jpg)

**Comment by zhuxb711** [comment]
这个问题有点难办，似乎在我这里并没有任何问题。你刷新一下看看能不能出来？

**Comment by lsgbx** [comment]
emmm
我试过了重置软件，重启windows，以及把目录下奇奇怪怪的东西收起到文件夹里
都没有效果
我觉得比较有可能带来问题的东西（但也不是自运行改图标啊）
![1](https://user-images.githubusercontent.com/36256836/89704179-4bde6d00-d984-11ea-84c7-7e9b4ee0796b.jpg)
而另一个软件则没有此问题
![3](https://user-images.githubusercontent.com/36256836/89704191-5bf64c80-d984-11ea-88a2-f2221cd086db.jpg)
如果问题难以确认的话，我再等两个版本吧，RX做多开互补看着还不错，win10原生的多标签迟迟不肯上线
谢谢

**Comment by zhuxb711** [comment]
目前RX唯一会过滤的情况就是，如果某个文件或文件夹具有“系统文件”属性。
那么RX就不会予以展示，因为此类文件在UWP平台上完全无权访问

**Comment by lsgbx** [comment]
挨个文件搬动，未出现搬动后不显示，把文件夹清空成0B，包含0文件夹0文件，依旧不显示，设置安全所有用户完全控制，也不现实显示。。。。
我就把它删了重建，东西搬回去，好了
神奇，土办法居然好用😂

**Comment by ycllz** [comment]
这软件好大问题啊，卸载后全部文件夹 the item you selected is unavailable，咋办

**Comment by ycllz** [comment]
没有这么厉害就别宣传这么厉害嘛 难道重装系统

**Comment by zhuxb711** [comment]
@ycllz RX运行于应用安全沙箱中，无法进行你所说的更改，想这么厉害也没办法呀～
