### ISSUE TITLE
About .rar support

### ISSUE THREAD

**Issue by Sayor0630** [zhuxb711/RX-Explorer#150]
In RX-explorer, there is no support for compression and decompression support for .rar files. Can you please add compression and decompression support for .rar files?

**Comment by zhuxb711** [comment]
The algorithm compressed into RAR files is a commercial proprietary algorithm and decompression algorithm is public. But for the time being, RX is not support for RAR Decompression

**Comment by silentmoooon** [comment]
压缩tar如果能加个直接压成tar.gz的选项就好了

**Comment by Sayor0630** [comment]
Yes. But I need the rar 1st

**Comment by zhuxb711** [comment]
想要支持RAR的话应该是需要包含7z.dll进来的，目前的SharpZipLib库是不支持RAR的，它只支持Zip Tar Gz

**Comment by zhuxb711** [comment]
@silentmoooon 有空看看嘛？C#上针对7z.dll的包装库好像还挺多的

**Comment by silentmoooon** [comment]
应该是unrar.dll 吧.

**Comment by zhuxb711** [comment]
7z.dll是包含很多解压和压缩方法的库吧，unrar应该是专门做rar的？

**Comment by silentmoooon** [comment]
哦,好像是.  https://github.com/3F/7z.Libs  这个支持的蛮全的

**Comment by silentmoooon** [comment]
这里我改了一下, 加了unrar, 也加了 tar.gz tar.bz2之类的支持. 
然后解压这一块整体上也改了一下,明天把细节完善一下再提吧.

**Comment by Sayor0630** [comment]
I think if you add 7-zip extractor method or something like that, all compression and decompression problems will solve.
