### ISSUE TITLE
无法打开xlsx和docx文件

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#152]
![image](https://user-images.githubusercontent.com/41459054/114962108-b6916200-9e9c-11eb-93c1-7fd736d4da98.png)

**Comment by FlyingDragon0420** [comment]
![image](https://user-images.githubusercontent.com/41459054/114962303-06702900-9e9d-11eb-86a4-f83586d571cd.png)

**Comment by FlyingDragon0420** [comment]
windows 10 19041  RX 6.3.0.0

**Comment by zhuxb711** [comment]
6.3.1版本中是否还有此类问题？

**Comment by FlyingDragon0420** [comment]
> 6.3.1版本中是否还有此类问题？

还有这个问题

**Comment by zhuxb711** [comment]
已经查出来的结果就是报出 “拒绝访问” 的问题

**Comment by zhuxb711** [comment]
6.3.5版本会使用两个不同的系统底层API开启应用，且一个不行还会执行另一个，是否解决了这个问题？
