### ISSUE TITLE
RX长时间高cpu占用

### ISSUE THREAD

**Issue by luojunyuan** [zhuxb711/RX-Explorer#154]
![image](https://user-images.githubusercontent.com/28323948/115116178-e3dc2e00-9fca-11eb-9053-3d9b73eafc45.png)
rx有时候会一直占用cpu，风扇呼呼的转，关闭重开才能停下来。不清楚是什么原因触发的，如图打开了两个标签页。

**Comment by zhuxb711** [comment]
Runtime Broker这个进程是微软用来管理UWP的进程，RX的占用主要看这两个和那些FullTrustProcess，Runtime Broker是微软创建的RX也无法控制~~~~~~
![image](https://user-images.githubusercontent.com/42038175/115116276-551be100-9fcb-11eb-8ac0-00105acb62f3.png)
