### ISSUE TITLE
排序导致应用崩溃

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#157]
![sort_bug](https://user-images.githubusercontent.com/41459054/115171786-6e6d7c00-a0f6-11eb-9fd9-98da58185e31.gif)
[Export_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6332774/Export_Error_Log.txt)

**Comment by zhuxb711** [comment]
此问题已于6.3.1版本中修复
