### ISSUE TITLE
点击设置里的重置和初始化按钮后，程序卡死，一段时间后自动退出，然后就无法再打开

### ISSUE THREAD

**Issue by Meow-2** [zhuxb711/RX-Explorer#159]
![image](https://user-images.githubusercontent.com/67471300/115756002-8aac3a00-a3d0-11eb-9ee7-286135cf00ff.png)
一直保持这个界面，win+e也无法再打开rx，也无法打开系统自带的管理器。这种情况下如何修复，能够直接卸载吗？

**Comment by Meow-2** [comment]
![image](https://user-images.githubusercontent.com/67471300/115757900-22118d00-a3d1-11eb-9ecc-2c871bf93003.png)
任务管理器里的情况

**Comment by zhuxb711** [comment]
RX有这么多实例是不正常的，请在任务管理器中结束它后再启动。
另外想了解一下您的RX版本和Win10版本。

最后如果您想不通过RX还原Win+E的话，可以用这个，重命名为.reg文件后双击执行即可绕过RX来恢复
[Restore_WIN_E.txt](https://github.com/zhuxb711/RX-Explorer/files/6362239/Restore_WIN_E.txt)

**Comment by Meow-2** [comment]
> RX有这么多实例是不正常的，请在任务管理器中结束它后再启动。
> 另外想了解一下您的RX版本和Win10版本。
> 
> 最后如果您想不通过RX还原Win+E的话，可以用这个，重命名为.reg文件后双击执行即可绕过RX来恢复
> [Restore_WIN_E.txt](https://github.com/zhuxb711/RX-Explorer/files/6362239/Restore_WIN_E.txt)

![image](https://user-images.githubusercontent.com/67471300/115811493-62e5c200-a422-11eb-8d4c-fcc19da28a33.png)
![image](https://user-images.githubusercontent.com/67471300/115812146-7ba2a780-a423-11eb-9976-f146daed4935.png)

RX我目前卸载了，重装的时候，微软商店一直报错，我在商店界面看了一下，没有写具体的版本信息，但我是昨天晚上十点钟在微软商店安装的
目前我使用Restore_WIN_E.txt还原了Win+E，但是系统资源管理里*在文件上点击右键鼠标就转圈圈卡死*的情况依旧存在，请问这个要怎么恢复呢？

**Comment by zhuxb711** [comment]
右键打开的问题与RX无关哦，尤其是您已经卸载了的话，因为RX对右键菜单的更改就是提供了一个小快捷方式，并且它不是侵入式的更改，而是向系统报告了我这里有一个接口，请展开右键菜单的时候调用我。同时由于UWP的安全性，卸载RX后将该功能也一并删除，因此系统右键菜单的问题与RX是无关的，您可以多等一会。

如果您是安装的最新版，则是6.3.1版本，该版本并没有太多的已知问题
