### ISSUE TITLE
墙裂要求增加书签功能啊！！

### ISSUE THREAD

**Issue by Hickoo** [zhuxb711/RX-Explorer#16]
win10自带的都有快速访问呢！！！

一个第三方管理器我觉得书签的功能要比官方的强才行吧，rx-explorer居然没有?

**Comment by zhuxb711** [comment]
右键文件夹选择“固定至主界面”

**Comment by Hickoo** [comment]
> 右键文件夹选择“固定至主界面”

好的谢了
