### ISSUE TITLE
希望可以增加下对WSL的文件系统支持

### ISSUE THREAD

**Issue by Jkker** [zhuxb711/RX-Explorer#160]
在Explorer中，使用`\\wsl$`即可打开WSL的文件系统。（Windows 10 19042+）
隔壁Files UWP近期也支持了将WSL的文件系统自动挂载到快捷启动栏了。希望可以考虑下对这个功能的支持，作为一个分区挂载到侧边栏或者快速启动栏。

**Comment by zhuxb711** [comment]
暂时没有计划为除Win32以外的Subsystem提供支持，而且不知道UWP的API、Win32 API是否支持WSL的路径。 
@silentmoooon 有没有兴趣看看？
@Jkker 您也可以提交一些PR来帮助RX支持WSL

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/115813162-41d2a080-a425-11eb-8ed9-b006f465f4ec.png)
![image](https://user-images.githubusercontent.com/9210514/115813181-49924500-a425-11eb-9223-7ab7c671b9dd.png)


![image](https://user-images.githubusercontent.com/9210514/115813558-f7055880-a425-11eb-8aa9-55f6755da17c.png)
![image](https://user-images.githubusercontent.com/9210514/115813566-fa004900-a425-11eb-8d5c-f7e8a2ebb85d.png)



刚简单试了下,如果通知添加驱动器的方式来添加wsl文件系统的的话,只需要把那个new DriveInfo(DriveFolder.Path).DriveType改成DriveType.Network ,  然后那个NetworkDriveCheckTimer_Tick再处理一下(因为 DriveInfo.GetDrives()获取不到),就可以使用了,然后地址栏好像有点兼容问题,盘符容量也不对.
所以API这块应该是没问题的, 就看用什么方式了吧.

**Comment by zhuxb711** [comment]
那如何呈现WSL呢？你的想法是作为驱动器添加？需要手动还是自动？地址栏并没有为纯UNC这种没有根目录的路径进行过任何优化，它会假设它存在根目录

**Comment by zhuxb711** [comment]
看样子WSL应该是网络驱动器，RX对于网络驱动器是有限度的支持的，只需要把WSL的路径映射为驱动器，RX就可以读到

**Comment by silentmoooon** [comment]
是的,按网络驱动器来读是可以的, 
那肯定不能手动,我觉得可以的话最好像explorer一样放左边树那里, 但现在树不是顶级的,好像暂时作为驱动器是比较好的方式.
我加了段读写为驱动器的,要不要提上来你看下行不

emm,地址栏乱了.

![image](https://user-images.githubusercontent.com/9210514/115831236-e95ecb80-a443-11eb-92bb-e00486925b17.png)

**Comment by zhuxb711** [comment]
可以啊，你提个PR吧，估计地址栏那里要改改，没想好怎么适应这种路径......因为RX以前的都是只支持带根目录的
