### ISSUE TITLE
重命名导致程序闪退

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#163]
![rename_bug](https://user-images.githubusercontent.com/41459054/115846314-5a0de400-a454-11eb-8ea5-5fa80cc8cc0f.gif)

**Comment by FlyingDragon0420** [comment]
测试了下，在重命名文件或文件夹时，如果不做任何变更，就会导致程序崩溃  V 6.3.5.0

**Comment by zhuxb711** [comment]
请重新下载Github的6.3.5版本，你下得太早了，我一提交就发现这个问题了，编译需要时间
