### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by wy164519317** [zhuxb711/RX-Explorer#165]
软件UI：
首先来说软件UI还是比较美观，流畅的动画也非常舒服，多开标签页也方便了找资料，还支持自定义网站标签简直不要太爽，总体来说：爆赞！
BUG：
1.选中文件时按住Shift有极大的概率抽风不能正确选择到指定文件夹
看评论不能复制粘贴，或者Ctrl多选错误我这里是没有遇到的可能已经修复了吧。
建议：
虽然设置里有启动时可以恢复上一次打开的标签页，但标签页关闭最后一个的话会退出应用，我还是建议开发者改为，关闭最后一个标签页后软件自动新建一个主界面的标签页，因为不确定用户是不是不小心关掉的最后一个标签页，退出应用重新打开的话会消耗掉2~3秒的时间，当然如果可以的话加个判断第二次关闭最后一个标签页退出应用，360极速浏览器是这么做的，这里还是祝愿rx文件管理器越做越好，还是希望有能力者支持下开发者购买所有权版本，毕竟不锁绝大多功能的开发者不多。

**Comment by zhuxb711** [comment]
话说今天下载量暴涨，是被哪个大佬翻了牌子？
1.选中文件的问题，微软传统老BUG了，它默认的Shift快捷键选取有问题，第一次选择是好的，然后你在Shift其他的，起始位置就可能错乱了，还没想好怎么去覆盖它的行为
2.关闭最后一个标签页退出是看浏览器是这样设计的(Chrome/Edge)，不知道要不要改

**Comment by zhuxb711** [comment]
我会尽快发布下一个版本来解决现在的问题，你的建议可以采纳，但估计等到下下个版本（如果快的话我可以一周双版本）

**Comment by wy164519317** [comment]
rx现在可是被好多博主安利，看最近讨论不少，放平心态，尽力就好！用户建议都会向开发者提出自己心仪的功能，建议只是建议，不要给自己太大压力，毕竟没有软件能够让所有人满意，加油！

**Comment by wy164519317** [comment]
rx现在可是被好多博主安利，看最近讨论不少，放平心态，尽力就好！用户建议都会向开发者提出自己心仪的功能，建议这东西吧，少数服从多数嘛，不要给自己太大压力，毕竟没有软件能够让所有人满意，加油！

**Comment by zhuxb711** [comment]
Shift抽风暂时无解，请使用框选功能

**Comment by zhuxb711** [comment]
抱歉，您提出的建议应当于6.4.0上线，我不小心提前关闭 了这个issue，请知悉

**Comment by wy164519317** [comment]
太客气了老哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上7:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 反馈 (#165)





 
抱歉，您提出的建议应当于6.4.0上线，我不小心提前关闭 了这个issue，请知悉
