### ISSUE TITLE
文件关联的打开方式不对

### ISSUE THREAD

**Issue by TJU-kdj** [zhuxb711/RX-Explorer#166]
我在管理器中打开pdf和jpg都是用rx内置的查看器打开，但我想用adobe的软件查看，修改了文件打开方式也没用，.pdf的默认打开方式也是adobe

**Comment by zhuxb711** [comment]
经过调查，由于数据库的一些变动，可能会导致您在“选择其他应用”窗口弹出后清除该类型已保存的默认设置。对于目前的情况，请设定好默认打开方式后不要再次该类型的“选择其他应用”。如果您还发现有其他情况下也会丢失配置文件，请继续与我联系，谢谢~

**Comment by TJU-kdj** [comment]
试了一下，除了第一次设置的时候是用adobe dc打开的，之后打开又是用自带的PDF了

**Comment by zhuxb711** [comment]
如何复现此问题？目前我这里测试是只要不再打开“选择其他打开方式”，就可以一直保持使用上次设置的默认设置

**Comment by TJU-kdj** [comment]
![bug](https://user-images.githubusercontent.com/59144168/115944722-00f08f80-a4ea-11eb-9b2c-73c4e0dfb4f0.gif)

**Comment by zhuxb711** [comment]
ok了解，理论上不应该出现此行为，但我会继续调查该问题

**Comment by zhuxb711** [comment]
（我是被哪个大佬翻牌子了么？突然暴涨的下载量.....）

**Comment by TJU-kdj** [comment]
不知道啊，我只是个小网民😂

**Comment by zhuxb711** [comment]
版本6.3.7应当已修复此问题

**Comment by TJU-kdj** [comment]
问题好像没有解决，我用的是adobe acrobat dc

**Comment by kxyihxy** [comment]
我也使用的adobe acrobat dc，双击是内置查看器打开

**Comment by zhuxb711** [comment]
![GIF 4-29-2021 11-02-23 AM](https://user-images.githubusercontent.com/42038175/116497700-928d4200-a8da-11eb-9bef-9b4750d943c3.gif)
完全木得毛病

**Comment by kxyihxy** [comment]
但是我这边用不了，设置默认应用后，双击还是内置阅读器打开




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 文件关联的打开方式不对 (#166)





 

 完全木得毛病

**Comment by zhuxb711** [comment]
我研究了一下代码，发现可能有一条路径使得无法设置为默认打开方式。
需要满足以下条件：
1. 从未在RX中设置使用Adobe打开pdf
2. Win10中已设置为使用Adobe作为pdf的默认打开方式
3. 在RX中右键-选择打开方式-发现Adobe出现在"继续使用以下应用"一栏中
4. 勾选“默认使用此应用打开该类型文件”
点击确定后，首次可使用Adobe打开，但是后续仍继续使用内置PDF查看器。

那如何让RX确实使用Adobe打开呢？
1. 系统中设置其他PDF软件作为默认打开方式
2. 在RX的选择打开方式中，从“选择其他应用”一栏中选择Adobe软件，勾选“默认使用此应用打开该类型文件”
或
1. 在RX的选择打开方式中，在"选择其他应用"一栏中选择任意其他PDF软件，勾选“默认使用此应用打开该类型文件”
2. 再次点击选择打开方式，选中Adobe，勾选“默认使用此应用打开该类型文件”

请确认是否是该问题引起？对应的临时解决办法是否成功设置了Adobe作为默认打开方式？

**Comment by kxyihxy** [comment]
我系统默认PDF阅读器为adobe；
解决方法：
将系统默认pdf阅读软件调整为其他阅读器后，
设置RX里PDF格式文件打开方式为adobe，
将系统默认PDF阅读器设置为adobe，问题可以解决；
不管RX还是系统资源管理器里面双击PDF格式文件，打开方式皆为adobe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 文件关联的打开方式不对 (#166)





 
我研究了一下代码，发现可能有一条路径使得无法设置为默认打开方式。
 需要满足以下条件：
  
从未在RX中设置使用Adobe打开pdf
 
Win10中已设置为使用Adobe作为pdf的默认打开方式
 
在RX中右键-选择打开方式-发现Adobe出现在"继续使用以下应用"一栏中
 
勾选“默认使用此应用打开该类型文件”
 点击确定后，首次可使用Adobe打开，但是后续仍继续使用内置PDF查看器。
  
那如何让RX确实使用Adobe打开呢？
  
系统中设置其他PDF软件作为默认打开方式
 
在RX的选择打开方式中，从“选择其他应用”一栏中选择Adobe软件，勾选“默认使用此应用打开该类型文件”
 或
 
在RX的选择打开方式中，在"选择其他应用"一栏中选择任意其他PDF软件，勾选“默认使用此应用打开该类型文件”
 
再次点击选择打开方式，选中Adobe，勾选“默认使用此应用打开该类型文件”
  
请确认是否是该问题引起？对应的临时解决办法是否成功设置了Adobe作为默认打开方式？

**Comment by zhuxb711** [comment]
Ok，那这个问题可以确定了，是由于6.3.0版本引入的自动探测系统默认打开方式功能而带来的BUG。
原因是在引入这个功能之前，RX认为能够显示在"继续使用以下应用"一栏的必定是已经存储了的默认打开方式，在没有这个功能的时候，确实“继续使用以下应用”的唯一来源就是用户的设置。但引入这个功能后，若用户从未设置此类型的默认打开方式，则会自动探测系统默认打开方式，打破了之前的假设，但由于有一些代码没有更新，以至于如果您选择的仍然是"继续使用以下应用"一栏的内容，则不会保存至数据库(因此它假设此栏的唯一来源是数据库存储的设置，若无变化，则无需更新)

此问题将于下一个版本中修复
