### ISSUE TITLE
Acrylic特效偶尔失效

### ISSUE THREAD

**Issue by Eupphoria** [zhuxb711/RX-Explorer#167]
利用窗口最上面的操作栏进行拖动、或者点击时，透明特效会失效并回到纯色底色，在失去透明效果时再次拖动窗口一定会在拖动过程中恢复特效，停止拖动又会变成纯色，最后再随便操作数次之后，窗口在静止状态又会回到透明

这个缺点发生在任何一个页面中

**Comment by zhuxb711** [comment]
![GIF 2021-4-24 0-13-22](https://user-images.githubusercontent.com/42038175/115899902-eee30280-a491-11eb-9d2a-bd834e3ef51f.gif)
应该没有问题呀？
![image](https://user-images.githubusercontent.com/42038175/115899968-00c4a580-a492-11eb-8eb3-f6144c67f192.png)
尝试勾选这个“始终应用Acrylic效果”看看？

**Comment by Eupphoria** [comment]
好的收到了，我今天打开电脑也没办法复现昨晚的bug，所以暂时没事了，下次好好研究是哪个部分出了问题再给你反馈，或许不会出现了吧，谢谢你




钟彬&nbsp;Neil
***@***.***

华南师范大学&nbsp;SCNU
English&nbsp;Translation&nbsp;Major


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 凌晨0:15
***@***.***&gt;;
抄送:&nbsp;"钟彬 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] Acrylic特效偶尔失效 (#167)





 

 应该没有问题呀？
 
 尝试勾选这个“始终应用Acrylic效果”看看？

**Comment by zhuxb711** [comment]
不用谢，我关闭这个Issue了
