### ISSUE TITLE
win10 20h2版本 rx文件管理器的右键功能延迟严重，点击后十几秒后才反应弹出

### ISSUE THREAD

**Issue by sdjames64157** [zhuxb711/RX-Explorer#169]

**Comment by sdjames64157** [comment]
![Uploading 动画2.gif…]()

**Comment by sdjames64157** [comment]
> _No description provided._

![动画2](https://user-images.githubusercontent.com/50286370/115911809-21e0c280-a4a1-11eb-9253-6abe253edc80.gif)

**Comment by zhuxb711** [comment]
右键菜单延迟是由于RX需要请求系统然后获取系统菜单而导致的，部分系统可能需要的时间过长，为避免时间过长的问题，您可以进入设置，关闭“扩展右键菜单”以保证最快速的展开，在这种情况下，您将无法获取系统菜单项，但可避免时间过长的问题

**Comment by sdjames64157** [comment]
感谢，关闭扩展后确实能解决问题！
