### ISSUE TITLE
默认打开RX-Explorer

### ISSUE THREAD

**Issue by FerryChan666** [zhuxb711/RX-Explorer#17]
在任务栏上点击此电脑，默认打开RX-Explorer，要如何更改为正常？卸载软件就会出现“文件没有与之关联的程序"

**Comment by zhuxb711** [comment]
请详细阅读RX设置中有关WIN+E开关开启的有关说明和指南，其中注明您必须在卸载RX文件管理器之前关闭WIN+E开关
