### ISSUE TITLE
快速启动的瑕疵

### ISSUE THREAD

**Issue by Xtimeshadow** [zhuxb711/RX-Explorer#170]
快速启动添加远程桌面连接点击后不是提示在最上一层，而是被软件本身覆盖

**Comment by zhuxb711** [comment]
这是微软的问题了，RX仅能提供启动动作，但微软不允许调整UWP应用的Z轴顺序，因此您在RX中点击的时候系统会认为您仍然在使用RX，所以其他应用无法到最前，这也是目前UWP的一个缺点吧。

如果微软不开放API，则无法解决此问题
