### ISSUE TITLE
部分快捷方式打不开

### ISSUE THREAD

**Issue by li470601611** [zhuxb711/RX-Explorer#171]
win资源管理器是正常的，这个软件打不开，图标是白色的，属性页一打开软件就报错。
[Export_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6369166/Export_Error_Log.txt)

**Comment by zhuxb711** [comment]
你这个是什么软件的快捷方式？我看到在获取这个快捷方式的信息的时候系统给出了没有注册接口的异常，该快捷方式不能正常获取其信息

**Comment by zhuxb711** [comment]
但是就算不能获取快捷方式，也不应该报错而崩溃，我会在下一个版本中修复这些问题，确保即使无法获取快捷方式也不会崩溃

**Comment by li470601611** [comment]
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 部分快捷方式打不开 (#171)





 
你这个是什么软件的快捷方式？我看到在获取这个快捷方式的信息的时候系统给出了没有注册接口的异常，该快捷方式不能正常获取其信息
