### ISSUE TITLE
文件夹重命名和新建文件夹问题

### ISSUE THREAD

**Issue by FM131** [zhuxb711/RX-Explorer#172]
![image](https://user-images.githubusercontent.com/83116487/115954436-971fb800-a4e0-11eb-8322-9fc050d0fd26.png)
无法通过回车键确认操作！没法重命名和新建文件夹的文件管理器？？？？？

**Comment by zhuxb711** [comment]
首先你用的什么版本？况且6.3.5版本已重新恢复此功能

**Comment by FM131** [comment]
![image](https://user-images.githubusercontent.com/83116487/115954870-d0592780-a4e2-11eb-805f-d4be579daf7
最新版，新建文件夹后根本取消不了，就一直卡着，非要退出重进，这是个啥呀

**Comment by FM131** [comment]
![image](https://user-images.githubusercontent.com/83116487/115954907-0e564b80-a4e3-11eb-8d6b-e40c8d049c4a.png)

**Comment by FM131** [comment]
退回前一级目录还在这里卡着，我服了
![image](https://user-images.githubusercontent.com/83116487/115954928-2928c000-a4e3-11eb-9e67-4386961d8d9b.png)

**Comment by FM131** [comment]
> 首先你用的什么版本？况且6.3.5版本已重新恢复此功能

最新版
自己看，这是什么呀

**Comment by FM131** [comment]
> 首先你用的什么版本？况且6.3.5版本已重新恢复此功能

![image](https://user-images.githubusercontent.com/83116487/115955026-bc61f580-a4e3-11eb-9b8a-27d8fb3cbe38.png)

**Comment by FM131** [comment]
> 首先你用的什么版本？况且6.3.5版本已重新恢复此功能
![image](https://user-images.githubusercontent.com/83116487/115955043-d3a0e300-a4e3-11eb-898d-3769d94da03f.png)
现在还在这里卡着呢

**Comment by FM131** [comment]
> 首先你用的什么版本？况且6.3.5版本已重新恢复此功能

![image](https://user-images.githubusercontent.com/83116487/115955231-dc45e900-a4e4-11eb-89bf-be499156b970.png)
！！！！！！！！！！！

**Comment by FM131** [comment]
就这

**Comment by zhuxb711** [comment]
激动啥，有Bug会调查的，我跟你确认版本是因为 #88 6.3.1版本移除了这个功能，这个版本才带回来，原来移除就是因为有问题

**Comment by FM131** [comment]
> 激动啥，有Bug会调查的，我跟你确认版本是因为 #88 6.3.1版本移除了这个功能，这个版本才带回来，原来移除就是因为有问题
主要是新建个文件夹，一直卡在那里，他也影响正常使用呀！这种功能不应该是最基础的嘛

**Comment by zhuxb711** [comment]
你可以用右键去重命名，这样应该没有问题，关于这个直接重命名的方式的BUG，我会继续调查的，有任何进展，我会在这里通知您，谢谢~~~~

**Comment by FM131** [comment]
> 你可以用右键去重命名，这样应该没有问题，关于这个直接重命名的方式的BUG，我会继续调查的，有任何进展，我会在这里通知您，谢谢~~~~

直接重命名，弹出对话框的时候可以用！现在主要是没法新建文件夹，就算新建的文件夹使用默认名称都不行。更别说在新建文件夹时更改名字了。总是会卡住，甚至会影响到上一级菜单里的文件！每次新建文件夹还要返回win10自带的文件管理里去新建！

![image](https://user-images.githubusercontent.com/83116487/115956778-529b1900-a4ee-11eb-876b-2c2e2f96b824.png)
![image](https://user-images.githubusercontent.com/83116487/115956780-575fcd00-a4ee-11eb-8eac-719e612f96b1.png)
![image](https://user-images.githubusercontent.com/83116487/115956781-59c22700-a4ee-11eb-9502-d13f95fd2bd5.png)

**Comment by Golden-Mean** [comment]
这个不能新建问题很大 .而且你点到其他目录去 同时会将其他目录的文件名称显示覆盖掉 切换后还原了 虽说不是真正意义上的覆盖 但是这真的很让人困恼 .希望能尽早解决 特意购买支持下 希望你们越做越好

**Comment by zhuxb711** [comment]
哈其实只有我一个人做，偶尔有热心童鞋帮忙提个PR这个样子，感谢支持，突然很多人关注到RX，提了很多问题，但开发和修复需要时间，我会尽力尽快解决所有问题（话说你们是在哪里发现的RX）

**Comment by zhuxb711** [comment]
此问题比较神奇，正在努力调查中，如果有任何进展，我会在此通知您

**Comment by FM131** [comment]
> 哈其实只有我一个人做，偶尔有热心童鞋帮忙提个PR这个样子，感谢支持，突然很多人关注到RX，提了很多问题，但开发和修复需要时间，我会尽力尽快解决所有问题（话说你们是在哪里发现的RX）

哈哈
![image](https://user-images.githubusercontent.com/83116487/115962350-66547880-a50a-11eb-9c53-c2f31d7f07b0.png)
最近短视频平台有人在介绍这款软件，就特意去商城里找了找！目前就发现这么一个影响正常使用的问题。其他地方都还可以。

**Comment by zhuxb711** [comment]
此问题已调查清楚，影响范围仅限新建文件夹的时候的重命名。
RX在6.3.5版本中更改了直接重命名的机制，使得其更加合理，但是由于一些疏忽，并没有更改创建文件夹时的一些代码，致使以新建文件夹的时候弹出的命名框框不会消失，我已修复此问题并将于下一个版本中解决。下一个版本将于下星期晚些之后和其他修复补丁一起发布
![GIF 2021-4-24 23-24-15](https://user-images.githubusercontent.com/42038175/115963902-37fb8b00-a554-11eb-8079-6182b409bacb.gif)

**Comment by zhuxb711** [comment]
版本6.3.7已发布
