### ISSUE TITLE
选择恢复上次打开的标签页不生效

### ISSUE THREAD

**Issue by stoneliulei** [zhuxb711/RX-Explorer#175]
![image](https://user-images.githubusercontent.com/9544719/115957463-40909900-a535-11eb-81b6-7dde9fcff72b.png)
启动时 ：选择恢复上次打开的标签页不生效
需要怎么解决？

比如上次打开了3个标签页，每次新启动的只有一个 我的电脑

**Comment by zhuxb711** [comment]
按照设计，RX需要正常退出以记录打开的标签页，如果您上次是崩溃退出的，则默认回到主页。另外如果在恢复标签页时遇到错误，也会回到主页

**Comment by stoneliulei** [comment]
> 按照设计，RX需要正常退出以记录打开的标签页，如果您上次是崩溃退出的，则默认回到主页。另外如果在恢复标签页时遇到错误，也会回到主页

好的，谢谢

**Comment by zhuxb711** [comment]
不过我也发现这个功能在某些情况下可能会缺失标签页，标签页太多也可能导致崩溃，将于下一个版本中修复
