### ISSUE TITLE
新建文件 .gitignore 失败

### ISSUE THREAD

**Issue by nov30th** [zhuxb711/RX-Explorer#176]
提示格式不正确。并无法建立文件。

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/115963627-b8b98780-a552-11eb-9ca5-22fb56176ea6.png)
可以啊，还是我理解错了？可以创建呀

**Comment by nov30th** [comment]
新建文件名为 ".gitignore" 失败。
github默认ignore文件，不带前缀。

**Comment by nov30th** [comment]
![image](https://user-images.githubusercontent.com/11451122/115987420-a5a4c700-a5e7-11eb-9383-f72cf9aa80b9.png)
![image](https://user-images.githubusercontent.com/11451122/115987442-bc4b1e00-a5e7-11eb-810c-ebe0da17d659.png)

**Comment by zhuxb711** [comment]
ok了解了，RX设计为新建文件必须具备文件名和扩展名，以目前的情况，其实是有文件可以只有扩展名的（或者是文件名以.开头？）。后续版本中我将更改，只要二者其中一个有内容即允许创建

**Comment by FlyingDragon0420** [comment]
二者其中一个有内容即允许创建比较合理

**Comment by zhuxb711** [comment]
版本6.3.7已发布

**Comment by nov30th** [comment]
6.3.7 市场更新后似乎这部分没有修改，和原来现象一样。

另外同时输入文件名与文件类型，删除文件类型所有字符后，点击确定会使用删除之前的扩展名。

**Comment by zhuxb711** [comment]
抱歉，搞错了，应该是于6.4.0版本中上线
