### ISSUE TITLE
大哥，你解压只是别zip文件能不能直接调用系统默认解压软件啊 

### ISSUE THREAD

**Issue by Stars-and-sea** [zhuxb711/RX-Explorer#177]
还有，右键菜单能不能不要折叠啊，右击菜单要的就是一个方便快捷，你把它折叠起来干嘛？那我直接属性不行吗？

**Comment by zhuxb711** [comment]
你的折叠是指？可以调用默认解压软件，只是这个6.3.5版本有一些问题

**Comment by Stars-and-sea** [comment]
就是，你至少吧常用的功能弄成列表，比如复制粘贴重命名解压，我感觉做成图标不方便。打开方式最好有缓存，文件夹也要有打开方式，我是一个前端学习者，有一些项目需要直接通过整个文件夹打开的，今天才接触到这个软件，然后感觉有点卡，启动慢，虽然确实有比自带的做的好的地方，但是我觉windows自带的只是功能的欠缺，并没有多余的功能。个人愚见。

**Comment by zhuxb711** [comment]
没事没事，多交流。

右键菜单项是有限制的，根据微软的指导，其建议上限为10个，RX需要适配各种分辨率的屏幕，因此右键菜单过长可能会导致部分设备上被遮挡(其实可以滚动，但是微软没开API来设置最大高度所以不可以滚)，因此右键菜单不可以过长，只能进行权衡。若您不习惯，可以配合键盘快捷键来完成。

打开方式是有缓存的，但是需要等待以比对数据，毕竟Win上文件关联其实经常有变化的，推荐项也会有变化

**Comment by Stars-and-sea** [comment]
文件夹的打开方式要有，您也是开发者，想也有同样的需求

**Comment by zhuxb711** [comment]
不过您可以通过右键文件夹，选择那些程序来打开，比如“使用VSCode打开”
