### ISSUE TITLE
文件名称排序错误

### ISSUE THREAD

**Issue by BlueApple233** [zhuxb711/RX-Explorer#18]
RX管理器会将文件和文件夹名称里的数字按照1 10 11......2 20这样的顺序排列，希望能够修复

**Comment by BlueApple233** [comment]
![JCUE(C_WBOF 3B~~3PLD5F](https://user-images.githubusercontent.com/69099171/89846893-f8317680-db71-11ea-977c-ddeed79d4046.png)
ru't如图

**Comment by BlueApple233** [comment]
![JCUE(C_WBOF 3B~~3PLD5F](https://user-images.githubusercontent.com/69099171/89846918-07b0bf80-db72-11ea-8962-ca12e184b71c.png)
如图

**Comment by zhuxb711** [comment]
从计算机的角度出发，这样的排序并没有问题，因为排序是依据ASCII码来排序的而不是根据名称里面的数字来排序的。
但从用户的角度出发，确实是您指出的这种排序方式是最直观的，因此RX将于下一个版本中更改排序规则。

**Comment by zhuxb711** [comment]
版本5.2.6已发布
