### ISSUE TITLE
希望添加可设置选项：文件夹默认展示形式

### ISSUE THREAD

**Issue by weijiachen12** [zhuxb711/RX-Explorer#180]
目前商店最新版只能一详细信息形式展示，希望增加默认展示形式选项，可以在平铺，详细信息等选项之中设置默认。

**Comment by zhuxb711** [comment]
RX会自动记住您对任意文件夹的更改，并在下一次显示时应用，比如您在下载文件夹更改为平铺，则您下一次进入下载时将以平铺显示而不是详细信息
