### ISSUE TITLE
无法更改pdf默认打开方式

### ISSUE THREAD

**Issue by wyxhappy365** [zhuxb711/RX-Explorer#181]
版本：6.3.5.0 Microsoft store下载
问题：只能使用RX自带的文件查看器，无法修改pdf的打开方式
![image](https://user-images.githubusercontent.com/65210568/115977841-23e47780-a5ae-11eb-9e7d-59a3e89cd2ce.png)
选择修改后
![image](https://user-images.githubusercontent.com/65210568/115977857-45456380-a5ae-11eb-8e3d-1256d50e507a.png)
再次查看，还是RX自带的查看器
![image](https://user-images.githubusercontent.com/65210568/115977873-5ee6ab00-a5ae-11eb-9bdb-995b85f77db6.png)
希望能修复，谢谢

**Comment by zhuxb711** [comment]
需要在选择其他应用的窗口内勾选“默认使用此应用打开此类型的文件“

**Comment by wyxhappy365** [comment]
是这样吗？
![image](https://user-images.githubusercontent.com/65210568/115978190-53947f00-a5b0-11eb-9148-d5da4cebf6d8.png)
![image](https://user-images.githubusercontent.com/65210568/115978226-7fb00000-a5b0-11eb-8123-4c15e5e1d309.png)
然而设置完成后，再次打开还是RX自带的查看器
![image](https://user-images.githubusercontent.com/65210568/115978274-bb4aca00-a5b0-11eb-9576-57d898713d85.png)
![image](https://user-images.githubusercontent.com/65210568/115978283-c7cf2280-a5b0-11eb-8e58-53468ebc090d.png)
谢谢！

**Comment by zhuxb711** [comment]
现在已知有一个问题就是设置完默认打开方式后，如果您再次打开“选择其他应用”的窗口，则会重置为默认值（也就是内置查看器），您看看是不是这个问题呢？

**Comment by wyxhappy365** [comment]
您好，应该是这个问题，当我设置完默认打开方式后确实会使用其他软件打开pdf，如图：
![image](https://user-images.githubusercontent.com/65210568/115978779-8fc9de80-a5b4-11eb-9a29-165ef01ce830.png)
但其他文件还是只会使用RX内置的文件查看器，如图：
![image](https://user-images.githubusercontent.com/65210568/115978811-d6b7d400-a5b4-11eb-9961-2ff3d97bf837.png)
且关闭刚才设置过打开方式的文件后，依然会自动变回RX自带的文件查看器：
![image](https://user-images.githubusercontent.com/65210568/115978879-12eb3480-a5b5-11eb-9b9f-8aa9539671ee.png)
我尝试修改其他类型文件的打开方式，比如.jpg、.m4a等都可以成功修改，目前只发现.pdf类型的文件会出现这样的问题：无法修改打开方式
谢谢

**Comment by zhuxb711** [comment]
所以您的意思是，设置为默认打开方式后，就算不再打开”选择其他打开方式“的窗口，也是会重置为默认的内置查看器嘛？这个与特定软件有关嘛？您可以试试将Edge设置为默认打开方式？

**Comment by zhuxb711** [comment]
我这边拿Edge做实验，是直接设置为默认打开方式之后就生效了

**Comment by wyxhappy365** [comment]
好像是跟软件有关，修改为Edge确实可以，但是修改为Adobe Acrobat Pro 2017就会失败。。。
这个有办法修复吗？因为我平时都是使用Acrobate的
谢谢！

**Comment by zhuxb711** [comment]
我下了Acrobat 2017好像。。也没有复现你遇到的问题

**Comment by wyxhappy365** [comment]
那我卸载后再重新安装尝试一下

**Comment by wyxhappy365** [comment]
我重新卸载安装后依然出现这一问题，我刚刚尝试先将打开方式改为Edge，修改成功，在这一设置下，将打开方式改为Acrobat 2017就会自动变回RX文件管理器，如图：
![image](https://user-images.githubusercontent.com/65210568/115986510-1a293700-a5e3-11eb-8f55-3f70d7198489.png)
![image](https://user-images.githubusercontent.com/65210568/115986530-30cf8e00-a5e3-11eb-989b-981802c9d2a0.png)
![image](https://user-images.githubusercontent.com/65210568/115986539-3e851380-a5e3-11eb-8428-7df2a51c2c4b.png)
我使用的系统版本为
![image](https://user-images.githubusercontent.com/65210568/115986590-79874700-a5e3-11eb-812e-293bbf2c7744.png)
Acrobat 2017的版本为：
![image](https://user-images.githubusercontent.com/65210568/115986606-97ed4280-a5e3-11eb-84e2-12e82c660ab9.png)
真的哭了，不知道问题出在哪里
非常感谢您！

**Comment by zhuxb711** [comment]
请等待6.3.7版本以确定该问题是否已经被修复

**Comment by wyxhappy365** [comment]
好的好的！非常感谢！

**Comment by zhuxb711** [comment]
问题已定位，将于6.4.0中修复

**Comment by wyxhappy365** [comment]
好的好的！非常感谢！
