### ISSUE TITLE
怎么设置everything的搜索，搜索那个按钮一直是灰色的

### ISSUE THREAD

**Issue by lwcye** [zhuxb711/RX-Explorer#182]
怎么设置everything的搜索，那个按钮一直是灰色的
而且已经18块钱支持开发
![image](https://user-images.githubusercontent.com/12707243/115978454-129d6a00-a5b2-11eb-81bd-afcbbe2abca1.png)
![image](https://user-images.githubusercontent.com/12707243/115978469-25b03a00-a5b2-11eb-89a8-c8df58275519.png)
![WQKOD)3%JP5 ~2QH5VQ5_%3](https://user-images.githubusercontent.com/12707243/115978538-a40cdc00-a5b2-11eb-9a78-7a175535f9e4.png)

**Comment by zhuxb711** [comment]
使用Everything需要：
1.购买
2.下载并保持Everything运行

**Comment by lwcye** [comment]
已购买，而且Everything运行中
![image](https://user-images.githubusercontent.com/12707243/115978611-29908c00-a5b3-11eb-957c-9c9fdcba7b7a.png)

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/115978643-6b213700-a5b3-11eb-8614-816694ea2e51.png)
应该是可以的，或许您可以重启一下Everything或者RX

**Comment by lwcye** [comment]
好了，重启没管用，然后我尝试把Everything升级到最新版本就可以了

**Comment by zhuxb711** [comment]
哈那就行~~~~可能是旧版本的Everything有什么BUG，RX需要探测Everything并且Everything给出回应才可以使用它的
