### ISSUE TITLE
建议添加最近访问文件和最近访问文件夹

### ISSUE THREAD

**Issue by TEEENEEET** [zhuxb711/RX-Explorer#184]
希望能在主页添加最近访问的列表，然后一个次建议是在主页添加搜索栏。

**Comment by TEEENEEET** [comment]
有一位朋友也提问了想同问题，但是没有被回答！看来被主理人无视了！

**Comment by zhuxb711** [comment]
不是，目前核心在于修复一些比较严重的Bug，issue也很多。最近访问可以通过右键RX的任务栏区域获得，里面有个近期 这样的分区

**Comment by TEEENEEET** [comment]
> 不是，目前核心在于修复一些比较严重的Bug，issue也很多。最近访问可以通过快捷的RX的任务栏区域获得，里面有个近期这样的分区

不好意思 没找到您说的那个快捷方式！

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/116036552-764e9280-a699-11eb-8e56-b7f552d38f96.png)
抱歉打错字，右键任务栏的RX

**Comment by zhuxb711** [comment]
主页搜索栏和地址栏于6.4.5已经上线了，最近访问记录暂时没有计划
