### ISSUE TITLE
<优化>

### ISSUE THREAD

**Issue by qiyueq** [zhuxb711/RX-Explorer#186]
蓝色选中标志与鼠标之前有很大的延迟

**Comment by zhuxb711** [comment]
这个是所有的文件夹都是这样的情况吗？能否在出现这种情况后前往设置中点击最底下有个导出日志文件然后发给我看看呢？

**Comment by qiyueq** [comment]
是 
[Uploading Export_All_Error_Log.txt…]()

**Comment by qiyueq** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6372165/Export_All_Error_Log.txt)

https://user-images.githubusercontent.com/83166187/115997520-ef0c0b00-a615-11eb-8a74-c2e412ce7fe3.mp4

**Comment by zhuxb711** [comment]
ok我想这是单选模式会在延迟800ms后才选中，目的是和系统文件管理器保持一样的行为，因为系统文件管理器也是这样的

**Comment by zhuxb711** [comment]
但似乎，已经划过去的不应该选中，可能还是有些问题

**Comment by zhuxb711** [comment]
这是一个Bug，将于6.3.7版本中修复，我已提交应用商店审核

**Comment by zhuxb711** [comment]
版本6.3.7已发布
