### ISSUE TITLE
文本编译器

### ISSUE THREAD

**Issue by Luo-Xinmin** [zhuxb711/RX-Explorer#189]
自带的文本编译器不支持回车，修改后保存文件夹会回退到上一层。
个性化若用纯色，白色后，文件名字等于无，因为是白色字体，所以看起来像没有一样。

**Comment by zhuxb711** [comment]
个性化用纯色后，如果您选择的是白色，则文字应当会自动更改为黑色以匹配您的纯色设置

**Comment by Luo-Xinmin** [comment]
![纯色](https://user-images.githubusercontent.com/75711845/116028428-bdcd2280-a689-11eb-8018-5ed600985188.png)

文本编译实在修改文本的时候遇到的。

**Comment by zhuxb711** [comment]
emmm您是如何操作然后使得上述那两个文件变成白色的呢？这有助于帮助我复现并找到问题根源，然后修复它

**Comment by Luo-Xinmin** [comment]
我就是在设置中设置个性化设置模式中选择纯色，然后点击坐上角的<—返回就出现了

**Comment by zhuxb711** [comment]
那两个变白色的文件您是否有进行过什么操作嘛？

**Comment by Luo-Xinmin** [comment]
操作后只要重启应用就好了，我这会在操作表，修改后就没在出现问题。又试了几遍发现没法再次复现问题。具体原因我也就不是很清楚了，抱歉。

**Comment by zhuxb711** [comment]
ok，那我先关闭这个Issue了

**Comment by zhuxb711** [comment]
文本编辑器的问题将于6.4.0中修复
