### ISSUE TITLE
不能显示.lnk快捷方式，希望RX可以显示！加油！

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#19]
隔壁的Files UWP已可以显示，你也可以做到

**Comment by zhuxb711** [comment]
#### 该Issue已过时，RX已于[此提交](https://github.com/zhuxb711/RX-Explorer/commit/feddf2d7a57035ccb317f384c2b7b7d643a67a1c)中支持lnk文件显示，目前处于开发阶段，尚未发布，预计下一版本将提供相应的支持
(你们都对比着来用的嘛......要是没记错Files UWP也是这几天才支持的)

**Comment by XSH-Hero** [comment]
好的！期待下一个版本的出色表现！

**Comment by zhuxb711** [comment]
版本5.2.6已发布
