### ISSUE TITLE
所处网络受限，无法从windows store下载，如何离线安装？谢谢

### ISSUE THREAD

**Issue by juneybw** [zhuxb711/RX-Explorer#190]
所处网络受限，无法从windows store下载，如何离线安装？谢谢，或者离线购买也行。

**Comment by zhuxb711** [comment]
您可以从Github下载侧载包，侧载包本身是仅供开发使用，但现在亦提供给不愿意等待微软审核更新/无法从微软商店下载的用户。

下载的位置在 [这里](https://github.com/zhuxb711/RX-Explorer/releases)
![image](https://user-images.githubusercontent.com/42038175/116027520-b60c7e80-a687-11eb-9645-2b015e2655b3.png)
找到具有SideLoadPackage名称的包，点击即可下载

下载后，解压，找到文件夹内的Install.ps1，右键它，选择“使用Powershell运行”。跟随Powershell一步步安装即可(可能需要UAC提权到管理员权限)。
![image](https://user-images.githubusercontent.com/42038175/116027681-18fe1580-a688-11eb-85f0-44b1619ce977.png)


请注意，您在首次使用Powershell安装RX之后，后续更新包您可以不通过Install.ps1安装，可以直接双击后缀为.msixbundle的文件来安装（原因是首次安装需要安装证书，用Powershell比较快，可以一键安装，后续无需再次安装证书）
![image](https://user-images.githubusercontent.com/42038175/116027713-2e733f80-a688-11eb-98cb-5b6d3d60495b.png)

请注意，使用侧载包安装的应用无法从应用商店更新，您需要每次新版发布之后手动下载新的侧载包，建议您订阅此Github的新版Release通知。同时，侧载包可能无法联系应用商店以解锁付费功能(因为它不是从应用商店下载的)。如果有可能，还是十分建议您从应用商店下载软件。

(现在可以稍微等一下，我1个小时后会发布新版6.3.7以解决6.3.5中的许多问题)

**Comment by juneybw** [comment]
已成功安装！开发者选项那里能否选回去？

**Comment by zhuxb711** [comment]
这个不清楚诶，不过放着不关也没事
