### ISSUE TITLE
个性化问题

### ISSUE THREAD

**Issue by Luo-Xinmin** [zhuxb711/RX-Explorer#195]
切换成纯色后有些文件名不会切换成黑色字体

https://user-images.githubusercontent.com/75711845/116066308-7ad77300-a6ba-11eb-8cea-76c44141d7d3.mp4

**Comment by zhuxb711** [comment]
我想这个是由于文件颜色标记功能导致的，现在下一个版本(6.4.0)已经针对这一块进行了改动，不会再有类似的问题，以下是效果预览
![image](https://user-images.githubusercontent.com/42038175/116108453-7de85880-a6e6-11eb-9f28-7613db2a8807.png)

**Comment by zhuxb711** [comment]
我想这个是由于文件颜色标记功能导致的，现在下一个版本(6.4.0)已经针对这一块进行了改动，不会再有类似的问题，以下是效果预览
![image](https://user-images.githubusercontent.com/42038175/116108453-7de85880-a6e6-11eb-9f28-7613db2a8807.png)

**Comment by Luo-Xinmin** [comment]
我并未对文件有任何的颜色标记

**Comment by zhuxb711** [comment]
Emmm Sorry，我的意思是这个问题的成因应该与文件标记功能有关，因为文件颜色的更改机制势必使得字体颜色不跟随RX的主题走，里面其实是自己实现了一套颜色变更机制的，因此可能有些问题。但在接下来的版本中我将移除这个机制，应该能够恢复正常

**Comment by Luo-Xinmin** [comment]
哦，谢谢耐心解答。
