### ISSUE TITLE
替换win10自带文件管理器

### ISSUE THREAD

**Issue by JackGlen1** [zhuxb711/RX-Explorer#197]
非常非常希望能够替换win10自带文件管理器，还是习惯性双击此电脑。希望作者能够出此项目，万分感谢耐心观看

**Comment by zhuxb711** [comment]
抱歉RX无法替换或者说不会提供官方替换方法，因为替换系统的管理器会有很多问题，比如控制面板，比如网络中心，这些都是系统资源管理器完成的(虽然看起来不像是同一个东西，但是确实是换皮了)，在系统级功能上RX无法进行替代，一旦完全替换势必导致这些功能崩溃

**Comment by JackGlen1** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        好的感谢您的回信
        
    
     
    
 

    在2021年4月26日 ***@***.***> 写道： 



抱歉RX无法替换或者说不会提供官方替换方法，因为替换系统的管理器会有很多问题，比如控制面板，比如网络中心，这些都是系统资源管理器完成的(虽然看起来不像是同一个东西，但是确实是换皮了)，在系统级功能上RX无法进行替代，一旦完全替换势必导致这些功能崩溃
