### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#198]
Version: 6.3.5.0

The following is the error message:

------------------------------------

Exception: System.NullReferenceException: Object reference not set to an instance of an object.

at RX_Explorer.FilePresenter.FilePresenter_obj39_Bindings.b__15_0(FrameworkElement, Object) + 0x8

at SQLitePCL.delegate_function_aggregate_final.Invoke(sqlite3_context, Object) + 0x2e

at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36

at RX_Explorer!+0x432587e

Message:

Object reference not set to an instance of an object.

StackTrace:

at RX_Explorer.FilePresenter.FilePresenter_obj39_Bindings.b__15_0(FrameworkElement, Object) + 0x8

at SQLitePCL.delegate_function_aggregate_final.Invoke(sqlite3_context, Object) + 0x2e

at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36

at RX_Explorer!+0x432587e

Extra info:

CallerMemberName: App_UnhandledException

CallerFilePath: D:\a\1\s\RX_Explorer\App.xaml.cs

CallerLineNumber: 102

------------------------------------

**Comment by zhuxb711** [comment]
这个错误报告我完全看不出来是哪里的问题.......是怎么触发的呢？

**Comment by taooceros** [comment]
好象是我挂在后台挂了一会，然后打开来就发生了

**Comment by taooceros** [comment]
我发现这个每次我把rx放在后台挂着，过一段时间打开就会出现这个报错

**Comment by zhuxb711** [comment]
可能是挂后台然后它挂起了？再恢复会有这个问题？

**Comment by taooceros** [comment]
> 可能是挂后台然后它挂起了？再恢复会有这个问题？

有可能

**Comment by zhuxb711** [comment]
我这里用VS挂起后再恢复是正常的，复现不出来这个问题

**Comment by taooceros** [comment]
> 我这里用VS挂起后再恢复是正常的，复现不出来这个问题

这样啊，我最近比较忙，待我忙完之后自己去测试一下

**Comment by zhuxb711** [comment]
有成功复现该问题嘛？

**Comment by taooceros** [comment]
最近一直比较忙，问题可以复现，但是没时间看看具体出在哪里

**Comment by zhuxb711** [comment]
好的，如果您有空的话可以帮忙看一下，谢谢~~~

**Comment by taooceros** [comment]
> 好的，如果您有空的话可以帮忙看一下，谢谢~~~

好的好的，我马上就要有空了hhh

**Comment by taooceros** [comment]
最近电脑丢去修了，可能得下周了😂

**Comment by zhuxb711** [comment]
我抓到这个BUG了，已修，所以发布之后我就会关闭这个issue

**Comment by taooceros** [comment]
okok, 感谢

**Comment by zhuxb711** [comment]
我复现这个问题是发现它会在更改系统主题（黑/白）的时候出现

**Comment by taooceros** [comment]
这确实有可能，我确实开了自动更换主题。不过我印象中好像出现的比切换主题更频繁一点。
