### ISSUE TITLE
希望能够关闭最小化时的弹窗

### ISSUE THREAD

**Issue by yuralandau** [zhuxb711/RX-Explorer#199]
我实在没能理解为啥最小化时会弹出弹窗是啥逻辑……希望能取消

**Comment by zhuxb711** [comment]
如果您正在执行任务，最小化RX可能导致其任务终止，没错UWP受到钳制就是这么大，没想到吧？
![image](https://user-images.githubusercontent.com/42038175/116111667-71b1ca80-a6e9-11eb-8604-9e4419380332.png)

在某些情况下，你最小化RX会导致所有的任务都像被暂停了一样，因为Win10中止了其执行，直到你重新点开RX
(和iOS有点像，但是UWP卡得更狠，在没有任何其他辅助措施得情况下，任何UWP最小化就一定会被立刻挂起，也称暂停执行)

最近的RX会在执行任务的时候申请扩展执行，可以暂时方式最小化RX导致的挂起问题，得以在最小化状态继续运行，微软关于扩展执行的时间表述如下：
![image](https://user-images.githubusercontent.com/42038175/116112500-32d04480-a6ea-11eb-984c-da5942b0d756.png)

对于台式计算机或连接电源的笔记本，RX在最小化执行时没有时间限制。对于使用电池的笔记本，RX将受到最大10分钟的配额限制(配额限制就是你现在用得多以后就只能越来越少的用了)，因此RX可能会在最小化状态被挂起甚至直接终止运行，这将导致用户的文件操作被迫中断，但是如果RX没有被最小化，则不受配额限制，因此在执行任何任务时，只要被最小化，RX都会提示您将其保持非最小化状态以避免意外终止。当然对于复制、移动、删除等关键任务，RX有独有的机制，可以确保即使RX被挂起，最多只是进度指示受到影响而不可用，而正在进行的此类任务仍将持续至完成后才会退出

**Comment by zhuxb711** [comment]
我将进行一些更改，如果现在计算机已接上电源，则不会显示该通知。

**Comment by yuralandau** [comment]
又学习了。👍
