### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by Mahan3340** [zhuxb711/RX-Explorer#2]
- Although the drag and drop works between the app and the windows desktop or windows file explorer, the copy/cut options do not, and I was wondering if it is possible to add that.
- The "Paste" option will be unavailable in the menu if some item is selected (accidentally, most of the time by touching)

Thanks for your continuous support.

**Comment by zhuxb711** [comment]
@Mahan3340 

- I don’t know why you need to copy and paste between this application and the system file explorer. Both are essentially file explorer.

- The “Paste” button only appears when you select a blank area

**Comment by Mahan3340** [comment]
@zhuxb711 

- Sometimes the app is open and wanted to copy something from desktop to the App or Vice or Versa quickly.
- That's the problem. There won't be a blank space when the list contains more than a specific set of items. That's why I used the bottom three-dot menu to paste when there's no keyboard, and when there is a file selected, there is no way to unselect it as there is no blank space to click to clear the focus.

**Comment by zhuxb711** [comment]
@Mahan3340 
Do you have any suggestions about "when there is no blank space to click".
I don't know how to improve this situation.

**Comment by Mahan3340** [comment]
@zhuxb711 I guess a similar workaround that has been used in the windows explorer could be good: If a file is selected to be copied or cut, then paste option appears in the right-click (long-pressed) or the bottom menu, even if a file is right-clicked (long-pressed). Thus, there is no need for explicit blank space any more. Now, if the menu is opened for a file, the paste would just simply copy/cut the previously selected file in the current folder. If the menu is opened for a folder, then the previously selected file would be copied/cut to the folder.

![Annotation 2020-05-26 101540](https://user-images.githubusercontent.com/21075867/82864504-ead4fa80-9f39-11ea-9478-4f45c56b0628.jpg)

**Comment by zhuxb711** [comment]
@Mahan3340 
The problem of “Paste” is solved, but there is still a problem that the blank area cannot be clicked under the "Detailed List". Do you want to remove the right-click menu of the entire blank area?

I still haven't found a compromise.

**Comment by Mahan3340** [comment]
@zhuxb711 I think a blank column could be added at the end to be used as a blank space. I just checked windows explorer and the used the same workaround. However, I believe if the paste option is fixed, then there is no need for a blank space to clear the selection anyway, as it won't cause any problems anymore.

**Comment by zhuxb711** [comment]
@Mahan3340 
The right-click menu in the blank area also contains a key function is "Create File / Folder".
Therefore, there is still a need to click on the blank area~~

**Comment by Mahan3340** [comment]
@zhuxb711 oh, I see. So I guess the extra column could be useful. Also, separate icons could be added on the top/bottom of the page, if the UX is appropriate. Though, I noticed that "Create File/Folder" is also available on the bottom menu, which is a good alternative. Besides, shortcuts (if not already available) could be useful while using keyboards to create files/folders.

**Comment by zhuxb711** [comment]
@Mahan3340 
I will consider the possibility of adding a blank column.
Thank you for actively discussing with me.

**Comment by zhuxb711** [comment]
@Mahan3340 
![image](https://user-images.githubusercontent.com/42038175/83320026-f6942a00-a275-11ea-8b98-c41b2e590841.png)
#### An additional column has been added. Right-click / touch long-press to eliminate the selected items and expand the "Blank Area Right-click Menu"

#### If you have no questions, I will close this issue later.

**Comment by Mahan3340** [comment]
@zhuxb711 sounds great!

**Comment by zhuxb711** [comment]
Close #2
