### ISSUE TITLE
模式选择“自定义”-Acrylic背景 没有反应

### ISSUE THREAD

**Issue by ArchKS** [zhuxb711/RX-Explorer#20]
模式选择Acrylic背景之后，更改颜色也没有反应，暂时只能用“推荐”和纯色两种，不知道在哪里开启毛玻璃特效。

**Comment by zhuxb711** [comment]
推荐模式下就已经具备毛玻璃效果了。如果您在设置界面里面更改主题颜色的话，需要将颜色透明度的滑动条降低~

**Comment by zhuxb711** [comment]
根据微软官方文档，Acrylic亚克力效果(即您指的毛玻璃效果)的适用场景如下，请比对是否满足要求:
![image](https://user-images.githubusercontent.com/42038175/90326721-42758600-dfbe-11ea-81ce-8c0377478d96.png)

**Comment by zhuxb711** [comment]
Hi，是否解决了您的问题？
