### ISSUE TITLE
桌面文件夹不能直接调用RX

### ISSUE THREAD

**Issue by HRxiaohu** [zhuxb711/RX-Explorer#200]
# 桌面文件夹双击无法使用rx打开

**Comment by zhuxb711** [comment]
RX不能成为默认的系统管理器，会影响Windows本身的许多功能。虽然不能够双击打开，但您可以使用右键菜单
![image](https://user-images.githubusercontent.com/42038175/116110073-f56ab780-a6e7-11eb-9038-cd8e3ab4c422.png)

**Comment by HRxiaohu** [comment]
谢谢
