### ISSUE TITLE
建议优化网络文件夹显示时间

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#201]
系统文件管理器基本秒开
![Animation](https://user-images.githubusercontent.com/41459054/116176135-31cc0100-a744-11eb-9533-c9bf8ad960a5.gif)

**Comment by zhuxb711** [comment]
UWP的文件API是没救的了，有些网络驱动器可以使用到Win32 API去读取，那就很快，如果不行，只能回退到UWP的文件系统API。虽然经过优化，还是很慢 (UWP所谓的安全，使得文件API的速度比Win32版本慢1000倍以上)，只能看.Net 6出来之后有木有改观
