### ISSUE TITLE
删除文件

### ISSUE THREAD

**Issue by Luo-Xinmin** [zhuxb711/RX-Explorer#203]
删除文件的时候，确定弹窗不会跳出。
https://user-images.githubusercontent.com/75711845/116177769-ff6fd300-a746-11eb-948e-8148a6f1a34b.mp4

**Comment by zhuxb711** [comment]
您可以在设置中决定是否让RX弹出确认删除弹框(系统那个管不了)

**Comment by Luo-Xinmin** [comment]
这样设置后它还是会再次提醒。

https://user-images.githubusercontent.com/75711845/116214472-5098ba80-a779-11eb-9b52-aa88abfb285c.mp4

**Comment by zhuxb711** [comment]
虽然我确实发现了一些代码上的问题，但仅在我这里是没有重复的确认框的，我会稍微更改一下，然后您可以在下一个版本中再次尝试。
