### ISSUE TITLE
付过费，但卸载重装RX后，搜索框还只能选择本地搜索，everything搜索单选框是灰色不可选择！

### ISSUE THREAD

**Issue by galaxySix** [zhuxb711/RX-Explorer#205]
反馈（FeedBack）：为了诚意支持开发者，所以付费软件了，但在使用时因卡死重装了RX ，发现搜索框又变成了付费前的样子-无法选择everything搜索（虽然设置中已经设置默认以everything来搜），此体验较差，辛苦开发同事高度重视并及时解决~让付费和软件质量形成正向良性循环。

建议(Comments)：
1.启动首页，确少搜索框，现在是只能在进入某磁盘后，才能搜索，有时全局搜索时不太方便
2.文件拖动逻辑，强烈建议与windows保持一致，默认拖动是赋值（摁住Ctrl再拖动效果一致），若是摁住shift再拖动，应该是移动，而可惜当前无论怎么拖动文件，都是复制。
3. 强烈建议参考MAC的文件管理，新增第三栏，最左侧是根目录树，中间是左侧目录树选定的文件夹内容展示，以此类推，新增第三栏展示中间文件夹列表中，选中的文件夹下的文件夹展示。这样会极大的减少双击文件打开的频率，降低文件定位的成本，增加工作效率。
4. 最后一点但也是最重要的一点，软件的稳定性还需加强，导出错误日志时看到了大量的连接数过多及mysql连接错误，请保证核心功能的性能稳定高效，在此基础上细化更多细节的优化。
5. Finally，愿RX早日名副其实的超越windows 的explorer，让更多用户喜欢上它，付费也是值得。

**Comment by zhuxb711** [comment]
搜索框在Everything的部分逻辑如下：
1.启动时检查应用商店的购买情况，一启动就检查以最大化响应能力。若已经存在购买，则写入存储并且以后无需再次检测。
2.检测Everything情况，尝试与其通信，若其不响应则认为Everything尚未在运行，禁用Everything搜索功能。

根据之前的报告，有人说Everything版本太旧也会导致无法识别到。您可以尝试在Everything运行时启动RX(但其实RX可以动态侦测)

拖动逻辑是按下Ctrl切换复制/粘贴，系统文件管理器也是这样的

稳定性的问题，其实大部分崩溃来自于微软框架，特别是直接闪退那种，如果是开发的问题，会进入到内置的蓝屏错误页面。Mysql连接错误是因为云端数据库只有900的最大连接数，最近暴涨的下载量直接搞炸了(我随便买的个数据库，哪知道有高并发的场景，最近使用的人以万记)

**Comment by silentmoooon** [comment]
可以搞个后端服务去连mysql

**Comment by zhuxb711** [comment]
不会，嘿嘿 @silentmoooon

**Comment by silentmoooon** [comment]
额,你技术这么6,只搞c/s么.
用.net core搞个后端应该也是小菜一碟才对.

**Comment by zhuxb711** [comment]
不是我买的是PaaS不是IaaS，（最近被公司要求考了Azure Fundamental AZ-900证书所以记这么清楚）直接就是云数据库的而不是虚拟机，所以也没办法布置后端，再加上我一直没搞过后端，云数据库又是刚刚续费的。。有一个办法是让MySQL每次获取的时候重连数据库，用完立马断开，我现在的设计是保持直到程序关闭

**Comment by silentmoooon** [comment]
哈哈,了解.
嗯,用完立马断开应该也够用了.

**Comment by lijialin9** [comment]
请问该问题什么时候可以解决，如果不解决付费还有什么意义？

**Comment by zhuxb711** [comment]
没有问题有什么解决的？
RX向Everything发送试探消息没有收到回复就是灰色的，就算开放也是没有办法搜索的，一般来说都是Everything没有配置好的问题

**Comment by lijialin9** [comment]
这个Everything我还以为是在应用商店下载的Everything呢，怎么都不管用，起码说一下啊，应该是这个文件搜索服务（https://www.voidtools.com/zh-cn/downloads/）

**Comment by lijialin9** [comment]
不允许内置安装，就贴个下载连接啥的，至少不会搞混

**Comment by zhuxb711** [comment]
贴链接不知道会不会有问题，以后可以改
