### ISSUE TITLE
内置文本编辑器

### ISSUE THREAD

**Issue by Xtimeshadow** [zhuxb711/RX-Explorer#206]
内置文本编辑器使用回车后，无法保留修改内容

**Comment by zhuxb711** [comment]
怎么使用回车？

**Comment by Xtimeshadow** [comment]
在内置编辑器内输入完成后按enter键，内容清空




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 下午3:01
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 内置文本编辑器 (#206)





 
怎么使用回车？

**Comment by zhuxb711** [comment]
该问题已确认，将于下一个版本中修复
