### ISSUE TITLE
建议添加的功能及需要更改的地方

### ISSUE THREAD

**Issue by MeteoriteXX** [zhuxb711/RX-Explorer#207]
建议添加一个删除驱动器的功能（指让驱动器不显示在列表里）
还有CD-ROM驱动器不显示问题，添加CD-ROM驱动器显示不是驱动器

https://user-images.githubusercontent.com/77538573/116496371-7dfb7a80-a8d7-11eb-9656-b3c73d987159.mp4

**Comment by zhuxb711** [comment]
很久之前有删除驱动器功能，但后来因为某些原因移除了。RX不支持CD驱动器

**Comment by RiverCrabs** [comment]
能不能实现桌面拖拽文件放进Rx文件管理器中的文件夹下，这个基础的功能我怎么实现不了？还是不能怎么使用？

**Comment by zhuxb711** [comment]
可以拖拽桌面文件到RX内呀，直接拖拽就可以了
