### ISSUE TITLE
xshell拖拽传文件没反应

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#208]
![Animation](https://user-images.githubusercontent.com/41459054/116526353-1875b100-a90c-11eb-9fd2-3b3a1bf695bc.gif)

**Comment by zhuxb711** [comment]
RX的拖拽都是交由系统API来传输的，具体过程不由RX控制，不清楚目标应用无法使用的原因

**Comment by zhuxb711** [comment]
![GIF 4-29-2021 5-37-53 PM](https://user-images.githubusercontent.com/42038175/116531378-b0c26480-a911-11eb-8951-9b88bdc80d1c.gif)
去Xshell下面提交issue吧，你看人家Powershell都有反应
