### ISSUE TITLE
怎么替换window10的默认资源管理器

### ISSUE THREAD

**Issue by as2517420** [zhuxb711/RX-Explorer#210]
有了RX很方便，但是没有办法把桌面上的文件夹双击用RX打开

**Comment by zhuxb711** [comment]
无法替换，如果您强行替换，需要自行承担风险，包括控制面板不可用等问题

**Comment by as2517420** [comment]
谢谢，那还是不要的好

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年5月1日 14:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [zhuxb711/RX-Explorer] 怎么替换window10的默认资源管理器 (#210)


无法替换，如果您强行替换，需要自行承担风险，包括控制面板不可用等问题

―
