### ISSUE TITLE
界面问题和安全域验证问题

### ISSUE THREAD

**Issue by lijialin9** [zhuxb711/RX-Explorer#211]
界面切换到安全域模块后软件左侧边缘会多出一块，切换到其他模块也不消失，移动软件界面消失，这应该是个bug吧。还有就是安全域的win hello验证，验证界面应该弹出到最前端。界面问题只是对于有强迫症的人来说看着不舒服，安全域验证却是影响使用体验，建议优化一下哈。

**Comment by zhuxb711** [comment]
这两个都是微软的框架Bug，作为开发者我无法修复

**Comment by lijialin9** [comment]
window是消息驱动的系统，系统api，例如user32.dll，应该还是可以处理的吧

**Comment by zhuxb711** [comment]
可能您不了解UWP吧，UWP能使用的所有API严格受控制，不是你想就可以用的。User32.dll名下所有API禁止访问

**Comment by lijialin9** [comment]
好吧

**Comment by zhuxb711** [comment]
微软的“安全”的代价┑(￣Д ￣)┍

**Comment by lijialin9** [comment]
局限性好大→_→反射有局限没？

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/116855040-410eeb00-ac2b-11eb-8ab5-65cd891d15b8.png)
反射的问题主要集中在[.Net Native](https://docs.microsoft.com/zh-cn/dotnet/framework/net-native/getting-started-with-net-native#Step2)上

**Comment by zhuxb711** [comment]
[这里](https://docs.microsoft.com/zh-cn/dotnet/framework/net-native/reflection-and-net-native)

**Comment by lijialin9** [comment]
-_-||这个反射毫无意义，只是能让自己的代码灵活一点
