### ISSUE TITLE
网络驱动映射磁盘(nas)不可拖至上传文件

### ISSUE THREAD

**Issue by ericxuyihao** [zhuxb711/RX-Explorer#213]
无法上传文件至内网nas 映射的本地磁盘

**Comment by zhuxb711** [comment]
有Gif或者视频可以参考吗？

**Comment by ericxuyihao** [comment]
您好:
  如视频所示拖动文件/文件夹 无法复制到盘中

发件人: Ruofan ***@***.***>
发送时间: 2021年5月5日 11:28
收件人: zhuxb711/RX-Explorer ***@***.***>
抄送: eric ***@***.***>; Author ***@***.***>
主题: Re: [zhuxb711/RX-Explorer] 网络驱动映射磁盘(nas)不可拖至上传文件 (#213)


有Gif或者视频可以参考吗？

**Comment by zhuxb711** [comment]
无法在网页端查看您的视频

**Comment by ericxuyihao** [comment]
***@***.***D7446A.289B7DA0]
就是说把文件从桌面拖入至硬盘中无法拖入

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年5月6日 23:36
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [zhuxb711/RX-Explorer] 网络驱动映射磁盘(nas)不可拖至上传文件 (#213)


无法在网页端查看您的视频

―
