### ISSUE TITLE
ctrl + t 快捷键无效

### ISSUE THREAD

**Issue by nuui** [zhuxb711/RX-Explorer#217]
有文件被选中的情况下 ctrl + t 无效

**Comment by zhuxb711** [comment]
设计上确实是Ctrl+T对文件是不起效果的

**Comment by zhuxb711** [comment]
考虑到该快捷键目标是打开新窗口，下一个版本中将改为对非文件夹对象使用此快捷键一律也打开标签页，只是不会导航到具体的位置

**Comment by zhuxb711** [comment]
6.4.5已发布
