### ISSUE TITLE
建议添加一个图片背景亮度调整功能

### ISSUE THREAD

**Issue by Yz-Leaf** [zhuxb711/RX-Explorer#218]
建议添加一个图片背景亮度调整功能，因为有图片过于鲜亮，不易看清文字，希望能调整图片的亮度

**Comment by zhuxb711** [comment]
现在可以调节背景的模糊度，以增加可读性，亮度调节不是不可以做，用OpenCV处理的话会比较卡，特别是大型图片

**Comment by Yz-Leaf** [comment]
thank you!!

**Comment by Yz-Leaf** [comment]
> 我想不出意外的话此功能将于下一个版本中上线

Thank you
