### ISSUE TITLE
Microsoft Store无法购买

### ISSUE THREAD

**Issue by leonme** [zhuxb711/RX-Explorer#222]
这款软件现在还在微软应用商店上架的， 但是需要兑换代码， 貌似下载不了， 是什么原因？ 怎么操作？ 抱歉对微软应用商店不熟， 望解答。

**Comment by zhuxb711** [comment]
由于6.4.4版本存在严重问题，为避免问题进一步扩大，现已临时下架直至微软通过新版6.4.5的审核，给您带来不便，请谅解。

新版发布后我将通知您，谢谢。

**Comment by zhuxb711** [comment]
@losic719 好的，周末微软商店没有过审，估计在放假
