### ISSUE TITLE
删除rx文件管理器后无法打开原本的文件管理器

### ISSUE THREAD

**Issue by qiyueq** [zhuxb711/RX-Explorer#224]

**Comment by zhuxb711** [comment]
为何总是看不到开启WIN+E前的提示？
![image](https://user-images.githubusercontent.com/42038175/117576457-ad508980-b118-11eb-9af1-dbb60eb1b2ef.png)

**Comment by zhuxb711** [comment]
如果您需要还原文件，可从WIN+E开关旁边的小问号中取得
