### ISSUE TITLE
无法成功安装，使用安装包安装时显示如下信息，证书已经安装。

### ISSUE THREAD

**Issue by Sever223** [zhuxb711/RX-Explorer#225]
此应用包未使用受信任的证书签名。请与系统管理员或应用程序开发人员联系，以获取新证书或带有受信任证书的应用程序包。应用程序包中签名的根证书和所有即时证书必须受信任（0x800B010A）

**Comment by zhuxb711** [comment]
可能是由于您的PC存在限制不受信任的证书的策略？建议使用Install.ps1来安装此应用
