### ISSUE TITLE
右键菜单建议增加快捷键

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#227]
![image](https://user-images.githubusercontent.com/41459054/117750203-99567600-b245-11eb-89aa-380318f3199d.png)
![image](https://user-images.githubusercontent.com/41459054/117750248-ac694600-b245-11eb-8678-c0922dec9558.png)

**Comment by zhuxb711** [comment]
有啥区别？右键菜单已经足够拥挤了。根据微软的建议，右键菜单项至多不超过10个

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/117751728-28648d80-b248-11eb-8581-1a381779a003.png)
我用的是不是盗版Win10

**Comment by FlyingDragon0420** [comment]
不好看。。。。像系统文件管理器一样，直接加在菜单后面呗

**Comment by FlyingDragon0420** [comment]
主要是支持功能，不要界面的提示都行，一般都是用惯了的，不需要看提示

**Comment by zhuxb711** [comment]
为啥英文版Win10没有这些快捷操作？如果要紧贴文字的话那其实就是改翻译文件.....

**Comment by zhuxb711** [comment]
这个建议不会实施，我将关闭这个issue，感谢
