### ISSUE TITLE
【提问】文件搜索栏如何关闭历史记录或者智能推荐？

### ISSUE THREAD

**Issue by ykytutou** [zhuxb711/RX-Explorer#229]
### 请问如何关闭历史记录和推荐？无奈于个人的强迫症，不想看见历史记录。
![image](https://user-images.githubusercontent.com/55079235/118247175-75a95f00-b4d5-11eb-9ec8-ef9e8723e75c.png)

**Comment by zhuxb711** [comment]
暂时无法关闭此功能，但是下一个版本中将允许删除搜索历史记录(需要单条删除)，对于您不需要的条目可以删除

**Comment by ykytutou** [comment]
好的，非常感谢！
