### ISSUE TITLE
【提问】关于选择“始终使用Everthing搜索引擎”时，主页搜索栏无法进行全局搜索。

### ISSUE THREAD

**Issue by ykytutou** [zhuxb711/RX-Explorer#230]
### 搜索引擎配置设置“每次询问”
> 主页搜索栏搜索“入党志愿书”，“全局搜索”功能默认选择并且可自主勾选，点击搜索后可以找到目标文件。

![image](https://user-images.githubusercontent.com/55079235/118248956-76db8b80-b4d7-11eb-8fa3-5a8d65a73001.png)
 
### 搜索引擎配置设置“始终使用Everthing搜索引擎”
> 主页搜索栏显示搜索“这台电脑”

![image](https://user-images.githubusercontent.com/55079235/118249384-f6695a80-b4d7-11eb-8943-a589913965df.png)

> 主页搜索栏搜索“入党志愿书”，点击搜索后无法找到目标文件。

![image](https://user-images.githubusercontent.com/55079235/118249470-0d0fb180-b4d8-11eb-9ec0-71499b1e7562.png)

> 目标文件位于我的D盘

![image](https://user-images.githubusercontent.com/55079235/118249601-2a448000-b4d8-11eb-9880-a7a704c92921.png)

> 进入D盘进行搜索，“入党志愿书”，可以找到目标文件

-----------------
> 不太清楚这是我的操作有误、理解偏差还是Bug，我的需求是在主页搜索栏始终进行Everthing的全局搜索，谢谢！

**Comment by zhuxb711** [comment]
此问题已知并且已于即将发布的6.5.0版本中修复
