### ISSUE TITLE
随系统自动启动无法开启

### ISSUE THREAD

**Issue by kevinsun6610** [zhuxb711/RX-Explorer#236]
![image](https://user-images.githubusercontent.com/38686609/118746144-3b034600-b88a-11eb-9783-15240207eee3.png)
![image](https://user-images.githubusercontent.com/38686609/118746181-4f474300-b88a-11eb-88e8-c7834e0f4f31.png)
里面没有开启随系统启动的开关

**Comment by zhuxb711** [comment]
请前往系统设置-应用-左边选择 启动 - 右边寻找是否有RX文件管理器。
但正常来说RX的应用设置内应当有这个启动的配置，不然就是系统BUG了
![image](https://user-images.githubusercontent.com/42038175/118747442-91718400-b88c-11eb-8fb7-6fa665f6c9ae.png)

**Comment by kevinsun6610** [comment]
系统版本
![image](https://user-images.githubusercontent.com/38686609/118748937-2bd2c700-b88f-11eb-905d-12f44813f7a3.png)
rx explorer版本
![image](https://user-images.githubusercontent.com/38686609/118749052-591f7500-b88f-11eb-9160-d842f250b36b.png)
还有个问题就是有时候启动rx explorer的时候系统盘符图标发生改变
![image](https://user-images.githubusercontent.com/38686609/118749112-76544380-b88f-11eb-86aa-6d14cc51adce.png)

**Comment by zhuxb711** [comment]
图标改变的问题是由于RX未能够在规定的时间内获取到磁盘图标，因此为了不空着，填充默认图标

**Comment by kevinsun6610** [comment]
是因为当前版本启动缓慢导致的么？下个版本修复了启动缓慢的问题就不会出现了是么？

**Comment by zhuxb711** [comment]
应该与启动缓慢关系不大，下版本会修复启动缓慢的问题

**Comment by zhuxb711** [comment]
6.5.5已发布，已解决启动缓慢的问题
