### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#237]
内置的PDF查看可以实现页面的转跳,不然页数太多时不方便
如图:
![屏幕截图 2021-05-22 215646](https://user-images.githubusercontent.com/62456287/119229082-c3167380-bb48-11eb-9501-3e4942f03d29.png)
靠鼠标滚轮太累了

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/119338637-d2b9c780-bcc2-11eb-90d2-8254cd4ebf7a.png)
下一个版本中内置PDF将得到加强。

包括
1. 可调节的缩放大小 (50%-500%)
2. 可在放大状态下直接滚动至下一页
3. 可直接根据页码跳转到指定页
4. 预加载逻辑更新
5. 可选垂直滚动/水平滚动
6. 显示当前文件名称
