### ISSUE TITLE
文件选择动画不统一

### ISSUE THREAD

**Issue by LeMonThELord** [zhuxb711/RX-Explorer#238]
版本6.5.1.0（微软商店更新慢？）
如动图所示，选中文件时，鼠标指针不移走动画显示不完全，指针移走后回来再次点击动画显示完全
![55](https://user-images.githubusercontent.com/39843121/119247518-c8ada100-bbbc-11eb-87fc-a824eff1c6b1.gif)

**Comment by zhuxb711** [comment]
微软祖传控件bug，修不好
