### ISSUE TITLE
是否可以增加按颜色归类显示功能

### ISSUE THREAD

**Issue by wangzhiyun** [zhuxb711/RX-Explorer#245]
既然可以给文件和文件夹进行标记颜色，应该给个快速查看对应颜色文件的界面。 参考苹果的方达文件管理器

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/119948014-fafb3c00-bfca-11eb-91ff-e7b432732c6e.png)
干嘛要对标苹果设计，但是过滤选项中会加入按颜色过滤的功能

**Comment by zhuxb711** [comment]
6.6.3已发布
