### ISSUE TITLE
一直出现“关键错误，辅助进程意外推出，这可能导致某些功能无法正常使用”

### ISSUE THREAD

**Issue by huzzame** [zhuxb711/RX-Explorer#246]
每次打开都会出现这种提示，关掉之后下一次打开依旧出现，请问怎么解决。
![image](https://user-images.githubusercontent.com/43633685/119649779-9c608180-be55-11eb-9f06-9a33818f2c49.png)

**Comment by huzzame** [comment]
同时，出现一直无法购买的情况

**Comment by zhuxb711** [comment]
出现这种情况一般是由于辅助进程意外崩溃，最常见的原因是您的右键菜单中存在可能导致RX辅助进程崩溃的菜单项，如某些早期设计不规范的“格式工厂”等菜单项

**Comment by chongyang-wei-b** [comment]
如何解决

**Comment by zhuxb711** [comment]
更换使用新版 RX文件管理器 (WAS)，从根本上杜绝该问题。
