### ISSUE TITLE
建议新增属性快捷键

### ISSUE THREAD

**Issue by Herry0818** [zhuxb711/RX-Explorer#247]
右击对象，选择属性有两项快捷按键建议可以加上：
1、选中对象，按Alt+Enter
2、按住Alt，双击对象

这两项快捷键都可以弹出来对象的属性对话框

**Comment by zhuxb711** [comment]
这两个快捷键有出处嘛？还是你自己想的呢？我怀疑绝大部分人都不知道这个快捷键

**Comment by zhuxb711** [comment]
嗯。。。我在系统管理器里面试了，确实是有这样的快捷键

**Comment by Herry0818** [comment]
> 嗯。。。我在系统管理器里面试了，确实是有这样的快捷键

就是windows里面自带的一个快捷按键，特别是Alt+双击左键 打开属性对话框  用处很大

**Comment by zhuxb711** [comment]
6.6.3已发布
