### ISSUE TITLE
文件显示

### ISSUE THREAD

**Issue by Yao3596** [zhuxb711/RX-Explorer#248]
我觉得文件显示的内容不要拘束于1：1的比例显示，这样可能不太方便查看完整内容

**Comment by zhuxb711** [comment]
什么1:1比例显示？

**Comment by Yao3596** [comment]
就像这两张图片WIN10系统文件夹是按照内容的大小比例显示，而RX都统一为正方形的形状作为显示出来，不方便查看缩略图内容（1：1就是宽高尺寸相同，一个正方形）
我觉得可以优化一下这个问题，对于一个设计工作者来说有很大的帮助。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 文件显示 (#248)





 
什么1:1比例显示？

**Comment by zhuxb711** [comment]
因为这样显示的速度最快，而且1:1是因为系统给的缩略图就是1:1的，最后的话就是根据图片本身的比例来做比较难搞

**Comment by Yao3596** [comment]
好吧

**Comment by zhuxb711** [comment]
如果您需要预览，可以使用内置图片查看器或指定其他软件来预览

**Comment by Yao3596** [comment]
还有个问题
新建标签或文件夹可以使用WIN10默认快捷键会更好
新加一个标签是Ctrl+N
新建文件夹是Ctrl+Shift+N
鼠标点会稍慢

**Comment by Yao3596** [comment]
刚刚试了一下好像只有标签不可以快捷键，抱歉

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/120059371-c7301d00-c083-11eb-816b-26facb36c5bf.png)
新加标签在RX中是Ctrl+T
