### ISSUE TITLE
地址栏不能右键复制path

### ISSUE THREAD

**Issue by richwxd** [zhuxb711/RX-Explorer#249]
发现了bug： 点击地址栏，右键想要复制当前路径地址，结果地址栏突然变回了 这台电脑 > 本地磁盘 > dir1 这种风格，导致复制路径失败。

**Comment by zhuxb711** [comment]
右键的时候地址栏失去焦点，因此导致了这种行为，此问题将于下一个版本中修复

**Comment by zhuxb711** [comment]
6.6.3已发布
