### ISSUE TITLE
请问能否提供隐藏顶部“这台电脑”一行的选项

### ISSUE THREAD

**Issue by alone231024** [zhuxb711/RX-Explorer#25]
使用中感觉顶部太大了，如果可以的话，希望地址栏这行，以及标签栏这行也可以调整宽度
开发者辛苦了

**Comment by alone231024** [comment]
地址栏一行，我个人平时几乎不会使用，而且RX也提供了侧边的访问模式，所以我个人希望也可以提供一个隐藏的选项

**Comment by zhuxb711** [comment]
无法隐藏或调整顶部宽度哦。RX提供的功能应当具有普适性，隐藏地址栏的要求不符合RX作为文件管理器本身的定位哦
