### ISSUE TITLE
右键加密功能菜单没有找到

### ISSUE THREAD

**Issue by richwxd** [zhuxb711/RX-Explorer#250]
电脑上安装了亿赛通，使用Files这个工具和Total Commander都可以出现亿赛通的加密，解密菜单，但是RX文件管理器没有

**Comment by zhuxb711** [comment]
我相信这是由于部分右键菜单未提供动词Verb导致的，RX会过滤这一部分的右键菜单。研究之后其实觉得动词不是必须的，RX在真正执行菜单项的时候，如果没有动词是会转而使用ID去寻找并执行，我会在下一个版本中更改相关的逻辑

**Comment by zhuxb711** [comment]
6.6.3已发布
