### ISSUE TITLE
无法复制或者拖拽文件

### ISSUE THREAD

**Issue by woody962464** [zhuxb711/RX-Explorer#251]
第三方软件接收的文件无法进行复制或者进行拖拽指定的文件夹，导致使用过程复杂，现先将第三方接收的文件复制或拖拽到桌面后，再剪切指定的文件夹，使用十分麻烦。

**Comment by zhuxb711** [comment]
不是很清楚您具体指的是什么？

**Comment by zhuxb711** [comment]
![GIF 2021-6-2 10-40-50](https://user-images.githubusercontent.com/42038175/120416118-36ad5180-c38f-11eb-887e-eb8d52146065.gif)
随便找了个QQ都可以
