### ISSUE TITLE
无法查看手机储存

### ISSUE THREAD

**Issue by wenjiahao9803** [zhuxb711/RX-Explorer#252]
电脑连接手机传输文件，原生文件资源管理器能正常访问，RX提示"不支持此驱动器，因为它的路径为空"，有办法解决吗？
PC系统版本Windows 10 Pro workstation Build 21390.co_release
手机Redmi K30 Pro 安卓11

**Comment by zhuxb711** [comment]
手机基于MTP协议，可能存在空路径，对于此种情况，RX不予支持
