### ISSUE TITLE
文件打开优化

### ISSUE THREAD

**Issue by ws666-github** [zhuxb711/RX-Explorer#254]
建议增加双击打开过程中手抖导致鼠标移动也能打开文件，以提高使用软件时的流畅性。相较于两次单击间隔过短导致误打开文件更容易让人接受

**Comment by zhuxb711** [comment]
双击打开的触发源自系统事件，该系统事件可能对双击有要求，因此无法改进此问题。另外微软的基础控件也存在问题，某些情况下双击事件不会正确触发。该问题必须由微软修复
