### ISSUE TITLE
没有收藏夹

### ISSUE THREAD

**Issue by ChinarG** [zhuxb711/RX-Explorer#255]
没有收藏夹无法打开目录

**Comment by zhuxb711** [comment]
右键“文件夹和库”的空白区域然后选择“添加”

**Comment by silentmoooon** [comment]
要不搞一个和资源管理器的快速访问那样的?  文件夹和库要先回到主页 还是没那么方便

**Comment by zhuxb711** [comment]
有专门的主页按钮呀，按一下就行了

**Comment by silentmoooon** [comment]
如果能一步到位还是更方便些吧.

**Comment by zhuxb711** [comment]
这个功能不可能一直简化下去的~很难满足所有人的要求全部一步到位，现在的状况下没有什么特别不方便的地方

**Comment by williamyan1024** [comment]
> 右键“文件夹和库”的空白区域然后选择“添加”

6.6.4.0 版本在文件夹上,文件夹内空白处, 点击右键均未看到有"添加"功能

**Comment by zhuxb711** [comment]
@williamyan1024 
![image](https://user-images.githubusercontent.com/42038175/121455679-78657a00-c9d7-11eb-817a-06713cf1303d.png)
