### ISSUE TITLE
地址栏逻辑优化

### ISSUE THREAD

**Issue by PeppaNO1** [zhuxb711/RX-Explorer#258]
地址栏选择好 目标地址后
按任何区域都无法关闭快捷访问的地址（常用地址）
包括切换到设置界面 那个快捷访问地址界面依旧存在

**Comment by zhuxb711** [comment]
![GIF 2021-6-4 0-03-38](https://user-images.githubusercontent.com/42038175/120676230-64e27c80-c4c8-11eb-8bed-0b6f768d7a5d.gif)
未发现此情况
