### ISSUE TITLE
垂直拆分按钮

### ISSUE THREAD

**Issue by silentmoooon** [zhuxb711/RX-Explorer#259]
这个按钮总感觉默认就处于"按下"状态, 是特意这样设计的么?
然后我感觉应该拆分成2份就够了吧, 我觉得可以改成按下拆分成2份,再按一下就取消拆分.

**Comment by zhuxb711** [comment]
设计上是允许无数多个份数，这个应该是不会改的，因为实际上可以在不同窗口上面滚动来查看。同屏显示的就是两份。这个按钮的问题，其实没有特别好的选择，取消边框也不好看，显得不对齐。没有什么好的解决办法
