### ISSUE TITLE
无法打开共享文件夹

### ISSUE THREAD

**Issue by jipeigong** [zhuxb711/RX-Explorer#26]
驱动器配置了NAS内网文件夹 打开RX后无法打开共享文件夹

**Comment by zhuxb711** [comment]
RX仅支持映射为网络驱动器的NAS哦

**Comment by jipeigong** [comment]
就是网络驱动器，NAS是市面上主流nas群晖
![微信截图_20200909113824](https://user-images.githubusercontent.com/7414916/92551655-1bdefe00-f291-11ea-8014-4be078d325eb.png)
![微信截图_20200909113950](https://user-images.githubusercontent.com/7414916/92551697-374a0900-f291-11ea-863b-59a34910ebb6.png)

**Comment by zhuxb711** [comment]
Value does not fall within the expected range这个错误似乎并没有明确的指向性
我无法判断该问题的原因，在我这里，是通过映射本地文件夹的方式来测试网络驱动器的，我觉得NAS方面应该是一样的。RX仅保持对网络驱动器的最低限度支持，因为很多高级功能在网络驱动器上不可实现，它仅依赖于UWP平台自身提供的（龟速）方式来显示文件，因此可能存在一些问题

**Comment by zhuxb711** [comment]
由于网络驱动器文件管理器API的返回结果不具有一致和稳定性，致使网络驱动器难以维护，RX已取消对网络驱动器的支持。
