### ISSUE TITLE
希望可以自定义快捷键启动应用，而不是非得WIN+E

### ISSUE THREAD

**Issue by Andy001847** [zhuxb711/RX-Explorer#260]
由于现在的RX文件管理器里面的右键菜单比较少，不能完全替代win10自带的文件管理器，所以希望可以自定义额外的快捷键去启动RX文件管理器，同时保留Win+E快捷键启动自带的文件管理器

**Comment by zhuxb711** [comment]
右键菜单少的问题在6.6.3中解决了（虽然撤包了，有一些小BUG），UWP本身不支持快捷键启动，能用Win+E启动是因为修改注册表重定向让他启动RX而已，因此无法自定义。您可以使用第三方辅助软件，以命令行方式启动RX(但设置为某个快捷键触发)。
