### ISSUE TITLE
右键菜单的BUG并未彻底解决，亿赛通等工具的右键还是不能显示

### ISSUE THREAD

**Issue by richwxd** [zhuxb711/RX-Explorer#261]
Win10 64位系统，安装亿赛通文档加解密工具，设置好后。
1. 在桌面上新建doc/docx文档，随意写一些文字
2. 此时点击文档右键，应该出现解密，解密菜单
3. 实际上未出现这样的菜单。
4. 对比程序为微软商店中下载的Files工具，右键有。
![3](https://user-images.githubusercontent.com/22185826/120875309-cf391100-c5dd-11eb-9e9a-c21b93247bc3.png)
![1](https://user-images.githubusercontent.com/22185826/120875315-d6f8b580-c5dd-11eb-96d0-5b496ec40071.png)
![2](https://user-images.githubusercontent.com/22185826/120875319-de1fc380-c5dd-11eb-8202-60965b852030.png)

**Comment by zhuxb711** [comment]
6.6.4中开放了非Verb菜单项的显示，应该是比以前多了菜单项的。至于你那个啥软件的菜单项为啥没有，不太清楚。没有那个软件的测试环境。

**Comment by richwxd** [comment]
等会上传一个亿赛通客户端到云盘

**Comment by richwxd** [comment]
亿赛通客户端，安装后右键就出现。链接: https://pan.baidu.com/s/10r7xY5U_b_k2tgPUZTznRg 提取码: 75if

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/120982194-014b9e00-c7ab-11eb-9de9-475c4f4ae665.png)
@richwxd 仿佛装了个病毒进来

**Comment by zhuxb711** [comment]
<img width="749" alt="无标题" src="https://user-images.githubusercontent.com/42038175/120985695-7076c180-c7ae-11eb-92f9-a90845ac776e.png">

没啥好说的，辣鸡软件，右键菜单项设计有问题，

**Comment by zhuxb711** [comment]
你发的这个软件直接淦到我重装系统，牛皮

**Comment by zhuxb711** [comment]
Whatever..你的那个软件的右键菜单项我改好了

**Comment by richwxd** [comment]
嗯嗯，这个软件卸载码我试过不好用，得删注册表。国产的这个软件，销量还是很好的。对标的是国外的GPG加密。单位电脑要求都得安装上。开发java的时候需要申请依赖库jar不加密，导入导出的excel不加密.
Anyway，啥时候有新版

**Comment by richwxd** [comment]
空白处右键怎么出这个菜单了？中间是断开的
![微信截图_20210609090847](https://user-images.githubusercontent.com/22185826/121277151-944b1c00-c902-11eb-8e9a-abc198e74fc8.png)

**Comment by zhuxb711** [comment]
这个是微软的控件库的bug，早就给他们提了issue了现在还没修好。新版应该明天之前会提交商店，这个星期内过审

**Comment by richwxd** [comment]
使用的时候有个体验问题，rx-explorer开久了，比如中间把电脑休眠了，再开以后，有些功能比如右键菜单就不出来，得关闭以后重开才可以正常。
还有打开python的安装目录，C:\Apps\Python\Python39 然后完全卸载Python, 然后这个目录切不出去了。也是关闭了软件再开才好的。
Rx-explorer 有没有快捷方式可以进入系统设置或控制面板这些，主要是方便修改环境变量。

**Comment by zhuxb711** [comment]
[看这里](https://github.com/microsoft/microsoft-ui-xaml/issues/3209)
我大半年前就提交了这个问题。

右键菜单弹不出来的原因大概率是微软弹右键菜单的函数报了异常出来，这个无解只能重新打开。

你可以在快速启动里面添加系统设置和控制面板等等的快捷方式

**Comment by richwxd** [comment]
感觉是UWP平台和C#底层不是很稳定。我们有个C#的form程序，一旦遇到网络抖动，恢复了也是不好使，要重启就正常。
其实这个快速启动的功能还是很好用的。现在同时开着Lucy启动，Listary

**Comment by richwxd** [comment]
mklink /J 链接的目录，好像区别不出来。这个功能都用着python的conda, jetbrains的IDE上，这些工具很喜欢占用C盘，重装很麻烦。

**Comment by zhuxb711** [comment]
> 感觉是UWP平台和C#底层不是很稳定。我们有个C#的form程序，一旦遇到网络抖动，恢复了也是不好使，要重启就正常。
> 其实这个快速启动的功能还是很好用的。现在同时开着Lucy启动，Listary

 稳定就有鬼了，你也不看看微软上次更新UI控件库是在6个月前？就这更新速度也配稳定这个词？
