### ISSUE TITLE
为什么没有移动功能

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#264]
现在拖动文件到文件夹，全都是复制，不方便。

**Comment by zhuxb711** [comment]
按Shift切换复制还是移动

**Comment by jxharp** [comment]
没试出来，是选中文件后按shift+右键？ 如果怎么隐蔽，为什么不放在显眼的位置？这样不是加大用户使用成本吗？

**Comment by zhuxb711** [comment]
> 没试出来，是选中文件后按shift+右键？ 如果怎么隐蔽，为什么不放在显眼的位置？这样不是加大用户使用成本吗？

系统文件管理器的拖拽没有用过吗？RX大部分行为包括拖拽的逻辑都是和系统文件管理器保持一致的，何谈加大使用成本一说？

拖拽的过程中按Shift切换复制和移动
