### ISSUE TITLE
在单击文件夹是打开的方式下，多选文件不方便

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#265]
目前只能框选文件，不能像win自带的资源管理器一样，按住ctrl跳空多选文件。
建议增加复选框可以自由多选。 或者按住ctrl+左键（双击打开文件夹）或ctrl+右键（单击打开文件夹）实现多选文件或目录

**Comment by jxharp** [comment]
看到底部有多选了，但是还是对于键盘操作非常不友好，希望能增加配合键盘的多选方式。在触摸屏用的毕竟是少数

**Comment by zhuxb711** [comment]
![GIF 2021-6-9 18-54-50](https://user-images.githubusercontent.com/42038175/121342444-36472480-c954-11eb-9778-1ec62ceb10df.gif)
不管单双击模式，都是可以Ctrl跳着选择的。不知道你所谓的
> 不能像win自带的资源管理器一样，按住ctrl跳空多选文件
是怎么得出来的
