### ISSUE TITLE
需要细分文件和文件夹的打开方式

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#266]
现在只能统一设定双击或单击。特别是单击模式下，对于多选非常不友好。
建议对文件和文件夹可以分别设定是双击或单击。配合多选，实现方便操作。

**Comment by zhuxb711** [comment]
Emmmm还是和之前那个Issue差不多，现在单选是可以进行多选操作的呀，不管是框选还是键盘的快捷键Ctrl选中
