### ISSUE TITLE
复制文件的进度条面板太生硬了

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#267]
能否采用悬浮面板，大小自适应任务多少。尽量小型化，半透明化，减少对操作的干扰

**Comment by zhuxb711** [comment]
？？？你到底是什么版本？

**Comment by zhuxb711** [comment]
现在的面板也是悬浮的一种，而且背景也是亚克力材质的。
不想被干扰你完全可以取消勾选
![image](https://user-images.githubusercontent.com/42038175/121330805-eadb4900-c948-11eb-8c48-a9f4a22395cb.png)

最后，不要比照Files的设计

**Comment by jxharp** [comment]
问题就在这个选项，取消此选项后，复制就完全没提示了。 我希望的是复制还是有进度提示，但是复制完就消失。这个选项能否取消？把 任务列表这四个字的区域做成进度条，显示第一个任务的总体进度，鼠标点击或悬浮，就打开现在的面板。只是谈谈一下是否合理。 另外，当前面板没有意见清除已完成任务功能

**Comment by jxharp** [comment]
一键清除

**Comment by zhuxb711** [comment]
有进度提示，现在的任务面板不是悬浮的么，你点一下其他地方它不就收回去了

**Comment by zhuxb711** [comment]
> 任务列表这四个字的区域做成进度条，显示第一个任务的总体进度

可以考虑在以后在这四个字下方添加一个小的预览进度条，这个还是觉得不错的
> 一键清除

现在只有单个清除，一键清除没有做，可以考虑，也不麻烦
