### ISSUE TITLE
垂直拆分问题

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#269]
区域从1拆成2，会自适应的1分为2，但是超过2个，就不会自动缩小自适应了，需要用鼠标滚轮才能看到，以为没拆分成功。建议可以自适应宽度。在拆分为超过2个区域时，可选择布局方式是平铺或者田字布局

**Comment by zhuxb711** [comment]
那我问你，用户打开100个拆分窗口的时候，怎么分割？

**Comment by jxharp** [comment]
可以超过N才会滚动。 一般4个面板以上吧，参考win的分屏。 按拆分模式，可以横向或垂直滚动。垂直更直觉一点。这个横向滚动很难发现。 当我在32寸显示器上拆分多个面板，老是只显示2个，确实是愣住了。

**Comment by zhuxb711** [comment]
首先，新建一个垂直拆分窗口的时候，整体会滚动至最后一个窗口，这个提示已经很明显了。
另外RX受众广泛，不是每个人都有32寸屏幕的，有些用RX的用户还是10多寸的720P屏幕，请从照顾这些用户的角度出发，不要从你个人拥有的设备上出发😀

**Comment by jxharp** [comment]
在拆分模式下，是否可以隐藏左侧目录栏。最大化时，像win这样“田”字拆分，效率最高

**Comment by zhuxb711** [comment]
四个垂直窗口将导致这部分用户难以使用

**Comment by jxharp** [comment]
不要纠结32寸，我的问题是很难发现横向滚动。因为初始拆分时，内容可能是一样的。 1366*768，田 字拆分也是可以用的。 当然，我提我的建议，你是作者你决策。

**Comment by zhuxb711** [comment]
很难横向滚动是因为你没有找准区域，你可以在每个垂直拆分窗口的顶上和底部滚动鼠标滚轮，直接在中间滚动滚轮那也不现实，我无法知道你是想滚动文件列表还是滚动垂直拆分窗口，这里有两个方向的控制歧义，自然是垂直滚动优先于水平滚动

**Comment by zhuxb711** [comment]
> 不要纠结32寸，我的问题是很难发现横向滚动。因为初始拆分时，内容可能是一样的。 1366*768，田 字拆分也是可以用的。 当然，我提我的建议，你是作者你决策。

UWP在分辨率低的设备上会自动缩放，因此很多模块的大小就放大了，加上分辨率的限制，实际可用空间也没多少了

**Comment by jxharp** [comment]
首先是很难发现可以滚动。我拆分后的内容是一样的，因为只显示2个分栏，由于宽度和分栏数量没有变化，所以不知道已经多于2个分栏了。 如果直观显示3个4个当然能很容易发现。  其次，如果可以垂直滚动，我希望是默认垂直滚动分栏，当鼠标点击某个分栏的空白处或选择文件，垂直滚动才对此分栏内的文件列表起作用

**Comment by zhuxb711** [comment]
![123](https://user-images.githubusercontent.com/42038175/121332869-d8620f00-c94a-11eb-8e2e-64b1d0aa197e.gif)
我觉得现在的动画足以提示用户超过2个垂直拆分窗口了，向左推的动画已经足够明显。

详细信息视图下，可能不存在空白空间，至于为什么没有，那就是另外一个可以长篇大论的内容了。因此你的建议不可行。你不是开发者，所以不太清楚这里面到底有什么难的。
