### ISSUE TITLE
无法重定向win+e

### ISSUE THREAD

**Issue by MarinaMarissa** [zhuxb711/RX-Explorer#27]
https://imgchr.com/i/wJA3hF
系统：10.0.19041.450

**Comment by zhuxb711** [comment]
若RX无法自动确定可供用于WIN+E的启动位置时，则会发生这个错误

**Comment by zhuxb711** [comment]
RX若无法在系统环境变量中的路径找到它的启动位置(一般是在%LOCALAPPDATA%\Microsoft\WindowsApps这个文件夹下面)，则将自动阻止使用WIN+E启动。这可以确保您不会因为设置了WIN+E启动却又无法正常使用它，您亦可以手动替换WIN+E，但不建议您这么做。

**Comment by MarinaMarissa** [comment]
> RX若无法在系统环境变量中的路径找到它的启动位置(一般是在%LOCALAPPDATA%\Microsoft\WindowsApps这个文件夹下面)，则将自动阻止使用WIN+E启动。这可以确保您不会因为设置了WIN+E启动却又无法正常使用它，您亦可以手动替换WIN+E，但不建议您这么做。

那如何解决呢

**Comment by zhuxb711** [comment]
1.首先在系统文件管理器中输入如下路径（若您未更改默认路径）
![image](https://user-images.githubusercontent.com/42038175/93155700-415c8380-f739-11ea-9701-030c60004646.png)

2.查看是否存在文件“RX-Explorer.exe”
![image](https://user-images.githubusercontent.com/42038175/93155739-533e2680-f739-11ea-941f-6fdea965343e.png)

3.若不存在该文件，则启动Powershell，输入Get-Command RX-Explorer.exe，如下图所示
![image](https://user-images.githubusercontent.com/42038175/93156080-fb53ef80-f739-11ea-8ed1-344a472dc926.png)

从中可以获取到该文件的实际路径，找到它的位置。

4.下载文件：
[Intercept_WIN_E.txt](https://github.com/zhuxb711/RX-Explorer/files/5222028/Intercept_WIN_E.txt)

5.打开并用上述路径替换\<FillActualAliasPathInHere\>这个位置（上述路径应当为RX-Explorer.exe的完整路径，并将所有的\改成两个\\，如：C:\\\\Users\\\\zrfcf\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps\\\\RX-Explorer.exe）
初始状态如下图：
![image](https://user-images.githubusercontent.com/42038175/93156380-98af2380-f73a-11ea-9a7e-c94e4d011dba.png)

更改之后如下图：
![image](https://user-images.githubusercontent.com/42038175/93156480-d318c080-f73a-11ea-921e-b1c05e82e56d.png)

6.保存并将.txt文件重命名为.reg后缀，双击运行即可将WIN+E按钮重定向为RX文件管理器（建议先备份注册表）

7.（可选）若需要恢复系统WIN+E按钮的默认状态，下载如下文件：
[Restore_WIN_E.txt](https://github.com/zhuxb711/RX-Explorer/files/5222064/Restore_WIN_E.txt)
直接更改后缀为.reg文件，双击运行，即可恢复原始状态。

**Comment by sifenglib** [comment]
感觉回复，但按你的指导进行操作后还是没有生效，设置完成后机器也重启了

![image](https://user-images.githubusercontent.com/61527672/99232847-65b60880-282d-11eb-89eb-129e51210429.png)

**Comment by sdjames64157** [comment]
> 感觉回复，但按你的指导进行操作后还是没有生效，设置完成后机器也重启了
> 
> ![image](https://user-images.githubusercontent.com/61527672/99232847-65b60880-282d-11eb-89eb-129e51210429.png)

按照你的注册表地址把RX-Explorer.exe的地址填进去就生效了

**Comment by zhuxb711** [comment]
是的，这样本来就是自动打开Win+E的原理
