### ISSUE TITLE
垂直拆分快捷键ctrl+B 没有成功过

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#270]
如题

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/121340072-c041be00-c951-11eb-8f78-1797d06a9ecb.png)
注意，这里所说的Ctrl+B的提示，仅在选中文件夹时有效

![image](https://user-images.githubusercontent.com/42038175/121340146-d8b1d880-c951-11eb-9787-5608827dfe42.png)
指南里面也说了，需要选中一个文件夹

**Comment by zhuxb711** [comment]
当然，考虑到用户也可以直接不选中文件夹打开，直接使用Ctrl+B也是合理的
