### ISSUE TITLE
命令行建议增加 WT （windows Terminal）

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#271]
WT已经慢慢普及了，体验还不错，建议增加此方式

**Comment by zhuxb711** [comment]
WT需要你自己去设置里面配，不要懒........命令行明明都有可自定义的方式的

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/121343508-59be9f00-c955-11eb-9be5-7e83465717db.png)
如果已经安装了Windows Terminal，这里放个配置WT命令行的方式
