### ISSUE TITLE
右键弹出菜单太慢了

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#272]
似乎文件夹上右键比在文件上更慢

**Comment by zhuxb711** [comment]
暂时无法解决，由于微软控件存在问题，无法首先弹出菜单再去加载系统菜单项。首先弹出菜单的情况下，动态添加菜单项会导致菜单显示不全、闪动、被裁切等问题，微软尚未解决此问题。因此必须等待系统菜单项加载完成后才可以弹出
