### ISSUE TITLE
启动在空界面卡顿5-6秒

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#273]
如题, 每次启动都会在空界面卡个5-6秒
![image](https://user-images.githubusercontent.com/45326534/121397505-fa798280-c986-11eb-990b-47bd7359d63e.png)
在这个界面或者开始界面但没有任何图标, 且无法响应

ps. 我如果有机会可以也帮忙看看, 但是目前电脑没装vs, 我回头研究研究rider怎么编译uwp

**Comment by zhuxb711** [comment]
似乎并没有发现存在这个问题诶....内测也没有人报告此问题

**Comment by taooceros** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6628054/Export_All_Error_Log.txt)
这是log, 我看到里面出现了很多sqlite的报错, 可能是更新遗留的问题吧.
我重置一下试试

**Comment by taooceros** [comment]
确实, 重置之后就不会了, 我之后再多试试, 估计是检查sqlite的时候出的问题?

**Comment by zhuxb711** [comment]
咦为啥会发生这个错误，唯一约束异常。你向文件夹和库中添加了什么路径吗？

**Comment by taooceros** [comment]
> 咦为啥会发生这个错误，唯一约束异常。你向文件夹和库中添加了什么路径吗？

另一个onedrive? 但是路径应该是不一样的啊

**Comment by zhuxb711** [comment]
我研究了一下，原因应该是某个文件夹的路径发生了重复，比如Download和OneDrive的文件夹路径相同(虽然我也不知道这是怎么发生的)

**Comment by taooceros** [comment]
> 我研究了一下，原因应该是某个文件夹的路径发生了重复，比如Download和OneDrive的文件夹路径相同(虽然我也不知道这是怎么发生的)

我不太清楚自动寻找onedrive文件夹的逻辑, 会不会是更新之后重新找了一次, 然后和之前添加过的文件夹重复了?

**Comment by zhuxb711** [comment]
[是这里抓到的异常](https://github.com/zhuxb711/RX-Explorer/blob/e90dc0bd6e266e2545e018d0b0e42004427929ea/RX_Explorer/Class/CommonAccessCollection.cs#L281)

它在启动的时候重新确认了默认包含的文件夹的位置，然后更新数据库(有些用户可能会更改诸如Download的位置)。更新数据库的时候Path是主键，因此拥有唯一约束。它错误里面说是唯一约束冲突，说明某个文件夹的路径和默认的冲突

**Comment by zhuxb711** [comment]
为了避免此问题，我将把Update的SQL更改为 Insert Or Replace

**Comment by taooceros** [comment]
okk, 谢了

**Comment by zhuxb711** [comment]
[看这里](https://github.com/zhuxb711/RX-Explorer/blob/e90dc0bd6e266e2545e018d0b0e42004427929ea/RX_Explorer/View/Home.xaml.cs#L584)

不明白为啥会有重复的内容.......这里其实对用户添加的内容进行了拦截，如果已存在就不予添加。除非是用户之前添加了一个原本不存在的路径，下次RX启动的时候读取环境变量的OneDrive路径后，又恰好和用户之前添加的重复

**Comment by taooceros** [comment]
> [看这里](https://github.com/zhuxb711/RX-Explorer/blob/e90dc0bd6e266e2545e018d0b0e42004427929ea/RX_Explorer/View/Home.xaml.cs#L584)
> 
> 不明白为啥会有重复的内容.......这里其实对用户添加的内容进行了拦截，如果已存在就不予添加。除非是用户之前添加了一个原本不存在的路径，下次RX启动的时候读取环境变量的OneDrive路径后，又恰好和用户之前添加的重复

我觉得是用户之前就添加了Onedrive, 但是下次rx启动的时候又想添加一次, 就出问题了
