### ISSUE TITLE
Bug:全屏模式下标题栏与工具栏重叠，工具栏图标无法点击

### ISSUE THREAD

**Issue by oxygen-dioxide** [zhuxb711/RX-Explorer#275]
按Win+Shift+Enter进入全屏模式，标题栏与工具栏重叠
![image](https://user-images.githubusercontent.com/54425948/121453229-6386e780-c9d3-11eb-91ae-4672b72b4c67.png)
点击左上角的“主页”、“回收站”、“快速启动”、“安全域”、“蓝牙音频”，均无反应

其实可以直接把标题栏删掉，就像第三方的[bilibili uwp v4](https://www.showdoc.com.cn/biliuwpv4)那样。现在的ui五栏显示在顶上，挤占了大块屏幕空间。
![image](https://user-images.githubusercontent.com/54425948/121453467-cd06f600-c9d3-11eb-8e2a-271422961a84.png)

win10版本：1903
rx文件管理器版本：6.6.4.0

**Comment by zhuxb711** [comment]
标题栏应该是不会移除的，它本身不会占用太多空间。Win+Shift+Enter这个确实是一个BUG，将于下一个版本中修复
