### ISSUE TITLE
已安装everything服务但无法调用

### ISSUE THREAD

**Issue by williamyan1024** [zhuxb711/RX-Explorer#276]
![image](https://user-images.githubusercontent.com/34412175/121456779-2aea0c80-c9d9-11eb-8517-3fda095ba550.png)

**Comment by zhuxb711** [comment]
你可以点一下右边那个小问号看看是否已经满足所有条件？

**Comment by williamyan1024** [comment]
![image](https://user-images.githubusercontent.com/34412175/121457549-66390b00-c9da-11eb-9e20-a0f6f461c958.png)
目前状态:服务正在运行,everything本体并未运行
那么按照说明中"或"是只要两者运行其一就可以了吧

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/121460087-f11c0480-c9de-11eb-86f9-274b9c1b2919.png)
根据Everything官网的描述，Everything服务只用于“索引 NTFS 分卷和监控 USN 日志”。Everything服务并不包括搜索功能，它只是帮助Everything在后台记录索引和磁盘变化，在Everything本体运行的时候无需再次获取并等待刷新。

![image](https://user-images.githubusercontent.com/42038175/121460291-4eb05100-c9df-11eb-9f9c-627d1c68485b.png)
根据SDK说明，使用Everything搜索必须使Everything运行。

可能您错误理解了Everything服务的含义，它并不是将Everything作为后台运行。

**Comment by zhuxb711** [comment]
抱歉我的那个小问号中的表述存在问题，我将更改此处的表述以免引起误解
