### ISSUE TITLE
[bug]导航视图位于左侧时，快速启动打不开

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#278]
https://user-images.githubusercontent.com/69738882/121768998-c58e4b00-cb93-11eb-9d54-1f1273d6a437.mp4

**Comment by XSH-Hero** [comment]
如上，快速启动点开时，刚一出现就消失

**Comment by zhuxb711** [comment]
进行了你这个BUG的修复后将导致重新排序快速启动失效

**Comment by zhuxb711** [comment]
该问题是微软控件已知问题，并且由于该问题是存在于Windows SDK中的，故无法进行修复。总之目前的情况是只能这个无法弹出和那个不能重新排序的问题二选一
