### ISSUE TITLE
project reunoin有跟进没

### ISSUE THREAD

**Issue by silentmoooon** [zhuxb711/RX-Explorer#279]
好像后面windows的设计和接口都会基于这个了

**Comment by zhuxb711** [comment]
预览版你现在跟进也没有用，出来之后还要考虑

**Comment by zhuxb711** [comment]
Reunion现在准备在正式版中砍掉背景亚克力效果

**Comment by silentmoooon** [comment]
啊 这样的么.  果然是砍刀部..
果然变得更加苹果味儿了

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/122330603-145a2d00-cf66-11eb-8eac-c2d257a45903.png)
路线图里面说应用内亚克力效果会有，窗口背景的亚克力效果 "Plan for future"
[路线图](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md)

**Comment by silentmoooon** [comment]
https://www.zhihu.com/question/461439249/answer/1908451934
https://www.zhihu.com/question/462862074/answer/1922051516
我是看了这两篇爆料有提到,变得更加苹果味儿了,近期泄露的11好像还只是早期的,爆料提到的还没实装.
reunoin 0.8倒是马上发布了. 不过问题估计不少. 
看24号能放出些啥来.

**Comment by zhuxb711** [comment]
Reunion发布应该是在11月初，和.Net 6一起出

**Comment by zhuxb711** [comment]
而且就算移植时机成熟，没有什么太大的障碍，整体架构也要大改呀。Reunion都出来了还要个鬼的辅助进程，直接应用内解决就完事

**Comment by silentmoooon** [comment]
总体来说是个好消息.  只是工作量不小. 哈哈

**Comment by oxygen-dioxide** [comment]
> 而且就算移植时机成熟，没有什么太大的障碍，整体架构也要大改呀。Reunion都出来了还要个鬼的辅助进程，直接应用内解决就完事

还是得分开，因为rx可能会移植到Xbox、Hololens，以及未来可能出现的其他UWPOS（虽然不太可能），得把”能在沙盒里运行的代码“和”必须在沙盒外运行的代码“分开

**Comment by zhuxb711** [comment]
> > 而且就算移植时机成熟，没有什么太大的障碍，整体架构也要大改呀。Reunion都出来了还要个鬼的辅助进程，直接应用内解决就完事
> 
> 还是得分开，因为rx可能会移植到Xbox、Hololens，以及未来可能出现的其他UWPOS（虽然不太可能），得把”能在沙盒里运行的代码“和”必须在沙盒外运行的代码“分开

不行，因为现在RX能做那么多功能都拜沙箱外的代码所赐。沙箱内和沙箱外不是相互独立的关系，而是依存的关系，不可以分开的。RX不上Xbox是因为XBOX不支持某些RX需要的文件管理权限

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/123885048-30ef5f80-d97f-11eb-8676-17e6d3f4f202.png)
这怎么感觉是抄的你的,哈哈.

**Comment by zhuxb711** [comment]
> ![image](https://user-images.githubusercontent.com/9210514/123885048-30ef5f80-d97f-11eb-8676-17e6d3f4f202.png)
> 这怎么感觉是抄的你的,哈哈.

震惊！国际大公司微软居然做出这种事

**Comment by XSH-Hero** [comment]
> ![image](https://user-images.githubusercontent.com/9210514/123885048-30ef5f80-d97f-11eb-8676-17e6d3f4f202.png)
> 这怎么感觉是抄的你的,哈哈.

发现了一个有趣的现象：
![image](https://user-images.githubusercontent.com/69738882/126760272-da6b547e-0689-49ce-8969-3850cd734b18.png)
![image](https://user-images.githubusercontent.com/69738882/126760305-aa97ad53-158a-4575-8803-7cc88cdc9f55.png)
刚打开的motor菜单有“使用RX文件管理器打开”选项，点击“显示更多选项”后，出现的菜单那个选项不见了

**Comment by silentmoooon** [comment]
https://m.ithome.com/html/564019.htm
看起来好像是feature

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/126999645-5c4a66a7-51a6-4bb1-b49f-ae687293b76c.png)
![image](https://user-images.githubusercontent.com/9210514/126999701-af58e570-c30e-45de-9524-f7582d2128de.png)
隔壁的看这外观搞得还可以啊  @zhuxb711

**Comment by zhuxb711** [comment]
> ![image](https://user-images.githubusercontent.com/9210514/126999645-5c4a66a7-51a6-4bb1-b49f-ae687293b76c.png)
> 
> ![image](https://user-images.githubusercontent.com/9210514/126999701-af58e570-c30e-45de-9524-f7582d2128de.png)
> 
> 隔壁的看这外观搞得还可以啊  @zhuxb711 

2.6的Bug实在是太多，想直接2.5用到.Net 6出来当场团圆，用个屁的垃圾WinUI 2.6

**Comment by zhuxb711** [comment]
继续留守WinUI 2.7，Windows App SDK不是UWP的超集，现在它缺少很多RX自己用到的东西，加上现在它的性能比UWP还辣鸡。这玩意还得等一两年

**Comment by oxygen-dioxide** [comment]
> 继续留守WinUI 2.7，Windows App SDK不是UWP的超集，现在它缺少很多RX自己用到的东西，加上现在它的性能比UWP还辣鸡。这玩意还得等一两年

今 日 辱 软 (1/1)

**Comment by zhuxb711** [comment]
> > 继续留守WinUI 2.7，Windows App SDK不是UWP的超集，现在它缺少很多RX自己用到的东西，加上现在它的性能比UWP还辣鸡。这玩意还得等一两年
> 
> 今 日 辱 软 (1/1)

UWP开发本质上就是在跟微软BUG斗智斗勇
