### ISSUE TITLE
.exe可执行文件问题

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#28]
当可执行文件拓展名为大写的exe[.EXE]时，RX不会将它识别为exe，而是选择打开方式，希望修复一下。

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/92937979-9620a580-f47e-11ea-8cdc-bd56cbd0d4f8.png)

**Comment by XSH-Hero** [comment]
如上图所示，双击“WINWORD.EXE”(此时的拓展名为大写的exe)时，弹出的是选择打开方式而不是打开此程序

**Comment by zhuxb711** [comment]
请更新至5.3.3版本以解决该问题
