### ISSUE TITLE
文件类型filter这里加个scrollviewer?

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#280]
![image](https://user-images.githubusercontent.com/45326534/122244474-7def2280-cef7-11eb-8c0a-370eb514ef48.png)

**Comment by zhuxb711** [comment]
现在是无法滚动的嘛？

**Comment by zhuxb711** [comment]
[代码在这里](https://github.com/zhuxb711/RX-Explorer/blob/33aa728461e301843e30111d424a832b13ead303/RX_Explorer/View/FilePresenter.xaml#L1829)

是有ScrollViewer

**Comment by taooceros** [comment]
咦，好像确实有，但是为什么我不能用鼠标滚动，键盘倒是可以

**Comment by taooceros** [comment]
要不考虑一下不让scroller hide？不然有可能用户都不知道可以下滑，这个如果没到长度应该是不会展示的吧

**Comment by zhuxb711** [comment]
那也可以。最大高度要不要缩减一些

**Comment by taooceros** [comment]
我觉得高度还好诶，只要在rx默认高度之内我感觉都可以。

鼠标那回事，我试了一下，应该是windows，或者uwp的问题。。。。windows terminal 的scroller我也用鼠标划不了。。。
