### ISSUE TITLE
搜索功能优化

### ISSUE THREAD

**Issue by PeppaNO1** [zhuxb711/RX-Explorer#282]
之前使用everything搜索引擎选了后 直接搜索。现在还要进去点搜索才可以搜索结果 没有之前的好用

**Comment by zhuxb711** [comment]
不是很清楚你在说什么

**Comment by wangdajunttf** [comment]
我win10电脑安装了，搜索功能没反应怎么回事

**Comment by zhuxb711** [comment]
> 我win10电脑安装了，搜索功能没反应怎么回事

什么叫没反应，给视频或者Gif看看

**Comment by wangdajunttf** [comment]
![Uploading Snipaste_2021-07-06_10-31-15.png…]()

**Comment by wangdajunttf** [comment]
搜索框内输入内容后，没反应，回车后也没反应
 windows 自带的文件管理器 输入后就会出结果呀

**Comment by zhuxb711** [comment]
![GIF 7-6-2021 2-35-22 PM](https://user-images.githubusercontent.com/42038175/124553531-6dcbc280-de67-11eb-9d93-55dbd18ce849.gif)
你之前的图没传成功吧，搜索功能正常啊

**Comment by PeppaNO1** [comment]
搜索时，需要二次点击搜索引擎我记得前面两个版本，解锁了Everything后是不需要再次选择搜索引擎的

从用户的使用习惯上来说，肯定是解锁了更高效的搜索引擎后，不想再去选择默认的搜索引擎的
我的问题是这个，很希望改回来~
（录制的文件太大了，无法上传，故上传了一张截图）

------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 搜索功能优化 (#282)





 

 你之前的图没传成功吧，搜索功能正常啊

**Comment by zhuxb711** [comment]
选择默认引擎，可以前往设置中设置啊，不是没有给选项捏

**Comment by PeppaNO1** [comment]
感谢~~
那就是某一次更新后，重置了设置





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuxb711/RX-Explorer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuxb711/RX-Explorer] 搜索功能优化 (#282)





 
选择默认引擎，可以前往设置中设置啊，不是没有给选项捏

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/124573948-95795580-de7c-11eb-85d9-1c645c14de36.png)
在这里...
