### ISSUE TITLE
提供appx安装包，以使用winget安装

### ISSUE THREAD

**Issue by oxygen-dioxide** [zhuxb711/RX-Explorer#283]
winget是windows官方包管理器，一行命令即可安装软件。希望rx explorer提供appx安装包，以加入winget。

**Comment by zhuxb711** [comment]
misxbundle包在Github Release中有。UWP不支持通过命令行分发吧

**Comment by oxygen-dioxide** [comment]
> misxbundle包在Github Release中有。UWP不支持通过命令行分发吧

Notepads就能通过winget安装
要签过名的Msixbundle，无需导入证书，双击直装的

**Comment by zhuxb711** [comment]
> > misxbundle包在Github Release中有。UWP不支持通过命令行分发吧
> 
> 
> 
> Notepads就能通过winget安装
> 
> 要签过名的Msixbundle，无需导入证书，双击直装的
> 
> 

没有可信证书，UWP的签名是你提交给微软商店后，如果通过审核，微软予以签名并发布。它的签名不是由开发者进行的，开发者只能生成不受信任的自签名证书

**Comment by oxygen-dioxide** [comment]
> > > misxbundle包在Github Release中有。UWP不支持通过命令行分发吧
> > 
> > 
> > Notepads就能通过winget安装
> > 要签过名的Msixbundle，无需导入证书，双击直装的
> 
> 没有可信证书，UWP的签名是你提交给微软商店后，如果通过审核，微软予以签名并发布。它的签名不是由开发者进行的，开发者只能生成不受信任的自签名证书

https://store.rg-adguard.net/
在这个网站输入微软商店链接，即可下载微软商店签好名的msixbundle
![image](https://user-images.githubusercontent.com/54425948/123618500-d77e1800-d83a-11eb-9934-b09cda6c3309.png)
