### ISSUE TITLE
win+e激活失败

### ISSUE THREAD

**Issue by Passerby1011** [zhuxb711/RX-Explorer#284]
win+e打开的依旧是系统的文件管理器

**Comment by zhuxb711** [comment]
可能是由于多方面的原因导致，比如注册表写入失败，或者某些Win系统也没有办法使用这种方式激活RX，原因不明

**Comment by zhuxb711** [comment]
[手动教程在这里](https://github.com/zhuxb711/RX-Explorer/issues/27#issuecomment-692418152)
