### ISSUE TITLE
读取文件夹图标

### ISSUE THREAD

**Issue by RZYplus** [zhuxb711/RX-Explorer#285]
RX文件管理器读取自定义的文件夹图标是没有问题的，但是我下载win10主题包就无法读取文件夹图标。
![86N A9E@CE8DB`@N(O)DGKY](https://user-images.githubusercontent.com/64346858/123518714-c073e480-d6d9-11eb-8059-4c8adf128d9c.png)
![OLVJ~FS@CJR5I112AYG$Z{V](https://user-images.githubusercontent.com/64346858/123518718-c23da800-d6d9-11eb-8f5e-bef4145ac00d.png)
![%Z~Z8EYC%9 SSXATQ ID6FT](https://user-images.githubusercontent.com/64346858/123518719-c2d63e80-d6d9-11eb-96c7-40cbed35627c.png)

**Comment by zhuxb711** [comment]
可以读，只不过你没有仔细研究设置，没发现罢了，这不是一个issue。

前往设置-图标加载模式-加载文件夹和文件

你如果这样选的话就是取消了RX的一些优化，对速度肯定有一定的影响，因为它现在必须读取每个文件夹的实际图标，默认设置下文件夹图标是不予读取以优化加载速度的。

至于文件夹和库那部分，不受该设置影响，始终加载实际图标，所以你可以在这里看到

**Comment by RZYplus** [comment]
好的，已解决
