### ISSUE TITLE
升级至WinUI 2.6

### ISSUE THREAD

**Issue by zhuxb711** [zhuxb711/RX-Explorer#287]
WinUI2.6已发布但升级并使用圆角样式仍然还有很多问题。其中最大的问题是NavigationView莫名丢失它的Item，以及样式全乱了，具体原因不明。如果在单独创建一个空白的UWP应用，使用同样的NavigationView XAML代码，却表现正常，很奇怪了。

具体情况看[这里](https://github.com/microsoft/microsoft-ui-xaml/issues/5274)

@silentmoooon @taooceros 是否能帮助查找该问题的根本原因？

**Comment by taooceros** [comment]
好，不过要明天，今天手上的电脑没装vs👀

**Comment by zhuxb711** [comment]
> 好，不过要明天，今天手上的电脑没装vs👀

好的，慢慢来

**Comment by silentmoooon** [comment]
好 我有空也看一下

**Comment by zhuxb711** [comment]
> 好 我有空也看一下

谢谢~

**Comment by silentmoooon** [comment]
现在在win11, 貌似debug跑不了,一堆的错误. 
但直接商店安装的没问题

**Comment by zhuxb711** [comment]
Win11肯定跑不动吧，才第一个预览版，Debug应该要到Win10

**Comment by silentmoooon** [comment]
那没办法帮你看了,其他方面用着没啥问题  懒得回退了  
应该说也回退不了了  硬盘空间紧张  直接把旧版本干掉了

**Comment by zhuxb711** [comment]
看看海量的WinUI 2.6的BUG，就这？还用了6个月做出这么个垃圾？

**Comment by zhuxb711** [comment]
最搞笑的是WinUI2.6用了之后商店过不了审了

**Comment by taooceros** [comment]
哈哈哈哈哈哈🤣

**Comment by taooceros** [comment]
我暂时解决不掉System.Memory的问题。。。debug的时候疯狂丢error。。。我明天尝试一下重新下一遍repo

**Comment by zhuxb711** [comment]
> 我暂时解决不掉System.Memory的问题。。。debug的时候疯狂丢error。。。我明天尝试一下重新下一遍repo

VS的锅，降级到16.9.8版本，别上16.10

**Comment by taooceros** [comment]
。。？怪不得。。我装的是2022的preview

不过这是什么鬼bug。。。
目前没有别的解决方案么。。

**Comment by zhuxb711** [comment]
> 。。？怪不得。。我装的是2022的preview
> 
> 不过这是什么鬼bug。。。
> 目前没有别的解决方案么。。

不清楚，从16.10.0就开始了
16.10.1还是等待调查
16.10.2正在调查中
16.10.3正在调查中
你说它会在16.10.4中修复嘛？未必，毕竟老框架WinForm是一等公民，WPF是二等公民，最新最不稳定的框架UWP是四等公民，显而易见的Bug调查了这么多版本还没找到原因

估计是编译器还是链接器的问题

有人说降低UWP的框架到6.2.0的一个预览版可以解决这个问题，这就是扯淡的方案，UWP框架更新多慢啊，从6.2.12降到6.2.0？怕是梦回2017

**Comment by taooceros** [comment]
就离谱嗷

**Comment by silentmoooon** [comment]
emmm. 我也是这个问题, 看来不是win11的问题

**Comment by zhuxb711** [comment]
VS可以降级的，指定版本安装

**Comment by taooceros** [comment]
> VS可以降级的，指定版本安装

明儿尝试一下

**Comment by taooceros** [comment]
我被vs约谈了，到时候顺便问问他们吧

**Comment by zhuxb711** [comment]
> 我被vs约谈了，到时候顺便问问他们吧

约谈？好的还是坏的约谈🤪？发生了啥~

**Comment by taooceros** [comment]
> > 我被vs约谈了，到时候顺便问问他们吧
> 
> 约谈？好的还是坏的约谈🤪？发生了啥~

好的约谈哈哈哈，2022的反馈回访（不过我用个community版本都能被回访我也没想到

**Comment by zhuxb711** [comment]
> > > 我被vs约谈了，到时候顺便问问他们吧
> > 
> > 
> > 约谈？好的还是坏的约谈🤪？发生了啥~
> 
> 好的约谈哈哈哈，2022的反馈回访（不过我用个community版本都能被回访我也没想到

哈你约谈这个词让我想到纪委(沙雕)

**Comment by zhuxb711** [comment]
感觉还是直接停在2.5然后等Reunion直接上吧

**Comment by taooceros** [comment]
https://developercommunity.visualstudio.com/t/Visual-Studio-2019-version-1610UWP/1437211

这个问题似乎有workround了，我试试

**Comment by silentmoooon** [comment]
好像最新版已经OK了

**Comment by taooceros** [comment]
好像是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 上午7:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhuxb711/RX-Explorer] 升级至WinUI 2.6 (#287)





 
好像最新版已经OK了

**Comment by zhuxb711** [comment]
RX大概上上个星期已经应用了这个workaround 了(⁎⁍̴̛ᴗ⁍̴̛⁎)
