### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#288]
1. 清空回收站时进度要放在任务列表里才好看；
2. 将“永久删除”和“删除”做出一些区分，建议参考系统方案；
3. 好像不能自定义快速访问？
4. 在盘符上右键的功能好像太少了那么一点点；
5. 文件夹打开设为单击，但是只有盘符可以单击打开，文件夹不行；（UpDate：这个单击模式很多bug，还是先算了吧）
6. 文件（夹）属性中可以设置的项太少了；
7. 复制完文件后如果目标文件夹的选项卡还开着的话要将焦点定位至复制后的文件；
8. 查看文件为“详细信息”模式的时候，不要只有“名称”、“修改时间”、“类型”、“大小”几个方式，可以多给很多方式。在顶端右键应该要可以自定义显示哪些方式，参照系统方案。
9. 文件夹要自动刷新，而避免手动刷新。当文件夹中由程序或者其他窗口修改或创建、删除了文件的时候，Windows资源管理器会立马显示，但RX文件管理器不会，需要手动刷新。

就是很多系统文件管理器有的功能没有，我觉得应该至少包含Windows资源管理器的文件方面的全部功能吧……=

**Comment by g-mph** [comment]
哦，原来快速访问要在主页上面右键点添加
可以加几种方式添加吗，比如：
在文件夹上右键选添加到快速访问；
在快速访问右键选将当前文件夹添加到快速访问；
将文件夹拖至快速访问上方以添加到快速访问

**Comment by zhuxb711** [comment]
> 至少包含Windows资源管理器的文件方面的全部功能吧

那你还真是高看我了，微软写系统文件管理器的历史少说也有十多年了，维护的人也应该有几百，RX主要就我一个人，这要求是不是有点过分了。再提一句，Windows资源管理器不只是文件管理，严格来说你用的桌面也是资源管理器的一部分(不是文件夹的那个桌面)，控制面板、网络中心、系统属性等等都是资源管理器的一部分

1. 清空回收站无法跟踪进度，放到任务列表里也是没卵用的
2. 这个可以考虑
3. 文件夹右键菜单已经没有额外的空间了，现在已经很拥挤了；快速访问右键将当前文件夹添加到快速访问？用户可能通过垂直拆分窗口而产生多个文件夹，我会觉得这将导致用户不太清楚是添加了哪个文件夹；目录树现在不允许拖拽是因为微软的控件有BUG
4. 该问题将于下一个版本中解决
5. 单击模式适用于盘符、库文件夹、和正常显示的文件夹，目前没有观察到明显的问题
6. 文件属性基本没有开放设置，这个功能复杂且较少用户会使用，大部分都是查看(查看也已经够复杂了)
7. 从RX允许并行复制、粘贴和删除操作并且不会阻止用户在操作期间做其他事情的时候开始，就已经无法跟踪并在操作后选中文件了(现在唯一能做到这件事情的就是重命名后选中，这个是有的)，早期RX做任何文件操作都会阻止用户进一步操作软件，直到完成，这样的话可以完成后选中，软件开发总是充满了取舍
8. 微软官方控件不支持这么动态的更改(非UWP的控件是可以调整列宽的，UWP砍了，可见一斑，微软不想你这么做，因为要触摸屏优化，(鼠标体验？关我微软什么事情))
9. RX是具备文件变化跟踪的，但在“网络驱动器”和“某些需要特别权限”的区域除外，不知道你是怎么得出RX没在跟踪文件变化的结论的

**Comment by g-mph** [comment]
5.这个可能是我系统的问题了。。
9.好像没法复现了，可能是我电脑卡了吧

新增一点10.开始了一个任务貌似就没法停止了

**Comment by g-mph** [comment]
算了，bug有一点多

**Comment by zhuxb711** [comment]
> @zhuxb711
> 
> 0.那句话里不是有“文件方面”吗
> 5.这个可能是我系统的问题了。。
> 9.好像没法复现了，可能是我电脑卡了吧
> 
> 新增一点10.开始了一个任务貌似就没法停止了

你用系统文件管理器可以停止是因为它是官方的东西，用了不知道什么内部的接口从而可以中断文件操作，第三方是做不到的
