### ISSUE TITLE
建议添加功能：在快速访问中固定自定义目录

### ISSUE THREAD

**Issue by noahtie** [zhuxb711/RX-Explorer#289]
![image](https://user-images.githubusercontent.com/71956825/123993929-76ec0800-d9ff-11eb-9487-732c985bac67.png)
类似于Windows资源管理器的这个功能

**Comment by zhuxb711** [comment]
有，它和文件夹和库是联动的

**Comment by zhuxb711** [comment]
我知道你接下来要巴拉巴拉一堆什么直接能够添加会更方便啊啥的。打住，这个功能已经做好了只是还没有发布。😀
