### ISSUE TITLE
bat 格式文件的打开方式无法选择其他应用

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#29]
version：5.3.3.0
如果想通过记事本等工具编辑 bat 文件，右键选择“打开方式——选择其他应用”是灰色的，
另外不是所有的 bat 格式文件双击都能执行，我在使用 Tomcat 的时候就无法执行 startup.bat，双击没有反应，必须通过终端手动执行 bat 文件或者调用系统资源管理器去双击打开
![屏幕截图 2020-09-13 221512](https://user-images.githubusercontent.com/26058690/93020685-f9424180-f610-11ea-9b77-2bcc4722fb03.jpg)

**Comment by zhuxb711** [comment]
下个版本中将支持编辑bat文件

**Comment by zhuxb711** [comment]
版本5.3.6已解决该问题
