### ISSUE TITLE
属性界面多次按Tab，发现一个莫名其妙的可选中的控件

### ISSUE THREAD

**Issue by oxygen-dioxide** [zhuxb711/RX-Explorer#290]
![image](https://user-images.githubusercontent.com/54425948/124113414-00521780-da9e-11eb-92de-cffcca423a08.png)

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/124237846-8fb50480-db4a-11eb-834c-5f8e22c54a92.png)

文件夹和文件通用一个模板，只是启用了不同的部分，我已确定该问题实际上是来源于文件属性窗口中的“更改”按钮。
我手动指定了它的内边距，因此在父控件的大小设置为0的时候，它还是能够出现在Tab的顺序内。该问题将于下一个版本中修复

(6.7.8的下一个版本，6.7.8已提交商店)
