### ISSUE TITLE
虽然之前反馈了很多问题，还是想反馈一下这个

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#294]
就还是这个**设为单击打开经常单击会打不开文件夹**的问题，
一开始我以为是我电脑的问题，现在用另外一台电脑测试之后发现还是存在这样的问题

![](https://z3.ax1x.com/2021/07/14/WZmGaq.gif)

**Comment by g-mph** [comment]
为啥GitHub加载不出图片。。
就不用MD了，直接链接粘这儿

<https://z3.ax1x.com/2021/07/14/WZmGaq.gif>

**Comment by zhuxb711** [comment]
跟我反馈没用，这是由于该问题是又微软的控件本身引起的。
显示文件的控件叫ListView，该控件具有一些严重的BUG，例如点击某些地方不会发出事件响应。而你遇到的这种情况就是该控件不会做出任何响应，因此虽然你点击了它，但它并没有通知RX的处理函数带你进入那个文件夹，对于RX本身来说，就仿佛什么都没有发生一样，RX是事件驱动的软件，没有事件发生=用户没有做任何操作。ListView吞了用户的操作而不告知RX=RX认为用户什么都没做=RX不会作出任何响应

**Comment by zhuxb711** [comment]
目前比较有效的办法是点击文件名所在的范围，其他地方都容易被吞。

**Comment by g-mph** [comment]
额，还有这种操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月14日(星期三) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhuxb711/RX-Explorer] 虽然之前反馈了很多问题，还是想反馈一下这个 (#294)





 
目前比较有效的办法是点击文件名所在的范围，其他地方都容易被吞。
 
&mdash;
