### ISSUE TITLE
在拖动时无论按住Alt还是Shift还是Ctrl都无法从复制切换到移动

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#295]
RT

**Comment by zhuxb711** [comment]
你的Gif或者视频呢？上来一句话其他全没有。

![GIF 7-16-2021 10-27-12 AM](https://user-images.githubusercontent.com/42038175/125882319-6379123b-6c66-4519-9a85-a6a7fa9c73f4.gif)

**Comment by g-mph** [comment]
就在我准备录gif的时候有遇到了第二个问题
<https://z3.ax1x.com/2021/07/16/WKS5l9.gif>

以下是原问题测试（录制不能显示键盘按键很别扭）：
Shift:<https://z3.ax1x.com/2021/07/16/WKpUn1.gif>
Alt:<https://z3.ax1x.com/2021/07/16/WKpOH0.gif>
Ctrl:<https://z3.ax1x.com/2021/07/16/WK9mCD.gif>

**Comment by zhuxb711** [comment]
你要在拖拽不松手的情况下持续按住Ctrl并保持到你拖拽松手

**Comment by zhuxb711** [comment]
第二个是啥问题，没权限就是没有权限

**Comment by g-mph** [comment]
> 第二个是啥问题，没权限就是没有权限

所有用户组都是满权限了

![image](https://user-images.githubusercontent.com/64201424/125884264-1017ab3c-d6e7-4a16-a3d7-7b6c88559420.png)

![image](https://user-images.githubusercontent.com/64201424/125884281-0a780e39-5598-4443-a8fa-490e268bd1ae.png)

![image](https://user-images.githubusercontent.com/64201424/125884300-4a8c10ae-13e8-4553-98be-e9d19ffb42a7.png)

![image](https://user-images.githubusercontent.com/64201424/125884316-6c59e406-89c5-4e53-8b34-aaddb7869557.png)

**Comment by zhuxb711** [comment]
这和你用户是不是满权限没有关系，UWP是沙盒应用程序，使用的是低权限令牌。微软自己的文件管理器是属于白名单的软件，它提权都不需要过UAC的直接就提了。用户权限和应用软件权限是两码事，有高权限令牌也有低权限令牌，传统Win32应用用的是和当前用户权限一致的普通权限令牌，所以你能干什么那些应用就能够干什么。对于UWP应用微软限制了只能分配低权限令牌，其权限小于当前用户权限，所以有些地方访问不到是正常的

**Comment by zhuxb711** [comment]
好消息是下一个版本中将支持创建文件时的提权操作

**Comment by zhuxb711** [comment]
另外就是下一个版本默认拖拽操作将会更改为移动，按下Ctrl切换复制
