### ISSUE TITLE
勾选”按 F7 时不再询问我“后又再询问我

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#296]
![image](https://user-images.githubusercontent.com/64201424/125885153-f9cffdd3-53f4-4ab0-b16f-9fe6795b54b5.png)

此时我勾选它，并且点击”否“，在当前窗口就不会再询问我了。

**但是！** 当我在另一个窗口使用时，它又在询问我了。。。

**Comment by zhuxb711** [comment]
这个不是RX自己的框框，是微软做的框框，RX的代码中没有关于此框框的代码

**Comment by zhuxb711** [comment]
你看这框没有亚克力效果，明显不是RX自己的
