### ISSUE TITLE
当我在Office里保存文件时，点一下保存RX里就多一个图标

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#297]
RT，得刷新才能恢复
![image](https://user-images.githubusercontent.com/64201424/125910834-589ff494-3d1b-40c8-a8c3-04c01934df3e.png)

**Comment by zhuxb711** [comment]
这个行为应该是与Office的行为相关联的。
保存的时候Office实际上做了很多工作，原文件是会被替换的，Office会采用事务的方式写入文件。因此产生了临时文件，但随后又快速重命名该临时文件为原有名称，设计上RX并没有预料到重命名可以产生和现有文件名称一致的情形(理论上同一个文件夹下没有两个文件可以是相同名称)，因此RX在重命名操作的时候只会移除 新名称/旧名称 二者其一 (有时候数据可能没有及时刷新，不清楚现在显示出来的名称到底是哪个)，如果文件不可能存在相同名称的情形，则上述逻辑正确。

但似乎Office写入文件的时候某一个瞬间存在这种情形，上述假设被破坏，现已修改为搜集目前在显示的所有文件路径并移除所有匹配 新名称/旧名称 的文件以解决该问题
