### ISSUE TITLE
在“快速启动中添加应用或网站时的一些问题

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#299]
不知道怎么表述，看gif吧

<https://z3.ax1x.com/2021/07/16/WM3OiT.gif>

**Comment by zhuxb711** [comment]
那就不用表述了，下一个版本已经改成向上弹出了，不存在什么向左弹出的问题

**Comment by g-mph** [comment]
> 那就不用表述了，下一个版本已经改成向上弹出了，不存在什么向左弹出的问题

然而更新后依然存在一模一样的问题

**Comment by zhuxb711** [comment]
> > 那就不用表述了，下一个版本已经改成向上弹出了，不存在什么向左弹出的问题
> 
> 
> 
> 然而更新后依然存在一模一样的问题

然而并没有

**Comment by g-mph** [comment]
> > > 那就不用表述了，下一个版本已经改成向上弹出了，不存在什么向左弹出的问题
> > 
> > 
> > 然而更新后依然存在一模一样的问题
> 
> 然而并没有

<https://z3.ax1x.com/2021/07/16/WQ9Sgg.gif>

**Comment by zhuxb711** [comment]
你这只有720p的屏吧，还是缩放开得大，空间小了啥都重叠在一起了，正常。就好像你把RX缩小到最小，啥都会重叠，优化也没有用。

**Comment by zhuxb711** [comment]
不过现在它会向左是因为RX指定向上是“建议”不是“必须”，上面空间不够了自己会选合适的方向

**Comment by g-mph** [comment]
> 你这只有720p的屏吧，还是缩放开得大，空间小了啥都重叠在一起了，正常。就好像你把RX缩小到最小，啥都会重叠，优化也没有用。

妙啊，我把窗口再拉大一点就行了

**Comment by zhuxb711** [comment]
屏幕空间小了就算我让他向上超过RX本身的高度，你还是可以说为啥会超过屏幕边缘

**Comment by zhuxb711** [comment]
我已经让它超过RX区域本身的的高度了（见最新提交，改动不包含在6.8.4里面）

**Comment by zhuxb711** [comment]
6.8.4的话如果任何一面都没有足够的空间，它会弹出来又弹回去，问就是辣鸡微软是这么设计的

Whatever，下版本就算上面位置不够也是阔以展开向上的，着急的话可以加内测版，过一段时间会推内测
