### ISSUE TITLE
无法显示NAS映射的驱动器内容

### ISSUE THREAD

**Issue by Renwq** [zhuxb711/RX-Explorer#3]
NAS映射出的驱动器 盘，打开后，不显示内容，无任何报错.

**Comment by zhuxb711** [comment]
抱歉，我将调查相关问题，查看是否能够予以解决，请耐心等待。

**Comment by zhuxb711** [comment]
该问题原因已经明晰，RX文件管理器所使用的快速枚举文件的API不能进行网络通信而导致

**Comment by zhuxb711** [comment]
但这并不是说无法解决，我正在进行一些更改，期望能够兼容NAS网盘，虽然加载速度较慢

**Comment by Yrp** [comment]
希望可以支持常用的一些像smb，nfs，sftp，ftp这样的网络传输协议
