### ISSUE TITLE
文件夹右键后菜单显示错误

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#30]
version：5.3.3.0

1. 打开 rx 文件管理器
2. 随便找某个文件夹右键，发现菜单显示显示异常，如下图所示，不是每次都有
![屏幕截图 2020-09-13 223012](https://user-images.githubusercontent.com/26058690/93021084-648d1300-f613-11ea-9f41-59b3971274d5.jpg)
3. 右键文件夹时不是每次都会选中，如下面四张图所示，比较令人困惑
![屏幕截图 2020-09-13 223523](https://user-images.githubusercontent.com/26058690/93021284-6e634600-f614-11ea-9f97-da27e7e0e0c0.jpg)
![屏幕截图 2020-09-13 223549](https://user-images.githubusercontent.com/26058690/93021289-715e3680-f614-11ea-89f3-354147a9d9a0.jpg)
![屏幕截图 2020-09-13 224259](https://user-images.githubusercontent.com/26058690/93021400-f2b5c900-f614-11ea-8fa0-9a6a85a748b2.jpg)
![屏幕截图 2020-09-13 224330](https://user-images.githubusercontent.com/26058690/93021405-f5b0b980-f614-11ea-976c-6734aa0a09c8.jpg)
4. 打开 rx 文件管理器后双击进入某磁盘根目录，比如 d 盘
5. 使用快捷键 shift + w 或者 shift + e 打开 cmd 或者系统资源管理器，无效
6. 右键某文件夹弹出菜单，出现上述第三步中的没有选中情况，即弹出菜单中出现 shift + w 和 shift + e 选项
7. 如果第六步出现选中情况，则继续右键某文件夹，直到出现没有选中情况为止
7. 随便点击某处取消右键菜单，这时候再使用快捷键 shift + w 或者 shift + e 就能打开 cmd 或者系统资源管理器
8. 此时打开新标签，进入另外一个磁盘根目录，比如 c 盘
9. 使用快捷键 shift + w 或者 shift + e 打开 cmd 或者系统资源管理器，却显示的是 d 盘内容而不是 c 盘

**Comment by zhuxb711** [comment]
右键位置必须处于每一个文件的中间附近的区域才能够显示该文件/文件夹的菜单
这不是一个BUG，而是刻意为之。RX并不会像文件管理器那样给下方预留很多空间，因此若文件铺满整个页面时，没有办法点击空白处进而弹出空白区域的右键菜单，因此RX设计上就利用了文件和文件之间的区域，若单击这些地方，则会弹出空白区域的右键菜单。如下图，蓝色区域是该文件对应的右键菜单触发区域，红色是空白右键菜单触发区域（实际上的面积比蓝色部分要稍大一些，以下仅作示意）
![image](https://user-images.githubusercontent.com/42038175/93034862-10634c80-f66e-11ea-8630-0536abce7339.png)

至于右键菜单的快捷键BUG，应该是由于控件本身引起的，RX放手让控件自动完成，但似乎现在看来效果不佳，对于这个右键菜单的快捷键问题，RX将在下一个版本中对其进行修改，确保功能恢复正常

**Comment by all-aroundbadass** [comment]
这个右键菜单的弹出位置设计可以参考微软的资源管理器设计，当目录中的内容超出一屏高度的时候，将滚动条拉到底，微软的资源管理器也不会在下方留出多余的空白位置，他是在未选中某行的情况下，文字范围外的地方就是空白区域，选中某行的情况下，整行范围都可以弹出文件/文件夹菜单，也就是说你的蓝色区域包含了空白区域和文字范围区域，目前你的设计在用户操作的时候没有明显的范围区分，导致在文字外点击有时候会选中，有时候不会选中，很明显微软的细节处理会更好一些，实现上是不是可以先判断这行有没有选中，如果选中，那么红色区域都是文件/文件夹菜单，如果没有选中，则判断点击位置是否在文字范围内，这个文字范围包括了文件名的长度，修改日期、类型、大小这些文字的长度，在这范围内的选中整行的同时弹出对应的文件/文件夹菜单（蓝色区域划分成四块空白区域，四块选中区域），否则就弹出空白区域的菜单，当然弹出空白区域的菜单是不会选中当前行的

**Comment by zhuxb711** [comment]
![GIF 2020-9-15 9-47-59](https://user-images.githubusercontent.com/42038175/93155450-b3809880-f738-11ea-86f5-f2f54063a0df.gif)
嘿你不说我还真没注意系统文件管理器是这样设计的，你想要的效果是这样的吧？

**Comment by all-aroundbadass** [comment]
是的，这从字面理解“空白位置点击右键”也好理解，怎么说呢，做一个好的产品，细节处理很重要，尤其用户体验这块，如果想做的完美一些，可以参考别人的设计，把人家好的设计吸收过来

**Comment by zhuxb711** [comment]
这些问题呀要慢慢来，一个版本一个版本的去改，毕竟这就我一个人开发，一上来就关注到太多细节问题也不太现实。但总之还是谢谢您的建议啦，预计这个更改将会在下一个版本中上线。

**Comment by all-aroundbadass** [comment]
嗯，好的，我忘了提一下，可能管理器的右边要留出固定宽度做为空白区域，比如10%，而不是现在的选中行铺满整个窗口宽度，因为当你全选所有文件的时候，再想点击空白处取消全选，或者右击空白处弹出菜单就没法操作了，不然只能从“全选 -> 选中一个 -> 点击空白处取消所有文件选中”之间来回切换

**Comment by zhuxb711** [comment]
最右侧一直都有最少50像素宽度的空白用于取消选择

**Comment by zhuxb711** [comment]
版本5.3.6已解决该问题
