### ISSUE TITLE
使用自带的解压功能,文件乱码

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#300]
![屏幕截图 2021-07-18 225718](https://user-images.githubusercontent.com/62456287/126071980-d7f907d1-a915-44fb-ac46-050fbf8126b2.png)
![屏幕截图 2021-07-18 225659](https://user-images.githubusercontent.com/62456287/126071982-d3632401-9ced-43ab-9f32-15e6993730de.png)

**Comment by zhuxb711** [comment]
您详细看了右键菜单了么？

只知道有一个解压按钮啥也不管点了解压出来是乱码然后就提issue？

有个叫解压选项的点过没有？明显是因为压缩包使用了奇怪的编码比如GBK之类的，自己用解压选项改编码，你不改，那就是用UTF8解压，用UTF8解压GBK编码的东西，那是你的问题，这不是RX的Bug
