### ISSUE TITLE
Missing network drive

### ISSUE THREAD

**Issue by clutz2000** [zhuxb711/RX-Explorer#301]
I just downloaded and really liking it so far. I have ran into an issue though. I am missing network drive in the left pane, specifically P drive. it is a shared folder on an extra computer just like the other mapped drives shown. I am not sure why P is missing.

![image](https://user-images.githubusercontent.com/9699859/126378173-c4231283-b100-4d49-8ef1-a9ddd5148072.png)

**Comment by zhuxb711** [comment]
Could you send me the logs that can be exported from the settings?

**Comment by clutz2000** [comment]
I uninstalled and reinstalled the software, which seemed to fix the issue. Sorry for the false alarm.

Chris

________________________________

**Comment by zhuxb711** [comment]
Never mind. I will close this issue. Thanks.
