### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#304]
~~没错我又来发Issue了~~

1. 发现RX在按住Alt并双击的文件夹或文件的时候会打开文件或文件夹的属性，而按住Alt并双击盘符则会打开这个盘符。

2. 在文件或文件夹上右键有标记的功能。但是，只要鼠标移到上面就会转换到标记页面，有时鼠标移动幅度太大就移到那儿了，直接就打开标记页面了，不方便。
3. 复制文件的时候进度条为什么卡住了？测试剪切的时候可能文件数量太少没发现，所以剪切的我不是很确定。<https://z3.ax1x.com/2021/07/23/WrHesI.gif>
4. 复制文件的时候如果遇到了重名的文件夹会提示，在点击“保存副本”之后按钮依旧没有消失。剪切或者点击“覆盖文件”也会，只不过我没有录制gif。<https://z3.ax1x.com/2021/07/23/WrHYyn.gif>
5. 另外剪切的时候如果选择了“保存副本”则剪切之后的文件（夹）会多出“ - 副本”来，此时执行撤销命令，文件回到原来的位置，但是“ - 副本”并没有删去。<https://z3.ax1x.com/2021/07/23/WrHtLq.gif>
6. 这讲不清楚，大概就是重命名之后顶栏上的文件夹名不会改变。<https://z3.ax1x.com/2021/07/23/WrHDW4.gif>

以上是我今天整理文件的时候遇到的一些奇奇怪怪的事情，经过反复测试确保能复现。

对了，版本号为6.8.4.0。

顺便问一句，Microsoft Store不能微信支付吗？

**Comment by zhuxb711** [comment]
抱歉迟了，前面在放假没有及时回复，相关问题正在关注，请等待后续消息。
MSStore只支持银行卡或者支付宝，微信支付在MSStore诞生的时候还没有火起来(2015)，因此只和支付宝有合作关系

**Comment by zhuxb711** [comment]
1. “驱动器”和“文件夹和库”并未提供Alt+双击打开属性的支持，这不是BUG，但将会在下一个版本中添加支持
2. 标记是有意设计成鼠标滑过时自动切换的，理由是当时有一些微软的BUG无法避免(鼠标状态下是鼠标进入就切换，触摸屏下是点击切换)，目前我试了一下似乎点击也没有啥问题了，那就改成点击切换洛
3. 经过检查确认这是一个BUG，由于代码的一些问题将导致进度无法从辅助进程同步至RX。该问题较为隐蔽，且应当已经存在了多个版本，SSD电脑上复制小型文件时不明显，机械硬盘上或复制大型文件时容易注意到没有进度显示。目前该问题已在开发版本中修复
4. 点击保存副本等按钮后不会立刻发生界面上的变化是因为在这种名称冲突时，该任务的状态由Processing→NeedAttention，用户做出反应之后，状态延续NeedAttention而不是继续转换为Processing，该状态持续直至该任务完成NeedAttention→Completed。因此界面上的变化仅会在任务完成时发生，若任务持续时间较短，该问题不明显；若任务持续时间较长，该问题明显，因为只有最终完成时才会变化，也就是你说的卡住。

简化流程并忽略所有无关流程分支、错误或终止分支后如下：
+ 错误流程：Preparing→Processing→NeedAttention→Completed
+ 正确流程：Preparing→Processing→NeedAttention→Processing→Completed

该问题现已得到更正

5. 仍在调查是否可以更正该行为
6. 你的操作是在重命名父文件夹，RX自身的文件检测仅会检测当前文件夹下的变动，因此若重命名父文件夹，则不会被检测到，因此地址栏中不会予以更新。我已重新设计重命名当前文件夹时的机制，重命名父文件夹现在将导致RX重新加载新名称的文件夹。地址栏灰色部分是临时显示一些历史记录，方便快速回溯之前访问过的具有相同起始地址的文件夹，该部分仅是记录而不是跟踪，不保证该文件夹是否仍然存在，因此它不被更新是正确的行为

**Comment by g-mph** [comment]
emmm，
你的README里面的UWP 应用隐私策略中文版第10点为啥变成了第11？

**Comment by zhuxb711** [comment]
> emmm，
> 你的README里面的UWP 应用隐私策略中文版第10点为啥变成了第11？

可能是序号乱了

**Comment by zhuxb711** [comment]
您提出的第5点现经过架构更新已得到更正，所有问题已更正完毕
