### ISSUE TITLE
快速启动添加网站时如果不设置图标将不能添加？

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#305]
<https://z3.ax1x.com/2021/07/27/WhDcSs.gif>

**Comment by zhuxb711** [comment]
导致拦截失效的原因是因为默认那个＋号的图片路径因为需要适应系统深浅色的变化而更改了路径。但此处作为拦截的相关逻辑没有更新导致意外绕过必须添加图片的限制
