### ISSUE TITLE
启动时检测移动存储设备的机制有待优化

### ISSUE THREAD

**Issue by jxharp** [zhuxb711/RX-Explorer#306]
前几天还在抱怨RX启动完成后要等几秒才能操作，今天仔细观察，发现有一种特殊情况，导致RX需要等待。

我是笔记本用户，插上一个type-c扩展坞，外接显示器和键盘使用。这个扩展坞商默认有两个存储卡插槽， tf和SD卡槽。我并没有插入任何东西。
RX启动时，本地硬盘盘符快速加载出来，然后等待了几秒钟，才加载这两个卡槽的盘符。这几秒内，是无法操作任何元素的，界面是停止响应的。等这两个盘符加载出来，才能操作。 我拔掉扩展坞，这个问题就消失了

为什么需要优化？ 因为微软自己的资源管理器和竞品File，就没有这个问题，启动后就能操作。 现在RX只能备用，这几秒的卡顿真的影响心情，需要快速操作时，只能用其他的文件管理器。

PS： 我笔记本也自带一个tf卡槽， 当没有插入tf卡时，RX并不会检测这个卡槽，也就不会卡顿。   检测机制请优化。

**Comment by zhuxb711** [comment]
目前RX仅考虑了网络驱动器存在延迟的问题，其他驱动器一视同仁，看你的描述，现在可能要考虑慢速USB的问题。

Files目前暂时无法与RX竞争哈哈哈哈，功能差太多

**Comment by jxharp** [comment]
今天更新后，并没有改善哦。 还是卡死。 是否可以将移动设备检测在启动后，在后台检测呢？ 扩展坞的卡槽，笔记本自带的卡槽，似乎与普通的U盘，移动硬盘不一样，没有插入卡也会显示盘符的，研究看看win自带的资源管理器怎么处理的呢？

**Comment by zhuxb711** [comment]
> 今天更新后，并没有改善哦。 还是卡死。 是否可以将移动设备检测在启动后，在后台检测呢？ 扩展坞的卡槽，笔记本自带的卡槽，似乎与普通的U盘，移动硬盘不一样，没有插入卡也会显示盘符的，研究看看win自带的资源管理器怎么处理的呢？

自带的文件管理器又不开源，研究不了，6.8.9已经将移动存储设备也纳入了后台加载，还不行那说明不是移动存储设备的问题。另外你讲扩展坞卡槽之类的没啥用，软件层面不会区分你是哪个卡槽进来的，不然怎么叫通用存储设备

**Comment by zhuxb711** [comment]
有新的怀疑对象了，请加群进入内测组以接收测试版来验证（可能下星期一或这周末会发新的内测版）

**Comment by zhuxb711** [comment]
6.9.0内测已发布

**Comment by zhuxb711** [comment]
6.9.3已发布

**Comment by jxharp** [comment]
更新到最新版本后，发现有一些变化：  1. 笔记本内置的读卡器，虽有延迟，但是时间不长，可以快速显示了。 2. type-c扩展坞的几个usb口，检测还是非常慢，还是会卡死8秒左右

**Comment by jxharp** [comment]
对比微软自带资源管理器和File， 在插上和拔下扩展坞的情况下，显示驱动器的时间几乎没有不同。   对比linux下，deepin的文件管理器，压根就不显示没插入移动设备的usb口。 看来各个系统，软件处理逻辑有所不同，但都能达到不被外接设备拖累的效果。 

RX再找找方法呢， 召集群友多测试下。

**Comment by zhuxb711** [comment]
最快的方法是用调试器直接在存在问题的电脑上测试，这是最快能够知道到底是哪里卡住的方法。但是我目前没有发现或者能够复现卡死的问题，只能是一遍遍看代码然后猜测哪里可能存在延迟

**Comment by zhuxb711** [comment]
这个方法对用户电脑有搭建编译环境的要求，比较难实现

**Comment by jxharp** [comment]
我用的是绿联的typc-c扩展坞，也算保有量比较高的知名品牌配件了，笔记本+扩展坞的用法大有人在，是不是可以针对扩展坞测试下呢？

**Comment by jxharp** [comment]
还是没有改善。 换个思路，能否把加载外置usb做一个开关放在设置里面？让用户自由选择启动时是否加载？ 再加一个选项，延迟加载，让用户输入秒数。           
在使用界面上也放一个快捷按钮，用户点击才加载？

这个思路外置驱动器和网络驱动器都能用

**Comment by zhuxb711** [comment]
改了这么多版本还没有解决，说明不是这里的问题

**Comment by jxharp** [comment]
可是微软自带的和File就没有这个问题啊，从不延迟。
