### ISSUE TITLE
单击文件夹时模糊动画回弹过慢

### ISSUE THREAD

**Issue by WhiteLeaf36** [zhuxb711/RX-Explorer#308]
有时候单击完一下如果鼠标停留在文件夹上不动的话动画要等大概一秒才回弹..如果鼠标立即移走的话会立刻回弹。

**Comment by zhuxb711** [comment]
这是微软ListView控件状态机BUG，由于微软现在对于UWP平台存在两种控件，一类是通过Microsoft.UI.Xaml来作为附加组件更新的控件，一类是与Windows SDK本身集成的控件。对于Microsoft.UI.Xaml，可以通过更新该附加组件来解决BUG，对于Windows SDK，需要更新SDK才能够解决。不幸的是ListView恰好是Windows SDK中的组件。

由于微软平台战略的改变，Windows SDK自2004版本以来从未更新过，因此该问题无法解决 (本来按惯例21H1是大更新，结果现在变成21H2太阳谷才是大更新了，所以一直没有更新SDK)
