### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by Lwife** [zhuxb711/RX-Explorer#31]
希望能夠添加更多快捷鍵的支持.
比如:
退格可以回到上級目錄,或者上一個瀏覽的文件夾.
Ctrl+shift+N可以新建文件夾等.
而且在資源回收站中好像是不支持使用Ctrl+A選擇全部文件的.
ctrl+T新建標籤頁等
現在很多都要依靠鼠標才能操作,很大的降低了該有的高效性.

**Comment by zhuxb711** [comment]
版本5.3.6已解决该问题
