### ISSUE TITLE
选中文件后右键,右键菜单未显示

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#312]
版本6.8.9.0
![QQ录屏20210731080813 00_00_00-00_00_30](https://user-images.githubusercontent.com/62456287/127722487-716e6cbf-ce83-4d7e-bcc2-918a1205f8a5.gif)

**Comment by a15355447898a** [comment]
日记:
链接：https://pan.baidu.com/s/1_eoX7fNQyOQUp63gdtBrPQ 
提取码：yiv8

**Comment by zhuxb711** [comment]
一般情况下是微软的Bug，重启软件后可以恢复

**Comment by a15355447898a** [comment]
重启后恢复,谢谢!

**Comment by zhuxb711** [comment]
> 重启后恢复,谢谢!

右键菜单这个控件在多次打开之后可能导致系统异常，从而阻止右键菜单弹出，继续不断尝试激活右键可能会导致RX崩溃，微软写的垃圾UWP控件的锅
