### ISSUE TITLE
一段时间后程序卡死

### ISSUE THREAD

**Issue by raozhihao** [zhuxb711/RX-Explorer#315]
操作系统信息:

>设备名称	Rao-PC
处理器	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   1.38 GHz
机带 RAM	16.0 GB (15.7 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

RX版本:6.8.9.0(试用版)

打开后,随意打开一个文件夹,并切换到其它应用程序后
在大概五至六分钟后再次切换到Rx,则会出现卡死现象

**Comment by zhuxb711** [comment]
似乎并没有办法重现该问题...

**Comment by raozhihao** [comment]
@zhuxb711 可能是系统的问题?你可以试着让它在后台运行久一点,我在之前的版本就下载试用了,也是这个问题,然后今天又更新了windows后也更新了RX也是这个问题,不过这次更新后,RX的标题栏还可以用,但也只限于最小化和双击,双击后,呈现最大化时,可以看到整个界面的右边和下边出现了一大片的空白

**Comment by raozhihao** [comment]
![image](https://user-images.githubusercontent.com/38253068/127833014-525198d3-cf5f-4802-a061-cebbad1d5e19.png)
这是最大化时的样子,这次我让它在后台运行了15分钟

**Comment by raozhihao** [comment]
![动画RX_L](https://user-images.githubusercontent.com/38253068/127835098-59f1a31b-5e31-4e48-a971-64fc51a93f9b.gif)

就是这个样子了

**Comment by zhuxb711** [comment]
请上传日志文件

**Comment by raozhihao** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6930225/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
并没有发现有价值的内容

**Comment by raozhihao** [comment]
@zhuxb711 在windows11 1000.22000.120.0 版本上没有再出现过

**Comment by zhuxb711** [comment]
你这个问题原本就是Win11上面的嘛？如果是这样，预览版系统有问题很正常，RX没有针对Win11进行任何适配

**Comment by raozhihao** [comment]
@zhuxb711 不是,这个问题原本是win10上的,现在我升级到win11反而没有这个问题了,而且使用都很正常

**Comment by zhuxb711** [comment]
Emmm那可能是操作系统背锅？
