### ISSUE TITLE
打开程序时网络位置的磁盘有时候不会被加载进导航试图

### ISSUE THREAD

**Issue by bobmst** [zhuxb711/RX-Explorer#316]
一个iscsi连接的盘和一个映射的网络驱动器，有时候在启动RX Explorer的时候不会在导航视图里加载出来。在主窗体里面还是有能看见并且正常使用。

**Comment by bobmst** [comment]
![image](https://user-images.githubusercontent.com/22798393/127965351-bbbf6c9f-3378-4319-a215-0fbfa5e846df.png)

**Comment by zhuxb711** [comment]
请上传日志文件

**Comment by zhuxb711** [comment]
6.9.3已发布，请确认是否解决该问题
