### ISSUE TITLE
微信聊天中接收到的文件无法直接复制出来

### ISSUE THREAD

**Issue by JimmyManU** [zhuxb711/RX-Explorer#317]
我用微信电脑版，聊天时候收到的文件，在微信中点击右键=>复制，再切到RX中点粘贴，没有任何反应。
同样的操作用WE就直接复制到目标文件夹了。
这个操作可是非常常用的呀，因为这个问题，还同时要开着WE的窗口，专门用来从微信复制文件。

不知道大家是否遇到和我同样的问题？

**Comment by zhuxb711** [comment]
经过调查，从微信中复制的文件是由于微信设计不规范，请求的操作为None而不是Copy或者Move，因此被RX忽略，复制请求的发起方应当填充请求类型而不是保留默认的None，否则视为不请求任何操作

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/128019922-a94d1627-12bb-4ae3-af99-c3b2714af8ab.png)
各定义如下

**Comment by JimmyManU** [comment]
这是跟微信硬刚，完全不考虑改了吗？

**Comment by zhuxb711** [comment]
到底是谁和谁硬刚，微信不按设计规范来可以怪到RX的头上？
你这样说无非就是因为微信没有给你反馈渠道，给了你提了也不一定有用，所以就来找RX的问题。

None - 此标志表示“无操作”，通常在需要延迟呈现时使用，微信需要个屁的延迟，就是烂，不按规范，瞎搞完算数得过且过

**Comment by zhuxb711** [comment]
RX要改，就是在给微信这种沙雕擦屁股

**Comment by JimmyManU** [comment]
开发者有技术洁癖是完全可以理解的，是否为了特定用户场景来破例适配微信，确实是见仁见智的一种选择。分别站在作者和使用者的角度，可能会得出不同的结论。这已经超出技术范畴了，争论无益，关闭问题。希望作者继续开发更多更好用的功能。

**Comment by JimmyManU** [comment]
开发者有技术洁癖是完全可以理解的，是否为了特定用户场景来破例适配微信，确实是见仁见智的一种选择。这已经超出技术范畴了，争论无益，关闭问题。希望作者继续开发更多更好用的功能。

**Comment by zhuxb711** [comment]
微信的拖拽功能就填了请求类型进去，因此可以被RX文件管理器正常识别。微信辣鸡没得洗，吐槽归吐槽，实际上RX昨晚提交的代码已经变更了处理方式

**Comment by JimmyManU** [comment]
强！
