### ISSUE TITLE
希望可以增加关闭更新提醒按钮

### ISSUE THREAD

**Issue by subframe7536** [zhuxb711/RX-Explorer#318]
最新版一开始启动会卡很久，回退到上版本一直提醒更新emmm

**Comment by subframe7536** [comment]
最新版还会出现 appdata文件夹添加到快速访问然后关闭，再打开会无法找到文件夹而删除的情况

**Comment by subframe7536** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6938560/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
不会增加类似于关闭更新提醒的按钮(加了你也要更新，不更新加了也白加)，老老实实更新

**Comment by zhuxb711** [comment]
另外你这错误报告似乎是早一些的版本的错误报告，我自己试了添加一个隐藏文件夹(就类似你说的AppData，重新启动后是还存在的)

**Comment by subframe7536** [comment]
后面我试着复现了一下，确实没有出现删除文件夹的情况，但是还是有需要等很久才能够点击的情况，有视频和日志
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6940005/Export_All_Error_Log.txt)

https://user-images.githubusercontent.com/78338239/128383890-5a0f4765-4ace-414d-a8a1-7f68fca7a1f8.mp4

**Comment by zhuxb711** [comment]
启动后卡住目前尚不清楚是由于何种原因造成的，可能需要实机调试才能够确定，我这里也无法复现。如果您有发现冻结与什么功能相关，请通知我，谢谢

**Comment by subframe7536** [comment]
emmm压缩的时候不知道为什么把后面剪掉了...后面吧Appdata目录取消固定到快速访问就可以正常用了

**Comment by subframe7536** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/6942423/Export_All_Error_Log.txt)
这是重置后的log，还是一样的问题

**Comment by subframe7536** [comment]
顺带一提 缩略图比较小的问题怎么解决
![image](https://user-images.githubusercontent.com/78338239/128442562-86dbe10e-cfdb-488e-b12e-e770f66b7afb.png)

**Comment by zhuxb711** [comment]
> 顺带一提 缩略图比较小的问题怎么解决
> ![image](https://user-images.githubusercontent.com/78338239/128442562-86dbe10e-cfdb-488e-b12e-e770f66b7afb.png)

解决不了，RX从系统API获取缩略图，UWP API对部分图标就是返回这种小图标，无解

**Comment by zhuxb711** [comment]
```
Exception: System.UnauthorizedAccessException: 拒绝访问。 (Exception from HRESULT: 0x80070005)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at RX_Explorer.Class.FileSystemStorageFolder.<GetStorageItemAsync>d__27.MoveNext() + 0xd1
```

这并不是什么大问题，也不会影响固定的操作，这个Log存在是因为你将一个隐藏文件添加了进来，对于UWP应用，无法访问隐藏文件

**Comment by subframe7536** [comment]
感谢解答！
