### ISSUE TITLE
關於文件重命名問題

### ISSUE THREAD

**Issue by TEEENEEET** [zhuxb711/RX-Explorer#319]
請問文件重命名可以選擇不彈窗麼？很多時候需要配合Quicker的動作批量修改文件名，望採納！

**Comment by zhuxb711** [comment]
可以间隔1s多一点再次点击已选中的文件，会有重命名的输入框可以直接让你重命名，不需要弹出对话框

**Comment by TEEENEEET** [comment]
> 可以间隔1s多一点再次点击已选中的文件，会有重命名的输入框可以直接让你重命名，不需要弹出对话框

但是用F2重命名，弹窗还是会有，动作录入都是键盘操作。

**Comment by zhuxb711** [comment]
因为这个非弹框的方式是仅为鼠标操作而设计的
