### ISSUE TITLE
目录树在特定情况下显示不完全

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#322]
发生的条件:
1. 进入一个隐藏文件夹
2. 退出软件
3. 重新打开软件
4. 点卡历史记录中的那个隐藏文件夹
![QQ录屏20210811174334 00_00_00-00_00_30](https://user-images.githubusercontent.com/62456287/129007720-ee3d4a83-de3a-46c5-b9ae-263924640943.gif)

**Comment by zhuxb711** [comment]
经调查，该问题确实存在，但与是否是隐藏文件夹无关，普通文件夹也可导致该问题。

该问题由竞争性条件导致，目录树监听文件夹和库模块添加文件的事件，这样它加载的时候就不必等待整个文件夹和库都加载完成，能够显著提高加载速度。那么该事件可能会导致它与另一个初始化代码相互干扰(初始化时也会加载一次文件夹和库，但可能不完整，剩余节点应当由后续的监听事件补全)，因此目录树仅在初始化完成之后才会开始监听，从而避免两个的竞争关系。

但由于代码设计缺陷，现已查明若RX被配置为恢复上次打开的标签页时，对于启动后从未点开过的标签页，它们会在初始化函数中卡住直至用户点选该标签页(主要是跟垂直拆分视图的布局有关系，设计垂直拆分视图的时候还没有恢复上次打开的标签页这个选项，因此一直没有改进它的设计)，因此初始化时加载库不完全，但卡住初始化则会导致不会开始后续监听，故可能错过一个或更多目录树根节点。

我已更改相关代码确保即使同时初始化和事件引发都不会存在问题，因此事件监听提前开始，消除了阻塞初始化完成的因素
