### ISSUE TITLE
希望能支持在右边区域打开文件夹时，左边区域文件树自动展开到打开的文件夹

### ISSUE THREAD

**Issue by luoxuwei** [zhuxb711/RX-Explorer#324]
希望能支持在右边区域打开文件夹时，左边区域文件树自动展开到打开的文件夹

**Comment by zhuxb711** [comment]
该功能不予支持，具体原因是目录树展开速度慢，深层次的目录需要很多时间才可以展开，将严重拖慢整体运行速度

**Comment by zhuxb711** [comment]
但是右键空白位置有个选项叫“展开目录树至当前位置”，你可以使用这个按钮，自动展开处于性能考虑不予支持
