### ISSUE TITLE
输入文件夹首字母选中相应文件夹，打开出错

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#33]
version：5.3.6
在 D 盘中存在 A 和 B 两个文件夹，先左键选中 A 文件夹，此时键盘按下 B 键，B 文件夹出现选中状态背景，此时按下回车，打开的却是 A 文件夹
![123](https://user-images.githubusercontent.com/26058690/93477445-982aae80-f92d-11ea-95a1-8b85c7a7d024.gif)

**Comment by zhuxb711** [comment]
该问题是由于焦点所在项与选中项不一致而导致。

RX内部使用选中项来进行操作，但是焦点更优先于选中项，因此键盘操作的一瞬间，选中项将会位移至焦点所在位置，因此发生了键盘Enter键进入的文件夹与实际所选的文件夹不一致的问题。

现在通过将焦点项与选中项保持一致的方式解决该问题

**Comment by zhuxb711** [comment]
该问题已于5.4.0版本中修复，请确认
