### ISSUE TITLE
地址栏能否加个环境变量自动补全

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#330]
![image](https://user-images.githubusercontent.com/45326534/132264018-9d4e1b48-72b3-4d82-b5c2-c1a338f95644.png)
类似如此，同时自动展开环境变量

（我有点找不到这块的逻辑，告诉下位置我来实现也可以🤣

**Comment by zhuxb711** [comment]
RX对于地址栏中键入的环境变量的解析依赖于辅助进程。

函数在这里：
https://github.com/zhuxb711/RX-Explorer/blob/6c863c1d7ac5418149abf47b3f562317cca9b878/RX_Explorer/View/FileControl.xaml.cs#L1438
定义在这里：
https://github.com/zhuxb711/RX-Explorer/blob/6c863c1d7ac5418149abf47b3f562317cca9b878/RX_Explorer/Class/CommonEnvironmentVariables.cs#L29
现在地址栏的使用的是单一模板，如果你想像截图里面那样显示两行的话，可能需要使用多模板选择器来根据不同情况选择不同模板，对应可能还需要更改地址栏提示背后的数据模板(如果有需要)

多模板选择器参考XAML：
https://github.com/zhuxb711/RX-Explorer/blob/6c863c1d7ac5418149abf47b3f562317cca9b878/RX_Explorer/View/FileControl.xaml#L17
https://github.com/zhuxb711/RX-Explorer/blob/6c863c1d7ac5418149abf47b3f562317cca9b878/RX_Explorer/View/FileControl.xaml#L139

对应的类：
https://github.com/zhuxb711/RX-Explorer/blob/da382756ef8c705202d4cc3ecde6ae6bd8340208/RX_Explorer/Class/CustomDataTemplateSelector.cs#L8

你可以提交PR，搞不定的我来办就是

**Comment by taooceros** [comment]
谢了，我研究研究

**Comment by zhuxb711** [comment]
搞得咋样啦，有没有啥问题？

**Comment by taooceros** [comment]
今天有点事，还没开始hhh🤣

**Comment by taooceros** [comment]
不得不说……uwp这个fulltrustprocess是真的有点麻烦……😅

**Comment by zhuxb711** [comment]
权限卡得死，只能这样变相越狱。搭建管理FullTrustProcess的工具才是最麻烦的，毕竟是跨进程通信，要有多个FullTrustProcess的任务调度，通信管理，FullTrustProcess挂掉后的退出机制，麻烦的YP

**Comment by taooceros** [comment]
听起来真是太难顶了😂

**Comment by zhuxb711** [comment]
想要多个标签页同时进行操作，必须实现多辅助进程的控制，确保每个标签页直接不会因为并发任务而导致相互阻碍。隔壁Files是单辅助进程的会有这个问题。表面多标签，实际单任务不能并发

**Comment by taooceros** [comment]
为什么要多辅助进程啊，用线程（池）无法做到嘛？

顺便问下，fulltrustProcess传一组数据是用json嘛？

**Comment by zhuxb711** [comment]
线程属于进程，你告诉我我在UWP里创建线程还能逃脱当前进程的管辖？你的意思是new Thread这个线程就不受UWP安全模型的管辖了咯

**Comment by taooceros** [comment]
> 线程属于进程，你告诉我我在UWP里创建线程还能逃脱当前进程的管辖？你的意new Thread这个线程就不受UWP安全模型的管辖了咯

你是指UI方面嘛？windows的进程不是可以允许并发的吗，那就算不脱离当前进程的管辖应该也是可以并发吧🤔
它的安全模型总不能不让你多线程吧，那并发任务就不应该会互相影响吧？

**Comment by zhuxb711** [comment]
与辅助进程建立连接的技术AppService每次仅允许一个连接，在当前请求返回之前第二条请求发不出去。所以单进程同一时间仅能处理一条请求，多请求会卡住，所以才需要多进程。当然现在的管道通信可以单进程多连接了，但是只能够在Win10 2004版本以上才能够建立管道通信，RX最低目标1903，所以必须多进程。况且管道通信不一定能够连接上

**Comment by taooceros** [comment]
学习了，那真是太不容易了😂

**Comment by zhuxb711** [comment]
所以很多情况下只能妥协用复杂的方法，总不能搞两套调度机制吧，那更复杂了。现在RX是管道通信能用的话优先选择管道通信，如果不能用，回退到AppService的机制。多进程的好处就是一个进程万一有严重错误只会炸一个进程，其他进程不受影响（跟WinAPI和Com交互或者读取某些写的垃圾的菜单项的时候抛出异常是很常见的，菜单项甚至可以抛出内存访问冲突直接卡擦了进程）。如果你单进程处理，一个任务炸了其他任务都得完蛋。背后通信用的是Json来交换信息的

**Comment by taooceros** [comment]
我快弄好了，不过还有一点收尾。最近开学了稍微忙了点hhh

**Comment by zhuxb711** [comment]
> 我快弄好了，不过还有一点收尾。最近开学了稍微忙了点hhh

Good，感谢提交PR

**Comment by taooceros** [comment]
不得不说，uwp这调试编译也太慢了……是我电脑的问题嘛，每次想要调试一下都要编译半分钟一分钟然后打开再花半分钟

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/133019973-c823d4ed-72e8-4932-8208-6572e875bc4f.png)
这块有点问题……uwp权限卡的过于死了……不知道怎么判断文件夹是否存在
之前你用的`Path.GetPathRoot`会直接返回一个`C:`，也不太行

**Comment by zhuxb711** [comment]
> 不得不说，uwp这调试编译也太慢了……是我电脑的问题嘛，每次想要调试一下都要编译半分钟一分钟然后打开再花半分钟

正常，UWP debug编译也很慢

**Comment by zhuxb711** [comment]
使用FileSystemStorageItem.CheckExists()检查是否存在
