### ISSUE TITLE
There's no way of viewing the size of multiple selected folders

### ISSUE THREAD

**Issue by bzzrak** [zhuxb711/RX-Explorer#332]

**Comment by zhuxb711** [comment]
Same behavior as system explorer

**Comment by bzzrak** [comment]
With stock explorer I can select multiple folders and open properties to see the size. On RX there's no properties option at all, which would be fine if there were another way of seeing the size.

**Comment by zhuxb711** [comment]
Oh, Property window is not support multiple selection for the time being. Maybe this feature will be added later.

And feel free to create a PR if you are willing to help develop RX-Explorer. Thanks.

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/147032024-a1a7db0d-719e-4ec8-85bf-1873ebed375f.png)
This will be added in the next release
