### ISSUE TITLE
地址栏两层目录以上错误目录会导致rx卡住一段时间

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#335]
似乎只有第一次试验会出现，关闭之后再打开似乎可以复现

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/133332822-f86cf418-c9e0-4474-9d4b-e29541eeafe6.png)

**Comment by zhuxb711** [comment]
什么叫两层以上的错误目录

**Comment by taooceros** [comment]
就是类似`C:\awefaewfa\awefawefawef`这种，`C:\adsdofjawejf`这种就不会

**Comment by zhuxb711** [comment]
确认此处是存在性能问题，原因是OpenAsync函数和Native Win32 API中的设计存在问题。
此问题导致OpenAsync()将不存在的路径识别为Win32 API不可达，进而回退到UWP API尝试获取，实际上UWP API会进一步抛出FileNotFoundException，由于错误的捕获异常，UWP API抛出异常后还会进一步回退至尝试从辅助进程中获取文件句柄(尽可能获取文件句柄来保持对文件的最大访问性)。

C#中处理异常的代价较大，与辅助进程通信存在延迟，这两个方面的因素加起来，在频繁变动的地址栏中较为明显，形成卡顿。

我已修正此处的行为，确保Win32 API正确区分路径不可达和路径不存在两种情况，还修正了回退至辅助进程获取句柄的逻辑，确保仅在非FileNotFoundException或DirectoryNotFoundException情况下才会回退
