### ISSUE TITLE
关于右键新建选择的疑问

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#336]
请问右键新建只能有以下几个新建选项吗?
![image](https://user-images.githubusercontent.com/62456287/134761287-d5bdd326-f3d8-4c24-86fe-b9a6ffb80a10.png)
系统的右键新建选择比RX文件管理器的要多:
![image](https://user-images.githubusercontent.com/62456287/134761374-f2f7f333-fbbb-47b1-8735-6adae8643a9c.png)
类似于Wolfram Notebook(Mathematica笔记本文件)的富文本文件不能通过新建.txt更改后缀名获得
希望可以增强?这个功能

可能可供的参考:
![image](https://user-images.githubusercontent.com/62456287/134761557-306dc3c1-1c49-41bc-882b-b5a27ccd3c2a.png)
[OneCommander](https://onecommander.com/)的新建也没法获取完整,但是可以在选中文件时将其作为模板
![image](https://user-images.githubusercontent.com/62456287/134761673-bf5d3ff2-0dde-4aef-8de5-7625c438ccd5.png)
![image](https://user-images.githubusercontent.com/62456287/134761721-4f9cac50-2605-4887-ae3a-1bddc794683a.png)
然后在新建时调用:
![QQ录屏20210925144944 00_00_00-00_00_30](https://user-images.githubusercontent.com/62456287/134761953-74f84229-32b3-4428-abf7-8f6079251c34.gif)

**Comment by zhuxb711** [comment]
此功能将不会支持，RX可以获取系统的新建按钮内的内容，但是无法正确激活这些菜单项，故不予显示
