### ISSUE TITLE
点击快捷库按enter会创建一个新的tab

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#338]
![image](https://user-images.githubusercontent.com/45326534/135385349-2bc29898-f814-4f23-8e7b-321555c99c52.png)
第一次点击之后按enter有机率会创建一个新的tab（当前tab仍然会进入指定目录）多次选择后再enter就不会

**Comment by zhuxb711** [comment]
可能是因为新建Tab的按钮在你选中库文件夹的时候仍然具有焦点？

**Comment by taooceros** [comment]
有可能
