### ISSUE TITLE
关于更新极其频繁还一堆提示这事

### ISSUE THREAD

**Issue by cyrxdzj** [zhuxb711/RX-Explorer#339]
RX文件管理器的更新极其频繁，这本是一件好事。

但是，每次更新都会弹出一条提醒，还会在应用程序显要位置显示，这就有点太烦了。

建议只有当有重要更新时，才会提醒。其他更新，仅在设置页面的“版本”中显示。

**Comment by zhuxb711** [comment]
微软商店的更新没有重要性分级，而RX非紧急Bug不会发布强制更新，而强制更新一旦发布RX会进一步弹出全屏框来提示更新，因此顶部的更新提示横幅目前用于提示一般更新

建议更新任何RX发布的更新以修正各种问题，是否更改此行为有待商榷

**Comment by cyrxdzj** [comment]
![image](https://user-images.githubusercontent.com/63708985/135560290-b23a25f3-093a-4066-9771-59f6b3cf9612.png)
每次启动电脑都会有这条提示，真的好烦。

这条提示是谁发出的？Microsoft Store还是RX文件管理器？

**Comment by zhuxb711** [comment]
不想见到这个提示自己不会屏蔽它？就是设置一下Windows通知的事情，你要是句句带着"真的好烦"这样的情绪来的我现场就关闭这Issue，这本来就属于可改可不改的内容，严格意义上甚至连BUG都不算，不是说一个Issue就可以变成私人定制的软件，根据个人喜好来进行更改。改了算是采纳，没改是本分。
