### ISSUE TITLE
自定义的默认终端应用程序无法调用

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#34]
version：5.3.6
安装第三方终端应用，如 windows terminal（[https://github.com/microsoft/terminal]）
在软件中设置为默认终端应用程序，按快捷键 shift + T 或者右键空白处菜单“在终端处打开”均无法调用，上一个版本 5.3.3 是可以调用的

**Comment by zhuxb711** [comment]
Hi，经过调查，是由于5.3.6版本增加了执行exe权限的检查，但是由于Windows Terminal的执行方式是 “wt.exe” ，它是一个相对路径，因此在权限检查时失败（执行时由系统自动寻找它在环境变量中的绝对路径），进而导致无法启动Windows Terminal。该问题已于最新的提交 [Here](https://github.com/zhuxb711/RX-Explorer/commit/8a44e7791cff2b72d9847e99dfee0fc8d46568a9)  中修复，并将随下一个版本修复。

您可以在设置中编辑Windows Terminal的配置文件，将相对路径更改为绝对路径，即可正常使用。

**Comment by zhuxb711** [comment]
版本5.4.0已解决该问题，请确认
