### ISSUE TITLE
退出菜单时菜单圆角变方角

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#340]
![29](https://user-images.githubusercontent.com/64201424/135951899-19db62a9-2412-4582-934b-98bc52cbac4c.png)
![32](https://user-images.githubusercontent.com/64201424/135951921-fe2dd16e-579b-419d-8216-334271735c37.png)

**Comment by zhuxb711** [comment]
微软的BUG，已向控件库提交Issue，不属于RX可以修复的范畴，后续进展请跟踪 [Microsoft.UI.Xaml #6034](https://github.com/microsoft/microsoft-ui-xaml/issues/6034)
