### ISSUE TITLE
建议：增加“字体样式”选项

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#342]
我想自定义RX文件管理器的显示字体，希望可以有这个选项

**Comment by XSH-Hero** [comment]
但我见过可以更换全局字体的uwp应用

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/136664896-94a90fcf-0d4d-400c-be8a-b96375f4adaf.png)
![image](https://user-images.githubusercontent.com/69738882/136664910-660db091-63f4-437c-81f6-8f4a33fa9bc0.png)
![image](https://user-images.githubusercontent.com/69738882/136664918-d7d94d54-01e0-47f2-a2d6-a58f38cbb171.png)

**Comment by zhuxb711** [comment]
不要被表象蒙蔽了，简单应用可以对每一处字体应用单独的控制，对于RX这种复杂的应用成为几乎不可能的任务。我说的是UWP平台并没有全局统一的控制字体的设置可以用，如果非要强上的话没什么做不了的，就是几百上千个控件都要手动设置字体就是了

**Comment by zhuxb711** [comment]
当然你要是有高效的方法也可以提出来

**Comment by zhuxb711** [comment]
这个事情有转机，和其他UWP大佬以及MVP进行了交流，正在进一步研究
