### ISSUE TITLE
UI建议

### ISSUE THREAD

**Issue by MYXXTS** [zhuxb711/RX-Explorer#343]
请问一下软件内的部分圆角可以取消掉或者是给一个可选项吗？使用win10系统外框是直角，内部有圆角不统一很难受
其次就是希望可以增加较多的可自定义的选项

**Comment by zhuxb711** [comment]
圆角升级并非无痛升级，目前RX已全面更换圆角风格，建议使用Win11系统以搭配外框圆角，外框圆角于Win11开始支持，Win10不支持外框圆角
