### ISSUE TITLE
Everything 内置搜索 效率很低 

### ISSUE THREAD

**Issue by LittleBlacklb** [zhuxb711/RX-Explorer#345]
并且 每次CPU占用率100%
然而用everything.exe就很快
不知道是不是问题只针对于我个人
![Screenshot 2021-10-31 192105](https://user-images.githubusercontent.com/49110208/139580510-467ff88f-b673-4c51-9cbe-441a2c66c091.png)

**Comment by lethe47** [comment]
上传一下日志文件给开发者看看？我的电脑上并没有出现这样的问题。内置的everything一样搜索很快

**Comment by zhuxb711** [comment]
内置搜索引擎采取传统遍历的方式搜索文件，因此磁盘占用率高。如果您通过Everything搜索引擎搜索，则全部工作由Everything完成，然后由RX进行统一显示。
