### ISSUE TITLE
【未知问题】使用SD卡时，文件的显示属性预览产生问题。

### ISSUE THREAD

**Issue by soloopooo** [zhuxb711/RX-Explorer#347]
电脑运行最新版本，
在使用 SDHC 存储卡时，
![image](https://user-images.githubusercontent.com/36123081/140637451-0c071630-d149-4ba8-b985-943f1b04dd55.png)
鼠标 hover 所显示的文件大小与实际文件大小不一致，所有文件均为 0 字节。
USB设备暂时没有测试。

**Comment by zhuxb711** [comment]
不清楚具体原因，但是这个描述内容是让Windows自己生成的，因此并不是RX自己搞错数据了啥的，RX只是一个搬运工。另外这个浮出控件在现在的7.1.9中存在一些问题，可能不会在每一个文件中都能成功打开
