### ISSUE TITLE
【功能优化建议】Quicklook相关优化建议。

### ISSUE THREAD

**Issue by soloopooo** [zhuxb711/RX-Explorer#348]
与Quicklook调用时，当Quicklook窗口已经打开的时候，可以像explorer那样选中即预览，而不用选中后再按下空格再更新预览。
对比：
windows自带资源管理器：

https://user-images.githubusercontent.com/36123081/140637639-e28b4a82-e664-4127-9bf4-c53ef6b0d2cc.mp4

RX：

https://user-images.githubusercontent.com/36123081/140637680-8a47f576-a10c-4071-ae36-59c00c4ab896.mp4

**Comment by soloopooo** [comment]
为什么浏览器内部播放不了（
烦请下载下来查看，谢谢

**Comment by zhuxb711** [comment]
之所以不支持该功能是因为RX不知道你什么时候想继续用Quicklook什么时候不想继续使用Quicklook，因此每当你想要用Quicklook的时候按下空格来提示RX使用Quicklook预览。如果你说想一次空格激活Quicklook预览，那RX怎么知道你不想继续用Quicklook呢？没有任何额外操作的情况下，RX没有办法知道你是不是还想继续用Quicklook，那RX只会继续保持Quicklook预览，你关也关不掉。

**Comment by soloopooo** [comment]
> 之所以不支持该功能是因为RX不知道你什么时候想继续用Quicklook什么时候不想继续使用Quicklook，因此每当你想要用Quicklook的时候按下空格来提示RX使用Quicklook预览。如果你说想一次空格激活Quicklook预览，那RX怎么知道你不想继续用Quicklook呢？没有任何额外操作的情况下，RX没有办法知道你是不是还想继续用Quicklook，那RX只会继续保持Quicklook预览，你关也关不掉。

谢谢解答。然而同样是第三方文件管理器的Files却可以完美支持选中即预览，也没有关闭Quicklook窗口后的问题，所以我想Quicklook应该有更好的调用方法。
如下：

https://user-images.githubusercontent.com/36123081/140640139-7e982bad-d557-40e3-8a27-a14158f2cac0.mp4

**Comment by zhuxb711** [comment]
你没有明白我在说什么，别急着先用Files举例。

你说，我一打开Quicklook开关，那所有我点到的文件都用Quicklook，很容易做的到。

那现在是这样，你想我一按空格，所有我按空格后再点到的文件都用Quicklook，也很容易做的到。

你再想，如果你想 我随时想按空格后就用Quicklook预览，但没有关闭的Quicklook预览的逻辑。那这个功能意味着只有开启的逻辑没有关闭的逻辑。现在的方式是按一次空格，激活一次，开关此功能的逻辑都具备，你切换到其他你不想用Quicklook的文件夹时不会激活Quicklook。

最后，你拿Files那个功能差RX一大截的玩意来比？不是做不了，而是我一直没有想好这里的逻辑，所以就一直保持下来了啰

**Comment by soloopooo** [comment]
不是这个意思啊。。。

我装了Quicklook就是为了随时按下空格预览，预览时即点即预览，这是正常功能吧；

如果我不想让RX用quicklook直接开关一关函数返回值一掐不就完事了吗，

我实在想不明白这两个功能有什么冲突。。

**Comment by zhuxb711** [comment]
我关注的点在于这个功能目前是可以保证随时用随时停，不按空格就不会激活。如果改了，那就是用起来就不能停，按到哪都弹Quicklook。

那为了阻止这种情况发生，必须有一个合理的自动退出Quicklook的逻辑，现在缺少这样的逻辑，我是这个意思

**Comment by soloopooo** [comment]
明白了，谢谢解答。

等我拜读一下源代码后再来尝试提供一下解决思路吧。

**Comment by zhuxb711** [comment]
我能想到的是如果用户切换了文件夹，那Quicklook预览自动终止，除非再次按下空格键。

也就是在文件夹按下空格键到切换文件夹之前，持续保持Quicklook激活。不知道这样是否合理。你觉得呢？

**Comment by soloopooo** [comment]
> 我能想到的是如果用户切换了文件夹，那 Quicklook 预览自动终止，除非再次按下空格键。
> 
> 也就是在文件夹按下空格键到切换文件夹之前，持续保持 Quicklook 激活。不知道这样是否合理。你觉得呢？

那恐怕不太对的。
Quicklook是支持预览文件夹的，
在原始文件管理器里的逻辑是：
比如我在 E:\ 下预览了 E:\1.txt，它会先预览1.txt;
然后我在地址栏切换到E:\path\ ，这里有两种情况：
1. 在地址栏输入地址，不双击文件夹进入：此时Quicklook预览1.txt不会停止，直到选中E:\path\中的某个文件（夹）;
2. 双击文件夹进入，此时Quicklook会预览文件夹后保持不动，直到选中E:\path\中的某个文件（夹）;

**Comment by soloopooo** [comment]
找到一个可能的方法：检测Quicklook的窗口是否存在。
https://github.com/QL-Win/QuickLook/issues/557#issuecomment-540944156

**Comment by zhuxb711** [comment]
那什么时候会停止预览并需要再次使用空格激活Quicklook呢？

**Comment by zhuxb711** [comment]
如果有可能，建议您提交一个PR来共同改进关于Quicklook方面的功能，感谢

**Comment by soloopooo** [comment]
> 那什么时候会停止预览并需要再次使用空格激活 Quicklook 呢？

在用户第二次按下空格键时或者文件管理器窗口被关闭。这就是原始文件管理器与Quicklook的交互逻辑。

**Comment by soloopooo** [comment]
> 如果有可能，建议您提交一个 PR 来共同改进关于 Quicklook 方面的功能，感谢

我不太会CSharp，所以恕我心有余而力不足，谢谢您创作出这么优秀的第三方文件管理器。

**Comment by zhuxb711** [comment]
Ok那我来处理，你发的Quicklook的链接里我不是很清楚Toggle和Switch命令的区别，RX现在使用Toggle命令来确定Quicklook是否正在运行，使用Switch命令+Path来调用Quicklook预览某个文件。不知道是否有其他用法。

**Comment by soloopooo** [comment]
好的，另外对于您的之前的思路我有个建议：

做文件管理器的不需要考虑什么时候关闭Quicklook。这是用户自己的事情，用户如果不需要预览的话，自己会去选择关闭它的，不要考虑什么时候去关闭Quicklook的预览，而要考虑什么时候去调用并且更新这个预览。

**Comment by zhuxb711** [comment]
> 好的，另外对于您的之前的思路我有个建议：
> 
> 
> 
> 做文件管理器的不需要考虑什么时候关闭Quicklook。这是用户自己的事情，用户如果不需要预览的话，自己会去选择关闭它的，不要考虑什么时候去关闭Quicklook的预览，而要考虑什么时候去调用并且更新这个预览。

实际上如果你调用Switch + Path这样的话，就算用户没有已经存在的Quicklook窗口的话，也会立刻弹出一个Quicklook窗口出来，这就是为啥我要关心它什么时候关闭Quicklook

**Comment by soloopooo** [comment]
> Ok 那我来处理，你发的 Quicklook 的链接里我不是很清楚 Toggle 和 Switch 命令的区别，RX 现在使用 Toggle 命令来确定 Quicklook 是否正在运行，使用 Switch 命令 +Path 来调用 Quicklook 预览某个文件。不知道是否有其他用法。

可以参考这里 https://github.com/QL-Win/QuickLook/blob/master/QuickLook/PipeServerManager.cs

**Comment by zhuxb711** [comment]
抱歉，我上面的言论并不正确，经过检查代码后，我发现RX现在使用Switch检查Quicklook是否正在运行，使用Toggle激活Quicklook，因此会在Quicklook不存在时使其弹出

**Comment by soloopooo** [comment]
> 抱歉，我上面的言论并不正确，经过检查代码后，我发现 RX 现在使用 Switch 检查 Quicklook 是否正在运行，使用 Toggle 激活 Quicklook，因此会在 Quicklook 不存在时使其弹出

Toggle 意为开关吧。Switch是切换，所以应该是调用反了（
不知道换一下调用方式能不能达到曲线救国的目的（

**Comment by zhuxb711** [comment]
我大致理出来了是这么个逻辑：

前提：
1. Toggle将会在没有Quicklook窗口时显示Quicklook窗口，已经有Quicklook窗口时作用同Switch
2. Switch仅在存在Quicklook窗口时才会预览特定路径

那么：
1. 如果设置中已经启用了Quicklook，那么无论何时用户按下空格，则都会使得RX执行Toggle命令
2. 如果设置中已经启用了Quicklook，那么切换选中项时执行Switch命令 (Quicklook会检查是否有它的窗口在，如果有才会显示，否则忽略)
3. 如果设置中禁用Quicklook，那么不执行任何动作

**Comment by soloopooo** [comment]
好耶！有了逻辑就不愁实现了，期待您发布的新版本！

**Comment by zhuxb711** [comment]
如果上述逻辑梳理没有问题，那关于Quicklook的改进将会包含于下一个新版本中

**Comment by soloopooo** [comment]
@zhuxb711 不太对劲，Quicklook在第二次按下空格的时候是会关闭预览的，您这个逻辑有无法通过空格键关闭预览的漏洞在啊

在PipeServerManager.cs中有这样一段代码：
```c#
 case PipeMessages.Close:
                    Application.Current.Dispatcher.BeginInvoke(
                        new Action(() => ViewWindowManager.GetInstance().ClosePreview()),
                        DispatcherPriority.ApplicationIdle);
```
您可以考虑试试使用ClosePreview命令。

**Comment by zhuxb711** [comment]
执行Toggle命令时如果和上次输入的是同样的路径的话，将会导致Quicklook窗口关闭 [看这里](https://github.com/QL-Win/QuickLook/blob/e640a8b98a96a43742993d249cec6bf1c8f2864c/QuickLook/ViewWindowManager.cs#L81)

由于一切换选项必定导致Switch命令执行，用户不可能快于RX自己的反应，因此隐含了Toggle第二次时将会关闭的逻辑

**Comment by soloopooo** [comment]
原来如此！受教了。

那我就期待新版本了，谢谢您

**Comment by zhuxb711** [comment]
请注意，Toggle仅在第二次输入同样路径时才会关闭窗口，如果Toggle第二次是不同路径，则不会关闭窗口而是等同于执行Switch命令

**Comment by zhuxb711** [comment]
感谢，经过和您的讨论之后发现Quicklook的调用方式确有错误，且缺少与系统文件管理器一致的行为，此问题应当于不晚于下星期五之前提交的新版本中加以改进

**Comment by zhuxb711** [comment]
此改进已包含于最新的内测版本中

**Comment by zhuxb711** [comment]
7.2.3已发布
