### ISSUE TITLE
【交互逻辑建议】将悬浮窗向右或者向下移动若干单位。

### ISSUE THREAD

**Issue by soloopooo** [zhuxb711/RX-Explorer#349]
在对文件进行管理的时候，一旦将鼠标移动到某个文件而稍稍较长时间不移动鼠标的时候，悬浮窗的最左边框会恰好显示在鼠标的触控区域内导致点不到文件列表。这在实际操作中很令人恼火。
比如：
我刚把鼠标移动到某个文件想要双击点开的时候，这个悬浮框就蹦出来阻挡我点文件，非常影响体验。
而且它还会阻挡文件名显示框。

如图：（圆形鼠标的圆心相当于箭头型鼠标的头部）
![D03](https://user-images.githubusercontent.com/36123081/140646983-8e5cd563-089b-4116-9fd7-167176504f4c.gif)

对比系统文件资源管理器：（红圈为鼠标位置，悬浮窗显示在鼠标的右下部分且离圆心（鼠标箭头的头部）有较大距离）
![image](https://user-images.githubusercontent.com/36123081/140647284-719d9ff7-ec5f-4a0c-996a-34f728b61624.png)

**Comment by zhuxb711** [comment]
这个呢你没提我也已经改了，应该是之前更换上下文菜单时把它的弹出位置改成了TopAlignLeft，由于原本设计是在右下角的RightAlignTop有额外20px偏移，因此现在会遮挡指针

**Comment by soloopooo** [comment]
了解了。
