### ISSUE TITLE
双击文件夹无法打开

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#35]
version：5.3.6
左键双击文件夹名称的前两个字母范围、第一个汉字范围和名称与文件夹图标之间的地方，均无法正常打开文件夹，windows 自带资源管理器是可以的
![123](https://user-images.githubusercontent.com/26058690/93481128-ce1d6200-f930-11ea-9b35-7d1d0822de8c.gif)

**Comment by XSH-Hero** [comment]
好像只有列表和详细信息模式有这个问题，平铺就没事

**Comment by zhuxb711** [comment]
该问题具体原因尚不明确，在点击某些位置的时候，该UI控件所对应的双击事件并不会按预期的那样发生，因此RX无法作出任何回应(相当于用户啥都没操作)，故无法修复。

**Comment by all-aroundbadass** [comment]
你现在的实现思路是什么，是判断双击的坐标是否在选中的一行范围内吗?

**Comment by zhuxb711** [comment]
订阅控件的双击事件来检测 @all-aroundbadass

**Comment by all-aroundbadass** [comment]
那在点击我提到的那些区域没有触发此控件的双击事件?

**Comment by zhuxb711** [comment]
暂时还没有测试过，您能否帮助提交一个PR来调查此问题呢？不胜感激....

**Comment by justiony** [comment]
hi @all-aroundbadass  您这个问题再5.4.2.0的版本已经解决了,可以更新试下, 相关信息我无法上传视频
@zhuxb711 信息的截图我邮件给你,

**Comment by justiony** [comment]
![hrfkm-988aa](https://user-images.githubusercontent.com/38231754/94632055-30e10700-02fc-11eb-8dc2-a3d2e751c954.gif)

**Comment by zhuxb711** [comment]
@justiony 不这个问题并没有解决，您可以双击文件名称最前面的那个字母，或者是更加前一点点的地方，就可以发现双击是无效的。我多次尝试找出问题所在，但很遗憾未能确定该问题的根源

**Comment by sirlis** [comment]
2020.11.26 问题依然存在，双击文件或文件夹图标和名称中间的空白部分，无法触发双击打开或进入操作。

**Comment by FlyingDragon0420** [comment]
V 5.8.6问题依然存在
列表模式  点击图标和名称中间的空白区域，无法打开文件夹或文件

**Comment by zhuxb711** [comment]
这似乎是微软ListView控件的BUG，修不了
