### ISSUE TITLE
【Quicklook相关优化】细小的区别，但是体验差别巨大。

### ISSUE THREAD

**Issue by soloopooo** [zhuxb711/RX-Explorer#351]
上一个issue虽然已经在最新版本解决，但是还有一个问题我之前没有注意到，就是在**不小心**取消选中之后，Quicklook的预览问题。

下方为系统文件管理器和Rx的对比

https://user-images.githubusercontent.com/36123081/142092194-53aef555-4910-4e5a-937a-c0c61d7b23bf.mp4

**Comment by zhuxb711** [comment]
现在设计是如果你不选择任何文件夹或文件，就显示父文件夹的详情

**Comment by soloopooo** [comment]
是不是加个设置选项会好一些

**Comment by zhuxb711** [comment]
干脆改成没选中就不动作洛

**Comment by soloopooo** [comment]
反正系统文件管理器的逻辑是没选中就保持原来的预览，不动作。看作者怎么想的了
