### ISSUE TITLE
Default file explorer setting not working properly

### ISSUE THREAD

**Issue by tangrichard** [zhuxb711/RX-Explorer#353]
After reverting back to the default explorer, programs like Steam are still using RX explorer to open folders.

**Comment by zhuxb711** [comment]
So System Explorer works well but Steam still use RX-Explorer?

**Comment by tangrichard** [comment]
Yes

**Comment by zhuxb711** [comment]
[Restore_Folder.txt](https://github.com/zhuxb711/RX-Explorer/files/7603753/Restore_Folder.txt)

Please rename this file from .txt to .reg and double click it to restore. Sorry for inconvenience, that would be fixed in the next version

**Comment by zhuxb711** [comment]
Version 7.2.9 released
