### ISSUE TITLE
不知道为什么 总是启动时要卡几秒钟

### ISSUE THREAD

**Issue by hastonewy** [zhuxb711/RX-Explorer#354]
只显示几两三个盘符和图标过几秒钟才加载完
我的系统WIN11 安装有raidrive正在连接远程SSH SFTP 还运行着WSL2的ubuntu 20.04

**Comment by hastonewy** [comment]
启动另一个进程也要经历这一个过程
希望能有个缓存机制 或者先按之前的状态启动再更新

**Comment by DesFo** [comment]
遇到了同样的问题

**Comment by zhuxb711** [comment]
7.2.9版本开始已经采用慢速磁盘加载超过2000ms时自动排到最后，优先加载其他驱动器的形式来避免卡住所有驱动器，因此在部分电脑上可能不会一下子完全显示，慢速驱动器将在所有其他驱动器加载完成后陆续完成加载

**Comment by soloopooo** [comment]
似乎与#341是相同的问题

**Comment by rom1c77** [comment]
没明白加载机制是什么。 每次win+e启动的时候，都会去加载磁盘， 要么就RX关闭的时候就只是界面关闭，不要关闭后台进程。 
这样就不会每次打开加载磁盘。

**Comment by rom1c77** [comment]
> 7.2.9版本开始已经采用慢速磁盘加载超过2000ms时自动排到最后，优先加载其他驱动器的形式来避免卡住所有驱动器，因此在部分电脑上可能不会一下子完全显示，慢速驱动器将在所有其他驱动器加载完成后陆续完成加载

**Comment by rom1c77** [comment]
> 7.2.9版本开始已经采用慢速磁盘加载超过2000ms时自动排到最后，优先加载其他驱动器的形式来避免卡住所有驱动器，因此在部分电脑上可能不会一下子完全显示，慢速驱动器将在所有其他驱动器加载完成后陆续完成加载

@zhuxb711  能不空间换时间，内存现在不值钱。 就算用户关闭了RX也只是前台界面上的关闭，后台进程不关闭可以吗？
目前的问题是，每次WIN+E打开RX都会加载硬盘，就很奇怪。

**Comment by zhuxb711** [comment]
> > 7.2.9版本开始已经采用慢速磁盘加载超过2000ms时自动排到最后，优先加载其他驱动器的形式来避免卡住所有驱动器，因此在部分电脑上可能不会一下子完全显示，慢速驱动器将在所有其他驱动器加载完成后陆续完成加载
> 
> 
> 
> @zhuxb711  能不空间换时间，内存现在不值钱。 就算用户关闭了RX也只是前台界面上的关闭，后台进程不关闭可以吗？
> 
> 目前的问题是，每次WIN+E打开RX都会加载硬盘，就很奇怪。

UWP平台不支持后台常驻

**Comment by oxygen-dioxide** [comment]
> > > 7.2.9版本开始已经采用慢速磁盘加载超过2000ms时自动排到最后，优先加载其他驱动器的形式来避免卡住所有驱动器，因此在部分电脑上可能不会一下子完全显示，慢速驱动器将在所有其他驱动器加载完成后陆续完成加载
> > 
> > 
> > @zhuxb711  能不空间换时间，内存现在不值钱。 就算用户关闭了RX也只是前台界面上的关闭，后台进程不关闭可以吗？
> > 目前的问题是，每次WIN+E打开RX都会加载硬盘，就很奇怪。
> 
> UWP平台不支持后台常驻

https://docs.microsoft.com/zh-cn/windows/uwp/launch-resume/run-in-the-background-indefinetly
