### ISSUE TITLE
[Feature Request] Add Git context menu to RMB && Move "More" pop-up context menu one slot down

### ISSUE THREAD

**Issue by yhyu13** [zhuxb711/RX-Explorer#355]
![QDk06H6VPj](https://user-images.githubusercontent.com/19365678/144360102-281ee07f-8e68-4bfd-98a4-3c4665c2cafb.png)

![bzECadJptm](https://user-images.githubusercontent.com/19365678/144360333-7bb2afd5-8c3f-47a2-aad0-9f74b0fccda1.png)

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/144583313-8a16fde3-c838-4ef0-a2b8-0c9a76973f74.png)
向上抬起一个我没猜错的话应该是辣鸡微软的BUG
