### ISSUE TITLE
Library feature

### ISSUE THREAD

**Issue by 2487163254** [zhuxb711/RX-Explorer#356]
The library function of Windows is very useful, and I use it all the time.Could you add this function

**Comment by 2487163254** [comment]
I mean custom libraries which you can all self folder

**Comment by 2487163254** [comment]
I mean custom libraries which you can add self folder

**Comment by zhuxb711** [comment]
Just simply right click the empty area of "Library" and you can add your folders to it

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/145335867-a277266f-1937-40b5-a77b-baaaa2f35d35.png)

**Comment by 2487163254** [comment]
sorry, I didnt say it clearly. 
I mean **the Library feature in Windows** , it contains folders in different paths
![image](https://user-images.githubusercontent.com/71128095/145347304-6a6d4d85-02ef-4f37-ae2b-d446468ad647.png)

If I add a Library it tolds me select folder instead
![image](https://user-images.githubusercontent.com/71128095/145347464-48c9c993-8cb7-4407-8feb-83cb7d5c0cd4.png)

**Comment by zhuxb711** [comment]
Unfortunately, this warning is not from RX-Explorer but from Windows. As UWP application, we could not control the "FolderPicker" which provided by Microsoft. So I'm afraid that it might not be able to support this feature
