### ISSUE TITLE
[Bug]无法使用“汉仪文黑-85W”字体作为界面显示字体

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#357]
![image](https://user-images.githubusercontent.com/69738882/145705850-b15b439a-55d3-484d-8cfe-5a045ea8f8e3.png)
如图所示，选择了该字体并重启软件后，仍显示为原来的字体，并未改变

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/145706174-7ebc8863-6fe0-4cca-90f9-665b66c96678.png)
但其他软件（同为uwp）是可以使用该字体的，说明字体应该没有问题

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/145790782-134dc0a9-d2f6-4d55-bc5a-2c51fddd23ab.png)
我这里是可以切换的，说明没有Bug (暴论...)

**Comment by zhuxb711** [comment]
该问题是否已经解决？

**Comment by XSH-Hero** [comment]
emmm在我提交问题后更新的版本时问题修复了，字体可以正常使用，但后续的更新又不能使用了。。。。。

**Comment by zhuxb711** [comment]
发个字体文件上来我测试一下？

**Comment by XSH-Hero** [comment]
[zh-cn.zip](https://github.com/zhuxb711/RX-Explorer/files/7847740/zh-cn.zip)

**Comment by XSH-Hero** [comment]
文件发了

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/149085957-c3422a6f-410e-4a3f-b907-5e17610b929b.png)
该问题的原因是字体FontFamilyName与DisplayName不同，RX使用DisplayName来选取字体文件，在某些情况下并不一定与FontFamilyName相同，因此该字体呈现无效状态。

此问题将于下一个版本中修复

**Comment by zhuxb711** [comment]
汉仪文黑 的 DisplayName: HYWenHei ，而FontFamilyName: HYWenHei-85W
