### ISSUE TITLE
没找到可以把字体换成黑色的设置

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#358]
![image](https://user-images.githubusercontent.com/62456287/146547179-f5ba51f4-7e37-41ba-a20a-87a9afabd54d.png)
![image](https://user-images.githubusercontent.com/62456287/146547420-728e25be-d7c0-4a64-8dd9-4a4ffd630f6e.png)
这根本看不到字啊,之前的版本都可以自动调整字体颜色的

**Comment by zhuxb711** [comment]
![111](https://user-images.githubusercontent.com/42038175/146559069-7a5ee7bd-6096-4473-84bb-d43982a5caaa.png)

这几个明显的大字，给你方法调整了
