### ISSUE TITLE
双击文件或文件夹名称无法进行修改名称操作

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#36]
version：5.3.6
在双击文件夹名称时，偶尔能进行文件名修改，大部分情况都无法触发
![123](https://user-images.githubusercontent.com/26058690/93482529-62d48f80-f932-11ea-9390-b26db9e865ec.gif)

**Comment by zhuxb711** [comment]
现在RX默认是间隔1200ms-2000ms之间点击才能够触发该功能，下一版本将放松限制到800-3000ms内点击触发

**Comment by zhuxb711** [comment]
版本5.4.0版本已发布，但最终定下来的间隔时间为：双击间隔1000ms-3000ms内即可正常触发
