### ISSUE TITLE
[功能请求]能否通过先压缩再加密的方式使安全域支持文件夹

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#360]
现有的安全域只能放单一文件,要放文件夹只能自己先压缩再导入到安全域,这太麻烦了

**Comment by zhuxb711** [comment]
实际上是可以的，但是没做，而且不知道怎么与普通压缩文件区分开

**Comment by a15355447898a** [comment]
请问有考虑过使用[openzfs](https://github.com/openzfs/zfs)的通明压缩+加密来完成这个功能吗?

**Comment by zhuxb711** [comment]
很高兴宣布这个功能将于8.0.0中发布
