### ISSUE TITLE
[功能请求]希望可以加强校验和计算功能

### ISSUE THREAD

**Issue by ktns01** [zhuxb711/RX-Explorer#362]
RX-Explorer有校验和计算功能，但它只能计算校验和，无法比较校验和。
希望可以加强校验和计算功能，使其像OpenHashTab一样可以进行校验和的计算，并自动与剪贴板中的校验和进行比较。
说起OpenHashTab，这个工具与RX-Explorer存在兼容性问题，在RX-Explorer中右键运行会卡死。不过另一款软件Files也有这种问题。

**Comment by zhuxb711** [comment]
感觉加上比较功能每个哈希值的框下面都要多额外一个框框，整体UI很不协调

**Comment by zhuxb711** [comment]
![GIF 2022-1-26 9-23-04](https://user-images.githubusercontent.com/42038175/151087406-7337d872-e4fb-4608-9975-eb7ec11caae9.gif)

**Comment by zhuxb711** [comment]
此功能将于7.4.5中上线
