### ISSUE TITLE
[Bug]不兼容NanaZip

### ISSUE THREAD

**Issue by ktns01** [zhuxb711/RX-Explorer#363]
右键菜单选项中的Nanazip选项无法使用。
<img width="261" alt="屏幕截图 2022-01-20 220434" src="https://user-images.githubusercontent.com/93424632/150353693-1e9043d5-8f8f-496a-b911-6fc9f0c57713.png">
本应还会有一个二级菜单。
点击Nanazip后弹出如下错误。
<img width="241" alt="屏幕截图 2022-01-20 220542" src="https://user-images.githubusercontent.com/93424632/150353835-0626714d-75ed-4fcc-93d7-3579951d7acc.png">

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/150624463-d4c7b3ae-4a9e-4386-8a05-f0518652d26a.png)
NanaZip的菜单采用自绘方式，普通状态下不会出现，该问题将于下一个版本中解决，RX将手动发送激活消息

**Comment by ktns01** [comment]
之前用的BandiZip，默认情况下在RX中BandiZip的上下文菜单选项是散乱的，在BandiZip中启用层叠菜单后不显示BandiZip的上下文菜单。不知道下个版本是不是也解决了这个问题。
<img width="1055" alt="屏幕截图 2022-01-26 115622" src="https://user-images.githubusercontent.com/93424632/151101600-873d171c-93b6-49fe-8211-09271fe0d553.png">

**Comment by zhuxb711** [comment]
此问题将于7.4.5中修复
