### ISSUE TITLE
在最小化后，任务栏上的关闭问题

### ISSUE THREAD

**Issue by arthur-x** [zhuxb711/RX-Explorer#368]
最小化到任务栏后，鼠标移动到任务栏图标上，在缩小视图右上角点击关闭后，任务栏图标不消失，需要再点击一下才消失。
RX最新版，win10最新版。

**Comment by zhuxb711** [comment]
该问题是微软UWP框架方面的BUG，无法修复

**Comment by arthur-x** [comment]
这样吗，太可惜了。
