### ISSUE TITLE
分文件扩展名记住用户所选择的“选择其他应用”

### ISSUE THREAD

**Issue by ChromaPIE** [zhuxb711/RX-Explorer#369]
在较常需要使用bandizip打开.jar文件时遇到了麻烦。每次选择jar文件的打开方式时都需要手动进入路径并选择bandizip.exe。是否可能记住用户对特定扩展名所选择的应用程序并保存，并在用户下次对该类型的文件选择打开方式时直接在“选择打开方式”对话框下的“选择其他应用”中直接将其推荐给用户，提高效率。

使用这款管理器的时间不长，对于这种问题可能已有快捷的方式，望包涵。

**Comment by zhuxb711** [comment]
只要你勾选了 “始终使用此应用打开该类型文件”，RX将会保存该类型的默认打开方式并在下次使用，也就是说现在已经是按类型设定默认打开方式的
<img width="423" alt="image" src="https://user-images.githubusercontent.com/42038175/152728206-566f3161-ae5e-4dc5-81c5-f1f75d6cd3a6.png">
