### ISSUE TITLE
txt 格式文件切换成记事本程序打开后，再切换回 RX 内置查看器失败

### ISSUE THREAD

**Issue by all-aroundbadass** [zhuxb711/RX-Explorer#37]
version：5.3.6

1. 找到一个 txt 格式文件，右击，“打开方式”——“选择其他应用”，选中记事本应用程序并勾选默认使用此应用打开该类型文件，此时双击会用记事本应用程序打开此文件
2. 继续选择其他应用打开此文件，这次选择“RX 内置查看器”，不选中为默认打开此类程序，点击确定后仍然用记事本打开
3. 使用其他第三方记事本程序重复步骤二无此问题

**Comment by zhuxb711** [comment]
我已调查该问题。

该问题源自RX处理用户选择“RX内置查看器”时错误的使用了一个会检索默认打开设置的方法，该问题在您同时选中“默认使用此应用打开该类型文件”时不会触发，这是由于同时选中该选项将会导致默认设置变更，于是虽然上述逻辑错误，但这种情况下却能够误打误撞的选用“内置查看器”打开。

该问题亦将于下一个版本中修复

**Comment by zhuxb711** [comment]
Close，版本5.4.0已发布
