### ISSUE TITLE
在微软商店无法更新， 快捷键失效

### ISSUE THREAD

**Issue by sugammadex** [zhuxb711/RX-Explorer#370]
本来安装了以后可以复制粘贴和删除
提示要更新，结果在微软商店怎么都无法更新， 然后快捷键也失效了

**Comment by zhuxb711** [comment]
快捷键失效问题已于7.4.7版本中解决，请更新

**Comment by sugammadex** [comment]
但是在微软商店里无法更新呢，圈圈总是停在70%左右到位置 就停止了， 卸载了重新装也不行。。。。

**Comment by zhuxb711** [comment]
微软出来背锅
