### ISSUE TITLE
能否加几个选项来选择默认打开方式

### ISSUE THREAD

**Issue by Neurotoxin0** [zhuxb711/RX-Explorer#371]
RT
比如打开pdf，视频等类型的文件时 ，默认使用RX内置的打开，但效果什么的并不好，能不能在设置里加几个按钮来让文件以系统默认的方法直接打开

**Comment by Neurotoxin0** [comment]
找到了办法来设置了，通过系统默认选项可以改，但还是推荐加几个按钮

**Comment by zhuxb711** [comment]
打开方式中可以更改默认应用程序
