### ISSUE TITLE
[功能请求]判定RX管理器是否已開啟，並開在相同視窗

### ISSUE THREAD

**Issue by peter1421** [zhuxb711/RX-Explorer#377]
如圖
![](https://media.giphy.com/media/Ta37jebRQorVUbfEEv/giphy.gif)
當我已開啟視窗A時
我在其他地方打開文件夾 EX:everything
RX管理器開啟另一個視窗B

有沒有辦法讓他開啟在視窗A中的新分頁，而不是新開一個視窗B

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/157032501-7c591b62-1842-42b0-9742-6e6d5664dc4a.png)
