### ISSUE TITLE
建议提供一个安装包，安装后的软件提供捐助功能

### ISSUE THREAD

**Issue by Shwen-Y** [zhuxb711/RX-Explorer#379]
建议提供一个安装包（只有现在试用版的那种功能也行），然后提供一个捐款页面，等用户自助捐款到18元就自动解锁所有功能，这样我觉得更利用推广使用。

**Comment by zhuxb711** [comment]
本地没有商店验证支持，无法确认购买/捐助真实性，本身也有侧载安装包

**Comment by Shwen-Y** [comment]
我用了一些其他开源软件，作者在软件介绍页附了自己的支付宝二维码，我觉得这样也是可以的。

微软商店把你的软件限定为最多只能10台机子使用，它的这一做法就违背了RX文件管理器作为开源软件的精神了。

**Comment by zhuxb711** [comment]
你的意思是我自己架一台专门给侧载RX的激活服务器？其实主要问题是无从获得这个捐助的人是否已经购买完成了，无法确保后续正确激活，限制设备数量我个人觉得也没啥问题，因为避免大量同账号传播
