### ISSUE TITLE
建议：标签页

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#38]
希望拖拽RX的标签页时，把标签页拖出主窗口可以再启动一个新的实例，且新的实例打开的是拖拽出去的标签页！

**Comment by XSH-Hero** [comment]
您可以参考一下Notepads APP和Files UWP，这两个已经具备了上述功能，加油！

**Comment by XSH-Hero** [comment]
[Bandicam.zip](https://github.com/zhuxb711/RX-Explorer/files/5246474/Bandicam.zip)

**Comment by XSH-Hero** [comment]
上面的压缩包中的视频是上述功能在Files UWP中的演示，希望RX也可以做到

**Comment by XSH-Hero** [comment]
更新了！感觉比files UWP更流畅，更稳定！感谢开发者！！

**Comment by zhuxb711** [comment]
Files uwp那我看了，拖拽最后一个标签页出来似乎会遇到数组越界的错误而崩溃，设计上有一些小问题┑(￣Д ￣)┍
