### ISSUE TITLE
单击文件重命名问题

### ISSUE THREAD

**Issue by Shwen-Y** [zhuxb711/RX-Explorer#382]
不知道算不算bug，单击文件名后原文件名消失，必须要完全重新输入文件名，而不是进入传统的重命名模式。

**Comment by zhuxb711** [comment]
![GIF 2022-3-27 1-02-26](https://user-images.githubusercontent.com/42038175/160249839-99ab71d8-f7b7-4cd9-991b-70e8d0a68a0b.gif)
未发现该问题

**Comment by zhuxb711** [comment]
请提供复现步骤或者GIF或进一步信息，否则我将关闭此Issue
