### ISSUE TITLE
压缩包中文件拖曳问题

### ISSUE THREAD

**Issue by Shwen-Y** [zhuxb711/RX-Explorer#383]
从压缩包中拖曳文件到外面时会报找不到文件的错误，不像一般文件管理器那样支持拖曳解压，必须要提取或解压才行。

**Comment by zhuxb711** [comment]
RX并不支持部分压缩软件的拖拽解压，因为RX是使用的任务队列来处理各种文件操作请求，因此在拖拽请求传入的时候，RX并不会立即处理该文件请求，而是排队处理，即使队列是空的也会有很短的间隔时间。这将导致某些压缩软件自行删除解压出来的文件。因为RX记录下路径等信息后会回报拖拽完成，此时某些压缩软件就会立即删除刚解压到临时目录的文件(当然也可能是放了DeleteOnClose的标志)，进而造成RX实际处理的时候找不到文件。一般文件管理器不支持队列任务，它们必定可以在收到请求的时候立即进行处理而无需排队(这也是造成它们卡死的主要原因，因为不处理完不会回报)

**Comment by zhuxb711** [comment]
RX可以支持的场景为：从内置压缩文件查看器拖拽至RX自身的情况，请知悉
