### ISSUE TITLE
默认不开启连接wsl

### ISSUE THREAD

**Issue by jyeric** [zhuxb711/RX-Explorer#385]
电脑默认wsl处于关闭状态 但每次打开rx文件管理器会自动连接打开wsl，占用内存 
希望能够添加选项不自动连接wsl

**Comment by zhuxb711** [comment]
RX只是会尝试读取WSL文件夹以确定是否需要显示WSL，但应当不会导致WSL自动启动吧~~~

**Comment by jyeric** [comment]
> RX只是会尝试读取WSL文件夹以确定是否需要显示WSL，但应当不会导致WSL自动启动吧~~~

我这里好像就自动启动了，开之前是关闭状态，每次打开rx的时候会开启

**Comment by silentmoooon** [comment]
试了下,确实会导致WSL启动. 得想个办法检测是否有安装WSL, 如果有安装,就显示个占位盘符在那里, 点开了再去真正加载.

**Comment by zhuxb711** [comment]
> 试了下,确实会导致WSL启动. 得想个办法检测是否有安装WSL, 如果有安装,就显示个占位盘符在那里, 点开了再去真正加载.

不知道有没有合理的WSL检测方法

**Comment by jyeric** [comment]
> > 试了下,确实会导致WSL启动. 得想个办法检测是否有安装WSL, 如果有安装,就显示个占位盘符在那里, 点开了再去真正加载.
> 
> 不知道有没有合理的WSL检测方法

cmd命令`wsl --list`会输出当前的wsl项目 不知道有没有用
另外#341 的卡死情况也有可能是wsl造成的，因为连接wsl时如果是关闭状态会开启整个wsl服务，开启wsl服务时rx会卡死

**Comment by silentmoooon** [comment]
> > > 试了下,确实会导致WSL启动. 得想个办法检测是否有安装WSL, 如果有安装,就显示个占位盘符在那里, 点开了再去真正加载.
> > 
> > 
> > 不知道有没有合理的WSL检测方法
> 
> cmd命令`wsl --list`会输出当前的wsl项目 不知道有没有用 另外#341 的卡死情况也有可能是wsl造成的，因为连接wsl时如果是关闭状态会开启整个wsl服务，开启wsl服务时rx会卡死

这命令可以的 .  
wsl --list --quiet  加个参数可能更好判断一些.

**Comment by zhuxb711** [comment]
没装WSL有没有这个命令的示例输出让我云一下

**Comment by silentmoooon** [comment]
咦 按理着这个命令是已经内置了的呀  哪怕没装wsl  也会有wsl这个命令吧.

**Comment by zhuxb711** [comment]
我的意思是搞个有WSL情况下这个命令的输出，这样我就可以偷懒不装WSL，按照示例输出我搞定这个事情

**Comment by silentmoooon** [comment]
哦, 理解错意思 了..

![image](https://user-images.githubusercontent.com/9210514/160606160-cd4c29ad-cc26-40e5-b765-20afa95ea5b0.png)

**Comment by zhuxb711** [comment]
> 哦, 理解错意思 了..
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/9210514/160606160-cd4c29ad-cc26-40e5-b765-20afa95ea5b0.png)
> 
> 

试试多个WSL会怎么显示？

**Comment by silentmoooon** [comment]
![image](https://user-images.githubusercontent.com/9210514/160609930-a511b094-6dc9-4a39-a4da-1981dc40649d.png)

**Comment by zhuxb711** [comment]
那核心问题来了，RX要读取WSL文件夹的时候会导致WSL启动，那启动不可避免呀，除非是明面上列一个假的文件夹这样子，然后双击时才实际获取真实文件夹

**Comment by silentmoooon** [comment]
感觉只能这样了. 先搞个假的

**Comment by zhuxb711** [comment]
假的不符合当前RX的架构设计，RX不允许搞一个假的出来，另外由于其他一些地方的限制，即使是假的也无法延迟到实际使用时才加载文件对象，简而言之，假的驱动器不符合当前架构的设计要求

**Comment by jyeric** [comment]
> 假的不符合当前RX的架构设计，RX不允许搞一个假的出来，另外由于其他一些地方的限制，即使是假的也无法延迟到实际使用时才加载文件对象，简而言之，假的驱动器不符合当前架构的设计要求

是否可以引入开关来选择是否加载呢？

**Comment by silentmoooon** [comment]
要不和资源管理器一样, 驱动这里就不显示WSL了, 就在左边的树搞一个Liunx节点,展开时再加载?

**Comment by zhuxb711** [comment]
我计划使用wsl --list --verbose来检测wsl是否正在运行，如果正在运行的话就把他添加进来

**Comment by silentmoooon** [comment]
这思路不错

**Comment by zhuxb711** [comment]
不过我看了一下Windows Explorer，它确实也是访问WSL的时候会启动一下子，随后就关掉了，似乎这是正常现象？那做检测是否正在运行没有意义呀，我还是添加一个开关让控制是否加载WSL文件夹吧，默认情况下不加载

**Comment by silentmoooon** [comment]
wsl本身的机制，如果一段时间不活动，会自动关掉，除非有开后台进程

**Comment by zhuxb711** [comment]
做了个开关，并且现在即使开启WSL连接也不会卡住UI线程了（让它卡辅助进程去了，然后RX等待辅助进程响应的方法又是真异步的设计，所以现在完全不会卡死UI，又没有额外的线程开销）

**Comment by zhuxb711** [comment]
7.6.3已发布
