### ISSUE TITLE
建议：版本7.6.1.0

### ISSUE THREAD

**Issue by ilovexy2tom** [zhuxb711/RX-Explorer#386]
我解压这个操作

以前用win的资源管理器，会解压完就在旁边

用Rx解压后，文件夹会排序到后面去，直接就找不到了

因为我的文件夹是下载文件夹，东西比较多，我还要点击分类，让文件夹在最上面，然后再点修改时间排序，找到刚解压的文件夹么？

建议保留win的习惯，不然解压完的还要找半天，非常不方便

**Comment by ilovexy2tom** [comment]
还有，双击有时候会出现重命名

我不知道是响应太慢还是我双击的确实慢

资源管理器不会这样

**Comment by zhuxb711** [comment]
双击重命名逻辑：第一次点击1200ms后再次点击同一个文件的时候会触发。不过这个问题也许是Win10的BUG触发的，Win10中列表组件点击时会有按下的动画，快速双击的时候这个动画可能会有bug，建议在Win10系统上前往RX设置-个性化-动画效果-勾选“关闭列表选择动画”

**Comment by zhuxb711** [comment]
关于提出的临时摆放至压缩文件旁边的问题，应该会在下一个版本中有所改善

**Comment by ilovexy2tom** [comment]
还有几个小问题，

解压和复制我容易卡住，进度在任务栏，不在当前界面吗？自带解压，有一次解压结果丢失文件（部分文件夹空了）

第二个是重命名时，ctrl+v粘贴不上，会造成和回车一个效果

**Comment by zhuxb711** [comment]
> 还有几个小问题，
> 
> 解压和复制我容易卡住。并且进度在任务栏，不在当前界面吗？
> 
> 自带解压，有一次解压结果丢失文件（部分文件夹空了）
> 
> 另一个是重命名时，ctrl+v粘贴不上，会造成和回车一个效果

停停停，你不会以为软件开发和错误修复就是听你空洞的描述就能准确的修到这些问题吧？能发现那是意外，你什么信息都不提供就光描述。有一次丢失文件，那你倒是把相应的压缩包提供给我啊。

改任何问题，靠的是准确复现，靠的是详实的复现步骤，不是假大空的曾经遇到过啥啥啥问题的几句描述，不能让我这边也搞出同样问题的错误报告都是扯淡。我不能重现，除非你自己会查问题自己修，否则怎么修？

正确的错误报告：
1怎么样2怎么样3怎么样（操作步骤）就一定会出现XXX问题。涉及特殊逻辑比如，只有在处理A压缩包的时候解压会出现问题（并提供会出现问题的压缩包以供参考）。

有上面的详细信息你快我也快，复现不出来的东西根本修不了，能修的只要找到原因很快就修了。

**Comment by ilovexy2tom** [comment]
> 

哦抱歉，是我的问题

压缩包暂时不能提供，那个其他的问题，我整理一下复现步骤后，再提到咱们这个issue下面吧

**Comment by zhuxb711** [comment]
重命名时不能使用Ctrl+V的问题无法复现，我这边可以正常使用

**Comment by zhuxb711** [comment]
有后续反馈可以继续在下面回复，我现在关闭这个issue
