### ISSUE TITLE
建议：优化启动速度

### ISSUE THREAD

**Issue by ilikerome** [zhuxb711/RX-Explorer#387]
如题。
不确定是否是我这台电脑环境导致的，但是启动确实有点慢了，大约要等待3~5s，鼠标才能有反应。

**Comment by silentmoooon** [comment]
> 建议暂时关闭WSL，可能是最近发现的与WSL有关的导致启动延迟的问题

唉, 是我的锅, 因为我电脑上WSL一直是开机自启的, 所以测试的时候也没考虑这一点

**Comment by zhuxb711** [comment]
> > 建议暂时关闭WSL，可能是最近发现的与WSL有关的导致启动延迟的问题
> 
> 
> 
> 唉, 是我的锅, 因为我电脑上WSL一直是开机自启的, 所以测试的时候也没考虑这一点

没事没事，这个我也没有想到，7.6.3已默认禁用WSL加载了，并且现在WSL加载也不会卡住UI了
