### ISSUE TITLE
一些 问题

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#388]
1. 右键菜单打开后会再次刷新，会改变位置，并且有时刷新后缺少部分按钮（如撤销）：
![1](https://user-images.githubusercontent.com/64201424/161385653-bf708011-2607-4ab0-b4ac-8c87189093c5.gif)
2. 有时右键菜单会由于显示范围不足导致部分按钮无法显示：
![3](https://user-images.githubusercontent.com/64201424/161385786-6fc4e2b5-9bc1-49d8-bb28-e5671c1bb169.gif)
3. 浅色背景时配色较为难以辨认文字。

**Comment by zhuxb711** [comment]
> 1. 右键菜单打开后会再次刷新，会改变位置，并且有时刷新后缺少部分按钮（如撤销）：
> 
> ![1](https://user-images.githubusercontent.com/64201424/161385653-bf708011-2607-4ab0-b4ac-8c87189093c5.gif)
> 
> 2. 有时右键菜单会由于显示范围不足导致部分按钮无法显示：
> 
> ![3](https://user-images.githubusercontent.com/64201424/161385786-6fc4e2b5-9bc1-49d8-bb28-e5671c1bb169.gif)
> 
> 3. 浅色背景时配色较为难以辨认文字。

1. 是，这个是由于部分电脑加载菜单项较慢而引入的优化，如果您加载速度足够快，可以在设置中设置菜单项加载完成后再显示。以避免后加载菜单项可能导致遮挡的Bug(其实这是微软控件的Bug)，当前升级Win11之后这个比较少见了。
2. 同1，Win10才有的Bug
3. 亚克力效果默认是较为透明的，因此如果背景较亮则可能导致文字无法识别。因此您可以避免将其放置于较亮的背景，或者在设置-个性化-模式中设置为自定义模式，选择Acrylic背景，然后根据需要调节下方的透明度和透光度来合理调节整体效果，以避免光线影响字体识别的问题
