### ISSUE TITLE
在地址栏敲\\似乎会直接卡死？

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#389]
![image](https://user-images.githubusercontent.com/45326534/161642556-e2ce39c9-81de-489d-81a4-63694e3477b6.png)
好像截图没什么意义的样子

**Comment by taooceros** [comment]
顺便有一个小建议是现在文件夹会重复加载一次图片，会不会判断一下如果是default的文件夹图片就不重新加载会更好？

**Comment by zhuxb711** [comment]
地址栏输入\\然后按Enter的时候会被消除为空字符串并在这里被拦截下来
https://github.com/zhuxb711/RX-Explorer/blob/372a18de4c10f7faa438b0a416a0fff004820c67/RX_Explorer/View/FileControl.xaml.cs#L1501

**Comment by taooceros** [comment]
> 地址栏输入\\然后按Enter的时候会被消除为空字符串并在这里被拦截下来
> 
> https://github.com/zhuxb711/RX-Explorer/blob/372a18de4c10f7faa438b0a416a0fff004820c67/RX_Explorer/View/FileControl.xaml.cs#L1501

我还没按enter rx就卡死了，不知道你能不能重现
我是想试试访问wsl

**Comment by zhuxb711** [comment]
TextChange的时候这个地方没有做处理，其他的地方有处理，单个\\会被系统API认为是要访问RX主程序目录下的文件，但是单个\本身并不是合法的路径，会导致一系列用于验证的API报错，可能瞬时间涌现的Exception导致了卡顿，经过测试，这个问题第一次出现时卡顿很明显，后续几乎不再卡顿。通过TrimEnd解决该问题

```csharp
//Before
string InputPath = sender.Text.Replace('/', '\\');
//After
string InputPath = sender.Text.TrimEnd('\\').Replace('/', '\\').Trim();
```

**Comment by taooceros** [comment]
话说如果要访问wsl需要在地址栏怎么操作呢？

**Comment by zhuxb711** [comment]
> 话说如果要访问wsl需要在地址栏怎么操作呢？

\\wsl$

**Comment by taooceros** [comment]
那不能敲\\确实有点奇怪hhh

**Comment by zhuxb711** [comment]
> 那不能敲\\确实有点奇怪hhh

没有不能敲，最新代码已经解决这个问题了

**Comment by zhuxb711** [comment]
7.6.4已发布
