### ISSUE TITLE
无法正确解锁 BitLocker

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#390]
解锁 BitLocker 时提示失败，实际上成功（管理员权限已提供）。

另外快速访问的文件夹发现由于 BitLocker 而无法访问会直接取消这些文件夹的快速访问，就算解开了 BitLocker 也无法自动恢复。

**Comment by zhuxb711** [comment]
这个问题已复现，将于下一个版本中修复

**Comment by zhuxb711** [comment]
7.6.5已发布

**Comment by g-mph** [comment]
> 7.6.5已发布

![image](https://user-images.githubusercontent.com/64201424/163700235-be698bce-5d55-40d1-b453-843ab499b93b.png)

上面有张截屏

所以快速访问文件夹不能自动恢复吗？
