### ISSUE TITLE
Can't make it the default opening method for folders.   无法让它成为文件夹的默认打开方式

### ISSUE THREAD

**Issue by mc-doge666** [zhuxb711/RX-Explorer#392]
![image](https://user-images.githubusercontent.com/77102592/164352520-8aad11e2-9b68-4a0b-9345-4d81dc331fe2.png)
当我试图让他作为文件夹的默认打开方式时，它会提示错误。
When I try to make it the default way to open a folder, it prompts for an error.
![image](https://user-images.githubusercontent.com/77102592/164352576-1319fd13-14e3-4921-a5c3-e862b235ee74.png)

**Comment by zhuxb711** [comment]
请提供日志文件以供分析

**Comment by mc-doge666** [comment]
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/8527023/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
Source: RX-Explorer

Version: 7.6.5.0

Message:
        An unexpected error was threw in InterceptDesktopFolderAsync, message: 无法加密指定的文件。 : 'C:\Users\doge\AppData\Local\RX-Explorer_Launch_Helper\D3DCompiler_47_cor3.dll'

Extra info: 
        CallerFileName: FullTrustProcessController.cs
        CallerMemberName: InterceptDesktopFolderAsync
        CallerLineNumber: 1706

**Comment by zhuxb711** [comment]
可能.Net6框架在你的电脑上运行时有什么奇怪的问题，这方面我也不知道该怎么处理

**Comment by zhuxb711** [comment]
这个开关是一系列操作的自动化版本，所以您如果非常需要该功能，可以手动完成一系列操作来启用相应功能
