### ISSUE TITLE
当手机插入电脑时，会发生崩溃，运行后立即崩溃，直到拔下外接手机

### ISSUE THREAD

**Issue by TTS-version** [zhuxb711/RX-Explorer#398]

**Comment by TTS-version** [comment]
具体情况是手机启用文件传输后ex管理器就会崩溃直到扒下

**Comment by TTS-version** [comment]
还有，感觉冷启有点慢，能加快第一次启动，或者开机就挂在后台，热启动的时候直接显示，省略启动的蓝色界面吗？

**Comment by zhuxb711** [comment]
1. 该问题已确认，由于MTP设备的 “名称 ⇄ 显示名称” 某些情况下产生无限循环递归调用导致StackOverflow进而导致严重错误内存访问违例AccessViolation从而使RX快速崩溃
2. 由于此问题的特殊属性，故任何时候插入MTP设备后都将导致RX文件管理器快速崩溃
3. UWP不支持启动后挂在后台，但可以随系统一并启动并以最小化的形式存在于任务栏中。
4. 启动时的界面是UWP应用特有的，供应用程序显示初始化进度或其他需要延时的操作，但即使不存在这些操作也不可以跳过
5. 冷启动速度随设备而变化，对于用户使用的发行版，在我的电脑上启动速度不慢于1s (若未使用Bing背景图片)

**Comment by TTS-version** [comment]
好的，感谢作者答复

**Comment by zhuxb711** [comment]
7.6.9已发布
