### ISSUE TITLE
Would we take possession of another FILE NAME?

### ISSUE THREAD

**Issue by Ishiharaerika** [zhuxb711/RX-Explorer#399]
Recently I've tested and downloaded your File Explorer at UWP store. It grabs my heart and fascinates me so much! No matter the price's acceptable, your design of this application deserves one of the top of my have-seen file explorers. However so far as I believe there'd be some of my opinions , NOT for the function but for the design.
I have to point out that the display name of RX-Explorer might have more choices. At present I can only have my gaze at the chinese characters and somehow it could be hardly to recognize, sometimes. I believe this app's not xenophobic but as a conclusion "humanity" to all mankind. So it would be grateful just to make a change at displayed app's name. Slightly changes of "globalized design" would be appreciated!

**Comment by xmydl520** [comment]
Sorry but to leave a message here. I somehow couldn't use the in-app mail contacter thus I send it with an open issue. 
I have intention to traslate the app into Japanese. Might you have any will to commit my translating? Might we have a deeper conversation with this topic?

**Comment by zhuxb711** [comment]
> Recently I've tested and downloaded your File Explorer at UWP store. It grabs my heart and fascinates me so much! No matter the price's acceptable, your design of this application deserves one of the top of my have-seen file explorers. However so far as I believe there'd be some of my opinions , NOT for the function but for the design.
> 
> I have to point out that the display name of RX-Explorer might have more choices. At present I can only have my gaze at the chinese characters and somehow it could be hardly to recognize, sometimes. I believe this app's not xenophobic but as a conclusion "humanity" to all mankind. So it would be grateful just to make a change at displayed app's name. Slightly changes of "globalized design" would be appreciated! 

Glad to hear your suggestions. Since RX-Explorer do not support for the Japanese currently. It should display English but Chinese on your device (if your Windows language is Japanese).

**Comment by zhuxb711** [comment]
> Sorry but to leave a message here. I somehow couldn't use the in-app mail contacter thus I send it with an open issue. 
> 
> I have intention to traslate the app into Japanese. Might you have any will to commit my translating? Might we have a deeper conversation with this topic?

It's totally ok to leave your thoughts on here, don't worry.

Yes any translation or other PR is welcome! If you want to help create a new translation for RX-Explorer, there are some tools that might help you. You actually do not need to clone this repository I will share a translation file and tools to you once free

**Comment by xmydl520** [comment]
I'm so glad hearing from your reply. I am a traditional Windows user with Japanese version. Since I've been suggested that it should be Engilish name displayed, I may have to mention it with my screenshot. As you can see, it somehow goes wrong.
[https://files.catbox.moe/w8eb6y.png](url)

**Comment by zhuxb711** [comment]
> I'm so glad hearing from your reply. I am a traditional Windows user with Japanese version. Since I've been suggested that it should be Engilish name displayed, I may have to mention it with my screenshot. As you can see, it somehow goes wrong.
> 
> [https://files.catbox.moe/w8eb6y.png](https://files.catbox.moe/w8eb6y.png)

That is an unexpected behavior if you do not change the language in the settings. For the time being, you could try modifying the language in settings page built in RX-Explorer. You should notice a setting named "语言" in the tab "基本"

**Comment by zhuxb711** [comment]
Besides, may I take a look at your Windows Display Language settings? And what is your language code? For example: zh-cn/en-us/fr-FR. That might help to solve this issue if it's reproduce-able

**Comment by xmydl520** [comment]
Thank you for replying! As you can see, what I'm using is Windows Japanese version. Languages and unicode settings all go belong the way. I've tried to turn RX's language into English. It still doesn't change the name right on the start deck(showed above).
[https://files.catbox.moe/ep7nx1.PNG](https://files.catbox.moe/ep7nx1.PNG)

**Comment by xmydl520** [comment]
I would wonder if it something went wrong there right on Microsoft Store. As you may see, it shows directly chinese on my store, as if it was designed like this.
[https://files.catbox.moe/gyjtdi.PNG](https://files.catbox.moe/gyjtdi.PNG)

**Comment by zhuxb711** [comment]
> I would wonder if it something went wrong there right on Microsoft Store. As you may see, it shows directly chinese on my store, as if it was designed like this.
> 
> [https://files.catbox.moe/gyjtdi.PNG](https://files.catbox.moe/gyjtdi.PNG)

That might be related to the settings of Microsoft Store. I have never set any configuration for those unsupported language. So I think Microsoft Store will choose one of the language that RX supported to display randomly. I will try to update Microsoft Store and let's find out whether this issue was fixed correctly. 

I will let you know once I updated Microsoft Store. Maybe one or two days. Thanks for reporting this issue.

**Comment by xmydl520** [comment]
> > Sorry but to leave a message here. I somehow couldn't use the in-app mail contacter thus I send it with an open issue.
> > I have intention to traslate the app into Japanese. Might you have any will to commit my translating? Might we have a deeper conversation with this topic?
> 
> It's totally ok to leave your thoughts on here, don't worry.
> 
> Yes any translation or other PR is welcome! If you want to help create a new translation for RX-Explorer, there are some tools that might help you. You actually do not need to clone this repository I will share a translation file and tools to you once free

That's really amazing! I've already forked this repository and I'm looking forward to translating it.

**Comment by zhuxb711** [comment]
Before start:
1. Download [MAT Editor](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads)
2. Install MAT

Optional 1 (Complex, make sure you create a new branch before commit and PR):
1. Open RX_Explorer.sln with Visual Studio 2022
2. Add a new extension named: "Multilingual App Toolkit v4.1 (VS 2022+)" for Visual Studio 2022
3. Right click the "MultilingualResources" folder in project RX_Explorer. Click "Add translation language"
![image](https://user-images.githubusercontent.com/42038175/170175073-2a73aeec-9fb1-46d2-b06f-aba276a2d19f.png)
4. Select ja-JP and click "Ok"
![image](https://user-images.githubusercontent.com/42038175/170175392-6a08399c-6ddf-41c9-a183-33acf39c4a25.png)
5. A new translation file and resource file was generated automatically for you
![image](https://user-images.githubusercontent.com/42038175/170175491-9323ba31-34c2-48e3-8a26-5bab7898322b.png)
6. Open "RX_Explorer.ja-JP.xlf" with MAT
![image](https://user-images.githubusercontent.com/42038175/170175667-2e0c7946-786d-4d37-a0de-1d3575ba6818.png)
7. Enter your translation in the "Translation Box" and click "Next" until to the end

Option 2 (Simple):
1. Download the translation file prepared in advance
[RX_Explorer.ja-JP.zip](https://github.com/zhuxb711/RX-Explorer/files/8767776/RX_Explorer.ja-JP.zip)
2. Open it with MAT
3. Enter your translation in the "Translation Box" and click "Next" until to the end
4. Save and send it back to me
5. I will finish the rest

**Comment by zhuxb711** [comment]
Please let me know if have any concerns, thanks

**Comment by xmydl520** [comment]
> Please let me know if have any concerns, thanks

I'm presently progressing the translation job. Somehow I have to apologize to slow-pace working cooperating with Japanese. The present situation of my work is that I've finished more than a half of the work and have listed a few items that was hard to translate. I believe the work will be finished in next 2 weeks.

**Comment by zhuxb711** [comment]
Don't worry, please follow your own path to translate it and should not take too much of your time. Thanks for helping translate it to Japanese! Any question is welcome if some of them hard to translate.
