### ISSUE TITLE
打开文件夹,能否直接使用RX-Exploer打开,而不是默认的

### ISSUE THREAD

**Issue by justiony** [zhuxb711/RX-Explorer#4]
[需求]桌面新建文件夹,已经安装RX程序,打开新建文件夹,响应为操作系统默认方式打开,是否能有方法,使用RX-Exploer打开

**Comment by zhuxb711** [comment]
理论上可以做到，但如果完全替换将会出现一些问题，比如查看设备等情况下，RX无法显示，您也将无法使用原来的文件管理器查看。为了避免不便的情况，故RX文件管理器只提供WIN+E按键的替换功能

**Comment by oxygen-dioxide** [comment]
> [需求]桌面新建文件夹,已经安装RX程序,打开新建文件夹,响应为操作系统默认方式打开,是否能有方法,使用RX-Exploer打开

可以新建文件夹后创建快捷方式，在快捷方式的属性里面，“目标”一项的开头插入“rx-explorer.exe ”（exe后面有个空格），确定。然后再双击这个快捷方式就是用RX打开
![image](https://user-images.githubusercontent.com/54425948/104139513-f3a21000-53e6-11eb-927f-9a6d56268900.png)
