### ISSUE TITLE
获取全部右键菜单

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#40]
今天看了一下Files UWP，他们那边已经可以获取全部右键菜单了！说明这是可以做到的！希望RX也可以

**Comment by XSH-Hero** [comment]
就像下面这样

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/94452151-ce93e380-01e1-11eb-9a61-e8ded0db1b89.png)

**Comment by XSH-Hero** [comment]
你一定能做到！

**Comment by zhuxb711** [comment]
StevenGLee会负责跟进这个建议，预计十一期间将进行可行性探索。

@StevenGLee 若有任何开发上、各种组件关系等问题，都可以随时问我，谢谢您提供帮助，若您届时提交PR，请@一下该Issue~

**Comment by XSH-Hero** [comment]
🆗👌

**Comment by StevenGLee** [comment]
OK👌

**Comment by XSH-Hero** [comment]
偶然间我发现Files那边是通过Win32程序“FilesFullTrust.exe”来获取右键菜单的

**Comment by zhuxb711** [comment]
@XSH-Hero 很正常，RX也有，很多UWP限制可以通过这个来绕过，Files uwp那个Win32采用的时间甚至比RX晚一些

**Comment by zhuxb711** [comment]
@StevenGLee 有任何的进展嘛？

**Comment by XSH-Hero** [comment]
？

**Comment by XSH-Hero** [comment]
怎么没有动静了？

**Comment by zhuxb711** [comment]
@StevenGLee 最近可能比较忙，没有时间来搞这个功能。Tips: 我刚刚瞄了一眼Files uwp，获取右键菜单那个崩得程度，各种把自己搞垮，啧啧啧~~~~~~~

@StevenGLee 最近是否有时间进行该功能的开发呢？

**Comment by XSH-Hero** [comment]
哈哈哈，是的！

**Comment by XSH-Hero** [comment]
files不能对普通文件使用全部右键菜单，只能对文件夹。。。

**Comment by XSH-Hero** [comment]
这是崩溃现场23333
![image](https://user-images.githubusercontent.com/69738882/97594668-ddb6bd00-1a3d-11eb-8807-068127b2a4d0.png)

**Comment by XSH-Hero** [comment]
也正是通过这个现象使我发现files获取右键菜单的途径

**Comment by StevenGLee** [comment]
最近确实忙，有几门实验课要验收（淦，大四竟然还要上课简直离谱），导师又让我调研一下毕设的东西。过一段时间吧，寒假再看看咕咕咕咕咕咕

**Comment by XSH-Hero** [comment]
没事，有时间再弄，这个也不太着急，只要弄出来就行

**Comment by zhuxb711** [comment]
我正在编写这部分的代码了

**Comment by zhuxb711** [comment]
[ContextMenuTest.zip](https://github.com/zhuxb711/RX-Explorer/files/5542209/ContextMenuTest.zip)
以上是示例代码，但有个奇怪的点，在于无论我怎么配置参数，总是和Files获取的内容有点不太一样，Files可以获取到“使用Microsoft Defender扫描”一类的菜单，但是我无法获取到，希望有知道的人帮助我一下

**Comment by zhuxb711** [comment]
此功能将随下一个版本发布，但右键菜单内容可能不全面，原因未知，先用着先

**Comment by zhuxb711** [comment]
@StevenGLee 有空康康为啥代码实现上与Files基本相同，但是获取到的菜单项数总是比它少一些的原因嘛？(即使代码完全一样)

**Comment by zhuxb711** [comment]
此Issue我暂时关闭，如有新进展会在这里通知，或者重新打开这个Issue

**Comment by silentmoooon** [comment]
不知道你解决了没有,帮你看了一下,区别就在于main方法上的[STAThread]

**Comment by zhuxb711** [comment]
我的Main方法上也有STAThread，但是凭空Files就是能够比我获得更多的右键菜单项 @silentmoooon  有何高见？

**Comment by silentmoooon** [comment]
但我试了下你之前发的这个ContextMenuTest.zip,加了STAThread,然后QueryContextMenu的枚举改成Shell32.CMF.CMF_SYNCCASCADEMENU| Shell32.CMF.CMF_EXTENDEDVERBS就和files uwp一样多了
我也没啥高见,就2边对, 哈哈

**Comment by zhuxb711** [comment]
那现在的项目中咋改捏？你说的那两个CMF我试过了，还是Files多。右键菜单的获取逻辑在FullTrustProcess/ContextMenu.cs里面，无论我怎么改还是比Files少，你会注意到RX的右键菜单中总是相比Files缺少一些项目，这个问题我至今没搞清楚。如果可能，您能否提交一个PR来解决这个问题？

**Comment by silentmoooon** [comment]
大概知道是什么原因了,你后来在ContextMenu.cs里边用的不是之前ContextMenuTest.zip的方式,是用Vanara封装好的, 
![image](https://user-images.githubusercontent.com/9210514/107107669-8ced0680-686d-11eb-91a1-7ec5c2fd7274.png),
它这里边取IContextMenu的方式不太一样,导致拿到的菜单数量也不一样了,换成ContextMenuTest.zip里边的Parent.GetChildrenUIObjects<Shell32.IContextMenu>(null, Item); 就可以得到一样的结果了

**Comment by zhuxb711** [comment]
Emmmm其实大概在5.9.0的时候都是用自己那一套获取方式的(也就是你说的zip里面那种) 但似乎也没有增加？所以后来才换了Vanara封装好的那种。你可以看看ContextMenu.cs的历史Commit @silentmoooon

**Comment by silentmoooon** [comment]
额..刚看了下5.9.0, 把main方式改成同步就基本上都有了. 
还有少数几个如"使用windows defender扫描" "固定到开始"等菜单 貌似得换成非.net framework 项目才能获取到.

**Comment by zhuxb711** [comment]
@silentmoooon 
理论上讲.Net framework的项目难道不是最全的？Files那个也是.Net framework吧。

另外居然跟Main函数是异步这都有关系？
老哥提个PR吧，谢谢啦～

**Comment by silentmoooon** [comment]
.Net framework的问题我也没深究,但确实纯.Net frameworks要比vanara的原生方式要少那么几个.  files的没注意.
同样  异步我也不知道啥原理.. 哈哈.

这个嘛,你自己弄下吧. .
其实我C#也不是蛮熟~~ 哈哈

**Comment by silentmoooon** [comment]
https://stackoverflow.com/questions/47553489/set-apartmentstate-for-async-void-main
异步main方法会导致[STAThread]失效

**Comment by zhuxb711** [comment]
ok我懂了，谢谢大佬的调查 @silentmoooon

**Comment by zhuxb711** [comment]
这个效果已经实现啦~~~~~~
@silentmoooon 
@XSH-Hero 
![image](https://user-images.githubusercontent.com/42038175/107150647-c589fe80-6999-11eb-9373-92e9417f9d8d.png)

![image](https://user-images.githubusercontent.com/42038175/107150651-cf136680-6999-11eb-9998-a33a2c68b820.png)

**Comment by silentmoooon** [comment]
高效! 哈哈~
刚试用了一下,发现还有点小问题.
![image](https://user-images.githubusercontent.com/9210514/107173220-3fee6900-6a02-11eb-9af5-acc8d9b5dce6.png)

刚启动时,只获取到11个菜单项,多点几次就会获取到12个菜单项.. 不知道是什么原理..
而且id也会变化..  

![image](https://user-images.githubusercontent.com/9210514/107173342-8ba11280-6a02-11eb-8bfb-fde9f94a166e.png)
![image](https://user-images.githubusercontent.com/9210514/107173348-8e9c0300-6a02-11eb-9d18-adb1c641be2d.png)

**Comment by zhuxb711** [comment]
@silentmoooon 你的意思是说有重复项？重复项的ID是不是一样的啊？如果是一样的我做个过滤。至于为啥一会会多一个，这个你要问辣鸡Windows

**Comment by silentmoooon** [comment]
你看那2个提示的图, 这是2次获取到的菜单.
后面那次多了1个"open in windows terminal",然后还导致其他项的id和前一次的不一样了.
然后你根据id判断做删减就有问题了.

**Comment by zhuxb711** [comment]
@silentmoooon 首先有没有重复项？其次我可以在同一次获取的过程中做相同项过滤，两次获取的Id不同并没有什么关系

**Comment by silentmoooon** [comment]
取到的菜单没重复项,展示的时候有.

**Comment by zhuxb711** [comment]
OK，RX当前的设计是根据id来决定如何对右键菜单更改（如它发现新获取的右键菜单项与当前的相同，那么就不会将新的添加；若没有则添加，当前存在的在新的里面没有，则移除；若需要更新，则更新。总之不是完全替换的），而目前您提到的情况来看，应该是同一个菜单项在不同次数获取的时候id可能不一致，这样就会导致RX错误的将其当成新的菜单项来添加，我会更改这个机制，改成完全替换现有菜单项。

**Comment by silentmoooon** [comment]
发现在fullTrustProcess启动时预先读取一次菜单可以有效避免突然多出来一个的情况.
当然,现在这个机制也还是得改一下.

**Comment by zhuxb711** [comment]
这个机制我改了，老哥提个PR可好？嘿嘿，关于预先读取一下的PR。我知道Files是这样的

**Comment by silentmoooon** [comment]
就一行代码的事,那我就"勉为其难"一下  哈哈.

**Comment by zhuxb711** [comment]
嘿嘿😁～大佬要是有其他的改进也可以提交PR哦！

**Comment by silentmoooon** [comment]
唉~ C#不太熟.  不太敢动代码
之前写个剪切板小工具也是磕磕碰碰的.

**Comment by zhuxb711** [comment]
@silentmoooon 尽管提交PR，没事，我会Review的，有什么问题我会告诉你的，如果改不好我可以直接提交Commit到你的PR里面，帮你完善它。
