### ISSUE TITLE
用everything開啟特定連結時，會開啟錯誤頁面

### ISSUE THREAD

**Issue by peter1421** [zhuxb711/RX-Explorer#401]
如圖演示

通常是雲端相關連結
不會打開選定頁面，而是跑出多個根目錄

![ww](https://user-images.githubusercontent.com/51041311/170528607-f762cd80-d093-43ca-acad-f243634a5a24.gif)

**Comment by zhuxb711** [comment]
请问您使用的那个Everything的浮窗是怎么打开的呢？我不太会用Everything然后我需要那个浮窗才可以测试这种场景下的问题

**Comment by peter1421** [comment]
這是方便開啟everything的軟體wox
相關連結:
https://zhuanlan.zhihu.com/p/68383315

但這問題也有可能是wox本身的問題
再麻煩幫忙看看了
感謝

**Comment by zhuxb711** [comment]
Hi 经过我这里的测试，一切正常。但我有怀疑：如果您稍早前(几个版本前)启用的Win+E/默认文件夹 拦截功能，则可能出现该问题，早期版本的拦截使用的注册表文件不完善，可能导致路径有空格的那些文件夹无法正常激活。该问题已于后续版本中修复，但如果您是早期版本启用的拦截，则该修复不对您生效。

解决办法：关闭下面所有的开关，然后依次重新开启，新的注册表文件将随之更新
![image](https://user-images.githubusercontent.com/42038175/171087164-ba6fbd7d-112c-4193-b9ae-1e77f20f9eeb.png)

**Comment by peter1421** [comment]
已成功修正 謝謝
