### ISSUE TITLE
It is recommended to add a remarks function -- （建议添加备注功能）

### ISSUE THREAD

**Issue by calldream** [zhuxb711/RX-Explorer#402]
I am a programmer with poor English, so I use the remarks  function in windows. Although there is a star function in Rx, it can not meet my needs. Therefore, I expect developers to add such a function. Of course, I also hope that remarks function can be common with the remarks  function in Windows. Thank you! 

The description is shown in the following figure.

In addition, we have purchased it to support you. Thank you again!

我是一个英语很差的程序员，所以我利用了windows中的备注功能，现在RX中虽然有标星的功能，但是无法满足我的需求，所以期望开发者也添加这么一个功能，当然，也希望这个备注功能可以和windows自带的备注功能互相通用。谢谢！

描述如下图所示。

另外，已经购买以对你们的支持，再次感谢！

![image](https://user-images.githubusercontent.com/28900469/170943926-5bc51ee5-401a-4c20-9923-42d9d9a90cd6.png)

**Comment by zhuxb711** [comment]
抱歉，由于RX的列表控件尚不支持 动态定制 列头和列表，因此该功能不知道能否做得出来。由于这个备注的属性是非常用属性，因此也不适合默认情况下展示

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/171637698-9704aca9-e38e-4cab-b28f-ac539d1f3b9f.png)
下一个版本中会有这样的东西，但是仅限4个分类，不支持无限增加分类
