### ISSUE TITLE
除详细(Details)以外的任何显示模式都会导致卡死崩溃

### ISSUE THREAD

**Issue by EdwardASU** [zhuxb711/RX-Explorer#403]
[CrashDumps.zip](https://github.com/zhuxb711/RX-Explorer/files/8837409/CrashDumps.zip)
如题，最新更新版本 无论是手动对单独文件夹显示模式调整为中等图标（Medium Icons) 或是列表(Lists) 还是设置里的默认显示 都会导致卡死崩溃
已尝试初始化和卸载重新安装 均无用

**Comment by q8161525** [comment]
我同样发现了这个问题

**Comment by zhuxb711** [comment]
已临时撤回7.7.3版本，已安装的用户无法撤销。代码原因引起，修复版本将尽快发布。

**Comment by zhuxb711** [comment]
7.7.4已发布
