### ISSUE TITLE
Directory not displaying in RX-explorer，一个在内置文件管理器里可以显示的文件夹在RX里找不到

### ISSUE THREAD

**Issue by Eason51** [zhuxb711/RX-Explorer#404]
确定该文件夹没有被隐藏，在内置文件管理器里可以正常找到并打开。
![image](https://user-images.githubusercontent.com/66631204/172086002-3fb4a3cf-3252-4b33-b11e-7684578dbe7c.png)

但是在RX里找不到该文件夹：
![image](https://user-images.githubusercontent.com/66631204/172086035-76157a4c-0474-4cbb-af6f-054e25110628.png)

现在只能通过内置的文件管理器找到再通过rx打开
![image](https://user-images.githubusercontent.com/66631204/172086120-d3544384-c905-4e25-9316-578e8bb312c3.png)

**Comment by zhuxb711** [comment]
可能被意外添加了正常文件不应该有的属性
标记: System
具备System标记的文件或文件夹RX在默认情况下不会予以显示，因为通常来讲是系统必备文件才会有这种标记。若需要显示该标记的文件，需要前往设置-基本-显示隐藏文件（以及其子选项）中进行调整

**Comment by Eason51** [comment]
> 可能被意外添加了正常文件不应该有的属性 标记: System 具备System标记的文件或文件夹RX在默认情况下不会予以显示，因为通常来讲是系统必备文件才会有这种标记。若需要显示该标记的文件，需要前往设置-基本-显示隐藏文件（以及其子选项）中进行调整

确实是这个问题，谢谢

**Comment by Eason51** [comment]
> 可能被意外添加了正常文件不应该有的属性 标记: System 具备System标记的文件或文件夹RX在默认情况下不会予以显示，因为通常来讲是系统必备文件才会有这种标记。若需要显示该标记的文件，需要前往设置-基本-显示隐藏文件（以及其子选项）中进行调整

确实是这个问题，谢谢
