### ISSUE TITLE
在文件中显示 无法设置rx文件管理器

### ISSUE THREAD

**Issue by 2218675712** [zhuxb711/RX-Explorer#405]
![image](https://user-images.githubusercontent.com/38459269/172424950-6a711ccc-124f-4c82-b4ff-17d750c2c82f.png)
![image](https://user-images.githubusercontent.com/38459269/172425042-769394d2-f4b4-4348-b7c9-10fe5fea4c30.png)
这种打开还是默认的文件管理器
我参考了files设置默认文件管理器的代码
可以修改注册表如下来实现
```
HKEY_CLASSES_ROOT\Folder\shell\open\command
HKEY_CLASSES_ROOT\Folder\shell\explore\command
//设置成 
"C:\Users\Administrator\AppData\Local\RX-Explorer_Launch_Helper\SystemLaunchHelper.exe" "%L"
```

**Comment by zhuxb711** [comment]
你要不提交一个PR?当然如果你不太清楚RX是如何拦截的话我来做也行

**Comment by 2218675712** [comment]
麻烦您有时间整吧

**Comment by zhuxb711** [comment]
OK已经应用，但是现有用户可能需要重新启用与系统集成相关的开关
