### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Vampiremu** [zhuxb711/RX-Explorer#406]
是从其他平台知道这个资源管理器，通过uwp下载使用，不得不说对于win11的系统资源管理器真的好用太多，体验了几天非常满意。
但是不知道是不是BUG ，创建新的文档后，任务列表无法关闭，重新启动也无法关闭

**Comment by zhuxb711** [comment]
有没有Gif之类的可以直观的演示一下呢？任务列表本身是可以固定的，按右上角的 图钉按钮
