### ISSUE TITLE
[建议]这问题应该很好解决,请看下

### ISSUE THREAD

**Issue by justiony** [zhuxb711/RX-Explorer#41]
[版本]:5.4.2.0
[操作描述]多个页面开启后,关闭最后一个页面,会将RX全部退出,是否能控制?或者添加一个设置
 无法上传视频,请看下,是否能解决,
当然解决不了也没关系,
你们一群人围着会议室 是不是再骂我,哈哈哈

**Comment by zhuxb711** [comment]
哈哈哈见笑了，基本上只有我一个人在开发，一群人围着会议室？哪呢哪呢？不存在的23333
关闭最后一个标签页是会退出RX是有意为之，这是一个特性😁
