### ISSUE TITLE
背景

### ISSUE THREAD

**Issue by xuziangh** [zhuxb711/RX-Explorer#410]
为什么我无论怎么调背景都是一片，怎么调成又blur有毛玻璃的感觉

**Comment by xuziangh** [comment]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/103920679/177111076-1938f58f-5bf7-4b95-ab91-958814f43672.png">

**Comment by xuziangh** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/103920679/177111218-e161f443-964e-4494-a4ad-80cc234fac06.png">

**Comment by zhuxb711** [comment]
UWP应用的亚克力效果受Windows设置的影响。系统设置-个性化-颜色-透明效果->开启

**Comment by xuziangh** [comment]
为何我开启了依旧没效果？

**Comment by xuziangh** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/103920679/177311828-b78acb79-7c89-44a3-a15e-ae02f66d6a8f.png">

**Comment by xuziangh** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/103920679/177311880-735b364c-3b90-422d-8d36-e05a09a9b226.png">

**Comment by xuziangh** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/103920679/177311923-e1beac31-e29c-4bf3-b570-a7b6b078fad1.png">

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/177313973-772233e1-567b-464e-8461-f14a1b061968.png)

**Comment by zhuxb711** [comment]
不知道这种情况下RX的自绘亚克力效果是否有用，你可以尝试勾选这个东西，如果还没用用就是你系统的亚克力坏掉了
![image](https://user-images.githubusercontent.com/42038175/177314126-3c879ba5-8f1d-4623-ad4d-03d79874628f.png)

**Comment by xuziangh** [comment]
勾选这个选项之后背景直接纯黑了
<img width="542" alt="image" src="https://user-images.githubusercontent.com/103920679/177314685-481445bd-efed-4f57-9d01-cdcc2f1c0567.png">
<img width="949" alt="image" src="https://user-images.githubusercontent.com/103920679/177314756-6562d85e-4a40-42b6-b2c3-2229b68c4e80.png">

**Comment by xuziangh** [comment]
系统亚克力如果坏了又办法修复吗

**Comment by xuziangh** [comment]
![image](https://user-images.githubusercontent.com/103920679/177315653-53741126-1c1d-47b6-a724-d4b623ecd0fe.png)
这个方法也没有效果

**Comment by zhuxb711** [comment]
那就没办法了，应该是你系统的亚克力相关的组件坏掉了，建议重装或升级Win11

**Comment by zhuxb711** [comment]
也可以用自定义背景，自己找图
