### ISSUE TITLE
在图片查看器里，无法直接设置壁纸。

### ISSUE THREAD

**Issue by Hugh1997** [zhuxb711/RX-Explorer#412]
我的两台电脑都出现了这个问题。

还有文件右击，出现的更多选项，如果出现的方向朝上，是很难选中的。
![屏幕截图 2022-07-11 153951](https://user-images.githubusercontent.com/69393988/178277786-388aeb92-b1b9-48f2-8b99-7b2ea6d48740.png)

**Comment by zhuxb711** [comment]
无法直接设置壁纸？有没有任何错误提示？建议导出日志以供分析。子菜单弹出未对齐的问题是微软官方控件的Bug，暂时无法修复

**Comment by Hugh1997** [comment]
我觉得这个内置图片查看器挺方便的，所以就很想用这个功能。对图片直接右击设置壁纸是可以用的，只有在这个内置图片查看器里设置壁纸被拒绝了。

**Comment by zhuxb711** [comment]
我注意到微软文档提及：如果希望设置的文件名称与前一次设置背景时的图片名称完全相同则可能导致设置错误，因此RX已更正该问题，并且发现了其他一些阻碍设置FTP或MTP文件作为背景的问题，也一并修复了

**Comment by zhuxb711** [comment]
7.8.3已发布
