### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Starcloudsea** [zhuxb711/RX-Explorer#413]
有时在使用调色板时，程序会卡住，然后崩溃
事件管理器找到的错误：
第一个：
日志名称:          Application
来源:            Windows Error Reporting
日期:            2022/7/22 11:28:15
事件 ID:         1001
任务类别:          无
级别:            信息
关键字:           
用户:            LAPTOP-7S234TFS\stars
计算机:           LAPTOP-7S234TFS
描述:
故障存储段 1815707065325677682，类型 5
事件名称: MoAppCrash
响应: 不可用
Cab ID: 1289499224557697420

问题签名:
P1: 36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t
P2: praid:App
P3: 1.0.0.0
P4: 62d109aa
P5: Microsoft.UI.Xaml.dll
P6: 2.8.2207.12001
P7: bf9431af
P8: c000041d
P9: 00000000001834cf
P10: 

附加文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4d614038-a54a-4201-9016-c099ce3fc26f.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1a2a6c2b-a9a7-4cba-bdea-c7c8fe6d5874.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220720_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9216682d-b95c-4530-8529-5fff9bc88b42.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7df9959c-e71e-4839-a39b-247a2182b9f5.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.94a657d7-9d7b-430b-9154-06967dcfb0ec.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.49547642-10ce-4661-bbc7-d3b23cbaa59f.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.40025449-4e41-447e-8b03-b6d72ad415bf.tmp.xml
\\?\C:\Users\stars\AppData\Local\Temp\WER.06991710-1e40-4641-9986-a5b4d7f424b3.tmp.appcompat.txt
\\?\C:\Users\stars\AppData\Local\Temp\WER.815148fd-5fe9-4c6a-9887-9a1d6e84491b.tmp.WERDataCollectionStatus.txt

可在此处获取这些文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_36186RuoFan.USB__f28b616216a0562add2d7fe1c9a4c4ac1263e0_63ccc333_cab_e9e729be-12ea-4777-9778-263817caed58

分析符号: 
重新检查解决方案: 0
报告 ID: c8c89692-da07-4b8c-94fe-5466d0557f78
报告状态: 268435464
哈希存储段: aa8010efb4d42c014932aff4b4e76c72nCab GUID: 0e4faa11-f6a6-4ead-81e5-38b671e7398c
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-22T03:28:15.2866563Z" />
    <EventRecordID>6197</EventRecordID>
    <Correlation />
    <Execution ProcessID="1084" ThreadID="22600" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-7S234TFS</Computer>
    <Security UserID="S-1-5-21-3396957189-3590652009-1404650094-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">1815707065325677682</Data>
    <Data Name="BucketType">5</Data>
    <Data Name="EventName">MoAppCrash</Data>
    <Data Name="Response">不可用</Data>
    <Data Name="CabId">1289499224557697420</Data>
    <Data Name="P1">36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t</Data>
    <Data Name="P2">praid:App</Data>
    <Data Name="P3">1.0.0.0</Data>
    <Data Name="P4">62d109aa</Data>
    <Data Name="P5">Microsoft.UI.Xaml.dll</Data>
    <Data Name="P6">2.8.2207.12001</Data>
    <Data Name="P7">bf9431af</Data>
    <Data Name="P8">c000041d</Data>
    <Data Name="P9">00000000001834cf</Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4d614038-a54a-4201-9016-c099ce3fc26f.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1a2a6c2b-a9a7-4cba-bdea-c7c8fe6d5874.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220720_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9216682d-b95c-4530-8529-5fff9bc88b42.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7df9959c-e71e-4839-a39b-247a2182b9f5.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.94a657d7-9d7b-430b-9154-06967dcfb0ec.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.49547642-10ce-4661-bbc7-d3b23cbaa59f.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.40025449-4e41-447e-8b03-b6d72ad415bf.tmp.xml
\\?\C:\Users\stars\AppData\Local\Temp\WER.06991710-1e40-4641-9986-a5b4d7f424b3.tmp.appcompat.txt
\\?\C:\Users\stars\AppData\Local\Temp\WER.815148fd-5fe9-4c6a-9887-9a1d6e84491b.tmp.WERDataCollectionStatus.txt</Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_36186RuoFan.USB__f28b616216a0562add2d7fe1c9a4c4ac1263e0_63ccc333_cab_e9e729be-12ea-4777-9778-263817caed58</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">c8c89692-da07-4b8c-94fe-5466d0557f78</Data>
    <Data Name="ReportStatus">268435464</Data>
    <Data Name="HashedBucket">aa8010efb4d42c014932aff4b4e76c72</Data>
    <Data Name="CabGuid">0e4faa11-f6a6-4ead-81e5-38b671e7398c</Data>
  </EventData>
</Event>
第二个：
日志名称:          Application
来源:            Application Error
日期:            2022/7/22 11:28:01
事件 ID:         1000
任务类别:          应用程序崩溃事件
级别:            错误
关键字:           
用户:            LAPTOP-7S234TFS\stars
计算机:           LAPTOP-7S234TFS
描述:
错误应用程序名称: RX_Explorer.exe，版本: 1.0.0.0，时间戳: 0x62d109aa
错误模块名称: Microsoft.UI.Xaml.dll，版本: 2.8.2207.12001，时间戳: 0xbf9431af
异常代码: 0xc000041d
错误偏移量: 0x00000000001834cf
错误进程 ID: 0x0x11EC
错误应用程序启动时间: 0x0x1D89D7A84BE8FD7
错误应用程序路径: C:\Program Files\WindowsApps\36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t\RX_Explorer.exe
错误模块路径: C:\Program Files\WindowsApps\36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t\Microsoft.UI.Xaml.dll
报告 ID: c8c89692-da07-4b8c-94fe-5466d0557f78
错误程序包全名: 36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t
错误程序包相对应用程序 ID: App
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-07-22T03:28:01.0378953Z" />
    <EventRecordID>6196</EventRecordID>
    <Correlation />
    <Execution ProcessID="1084" ThreadID="22600" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-7S234TFS</Computer>
    <Security UserID="S-1-5-21-3396957189-3590652009-1404650094-1001" />
  </System>
  <EventData>
    <Data Name="AppName">RX_Explorer.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">62d109aa</Data>
    <Data Name="ModuleName">Microsoft.UI.Xaml.dll</Data>
    <Data Name="ModuleVersion">2.8.2207.12001</Data>
    <Data Name="ModuleTimeStamp">bf9431af</Data>
    <Data Name="ExceptionCode">c000041d</Data>
    <Data Name="FaultingOffset">00000000001834cf</Data>
    <Data Name="ProcessId">0x11ec</Data>
    <Data Name="ProcessCreationTime">0x1d89d7a84be8fd7</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t\RX_Explorer.exe</Data>
    <Data Name="ModulePath">C:\Program Files\WindowsApps\36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t\Microsoft.UI.Xaml.dll</Data>
    <Data Name="IntegratorReportId">c8c89692-da07-4b8c-94fe-5466d0557f78</Data>
    <Data Name="PackageFullName">36186RuoFan.USB_7.8.3.0_x64__q3e6crc0w375t</Data>
    <Data Name="PackageRelativeAppId">App</Data>
  </EventData>
</Event>

**Comment by zhuxb711** [comment]
从提供的信息来看似乎是微软的控件Bug，来源于Microsoft.UI.Xaml的异常

**Comment by Starcloudsea** [comment]
哦，好的
