### ISSUE TITLE
[小建议]右键-属性-安全选项卡

### ISSUE THREAD

**Issue by chihy525** [zhuxb711/RX-Explorer#416]
如果可以像系统自带的文件管理器一样，修改文件的权限就更好了。

**Comment by zhuxb711** [comment]
仅支持查看文件权限，修改文件权限涉及 高级 Windows 安全 建议您使用系统文件管理器修改，许多权限修改操作需要权限提升，内置Windows资源管理器可以免UAC弹框提升权限，第三方程序无法做到

**Comment by chihy525** [comment]
> 仅支持查看文件权限，修改文件权限涉及 高级 Windows 安全 建议您使用系统文件管理器修改，许多权限修改操作需要权限提升，内置Windows资源管理器可以免UAC弹框提升权限，第三方程序无法做到

好的，谢谢
