### ISSUE TITLE
bug，右键文件所在目录的问题

### ISSUE THREAD

**Issue by 1665169869** [zhuxb711/RX-Explorer#417]
对某个快捷方式[右键]-[打开文件所在目录]后，rx文件资源管理器虽然被打开，但不会定位相对文件位置
经过搜索，[打开文件所在目录]大概率是调用了windows api的SHOpenFolderAndSelectItems函数，该函数的效果是使用资源管理器打开一个文件夹并选中指定文件,如果文件夹已经被打开就直接选中。
但在rx资源管理器里，只会打开相应文件夹不会选中这个文件

**Comment by zhuxb711** [comment]
RX是开源的，明显不是调用SH那个函数，同一个进程内你调用它干什么，而且SH是指示Windows资源管理器打开的，对于RX自己内部打开文件夹的情况，只需要参数传递就行了。

你可以看这一部分的源代码

**Comment by zhuxb711** [comment]
如果你说的是 在Windows资源管理器里面 点击 打开文件所在位置 然后调用RX的情况 这就是另外一回事了

**Comment by 1665169869** [comment]
> 如果你说的是 在Windows资源管理器里面 点击 打开文件所在位置 然后调用RX的情况 这就是另外一回事了

对的，我的意思就是这个。我在RX设置了调用windows资源管理器默认调用RX，但执行windows api的SHOpenFolderAndSelectItems函数只会打开该文件所在的文件夹并不会选中该文件

**Comment by zhuxb711** [comment]
打开文件所在目录 传入的路径仅为 该文件所在目录，并不包括文件名称或者完整路径等信息。如果您有其他方式可以获得有关于这一块信息的方式，则该问题可以被改进，否则将继续维持现状。目前RX使用 %L 的注册表参数启动应用程序
