### ISSUE TITLE
Seer is not working

### ISSUE THREAD

**Issue by alient12** [zhuxb711/RX-Explorer#419]
[Seer](http://1218.io) quick look software is not supported. please add this feature.

**Comment by zhuxb711** [comment]
I will consider that and have already made contact with the developer of Seer.

**Comment by alient12** [comment]
Hi, thank you for adding this feature so fast. But unfortunately it's not working for me.

Edition: Windows 11 Home
Version: 21H2
OS Build: 22000.856

RX-Explorer:
Version: 7.9.1.0

Seer Pro:
Version: 2.8.5.0 UWP (Latest Microsoft store version)

**Comment by zhuxb711** [comment]
According to the developer of Seer. Seer in Microsoft Store is not supported to be operated by 3rd party program currently.

You should use the Seer with installer downloaded from its website for the time being. (A new version of Seer in MS-Store is under the review which will add support for 3rd party program)

**Comment by zhuxb711** [comment]
Just for notifications.
The Seer in Microsoft Store is also support for 3rd party file explorer now.
