### ISSUE TITLE
bug, 新建快捷方式后程序会崩溃重启

### ISSUE THREAD

**Issue by howdareyou** [zhuxb711/RX-Explorer#421]
系统：Windows11
版本：试用版最新版
问题：新建快捷方式后界面会卡住，随后出现logo界面，然后才能回到原来的目录

**Comment by zhuxb711** [comment]
请提供您在创建快捷方式并导致崩溃时输入了哪些内容，以供更好的调查该问题。最好是有必现此问题的方法

**Comment by howdareyou** [comment]
我在创建快捷方式时输入了备注，备注是中英混合的。文件路径没有中文。至于必现此问题的方法，我连续三次创建快捷方式都会出现这个问题，前两次有输入备注，第三次没有

**Comment by zhuxb711** [comment]
本地测试的结果是未见异常，但是创建快捷方式完成之后会错误的弹出 无法访问该文件的 提示框
