### ISSUE TITLE
[bug]按住shift多选文件结果与预期不符合

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#422]
选中最开头的"\[Anytype\](https%3A%2F%2Fanytype.io%2Fen)",按住shift,选中"\[VMware Workstation Pro\](https%3A%2F%2Fwww.vmware.com%2Fcn%2Fproducts%2Fworkstation-pro%2Fworkstation-pro-evaluation.html)",多选的结果不是这两个之间的所有文件

这是录屏

<https://www.aliyundrive.com/s/yzFmHS7HxLq>

**Comment by zhuxb711** [comment]
这个问题是微软控件ListView的Bug，历史悠久了，没有人修复，也没办法自定义这个选择逻辑，建议你使用框选来选择文件

**Comment by zhuxb711** [comment]
一个可行的临时方案是，Shift来多选文件时，第一个点击和最后一个点击的文件必须点在文件名上，可以暂时解决这个问题，如果你多选时点击在没有文字的空白上，则会发生这个问题
