### ISSUE TITLE
从rx中选中文件拖入外部程序出错[bug]

### ISSUE THREAD

**Issue by GrahLnn** [zhuxb711/RX-Explorer#424]
选中多个文件拖入外部程序时只会有一个被移动
被移动的文件显示0byte

![image](https://user-images.githubusercontent.com/67181515/188419004-4b84dd05-16a7-4688-aed4-4ee5598e20e1.png)

app version: 7.9.0.0
windows version: win11

[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/9488702/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
这可能是潜在的一个bug，我会尝试修复
