### ISSUE TITLE
在RX中使用Delete键删除文件会导致程序崩溃

### ISSUE THREAD

**Issue by GrahLnn** [zhuxb711/RX-Explorer#425]
在RX中使用Delete键删除文件然后卡住，直接崩溃

version: 7.9.0.0
sys: win11

[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/9523718/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
Uwp框架崩溃，除微软外无法修复，但微软已停更Uwp
