### ISSUE TITLE
不知是否支援 png檔預覽

### ISSUE THREAD

**Issue by peter1421** [zhuxb711/RX-Explorer#427]
目前似乎只能顯示jpg預覽圖

還是已經有地方開放設定png預覽了?
![image](https://user-images.githubusercontent.com/51041311/190898695-8004402d-e887-4e52-bfa9-29696ac007df.png)

**Comment by zhuxb711** [comment]
预览需要Windows生成缩略图缓存，你可以多刷新几遍来要求Windows缓存即可，或者也可以下载Seer(付费)或Quicklook(免费)来预览各种文件
