### ISSUE TITLE
[Feature Request] add thumbnail for text files

### ISSUE THREAD

**Issue by alient12** [zhuxb711/RX-Explorer#428]
Hi, thank you for your great works and being so responsive. I've found a piece of C# code for making txt files preview on Windows Explorer. This is the [link](https://www.codeproject.com/Articles/563114/NET-Shell-Extensions-Shell-Thumbnail-Handlers)
I think it would be great if you add this optional feature for .txt, .cpp, .py, etc. files on RX-Explorer.

![image](https://www.codeproject.com/KB/shell/563114/txtfilethumbnails.jpg)

**Comment by zhuxb711** [comment]
You should use Seer or Quicklook to preview those files. You could find the download link in Settings-Advance

Let the professional program satisfy your needs.

**Comment by alient12** [comment]
I have Seer Pro, I mean icon preview, just shared my suggestion.

**Comment by zhuxb711** [comment]
Sorry about that. Uwp application do not support System.Drawing.Graphics. Not all the C# lib is supported by Uwp, so we could not make it work as expected.
