### ISSUE TITLE
Release下载的安装文件无法安装

### ISSUE THREAD

**Issue by juzq** [zhuxb711/RX-Explorer#429]
步骤：
1. 解压缩
2. 安装证书
3. 双击msix，点击安装
4. 提示：此应用包不支持通过应用程序安装，因为它使用了某些受限制的功能。

![image](https://user-images.githubusercontent.com/12960773/194692383-63689656-d142-4060-89d4-970e3435763b.png)

* Release版本：7.9.2.0
* Windows版本：Windows 10 1909

**Comment by zhuxb711** [comment]
Hi，安装的话有两个问题。

1. 当前版本的RX文件管理器已不再支持Win10 2004版本以下的系统了，如果您需要安装该版本，则需要首先升级系统版本
2. Release版本不再支持直接双击msix包安装，因为RX已经使用特殊的 禁用 文件系统/注册表虚拟化 的权限，以最大化所有路径下的可用性（虚拟化会导致通过RX访问比如系统临时文件路径时，会被隐式重定向至包内路径，所有的修改都会无效化），因此您必须右键安装文件下的Install.ps1，选择 使用Powershell运行 ，随后Powershell会自动安装（包括证书）

**Comment by zhuxb711** [comment]
最后一个支持2004以下的系统版本是7.2.3版本，不建议您安装该版本，因为可能存在潜在的问题或Bug，同时7.2.3版本的外观与最新版本已经有非常大的差别
