### ISSUE TITLE
Full Version Features

### ISSUE THREAD

**Issue by Abeiis** [zhuxb711/RX-Explorer#43]
Dear Developer,
I purchased the utility so I can use any hidden features like generating my own toolbar or have dual drives windows one can manage files between them, and right-click menus with options that are similar to Windows File Manager and more; only to find none of that exists - Please advise, Thanks!
Regards,
Abe

**Comment by zhuxb711** [comment]
We are adding the right-click menu item of the Windows File Manager to RX Explorer. It is currently under development and will be launched in a future version.

Best regards,
Ruofan

**Comment by zhuxb711** [comment]
The function of getting the Windows Explorer right-click menu will be launched in the next version, which may not be stable yet, but at least it is available.
