### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by youtehub** [zhuxb711/RX-Explorer#430]
希望能实现拖拽功能，就是像浏览器一样，单独拖拽一个标签页的时候，产生一个新的RX文件管理器窗口，目前只能通过点击桌面图标的形式重新开启一个新页面。
B站：https://www.bilibili.com/video/BV12e4y1v7B7/
youtube：https://www.youtube.com/watch?v=w2RafAZynuI

**Comment by zhuxb711** [comment]
我就这么解释吧，原来是支持的，后来因为可靠性问题以及微软自己各种奇奇怪怪的Bug所以后来拿掉了这个功能，我只能说看看有没有转圜的机会，能就可以加回来，不能，那还是得可靠性优先

**Comment by zhuxb711** [comment]
这个功能应该会在下一个版本中重新加入进来

**Comment by zhuxb711** [comment]
此问题将于8.0.0中修复，微软商店正在审核
