### ISSUE TITLE
[问题]使用空格调用quicklook预览文件,发现无法使用esc退出

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#431]
版本:应用商店上面的最新版

**Comment by zhuxb711** [comment]
请描述得清楚一些

**Comment by a15355447898a** [comment]
这是录制的视频
链接: https://pan.baidu.com/s/1mMF3PLfzP9t2xuOQY8HPrA?pwd=dgm9 提取码: dgm9 

前半段是在系统自带的文件管理器中使用quicklook,可以正常的使用esc退出
后半段是在rx文件管理器中使用quicklook,发现无法使用esc退出

**Comment by zhuxb711** [comment]
感谢您的详细报告。

我原来以为Seer或者Quicklook这一类预览软件的窗口调用之后都会夺取窗口焦点的，今天我测试了发现是不会夺取焦点的，换句话说如果用户不手动点击一次Seer或者Quicklook的弹窗，则Esc的输入仍然会定向至RX文件管理器，因此RX文件管理器仍然有责任关闭它们(如果已经呈现预览窗口)。

我已修改代码以确保如果用户在RX文件管理器中按下Esc时检测到Seer或者Quicklook窗口已弹出，则帮助发送关闭窗口的命令至对应的预览软件 (仅已在RX文件管理器的设置中启用Quicklook或Seer预览的情况下)。

**Comment by zhuxb711** [comment]
此问题将于8.0.0中修复，微软商店正在审核
