### ISSUE TITLE
文件夹缩略图加载错误

### ISSUE THREAD

**Issue by Eason51** [zhuxb711/RX-Explorer#432]
![image](https://user-images.githubusercontent.com/66631204/196044417-2c7b8cd6-c999-4396-953c-5e3b7529543f.png)
![image](https://user-images.githubusercontent.com/66631204/196044430-03d0827c-080f-46dc-925c-dffadf37fc1d.png)

这个文件夹的缩略图在内置资源管理器是正常加载的，其他所有文件夹的缩略图都正常，只有这个加载失败

**Comment by zhuxb711** [comment]
建议您刷新该文件夹

**Comment by Eason51** [comment]
> 建议您刷新该文件夹

谢谢，我已经尝试过在这个文件夹里还有父文件夹里刷新都没有用

**Comment by zhuxb711** [comment]
这个问题应该是系统提供的缩略图就是这样的，RX文件夹加载失败后的默认缩略图不是这个样子，说明是正常加载没有问题，但是RX不可能验证系统给的缩略图是否正确，因此只能是系统提供什么缩略图就提供什么缩略图
