### ISSUE TITLE
[问题]设置安全域密码的时候崩溃

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#434]
版本:最新版
录屏与报错日记
链接: https://pan.baidu.com/s/1aWATh1OkapU5zpcP8P0b9Q?pwd=rt2x 提取码: rt2x

**Comment by a15355447898a** [comment]
刚刚试了一下,没有设置windows hello也会导致崩溃

**Comment by zhuxb711** [comment]
光速issue是吧，这刚过审2分钟

**Comment by zhuxb711** [comment]
8.0.0正在撤回，8.0.1在路上了，这个问题出自保存加密密钥长度的设置时设置容器不接受枚举类型的数据
![image](https://user-images.githubusercontent.com/42038175/197226226-3855fc8b-b69a-4885-91d9-d53a4ff8cbf4.png)
