### ISSUE TITLE
8.0.1新版安全域未识别之前加密的SLE文件

### ISSUE THREAD

**Issue by Gokr-ble** [zhuxb711/RX-Explorer#435]
问题描述：在7.x版本安全域中存放的SLE文件（SLE1.5版本），当程序自动升级为8.0.1后，再次打开安全域，显示为空，此时安全与目录下仍存在先前的加密文件，但未能正确识别，也无法打开、解密或导出；偶尔出现输入安全域密码后不显示背景图案，几秒钟后闪退；
版本：8.0.1

备注：由于隐私限制，在安全域中的操作无法截图或录屏，故只能文字描述；导出的错误报告见附件。
[Export_All_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/9843936/Export_All_Error_Log.txt)

**Comment by zhuxb711** [comment]
能否分享一些文件以供参考，在我这边无法复现这个问题，我使用7.9.7加密的SLE 1.5版本的文件，然后让8.0.1版本加载，仍然可以正常进行解密操作。

**Comment by Gokr-ble** [comment]
您好，不好意思原始文件比较敏感所以不太好发，不过我又尝试在7.9.7和8.0.1用相同的密码创建安全域，在7.9.7中导入一张图片（如下）进行加密，再将.sle文件放入8.0.1的SecureFolder中，此时可以识别，但无法打开或解密；
ps：以下为原文件和加密文件
[plain&cipher.zip](https://github.com/zhuxb711/RX-Explorer/files/9844422/plain.cipher.zip)

**Comment by zhuxb711** [comment]
能否共享关于这个文件的密码？缺少密码的话就算是我也无法正确解密

**Comment by Gokr-ble** [comment]
上面的图片用例有些问题，抱歉请忽略。后续我又在同一台设备上测试了一个视频，用旧版加密再升级，能识别但无法打开，提示“错误：视频类型不受支持或文件路径无效”；
链接：https://pan.baidu.com/s/1NJ8V0ojStXS3ogzCBQwa4w?pwd=1234 
提取码：1234
加密文件时的密码涉及个人信息，另发您的邮箱。

**Comment by zhuxb711** [comment]
行，但没有邮箱收到你的密码

**Comment by Gokr-ble** [comment]
请问是zrfcfgs@outlook.com吗，这个已发送

**Comment by zhuxb711** [comment]
该问题将于8.0.2版本中修复，目前正在微软商店审核，谢谢
