### ISSUE TITLE
回收站按时间排序显示下，可否不要强行把目录排到后面

### ISSUE THREAD

**Issue by frostime** [zhuxb711/RX-Explorer#438]
目前的的 Rx 浏览器的回收站界面，如果选择按照“删除时间”来排序，会强行把文件和目录分开排序，导致明明是刚刚删除的目录却排到很后面才能找到的情况。

希望可以更改这个设置。

![Snipaste_2022-11-07_15-07-24](https://user-images.githubusercontent.com/27268127/200246446-90e8b9a5-4084-48b6-8bb8-f9c8eb21e0fc.png)

**Comment by zhuxb711** [comment]
8.0.6中已解决该问题
