### ISSUE TITLE
onedrive 的文件夹不显示

### ISSUE THREAD

**Issue by lancerXXXX** [zhuxb711/RX-Explorer#44]
![image](https://user-images.githubusercontent.com/42160297/95274574-c8080a80-0878-11eb-8cd9-3aff1f4aba66.png)
  这是用系统文件夹打开
放的是我的两个账号的OneDrive

![image](https://user-images.githubusercontent.com/42160297/95274643-f71e7c00-0878-11eb-86f5-05834b2477dc.png)
这是用rx文件管理器打开->显示不到OneDrive的文件夹

**Comment by zhuxb711** [comment]
若RX提示文件夹内为空，则可能是由于该文件夹目录下无法访问，具体的双OneDrive暂时还没有测试，但是似乎单个OneDrive是可以正常使用的

**Comment by zhuxb711** [comment]
Hi，我已深入调查并查明这个一个BUG。

您无法看到OneDrive的文件夹是由于RX过滤了“重解析点”的文件类型，而OneDrive本身正是重解析点的文件夹（NTFS特性）。在现在的版本中您只能通过主界面上的“”文件夹和库“区域中的OneDrive来进入（因为这里使用了不同的文件夹解析技术），在某些情况下，RX未能自动确定OneDrive的位置，故导致无法自行进入OneDrive（如位置更改）。

RX将在下一个版本中取消针对重解析点的过滤，并重新设计了OneDrive路径的获取机制，请您耐心等待下一个版本的修复，感谢您的Issue。

**Comment by zhuxb711** [comment]
该问题应当已于5.5.6版本中修复，请确认，我将Close这个Issue
