### ISSUE TITLE
新建文件夹时有些 bug

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#440]
新建文件夹时出现 bug，能稳定复现。

1. 新建文件夹时出现两个一样的文件夹（稳定复现，条件未知，但是至少在我的系统“音乐”文件夹下可以）
![1](https://user-images.githubusercontent.com/64201424/208271022-f81a33fe-6d6c-4bd9-818a-251633cc70d1.gif)

2. 新建文件夹时连按两下回车，会提示错误
![2](https://user-images.githubusercontent.com/64201424/208271163-1724a55b-1bc5-46c4-8783-6b1fd89558fc.gif)

以上 bug 对于文件也成立。

**Comment by zhuxb711** [comment]
我这边无法复现你的问题

**Comment by g-mph** [comment]
> 我这边无法复现你的问题

UWP 很玄学的，bug 又多，我估计又是“微软控件”的问题

建议趁早摆脱 UWP

**Comment by zhuxb711** [comment]
关于问题2，连按两下是因为重命名完成需要时间，第一次按下Enter时启动重命名操作，第二次按下时重命名可能已完成，但UI尚未更新(需要一个短暂的时间)，进而导致使用重命名前的路径尝试访问，从而弹出不存在的提示。
