### ISSUE TITLE
建议将删除文件时的速度单位改为 项/s

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#441]
建议将删除文件时的速度单位改为 项/s，这样应该会更科学一点

**Comment by zhuxb711** [comment]
删除文件时的进度仅在按下Shift永久删除时才会提供，具体微软为什么要这么设计我也不清楚。由速度更改为项/秒不是一个小型更改，目前估计很难实施，尤其是我现在全部都在关注迁移WinAppSdk的事情上

**Comment by g-mph** [comment]
好吧，期待更新

**Comment by zhuxb711** [comment]
但是我会研究一个替代方案，具体就是即使Shell组件不提供进度，RX文件管理器也会尝试通过每删除一个文件来推动进度条前进（如：删除5个文件，每删除1个，进度条推进20%）

**Comment by g-mph** [comment]
这些都是 UWP 类应用的限制吗？如果是 Win32 应用会不会解决问题？
&nbsp;


淼畔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月11日(星期三) 中午12:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhuxb711/RX-Explorer] 建议将删除文件时的速度单位改为 项/s (Issue #441)





 
但是我会研究一个替代方案，具体就是即使Shell组件不提供进度，RX文件管理器也会尝试通过每删除一个文件来推动进度条前进（如：删除5个文件，每删除1个，进度条推进20%）

**Comment by zhuxb711** [comment]
Uwp版现在已经用的部分Win32技术（通过某些魔法），所以这不是切换WinAppSdk就可以解决的问题
