### ISSUE TITLE
快速访问bug

### ISSUE THREAD

**Issue by MFuching** [zhuxb711/RX-Explorer#442]
1.添加文件夹到快速访问后，每次启动管理器后第一次点击快速访问，里面的所有文件夹都会出现两份，而且顺序是乱的。
2.单击展开或收起快速访问时，有概率被视为双击，即展开立马收起或者收起立马展开，一般是在点击动作较快时出现，这点我可以确认不是我手快点了两次，已经经过反复试验。

另外，能不能，像系统管理器一样，记住快速访问展开与否，不然每次打开管理器都要先点一下展开。

**Comment by zhuxb711** [comment]
启动时不自动展开快速访问的原因是防止快速访问内存在过多文件时影响启动时的性能。其他提到的Bug尚未复现或有待检查
