### ISSUE TITLE
进入磁盘或文件夹等待时间过长

### ISSUE THREAD

**Issue by wow1063490934** [zhuxb711/RX-Explorer#443]
进入磁盘或文件夹等待时间过长，进度条一直在加载中，上面显示“正在等待响应，辅助进程正忙，无法响应新的请求，请耐心等待”。如何解决？

**Comment by hitchao** [comment]
想问一下，为啥安装包这么大……666MB

**Comment by zhuxb711** [comment]
> 想问一下，为啥安装包这么大……666MB

因为666MB包含两个架构的包，一个是ARM64一个是X64，安装时自动根据架构安装其中一个。RX中除主要的程序外，还有一个需要使用UI框架的调用转发程序，这个程序是为了在用户忽略与系统组件集成功能中的警告，在开启其功能后直接卸载RX之后的备用方案，它可以确保侦测到RX已被卸载并且提示是否自动还原例如Win+E拦截等功能

**Comment by hitchao** [comment]
> > 想问一下，为啥安装包这么大……666MB
> 
> 因为666MB包含两个架构的包，一个是ARM64一个是X64，安装时自动根据架构安装其中一个。RX中除主要的程序外，还有一个需要使用UI框架的调用转发程序，这个程序是为了在用户忽略与系统组件集成功能中的警告，在开启其功能后直接卸载RX之后的备用方案，它可以确保侦测到RX已被卸载并且提示是否自动还原例如Win+E拦截等功能

感谢解答！

**Comment by liangddyy** [comment]
如何才能安装 Windows App Sdk内测版本 呢？

**Comment by zhuxb711** [comment]
> 如何才能安装 Windows App Sdk内测版本 呢？
> 
> 

加Q群767504997
