### ISSUE TITLE
WAS版本的RX文件管理器会把网络驱动器识别成系统盘

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#448]
在UWP版本中网络驱动器被正常识别

![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/52000102-fb3f-4db7-8a1c-be5ee00a5962)

但是在WAS版本中,网络驱动器被识别成系统盘

![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/16f0d0b7-1140-4619-85ff-9182defc3f13)

**Comment by zhuxb711** [comment]
此问题将于WAS 1.3.2中解决
