### ISSUE TITLE
打不开exe应用程序

### ISSUE THREAD

**Issue by forpleuvoir** [zhuxb711/RX-Explorer#45]
在默认资源管理器能打开
RX打开会闪退

**Comment by zhuxb711** [comment]
请使用Gif演示一下您是如何触发该问题，谢谢

**Comment by forpleuvoir** [comment]
> 请使用Gif演示一下您是如何触发该问题，谢谢


![Desktop 2020 10 10 - 10 25 06 01 mp4_20201010_103441](https://user-images.githubusercontent.com/38557552/95643820-44eaec80-0ae4-11eb-92fc-fc0ada4e337f.gif)
![Desktop 2020 10 10 - 10 25 06 01 mp4_20201010_103529](https://user-images.githubusercontent.com/38557552/95643840-6e0b7d00-0ae4-11eb-915e-05391476742a.gif)
![Desktop 2020 10 10 - 10 25 06 01 mp4_20201010_103547](https://user-images.githubusercontent.com/38557552/95643842-72379a80-0ae4-11eb-9cb8-78a0066b9a14.gif)

**Comment by forpleuvoir** [comment]
> 请使用Gif演示一下您是如何触发该问题，谢谢

![Uploading Desktop 2020.10.10 - 10.25.06.01.mp4_20201010_103441.gif…]()

**Comment by zhuxb711** [comment]
选择使用管理员权限允许也不行嘛？这些exe文件有什么特别的设置嘛？

**Comment by zhuxb711** [comment]
Hi，我已进行本地测试，现发现以下问题：

1. 对于单一文件，RX的启动机制并无问题
2. 对于游戏类型的exe文件，则可能存在问题，这与游戏自身的机制有关。一般而言，较老或者不规范的游戏更加有可能存在问题。该问题的根源取决于游戏是否依赖于WorkingDirectory属性，默认情况下RX并不会设置WorkingDirectory属性，根据[微软官方文档](https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.processstartinfo.workingdirectory?redirectedfrom=MSDN&view=netframework-4.7.2)，若不设置WorkingDirectory，则默认为%Systemroot%\system32

由此对于游戏而言，若其依赖于WorkingDirectory，它期望这个属性能够提供其所在文件夹中资源的位置，但实际上WorkingDirectory并未以其预料的那样提供正确的路径，因此游戏将无法寻找到对应的资源文件等，于是无法正确运行。

该问题将于下一版本中修复

**Comment by forpleuvoir** [comment]
> Hi，我已进行本地测试，现发现以下问题：
> 
> 1. 对于单一文件，RX的启动机制并无问题
> 2. 对于游戏类型的exe文件，则可能存在问题，这与游戏自身的机制有关。一般而言，较老或者不规范的游戏更加有可能存在问题。该问题的根源取决于游戏是否依赖于WorkingDirectory属性，默认情况下RX并不会设置WorkingDirectory属性，根据[微软官方文档](https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.processstartinfo.workingdirectory?redirectedfrom=MSDN&view=netframework-4.7.2)，若不设置WorkingDirectory，则默认为%Systemroot%\system32
> 
> 由此对于游戏而言，若其依赖于WorkingDirectory，它期望这个属性能够提供其所在文件夹中资源的位置，但实际上WorkingDirectory并未以其预料的那样提供正确的路径，因此游戏将无法寻找到对应的资源文件等，于是无法正确运行。
> 
> 该问题将于下一版本中修复

目前发现打不开的软件 geek  dism++

**Comment by zhuxb711** [comment]
版本5.4.9应当已经解决此问题，请确认

**Comment by forpleuvoir** [comment]
> 版本5.4.9应当已经解决此问题，请确认

游戏确实能打开了 但是那两个软件还是打不开

**Comment by zhuxb711** [comment]
这个具体情况就不太清楚了，该设置的也都设置好了

**Comment by zhuxb711** [comment]
期间发现了一个阻止EXE文件运行的BUG，应当已经全部可用了。
