### ISSUE TITLE
右键刷新时候图片疑似乱码

### ISSUE THREAD

**Issue by MemorXuxu** [zhuxb711/RX-Explorer#451]
![image](https://github.com/zhuxb711/RX-Explorer/assets/97904901/10797ad5-6698-490a-b88e-908d293eca78)
字体默认使用Segoe UI

**Comment by zhuxb711** [comment]
新版本框架在Win10系统上的Bug
方法1：升级Win11
方法2：[点击这里](https://aka.ms/SegoeFluentIcons) 下载并安装Segoe Fluent Icons字体
