### ISSUE TITLE
RX中无法复制文件到标签内

### ISSUE THREAD

**Issue by Frank18040131238** [zhuxb711/RX-Explorer#452]
![image](https://github.com/zhuxb711/RX-Explorer/assets/136333876/eaab0f07-3a24-47f7-9fc6-99b009ea94f3)

**Comment by zhuxb711** [comment]
这是一个bug，但本质原因是未能拦截通过地址栏拖拽进入的文件，快速访问和标签文件夹不允许直接文件操作
