### ISSUE TITLE
希望提供删除标签的功能

### ISSUE THREAD

**Issue by Frank18040131238** [zhuxb711/RX-Explorer#453]
删掉4个标签或再添加，标签bug太多啦

**Comment by zhuxb711** [comment]
先问有没有，不要轻易下结论说没有这个功能
![image](https://github.com/zhuxb711/RX-Explorer/assets/42038175/3c0b04f4-bc7f-4226-9065-9b9b7dc5859c)

**Comment by Frank18040131238** [comment]
emmmm.....是试用版没有吗？


| |
xhm18040131238
|
|
***@***.***
|
在2023年6月12日 ***@***.***> 写道：

先问有没有，不要轻易下结论说没有这个功能
