### ISSUE TITLE
[BUG]侧边栏的分区顺序混乱

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#454]
![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/20a8a60e-4ed3-4385-b1ac-d17cb252769b)
![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/349207b4-7264-4cad-9987-b75bdc0ebe20)
![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/5c9978df-a2fc-426b-95b7-e851fd047208)

有时启动的时候正常,有时不正常
不知道怎么复现

**Comment by zhuxb711** [comment]
此问题将在下个版本中通过对驱动器盘符排序解决

**Comment by a15355447898a** [comment]
在was版本,1.3.7.0上面仍然存在这个问题

![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/1ad1e75d-9031-4a8b-9a33-51a7aa9c203c)


![image](https://github.com/zhuxb711/RX-Explorer/assets/62456287/e2e95697-8f6e-496a-bf7c-d13090400501)

**Comment by zhuxb711** [comment]
我会继续调查该问题
