### ISSUE TITLE
在微软商店已购买RX文件管理器但无法兑换激活码

### ISSUE THREAD

**Issue by ZnFeSnH** [zhuxb711/RX-Explorer#455]
<img width="1280" alt="屏幕截图 2023-07-22 021221" src="https://github.com/zhuxb711/RX-Explorer/assets/76638184/6f1cf5e6-8c04-4842-b429-930532c084ba">

**Comment by 3588352205SQLB** [comment]
版本是RX文件管理器（UWP）

**Comment by zhuxb711** [comment]
可以从设置中导出日志以供参考吗？
