### ISSUE TITLE
为什么我右键某些图片和视频总是崩掉啊

### ISSUE THREAD

**Issue by g-mph** [zhuxb711/RX-Explorer#457]
`
******************************************************************************************************
* Log Name: Log_1.4.5.0_a3574467ac064a2d98938e10252de87f_NormalProcess_[2023-08-30 06.02.12.211].txt *
* Log Version: 1.4.5.0                                                                               *
* Log Size: 780.00 B                                                                                 *
* Log Date: 08/30/2023 06:02:12                                                                      *
******************************************************************************************************
START--------------------------------------------------------------------------------------------START

Log Date: 08/30/2023 06:02:12
Log Message: Launched without arguments
Caller Details: [CallerFileName: App.xaml.cs, CallerMemberName: ParseActivationArgumentsAsync, CallerLineNumber: 261]

Log Date: 08/30/2023 06:02:20
Log Message: AppCenter initialization success and enabled
Caller Details: [CallerFileName: App.xaml.cs, CallerMemberName: OnLaunched, CallerLineNumber: 181]

END------------------------------------------------------------------------------------------------END

******************************************************************************************************
* Log Name: Log_1.4.5.0_734ad9a74a444eecb33f2f2ca2af8d02_NormalProcess_[2023-08-30 06.02.11.759].txt *
* Log Version: 1.4.5.0                                                                               *
* Log Size: 592.00 B                                                                                 *
* Log Date: 08/30/2023 06:02:11                                                                      *
******************************************************************************************************
START--------------------------------------------------------------------------------------------START

Log Date: 08/30/2023 06:02:12
Log Message: Launched with arguments: ""C:\Users\我的用户名\AppData\Local\Microsoft\WindowsApps\RX-Explorer-WAS.exe" --Mode SystemTrayHostProcess"
Caller Details: [CallerFileName: App.xaml.cs, CallerMemberName: ParseActivationArgumentsAsync, CallerLineNumber: 287]

END------------------------------------------------------------------------------------------------END
`

我不懂，但是推测后台在预览之类的出了错误。因为发现右键一些不支持内部查看的视频格式不会出错。

**Comment by zhuxb711** [comment]
右键菜单导致的崩溃的话，可能是框架本身不稳定的崩溃，或者是你有些程序用了实现不规范的右键菜单项，导致RX读取的时候访问违例崩溃

**Comment by yaira2** [comment]
@zhuxb711 we were able to fix this in Files by filtering out `Cast to device`.

**Comment by zhuxb711** [comment]
> @zhuxb711 we were able to fix this in Files by filtering out `Cast to device`.

Seems `Cast to device` do not crash RX-Explorer from myside

**Comment by yaira2** [comment]
It wasn't consistent and even in Files it'll sometimes work, but we disabled it by default just to be safe.

**Comment by zhuxb711** [comment]
> It wasn't consistent and even in Files it'll sometimes work, but we disabled it by default just to be safe.

Thanks I also found that might lead to AVE, RX-Explorer (WAS) already filter that context menu out in the latest release, thanks for the information~🙂
