### ISSUE TITLE
[bug]右键,二级菜单背景颜色显示异常

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#458]
<img width="586" alt="image" src="https://github.com/zhuxb711/RX-Explorer/assets/62456287/7fcdcc48-27bc-4f06-a40d-a0a6b2f7f826">

**Comment by zhuxb711** [comment]
这是一个已知框架问题
https://github.com/microsoft/microsoft-ui-xaml/issues/8756

**Comment by zhuxb711** [comment]
解决方案：在RX中使用深色主题时，系统主题也应当设置为深色主题

**Comment by zhuxb711** [comment]
此问题已由WAS框架1.4.1更新解决，将包含在下一次更新中
