### ISSUE TITLE
[问题]微软商店更新后有错误警告

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#459]
![2023-10-14 08-50-17](https://github.com/zhuxb711/RX-Explorer/assets/62456287/1e674aaf-7cff-461c-8c98-5e02e04f5829)

**Comment by zhuxb711** [comment]
怎么触发的

**Comment by a15355447898a** [comment]
微软商店更新完,然后就有这个弹窗了
两台电脑都可以复现
不过看起来rx文件管理器可以正常用?

**Comment by a15355447898a** [comment]
只在更新完后自己弹出来了一次(这时候没启动软件),启动软件并没有弹窗
刚刚在虚拟机尝试了一下,重新安装并没有遇到这个弹窗,可能只有更新这个操作才能复现

**Comment by zhuxb711** [comment]
这应当是正常现象，该问题由初始化共享Windows App SDK框架引发，因为RX希望于初始化后立即重启，可能部分设计不合理导致无法找到自身的exe文件。该问题不会影响后续启动。

该问题不会修复，因为仅1.5.1更新临时启用了共享Windows App SDK框架，1.5.2更新时会重新切换回独占Windows App SDK框架，相关初始化共享Windows App SDK的代码将不会保留。1.5.1时怀疑Windows App SDK独占框架存在严重问题因而临时切换到共享框架，这只是短暂的一阵子而已，现在独占框架相关问题已经解除。

Tips: 
1. 共享框架通过Microsoft Store自动更新，会实时更新最新版本Windows App SDK，同时新版本尚未经过开发者测试，可能引入新的bug进而导致应用崩溃。每次启动需检查并执行初始化代码，框架可以独自被用户卸载进而导致所有依赖应用崩溃。但优势是该框架是共享框架，经过预热启动速度更快。
2. 独占框架是每个应用程序自己带一个Windows App SDK框架，该框架是应用私有的，因此除非开发者主动发布应用更新否则这个随附的框架不会自动更新，相对来说可以更加稳定的工作，不会被微软在新版本中埋的雷炸翻。框架不可被独立卸载，因此不存在潜在的用户骚操作风险。缺点是启动速度较慢框架未预热，应用安装包较大。
