### ISSUE TITLE
卸载后WIN+E提示explore.exe找不到应用程序

### ISSUE THREAD

**Issue by jotyy** [zhuxb711/RX-Explorer#46]
如问题所述

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/97827944-9e6bc300-1d00-11eb-9756-78ffa27948f3.png)
请详细阅读开启WIN+E功能时的说明，若您已经卸载了RX文件管理器，只需要重新安装并重复开启、关闭操作即可
