### ISSUE TITLE
[问题]打开属性窗口后关闭,主窗口的背景直接变成纯黑

### ISSUE THREAD

**Issue by a15355447898a** [zhuxb711/RX-Explorer#460]
![截图_20231104130903](https://github.com/zhuxb711/RX-Explorer/assets/62456287/52ae05ee-5518-4265-9e3f-932437a8d3da)

**Comment by zhuxb711** [comment]
该问题调查完毕并已内部修复，同时解决了与该问题相关联的可能导致崩溃的问题
