### ISSUE TITLE
卸载之后原来的资源管理器打不开

### ISSUE THREAD

**Issue by DianeDii** [zhuxb711/RX-Explorer#47]
![image](https://user-images.githubusercontent.com/48173189/98432454-6813b680-20f9-11eb-99d6-8ba336004c87.png)

![image](https://user-images.githubusercontent.com/48173189/98432461-7530a580-20f9-11eb-8e0f-d5bf986a2200.png)

**Comment by zhuxb711** [comment]
卸载前必须关闭Win+E功能，如关闭无效，请更新至最新版5.6.1版本再次开启Win+E后再关闭即可
