### ISSUE TITLE
希望可以增加分组功能

### ISSUE THREAD

**Issue by HernandoR** [zhuxb711/RX-Explorer#48]
我正在使用一个统一的download文件夹用于绝大多数文件的下载路径，可见地，这个文件夹将会按修改时间由近到远排序并经常使用。

然而，如同其他人在一些相似地时候会遇到的，我并不希望 某些上次修改时间在一个月或更久前的文件 被删除或整理，但同时文件、文件夹的增多会影响到该download文件夹的使用。

我认为可以如windows相似地，添加“分组”的功能，以便于在较大的文件夹中将不同类别或创建时间或修改时间的文件分隔开，便于使用
![image](https://user-images.githubusercontent.com/45709656/99179474-1b635780-2759-11eb-896f-9d4882566c19.png)

**Comment by zhuxb711** [comment]
如果RX使用分组功能，则ListView的虚拟化容器将失效，这可能导致在浏览大型文件夹的时候的卡顿，这也是为什么RX一直未采用分组设计的原因

**Comment by zhuxb711** [comment]
在最新版本中请使用详细列表视图来筛选文件的显示，替代分组功能
