### ISSUE TITLE
Product recommendations

### ISSUE THREAD

**Issue by Fantasylun** [zhuxb711/RX-Explorer#49]
**I hope the author can add the search engine of Everything in the search engine, so that it can be more efficient**

**Comment by zhuxb711** [comment]
But how should UWP integrate with Everything?

**Comment by Fantasylun** [comment]
如果不考虑集成,能否在外部调用

**Comment by zhuxb711** [comment]
与Everything的集成已于5.7.4版本中上线，并于5.8.1版本中获得改进，感谢您的建议
