### ISSUE TITLE
希望可以支援繁體中文

### ISSUE THREAD

**Issue by aunight** [zhuxb711/RX-Explorer#5]
很棒的應用程式 感謝製作
希望也能有繁體中文的版本

**Comment by zhuxb711** [comment]
Hello, 您能否提供相关翻译帮助？

**Comment by aunight** [comment]
可以的有語言檔嗎?

**Comment by zhuxb711** [comment]
[RX_Explorer.zip](https://github.com/zhuxb711/RX-Explorer/files/5009703/RX_Explorer.zip)

请下载压缩包
首先安装MultilingualAppToolkit.msi

随后使用安装好的软件打开RX_Explorer.zh-Hant.xlf

上方是英文原文，下方填写翻译后的内容，确保翻译完成后右侧的状态为“翻译”
![image](https://user-images.githubusercontent.com/42038175/89091936-19f76480-d3e0-11ea-97ec-6fc03a64f50f.png)

![image](https://user-images.githubusercontent.com/42038175/89091951-35626f80-d3e0-11ea-9aea-ecccdf677658.png)

有一些特殊的地方要提请您注意，凡是内容中存在"\r"的部分，请予以保留。如下图所示
![image](https://user-images.githubusercontent.com/42038175/89091973-63e04a80-d3e0-11ea-844c-f4f5bde6ad0f.png)


您只需要完成翻译并将翻译后的文件发送给我，即可让RX文件管理器支持繁体中文~~~😀

**Comment by aunight** [comment]
好的感謝

**Comment by aunight** [comment]
[RX_Explorer.zh-Hant.zip](https://github.com/zhuxb711/RX-Explorer/files/5010126/RX_Explorer.zh-Hant.zip)
翻譯完成可能會還有點小錯誤

**Comment by zhuxb711** [comment]
感谢您的翻译，目前观察到的小错误我将自行更正，无需麻烦您了。
"中文(繁體)"的支持将于下一版本中到来。届时若存在翻译得不太到位的情况，请及时通知我，感谢~

**Comment by aunight** [comment]
好的 感謝
名稱：秋夜AuNight

**Comment by zhuxb711** [comment]
v5.2.0已发布
