### ISSUE TITLE
win10 20h2版本，设置了win+e但未生效

### ISSUE THREAD

**Issue by sifenglib** [zhuxb711/RX-Explorer#50]
win10 20h2版本，设置了win+e但未生效，是否还有其它的操作？还希望给个操作说明会好一些

**Comment by zhuxb711** [comment]
您可以根据以下指南来手动尝试设置WIN+E功能：
https://github.com/zhuxb711/RX-Explorer/issues/27#issuecomment-692418152

**Comment by sifenglib** [comment]
这个是存在的

![image](https://user-images.githubusercontent.com/61527672/99234019-f9d49f80-282e-11eb-9bcf-edd1fd9513a5.png)

**Comment by sifenglib** [comment]
按了之后还是打开的系统的资源管理器

**Comment by zhuxb711** [comment]
按理来说应该是可以的，可能你的电脑有些与众不同？有在其他电脑上试过吗？

**Comment by sifenglib** [comment]
我找到问题所在点了，因为之前装了QTTabBar，导致这个快捷键未生效，现在把这个工具卸载之后可以了，谢谢指导。

**Comment by zhuxb711** [comment]
好的OK
