### ISSUE TITLE
卸载之后explorer.exe找不到，影响到我工作了，重装系统才解决，码农哥们，别着急开发，让测试好好测一下

### ISSUE THREAD

**Issue by licsman** [zhuxb711/RX-Explorer#51]
- 卸载之后explorer.exe找不到，影响到我工作了，重装系统才解决，码农哥们，别着急开发，让测试好好测一下
- 安全域存在大bug，换软件还是能打开加密的
- 在文件夹右键不能git以及其他复杂的操作

**加油，祝愿你们越来越好**

![image](https://user-images.githubusercontent.com/33518125/99632683-9473ef00-2a78-11eb-9d55-a7d4582b6213.png)

**Comment by licsman** [comment]
version:1909家庭版

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/99687195-55b55780-2abf-11eb-9480-30eca678f41e.png)

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/99687293-7382bc80-2abf-11eb-9ce7-f6e75a70784a.png)

**Comment by XSH-Hero** [comment]
明明有提示让你卸载前先关闭“WIN＋E”，并且说了重新安装RX并启用WIN＋E再禁用即可

**Comment by XSH-Hero** [comment]
明明有提示让你卸载前先关闭“WIN＋E”，并且说了重新安装RX并启用WIN＋E再禁用即可解决

**Comment by XSH-Hero** [comment]
重装系统可还行。。。

**Comment by XSH-Hero** [comment]
要记得看提示啊。。。

**Comment by zhuxb711** [comment]
安全域默认是复制并加密，看好多人都不太明白这是怎么回事，我以后干脆改成移动并加密好了(也就是添加到安全域的东西只是复制，因此原来的也还在的，真正加密的是提取不到的)
