### ISSUE TITLE
请问可以在github的release页面提供离线安装包吗

### ISSUE THREAD

**Issue by a-little-cat** [zhuxb711/RX-Explorer#52]
希望在公司电脑上用,公司断网..
可以用fiddler等工具抓包下载,但是不太优雅..

**Comment by zhuxb711** [comment]
您可以前往Azure PipeLine下载最新的编译包。
如：
https://dev.azure.com/zhuxb711/RX-Explorer/_build/results?buildId=96&view=artifacts

在这里：
<img width="793" alt="屏幕截图 2020-11-20 101156" src="https://user-images.githubusercontent.com/42038175/99749118-d5bbdb80-2b18-11eb-97a3-7f15eea83de0.png">

**Comment by a-little-cat** [comment]
多谢
