### ISSUE TITLE
软件出现奔溃

### ISSUE THREAD

**Issue by wxy-cloud** [zhuxb711/RX-Explorer#53]
使用的是20H2版本
错误信息如下：
------------------------------------
AdditionalComment: UnhandleException
------------------------------------
Exception: System.ArgumentException: 参数错误。

参数错误。

Message:
        参数错误。
        参数错误。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: LeadToBlueScreen
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\LogTracer.cs
        CallerLineNumber: 129
------------------------------------

**Comment by zhuxb711** [comment]
此问题是由于微软官方UWP框架引发的问题，最近微软再次更新了UWP框架(上次是今年3月份)，看看能不能解决问题。由于这是微软框架的问题我也无法修复~

**Comment by zhuxb711** [comment]
请确认5.7.1版本中是否仍然存在此问题，自5.7.0版本后更新了最新的UWP框架

**Comment by zhuxb711** [comment]
由于您未回应，则自动认为此问题已被解决

**Comment by wxy-cloud** [comment]
抱歉，并没有给我带来便利，不在使用了，万分抱歉。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ruofan"<notifications@github.com&gt;; 
发送时间: 2020年12月4日(星期五) 晚上7:00
收件人: "zhuxb711/RX-Explorer"<RX-Explorer@noreply.github.com&gt;; 
抄送: "似水流年"<285604864@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhuxb711/RX-Explorer] 软件出现奔溃 (#53)





 
由于您未回应，则自动认为此问题已被解决

**Comment by zhuxb711** [comment]
感谢您的使用，RX将不断完善自身
