### ISSUE TITLE
希望增加常规的Windows资源管理器功能，而不是只有一个多标签支持

### ISSUE THREAD

**Issue by kppomzh** [zhuxb711/RX-Explorer#54]
1. 拖动框选多个文件
2. 右键菜单整合，例如用压缩软件解压iso文件，或者我会用TortoiseGit一类的软件
3. Windows Terminal并不能真正的在当前文件夹下打开终端，还是在home目录

**Comment by zhuxb711** [comment]
1.框选将于下个版本上线
2.右键菜单已整合，但尚不完全，正在调查
3.经测试，Windows Terminal可以正常在当前文件夹中打开，如果不能，请自行在设置中编辑终端配置

**Comment by silentmoooon** [comment]
右键Windows Terminal 能不能再搞个子选择框让选择用什么方式打开,比如powershell   wsl之类的.
能自动检测最好 或者可以在设置里设置也行.
