### ISSUE TITLE
考虑在Release中加入.Msixbundle包吗?

### ISSUE THREAD

**Issue by lingting-gzm** [zhuxb711/RX-Explorer#55]
我的 win10 store 一直打不开,   很喜欢rx的界面, 今天挣扎了一下, 还是没有把store修复, 然后发现 files 的 release中有.Msixbundle可以直接安装,我就用了, 但我还是希望rx能在release中添加 .Msixbundle,方便像我这样无法使用store的用户
<a href="https://github.com/files-community/Files/releases" >files release</a>

**Comment by zhuxb711** [comment]
其实RX的源代码每天都会由Azure Pipeline编译，您可以直接在首页点击Azure Pipeline的图标就可以去找到最新版本下载。
当然我之后再发布新版本的时候会加上侧加载包到Release上去的

**Comment by lingting-gzm** [comment]
> 其实RX的源代码每天都会由Azure Pipeline编译，您可以直接在首页点击Azure Pipeline的图标就可以去找到最新版本下载。
> 当然我之后再发布新版本的时候会加上侧加载包到Release上去的

嗯嗯~我去看看

**Comment by zhuxb711** [comment]
https://github.com/zhuxb711/RX-Explorer/issues/52#issuecomment-730800403
