### ISSUE TITLE
不能解锁打开BitLocker保护的盘

### ISSUE THREAD

**Issue by LoRyu** [zhuxb711/RX-Explorer#56]
不能解锁打开BitLocker保护的盘
希望能添加这个功能

![} 5$VS6TMCR)294YBHIYQK](https://user-images.githubusercontent.com/51251337/99957294-6f59e600-2dc2-11eb-94a2-c1bf21d79053.png)

![_Q0SOH@@V6ZE4XUN%3O%30H](https://user-images.githubusercontent.com/51251337/99957341-839de300-2dc2-11eb-8f57-593fddf3926f.png)

**Comment by zhuxb711** [comment]
是的，该功能尚不支持~但有计划在以后提供支持

**Comment by zhuxb711** [comment]
版本5.7.4已发布并包含解锁Bitlocker的功能
