### ISSUE TITLE
使用体验

### ISSUE THREAD

**Issue by RedCarl** [zhuxb711/RX-Explorer#57]
软件在打开与关闭的时候,希望能做到与Windows资源管理器无差别的响应,比如取消开启软件时的那个LOGO界面,取消关闭软件的提示(关闭会丢失数据啥的)
我希望这款软件能真的融入Windows

有很多地方用起来让我感觉这款软件只是界面和动画很好看，其余的都很鸡肋

比如右键解压 压缩，我希望能兼容一下市面上的部分压缩包软件，能够更快捷的使用压缩包

**Comment by zhuxb711** [comment]
您可以自行设定某种类型的文件采用哪种程序打开，因此您也可以将某个压缩软件设置为默认打开方式，RX自身的解压压缩仅支持Zip文件。

RX会在一下情况中弹出关闭软件可能丢失数据的提示：
1.RX正在与辅助进程通信，尤其是以下情况：文件相关操作等，此时强行关闭RX将会导致文件操作中止，可能导致文件缺失或不完整（复制或移动了一半）
2.RX正在处理耗时任务，如正在压缩、转码等，此时不应该关闭RX

如果您确定您能够正确处理上述情形可能带来的问题，可以点击立即关闭按钮，但对于大多数用户来说，此提示可以防止误操作。

**Comment by zhuxb711** [comment]
下一版本中RX将能够获取全部文件关联应用，敬请期待
