### ISSUE TITLE
报错:  找不到动态链接库

### ISSUE THREAD

**Issue by i-curve** [zhuxb711/RX-Explorer#58]
![image](https://user-images.githubusercontent.com/40533808/100043839-3153d500-2e49-11eb-8bbc-a7f7a7335bda.png)

在任意分区下右键首先会报出这个错误，可以确定的是这个文件是没有问题的，VM也是正常的

**Comment by XYGR** [comment]
同上我也遇到这个问题

**Comment by zhuxb711** [comment]
请更新至5.7.0以查看是否仍然存在此问题

**Comment by XYGR** [comment]
![image](https://user-images.githubusercontent.com/43074851/100330667-3b710180-300a-11eb-8a24-8e4f30caaddc.png)
已经更新至5.7.0仍有这个bug

**Comment by i-curve** [comment]
我的不报错了:smile:

**Comment by i-curve** [comment]
顺便更新下vm看看吧,我的vm更新到16.1了

**Comment by i-curve** [comment]
仍旧有这个问题

**Comment by zhuxb711** [comment]
真奇怪，但是有个有同样问题的小同学正在帮我调查此问题，康康有木有啥结果

**Comment by zhuxb711** [comment]
自5.9.0版本开始，设置中提供选项以关闭获取系统右键菜单，如果此功能存在问题需要关闭的，可以关闭设置中的“扩展右键菜单”选项。导致此问题的具体原因尚不清楚。
