### ISSUE TITLE
特定配置下，右键菜单的颜色渲染异常

### ISSUE THREAD

**Issue by sirlis** [zhuxb711/RX-Explorer#59]
环境：win10 2004

操作：
- 个性化：【动画效果】-禁用，【关闭初始动画】-勾选，【模式】-纯色-白色。
- 右键任意文件或文件夹，有小概率出现深色背景的右键菜单，原因未知。

![无标题](https://user-images.githubusercontent.com/12960298/100304146-13b57580-2fd9-11eb-914f-f826cfa01cf8.png)

![1](https://user-images.githubusercontent.com/12960298/100304797-7fe4a900-2fda-11eb-91b0-d22a8ff8b584.gif)

**Comment by lingting-gzm** [comment]
最新版本有这个问题

**Comment by zhuxb711** [comment]
微软官方控件BUG----->我早就提交了相关的[issue](https://github.com/microsoft/microsoft-ui-xaml/issues/3373#issue-715271367)

**Comment by lingting-gzm** [comment]
> 微软官方控件BUG----->我早就提交了相关的[issue](https://github.com/microsoft/microsoft-ui-xaml/issues/3373#issue-715271367)

惨... 没有回应了...

**Comment by zhuxb711** [comment]
我看到有人说是因为这个控件有一些奇妙的问题比如   这个变成灰色的问题其实是   微软把这个控件的阴影绘制到了最上面....

**Comment by sirlis** [comment]
> 我看到有人说是因为这个控件有一些奇妙的问题比如 这个变成灰色的问题其实是 微软把这个控件的阴影绘制到了最上面....

emmmmm 这很微软

**Comment by zhuxb711** [comment]
已于Win11中修复
