### ISSUE TITLE
無法取得CD設備權限

### ISSUE THREAD

**Issue by aunight** [zhuxb711/RX-Explorer#6]
![image](https://user-images.githubusercontent.com/52199445/88989131-7dfd2880-d30d-11ea-8abd-fc28cd9a5f85.png)
如圖每次打開必會出現
求解決方法 感謝

**Comment by zhuxb711** [comment]
该CD设备是否装载了文件（即RX报错的时候能否通过系统文件管理器访问）？
您可以尝试一下放入任意光盘后再打开RX，是否提示消失？

**Comment by aunight** [comment]
裝了CD仍然顯示相同的的提示

**Comment by zhuxb711** [comment]
该情况是由于RX无法访问对应的设备造成的，由于我这里无法复现，我将尝试看看如何解决此问题

**Comment by zhuxb711** [comment]
最新版本已提供开关关闭相关提示
