### ISSUE TITLE
能否将显示隐藏文件的选项分开

### ISSUE THREAD

**Issue by xzsk2** [zhuxb711/RX-Explorer#60]
资源管理器中隐藏文件分为系统隐藏文件和普通隐藏文件

![image](https://user-images.githubusercontent.com/20642596/100338751-f5b93680-3013-11eb-8461-51d79475a669.png)

能否在RX中也将这两类隐藏文件分离成两个开关单独控制

**Comment by zhuxb711** [comment]
显示隐藏文件和文件夹的功能已于5.8.1版本中上线
