### ISSUE TITLE
releases 中的证书不受信任

### ISSUE THREAD

**Issue by lingting-gzm** [zhuxb711/RX-Explorer#61]
我已经通过手动信任解决此问题,  不过我觉得还是应该处理一下.  当然 ,只是建议,

**Comment by zhuxb711** [comment]
侧加载应用（指绕过微软应用商店安装的UWP版本）是属于开发测试版本，故是不被信任的，这是微软的安全机制。所有开发者的包在提交微软应用商店后由微软统一签署微软的证书，这样才会被系统信任。因此侧载包自带的测试证书不可能受系统信任，故需要导入证书（目录下的install.ps1也可以一键安装）

**Comment by lingting-gzm** [comment]
> 侧加载应用（指绕过微软应用商店安装的UWP版本）是属于开发测试版本，故是不被信任的，这是微软的安全机制。所有开发者的包在提交微软应用商店后由微软统一签署微软的证书，这样才会被系统信任。因此侧载包自带的测试证书不可能受系统信任，故需要导入证书（目录下的install.ps1也可以一键安装）

明白了
