### ISSUE TITLE
弹出u盘时崩溃

### ISSUE THREAD

**Issue by lingting-gzm** [zhuxb711/RX-Explorer#62]
下面是导出的错误日志
[Export_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/5603278/Export_Error_Log.txt)

就结果来看,不影响使用(除了需要重启); 即便崩溃,u盘也依旧弹出来了

**Comment by zhuxb711** [comment]
该问题已被确认，将于5.7.1版本中修复，感谢您的报告。

此问题于以下条件得到满足时触发：
1. 任意标签页已进入过文件呈现页面
2. 进入过文件呈现页面的标签页需返回主界面
3. 弹出USB设备

**Comment by zhuxb711** [comment]
版本5.7.1已修复此问题
