### ISSUE TITLE
:bug:  tab1 正在执行动作时(删除), 其他tab无法弹出右键菜单, 等tab1动作执行完成时, 会一次性弹出所有菜单

### ISSUE THREAD

**Issue by lingting** [zhuxb711/RX-Explorer#63]
一次性弹出所有菜单  指: tab1 执行动作时, 我右键单击多少次, 弹出多少次右键菜单

![6thk7-c0nx5](https://user-images.githubusercontent.com/59352063/100358630-63c02680-3031-11eb-9812-5451df242c6e.gif)

**Comment by zhuxb711** [comment]
严格的来说这并非是一个BUG，而是刻意设计。

如今RX大部分文件操作都已交由辅助进程来完成，而辅助进程按顺序执行所请求的操作（同一个进程中的所有标签页共享一个辅助进程），因此一个标签页执行的操作卡住时将会影响其他标签页。

没有采用所有标签页都启动一个辅助进程是出于性能和内存占用的最优化的考虑，但尽管文件操作需要排队，但仍然出现这种诡异的情况实属不应该，我将于5.7.1版本中进行更改以使得如果有任何任务正在进行中，则不再获取系统右键标签页，这样可以防止右键菜单被阻止弹出

**Comment by lingting-gzm** [comment]
> 严格的来说这并非是一个BUG，而是刻意设计。
> 
> 如今RX大部分文件操作都已交由辅助进程来完成，而辅助进程按顺序执行所请求的操作（同一个进程中的所有标签页共享一个辅助进程），因此一个标签页执行的操作卡住时将会影响其他标签页。
> 
> 没有采用所有标签页都启动一个辅助进程是出于性能和内存占用的最优化的考虑，但尽管文件操作需要排队，但仍然出现这种诡异的情况实属不应该，我将于5.7.1版本中进行更改以使得如果有任何任务正在进行中，则不再获取系统右键标签页，这样可以防止右键菜单被阻止弹出



> 严格的来说这并非是一个BUG，而是刻意设计。
> 
> 如今RX大部分文件操作都已交由辅助进程来完成，而辅助进程按顺序执行所请求的操作（同一个进程中的所有标签页共享一个辅助进程），因此一个标签页执行的操作卡住时将会影响其他标签页。
> 
> 没有采用所有标签页都启动一个辅助进程是出于性能和内存占用的最优化的考虑，但尽管文件操作需要排队，但仍然出现这种诡异的情况实属不应该，我将于5.7.1版本中进行更改以使得如果有任何任务正在进行中，则不再获取系统右键标签页，这样可以防止右键菜单被阻止弹出

或许可以添加一个配置, 让用户自己决定
1: 单进程所有标签页使用一个辅助进程
2: 每个标签页使用单独辅助进程

**Comment by zhuxb711** [comment]
您能否帮助提交一个PR来完成这个改进？这个问题暂时还没有计划，但改动起来应该不太难。对于目前的情况，请考虑使用多进程来完成并行任务

**Comment by lingting-gzm** [comment]
> 您能否帮助提交一个PR来完成这个改进？这个问题暂时还没有计划，但改动起来应该不太难。对于目前的情况，请考虑使用多进程来完成并行任务

抱歉, 我不会C#, 不过我可以找人试试, 您继续按照自己的计划来,这个配置的问题不重要

**Comment by zhuxb711** [comment]
开始做这个特性之后，发现并不是很容易就能够扩展为多标签页多实例。但很高兴的宣布，经过大量的底层变化之后，多标签页多辅助进程将随6.0.0版本一起到来~

**Comment by zhuxb711** [comment]
6.0.0已添加此特性，但由于一些调度问题，已停止发布并将由6.0.1替代
