### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by lingting-gzm** [zhuxb711/RX-Explorer#64]
操作:
1. 打开N层文件夹(N < 5)
2. 单击某个文件或文件夹
3. 按下字母搜索文件或文件夹
4. 卡住 -> 崩溃
以下是 log
[Export_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/5605933/Export_Error_Log.txt)

**Comment by lingting-gzm** [comment]
操作:
1. 打开文件
2. 按下字母h
3. 卡住 -> 崩溃
[Export_Error_Log.txt](https://github.com/zhuxb711/RX-Explorer/files/5605938/Export_Error_Log.txt)

猜测, 正在加载文件夹内容时,按下字母搜索会崩溃.

**Comment by zhuxb711** [comment]
请在5.7.1版本中确认是否仍然存在此问题。谢谢~
