### ISSUE TITLE
Suggestion to make Custom Quick access

### ISSUE THREAD

**Issue by Rikopara** [zhuxb711/RX-Explorer#66]
Hi.
Just downloaded RX Explorer, but find out terrible issue: There's no any way to pin folders for fast access. I always use quick access 'cause it's safes A LOT of my time. 
Also it's pretty strange that I can unpin folders in default library, but no way to pin another folder instead.
If you just make button for pinning folders, you'll be the best.
Thanks in advance!

**Comment by zhuxb711** [comment]
Just right-click the empty space of "Library" and you will found add button～

**Comment by Rikopara** [comment]
Thanks, this worked, but I think you should increase size of field with Add button. All upper empty space isn't clickable and 2/3 of bottom space too. This red rectangles shows up how much space that very intuitive to click just do nothing. 
Anyway, thanks for help!
![image](https://user-images.githubusercontent.com/48817751/100514246-17d1c680-3184-11eb-93b6-4717223705df.png)
