### ISSUE TITLE
建议将每个目录的布局模式和排序方式相互独立

### ISSUE THREAD

**Issue by Vixb1122** [zhuxb711/RX-Explorer#68]
自带文件资源管理器目前就是相互独立的。
具体参考：https://github.com/files-community/Files/issues/530

**Comment by zhuxb711** [comment]
暂时不知道会不会去实现这个功能，按说这个功能应该不复杂，但是考虑到RX有对应的优化（即：如果你不切换视图模式，则对应的控件将不会进行初始化），如果每个文件夹不同视图模式，则此优化将毫无意义，因为此优化能够得益的基础就是用户较少切换视图模式，如果进行更改，则有较大概率每次启动都会变更模式。

**Comment by Vixb1122** [comment]
可以提供该功能并加个开关吗，因为一些目录确实需要按照修改日期降序，每次进入这些目录都要手动点一下修改日期。
自带文件资源管理器应该是读写每个目录下的desktop.ini来实现的。

**Comment by zhuxb711** [comment]
我相信如果RX实现此功能的话是会利用数据库来记录的吧，但是最近我一直在忙于隐藏文件夹支持(当前版本尚不支持访问隐藏文件夹)，这个功能先放着等我完成当前的功能再来看，当然您要是有意向提交PR也是很欢迎的

**Comment by zhuxb711** [comment]
Hi，我抽时间实现了此功能了，预计于下一个版本中发布
