### ISSUE TITLE
希望能在当前路径中开启资源管理器。如:Rx-explorer .

### ISSUE THREAD

**Issue by i-curve** [zhuxb711/RX-Explorer#69]
自带的资源管理器可以很方便的用 **explorer.exe** .  在当前路径下启动资源管理器

希望能够增加这个命令行中启动的功能

**Comment by zhuxb711** [comment]
一直都可以，命令行输入RX-Explorer.exe

**Comment by i-curve** [comment]
不行的，我说的不是打开。我指的是后面还有一个点就能表示当前命令行路径下打开。

比如我命令行的位置是在桌面，那么rx-explorer .就能直接打开并直接进入桌面了

**Comment by i-curve** [comment]
我试过了, 是无法识别那个点的, 可以加一个路径, 但是不能用哪个点

**Comment by i-curve** [comment]
![image](https://user-images.githubusercontent.com/40533808/102709811-aef3ef00-42e8-11eb-9329-5d556f3fe240.png)

**Comment by i-curve** [comment]
![image](https://user-images.githubusercontent.com/40533808/102709849-01351000-42e9-11eb-85e9-7da8f437a8d2.png)
就像自带的这样

**Comment by zhuxb711** [comment]
命令行启动时未对 "." 参数作任何特殊处理，因此无法正确识别。
下一版本中将加入对 “.” 参数的处理以在当前工作目录打开
