### ISSUE TITLE
全透明的背景感覺有點辣眼睛

### ISSUE THREAD

**Issue by aunight** [zhuxb711/RX-Explorer#7]
希望能自定義文件欄位 如同mac的finder為實底 
閱覽上會更加清晰
其他地方則可以照舊為透明模式

**Comment by zhuxb711** [comment]
推荐模式下，根据不同场景，确实是会产生一些阅读问题。全局亚克力效果是为了保持风格的一致性。

但您可以尝试使用其他模式，包括自定义模式中的-“Acrylic模式”或者“自定义图片模式”，配合更改字体颜色，可以让显示更加清晰。

Acrylic模式中，您可以自行调节RX文件管理器的背景“透光度”和“透明度”，可以很好的解决无法阅读的相关问题。

**Comment by aunight** [comment]
但是仍希望與windows 10的fluent design趨同 體驗也會更良好

**Comment by zhuxb711** [comment]
不太希望一众UWP文件管理器都太过同质化，还是保留一些特色比较好~~~~

**Comment by aunight** [comment]
好的我尊重你的決定

**Comment by zhuxb711** [comment]
感谢您的谅解和支持~
