### ISSUE TITLE
安全域问题

### ISSUE THREAD

**Issue by alboert** [zhuxb711/RX-Explorer#70]
原来的文件无法导出，新文件无法导入，原因可能是：我导入的文件比较大，所以将SecureFolder文件夹链接到了D盘，软件跟新后就无法导出了，恢复之后还是无法导出和导入，重现安装之后还是同样的问题；

错误日志：
*************************
LogDate: 2020/12/22 15:17:59
*************************
﻿------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (5): 拒绝访问。

Message:
        拒绝访问。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: CheckContainsAnyItem
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 685
------------------------------------

------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。

Message:
        系统找不到指定的文件。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: GetStorageItem
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 1243
------------------------------------

------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。

Message:
        系统找不到指定的文件。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: GetStorageItem
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 1243
------------------------------------

------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。

Message:
        系统找不到指定的文件。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: GetStorageItem
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 1243
------------------------------------

------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (5): 拒绝访问。

Message:
        拒绝访问。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: CheckContainsAnyItem
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 685
------------------------------------

------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。

Message:
        系统找不到指定的文件。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: CheckExist
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 717
------------------------------------

------------------------------------
AdditionalComment: An error was threw when importing file
------------------------------------
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RX_Explorer.Class.Extention.GetHash[T](String) + 0x7a
   at RX_Explorer.SecureArea.get_EncryptionAESKey() + 0x1e
   at RX_Explorer.SecureArea.<AddFile_Click>d__19.MoveNext() + 0x56b

Message:
        Object reference not set to an instance of an object.

StackTrace:
        at RX_Explorer.Class.Extention.GetHash[T](String) + 0x7a
        at RX_Explorer.SecureArea.get_EncryptionAESKey() + 0x1e
        at RX_Explorer.SecureArea.<AddFile_Click>d__19.MoveNext() + 0x56b

Extra info: 
        CallerMemberName: AddFile_Click
        CallerFilePath: D:\a\1\s\RX_Explorer\View\SecureArea.xaml.cs
        CallerLineNumber: 396
------------------------------------

------------------------------------
AdditionalComment: An error was threw when importing file
------------------------------------
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RX_Explorer.Class.Extention.GetHash[T](String) + 0x7a
   at RX_Explorer.SecureArea.get_EncryptionAESKey() + 0x1e
   at RX_Explorer.SecureArea.<Grid_Drop>d__20.MoveNext() + 0x505

Message:
        Object reference not set to an instance of an object.

StackTrace:
        at RX_Explorer.Class.Extention.GetHash[T](String) + 0x7a
        at RX_Explorer.SecureArea.get_EncryptionAESKey() + 0x1e
        at RX_Explorer.SecureArea.<Grid_Drop>d__20.MoveNext() + 0x505

Extra info: 
        CallerMemberName: Grid_Drop
        CallerFilePath: D:\a\1\s\RX_Explorer\View\SecureArea.xaml.cs
        CallerLineNumber: 477
------------------------------------

------------------------------------
AdditionalComment: <Empty>
------------------------------------
Exception: System.ComponentModel.Win32Exception (5): 拒绝访问。

Message:
        拒绝访问。

StackTrace:
        Unknown

Extra info: 
        CallerMemberName: CheckContainsAnyItem
        CallerFilePath: D:\a\1\s\RX_Explorer\Class\WIN_Native_API.cs
        CallerLineNumber: 685
------------------------------------

*************************
LogDate: 2020/12/22 15:22:20
*************************
﻿------------------------------------
AdditionalComment: An error was threw when importing file
------------------------------------
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RX_Explorer.Class.Extention.GetHash[T](String) + 0x7a
   at RX_Explorer.SecureArea.get_EncryptionAESKey() + 0x1e
   at RX_Explorer.SecureArea.<AddFile_Click>d__19.MoveNext() + 0x56b

Message:
        Object reference not set to an instance of an object.

StackTrace:
        at RX_Explorer.Class.Extention.GetHash[T](String) + 0x7a
        at RX_Explorer.SecureArea.get_EncryptionAESKey() + 0x1e
        at RX_Explorer.SecureArea.<AddFile_Click>d__19.MoveNext() + 0x56b

Extra info: 
        CallerMemberName: AddFile_Click
        CallerFilePath: D:\a\1\s\RX_Explorer\View\SecureArea.xaml.cs
        CallerLineNumber: 396
------------------------------------

**Comment by zhuxb711** [comment]
请问您的PC是基于X64或者X86架构嘛？
该问题的根源仍不清楚，新版本的GetHash函数利用了新的反射技术，可能存在一些问题，我会继续跟进此问题~

**Comment by zhuxb711** [comment]
已更换Hash函数的实现方式并避免使用反射，预计可以解决此问题

**Comment by alboert** [comment]
64位的，cpu：I7-10875h，没开发过pc软件，对HashMap倒是比较熟
