### ISSUE TITLE
右键弹出的信息出现位置可能看不到

### ISSUE THREAD

**Issue by i-curve** [zhuxb711/RX-Explorer#72]
**严重影响了使用**  

当右键的条目比较多时，他出现的位置可能会在屏幕之外。无论怎么移动窗口或者是否缩放，都无法出现在屏幕内部。

例子：
比如，这是一个正常的图片右键后出现的条目。
![image](https://user-images.githubusercontent.com/40533808/103220133-755f5b80-495a-11eb-9b5b-b7478e7bb370.png)

当本文件夹下有一些其他内容时
![image](https://user-images.githubusercontent.com/40533808/103220252-c40cf580-495a-11eb-833d-67225075e58f.png)

注意： 此时已经下拉到屏幕最底部了。再下面的部分是不会出现的。

**严重影响了使用**

**Comment by zhuxb711** [comment]
如何复现？在我这里完全正常
![image](https://user-images.githubusercontent.com/42038175/103290506-b02dc600-4a24-11eb-9e1e-3dc5d0073f0d.png)

**Comment by i-curve** [comment]
找个以右键中条目比较多文件右键的就会超出屏幕了。

**Comment by i-curve** [comment]
我这里图片右键中的条目比较多

**Comment by i-curve** [comment]
![image](https://user-images.githubusercontent.com/40533808/103334424-2f1a1180-4aac-11eb-9b8c-b0b59bd741bb.png)
系统自带的右键后弹出的内容最顶部是会自动变化的，因此始终能够在屏幕内看到所有条目。
但是这个的话右键弹出框的顶部是鼠标的位置是持平的
![image](https://user-images.githubusercontent.com/40533808/103334575-d8610780-4aac-11eb-85f0-9db524d68bc3.png)
因此，当要查看的文件位置偏下一点并且条目内容偏多的话， 就会出现一部分内容超出屏幕了

**Comment by zhuxb711** [comment]
这个问题应该是微软控件库的问题，暂时无法修复，预计5.9.0版本中会提供关闭获取系统右键菜单的功能

**Comment by i-curve** [comment]
不是，主要就是希望能让那个右键弹出的**位置智能**一点。
**和自带的做个对比**
屏幕下边时:
![image](https://user-images.githubusercontent.com/40533808/104194152-e5daa200-545b-11eb-8773-3e504593ff29.png)
屏幕上边时:
![image](https://user-images.githubusercontent.com/40533808/104193994-b3c94000-545b-11eb-89a7-500587a1ea12.png)

- **注意**: 截的图像是整个屏幕的高度

**Comment by zhuxb711** [comment]
Sorry，这个问题暂时无解，右键菜单项的弹出位置被微软设计为固定模式，无法根据大小来重新布局。

**Comment by i-curve** [comment]
恩
