### ISSUE TITLE
远程桌面不能复制文件至RX管理器

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#73]
RT
![copy](https://user-images.githubusercontent.com/41459054/103391466-a0150400-4b54-11eb-8f2e-4fea9c763af1.gif)

**Comment by zhuxb711** [comment]
由于缺少可用的远程虚拟机，故无法进行相关测试，尚不清楚具体原因，其他UWP软件可以接受远程桌面的拖拽操作嘛？

**Comment by FlyingDragon0420** [comment]
没测其他UWP软件，虚拟机本地就能创建，vmware就行

**Comment by silentmoooon** [comment]
可以用内置的windows sandbox测

**Comment by zhuxb711** [comment]
测了，UWP平台无法支持此类文件操作，因为这种文件操作没有对应的路径可用，UWP平台无法为RX提供相应的文件对象，从而报出异常，此问题应该无法修复。

**Comment by silentmoooon** [comment]
用fulltrust做应该可以吧.

**Comment by zhuxb711** [comment]
#130 已解决该问题
