### ISSUE TITLE
建议覆盖安装保留配置

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#74]
建议覆盖安装保留配置，要不每次升级都得设置一遍~

**Comment by zhuxb711** [comment]
只要你不卸载重装，升级都是保留配置的。
(如果你指的是“默认打开方式”没保留的问题，那个是BUG)

**Comment by FlyingDragon0420** [comment]
测加载版5.8.1升级5.8.7，设置没保存，文件夹和库配置没保存

**Comment by zhuxb711** [comment]
测加载仅供测试，因此微软可能设计上没有允许保留配置，请安装商店版本

**Comment by zhuxb711** [comment]
5.9.0已可以导出配置文件
