### ISSUE TITLE
建议删除绕过回收站变成配置项

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#75]
建议删除绕过回收站变成配置项
![image](https://user-images.githubusercontent.com/41459054/103401688-d5d1e100-4b84-11eb-8ff0-2f1a24554760.png)

**Comment by zhuxb711** [comment]
您可以按住Shift并点击删除键即可跳过此窗口

**Comment by FlyingDragon0420** [comment]
一般删除的习惯是一致的，要跳过回收站就都会跳过，弄个记录上次选择也挺好，提高易用性

**Comment by zhuxb711** [comment]
Surprise ! 突然准备上线
