### ISSUE TITLE
win+e还是不能默认打开rx资源管理器

### ISSUE THREAD

**Issue by q19484** [zhuxb711/RX-Explorer#76]
有谁知道咋回事不  我win+e还是自动默认打开默认的资源管理器

**Comment by zhuxb711** [comment]
参考: https://github.com/zhuxb711/RX-Explorer/issues/27#issuecomment-692418152

**Comment by q19484** [comment]
> 参考：[＃27（评论）](https://github.com/zhuxb711/RX-Explorer/issues/27#issuecomment-692418152)

我想说试了下他的方法还是不行

**Comment by zhuxb711** [comment]
在某些电脑上确实会始终无法使用Win+E启动(无论手动处理或者自动处理)，原因不明，无法修复
