### ISSUE TITLE
当rx处于最小化时，右键任务栏图标，关闭窗口没有反应，必须点击图标退出最小化状态时才会关闭

### ISSUE THREAD

**Issue by oxygen-dioxide** [zhuxb711/RX-Explorer#78]
1.打开rx文件管理器，等待界面加载完成
2.最小化窗口
3.在任务栏的rx文件管理器图标上右键，关闭窗口，没有反应
4.再单击rx文件管理器图标以退出最小化状态，rx文件管理器关闭。

其他uwp软件（MIcrosoft Todo, Angry Birds 2, Windows自带邮件、计算器）和自带文件管理器均没有此问题，任务栏右键关闭时会立即关闭
（其实这并不影响体验，如果不好实现可以直接关闭我的issue）

**Comment by zhuxb711** [comment]
[参考讨论](https://github.com/microsoft/ProjectReunion/issues/59)
事实上这是一个已知问题，RX具备关闭确认功能，但是微软将这个功能设计为应用最小化时不可用，因此最小化时您点击关闭并不会通知到RX，而是等待您再次显示RX时才会收到通知

**Comment by zhuxb711** [comment]
该问题是由于微软导致的问题，由于无法修复此问题，我将关闭此issue，抱歉
