### ISSUE TITLE
如何让文件夹快捷方式在rx文件管理器中打开？

### ISSUE THREAD

**Issue by oxygen-dioxide** [zhuxb711/RX-Explorer#79]
在rx文件管理器中双击一个文件夹快捷方式(lnk)，会在系统自带文件管理器中打开这个文件夹，必须右键选择“打开文件所在位置”才会在rx文件管理器中打开。如何使文件夹快捷方式默认在rx管理器中打开？

**Comment by zhuxb711** [comment]
这是一个BUG，RX未能正确区分两种快捷方式，此问题将于下一版本中修复。
