### ISSUE TITLE
希望側邊欄能增加原檔案管理器 快速存取的功能

### ISSUE THREAD

**Issue by aunight** [zhuxb711/RX-Explorer#8]
希望側邊欄能更加實用
能夠收藏文件夾 將固定至主介面的文件夾放在側邊欄內

**Comment by zhuxb711** [comment]
文件夹应当固定至“库”的区域，左侧侧边栏是用于存放网页或其他应用程序的

**Comment by zhuxb711** [comment]
下一版本中，左侧侧边栏将支持直接添加Win32传统应用，因此还是推荐您将文件固定至“文件夹和库区域”

**Comment by aunight** [comment]
好的個人認為這樣會更實用 平常常用快速存取的功能

**Comment by aunight** [comment]
因為文件夾庫區域只能從主頁面選擇 操作起來不如側邊欄方便
