### ISSUE TITLE
关于用其他软件打开的一个建议

### ISSUE THREAD

**Issue by i-curve** [zhuxb711/RX-Explorer#81]
资源管理器中有些文件是要用其他的软件打开的。  
但是发现当用其他软件打开的时候，那个打开的软件是隐藏到了资源管理器后面，不知道能不能把那个软件给调到资源管理器前面。  
因为很多时候资源管理器都是全屏或者占屏幕很大的比重，而我还习惯把最下面的任务栏给自动隐藏，这样就会导致打开某一个软件的时候很费事。
例子：
比如我用typora打开a.md
![image](https://user-images.githubusercontent.com/40533808/104197527-16243f80-5460-11eb-8f4e-e87e27db82ad.png)
我希望的结果是：
![image](https://user-images.githubusercontent.com/40533808/104197565-250af200-5460-11eb-9db9-d215fa66afe9.png)
弹出来的软件要在rx-explorer上方。  

<hr>
我的天，我创建a.md文件的时候突然发现新建文件时候，就只能创建那么几种类型的文件。强烈建议把这个给拿掉。
![image](https://user-images.githubusercontent.com/40533808/104197891-84690200-5460-11eb-98dc-4bff177c098e.png)

**Comment by zhuxb711** [comment]
所以拿掉之后就彻底不能创建任何文件了？[滑稽] 这不是因噎废食嘛。
另外UWP不接受窗口Z轴调度，故无法将窗口置于底层，除非微软给API，否则该问题无法解决

**Comment by i-curve** [comment]
文件后缀为什么要限制只能创建那么几种形式的。  
用户不能创建个任意后缀类型的文件？

**Comment by zhuxb711** [comment]
新建文件窗口并不限制你用什么后缀，只是不保证可以正常使用，RX当作创建空白文件去做。另外那个选项也没有卡死，是可以编辑的

**Comment by i-curve** [comment]
恩
