### ISSUE TITLE
Suggestion: pt-BR translate

### ISSUE THREAD

**Issue by Alissonfm** [zhuxb711/RX-Explorer#82]
If you want a hand, i can help you translate from english to portuguese...

**Comment by zhuxb711** [comment]
Sure~
Intall the .msi and translate .xlf
Then send .xlf back to me

[RX_Explorer.zip](https://github.com/zhuxb711/RX-Explorer/files/5802925/RX_Explorer.zip)

**Comment by zhuxb711** [comment]
RX updates are fast, and translations may need to be updated frequently. Are you willing to provide follow-up translation support?

**Comment by zhuxb711** [comment]
You can send translation files to me or directly submit PR to update the translation in Portuguese

**Comment by zhuxb711** [comment]
Closed for no response.
