### ISSUE TITLE
安装VMware 后，在rx文件管理器文件夹内空白右键会弹出提示窗

### ISSUE THREAD

**Issue by YangsonHung** [zhuxb711/RX-Explorer#83]
![image](https://user-images.githubusercontent.com/32238889/104547715-2ad42380-566a-11eb-8657-3fb95b150317.png)

VMware版本：15.0.4 build-12990004

**Comment by WankkoRee** [comment]
同样情况+1

**Comment by zhuxb711** [comment]
建议前往设置中关闭“扩展右键菜单”选项，此问题无法解决，该弹窗是Windows自己弹出来的

**Comment by Sayor0630** [comment]
> It is recommended to turn off the Extend right-click menu option in Settings, an issue that cannot be resolved and which is played out by Windows itself

How to?

**Comment by zhuxb711** [comment]
@Sayor0630 Actually I don't know why it will pop up the error tip. For the time being. you could prevent this from switch off "Extent context menu* in settings

**Comment by Sayor0630** [comment]
> @Sayor0630 Actually I don't know why it will pop up the error tip. For the time being. you could prevent this from switch off "Extent context menu* in settings

ok. But your explorer is great!

**Comment by zhuxb711** [comment]
可以等6.0.5版本发布后查看一下是否解决了该问题

**Comment by Sayor0630** [comment]
I think this issue is resoved
