### ISSUE TITLE
FullTrustProcess.exe - Ordinal Not Found

### ISSUE THREAD

**Issue by Sayor0630** [zhuxb711/RX-Explorer#84]
When I Right-Click on my mouse in a drive, this error occurs. Also, I can't format my drive! here is a screenshot.
![image](https://user-images.githubusercontent.com/77576588/105316310-e35e1200-5bea-11eb-981a-86aed5d6cfb0.png)

**Comment by zhuxb711** [comment]
This issue should be Solved
