### ISSUE TITLE
How can I make RX explorer as default explorer?

### ISSUE THREAD

**Issue by Sayor0630** [zhuxb711/RX-Explorer#85]
When I download something or from the task manager, when I click show in folder, that file opens in windows explorer. But how can I make this RX explorer default to open with this RX explorer?

**Comment by zhuxb711** [comment]
Sorry, you can't. 

Because the Windows Explorer still manages some locations that RX cannot manage, such as the "Control Panel", so it cannot be set as the default explorer. Use Win+E instead. 

Besides, you could launch RX-Explorer in Windows Explorer 's context menu.

**Comment by Sayor0630** [comment]
> Sorry, you can't.
> 
> Because the Windows Explorer still manages some locations that RX cannot manage, such as the "Control Panel", so it cannot be set as the default explorer. Use Win+E instead.
> 
> Besides, you could launch RX-Explorer in Windows Explorer 's context menu.

ooh. ok
