### ISSUE TITLE
新建文件或文件夹、重命名文件或文件夹，Enter不能确认名称

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#88]
新建文件或文件夹、重命名文件或文件夹，Enter不能确认名称

**Comment by zhuxb711** [comment]
Enter确认名称确实是没有，我搞一搞，但是赶不上下一个版本了，5.9.7版本已经提交并正在审核

**Comment by zhuxb711** [comment]
已于6.0.0版本中解决该问题，但其已停止发布，6.0.1版本修复了其中一些问题，正在发布中

**Comment by FlyingDragon0420** [comment]
6.3.1版本，功能失效，回车不能确认

**Comment by zhuxb711** [comment]
不是功能失效，Enter键确认可能会导致一些问题，故移除
