### ISSUE TITLE
.msi类型的安装程序是不是无法运行？

### ISSUE THREAD

**Issue by i-curve** [zhuxb711/RX-Explorer#89]
安装go的时候，发现.msi的安装文件类无法运行。  

貌似上次别的程序也没运行成功。必须在系统资源管理器上才能运行。

**Comment by zhuxb711** [comment]
目前的RX并未添加对msi文件的特别识别，但添加此类文件的处理很容易，下一版本中将添加msi文件的识别

**Comment by zhuxb711** [comment]
Fixed by 6.0.0
