### ISSUE TITLE
在RX中打开word文件不友好

### ISSUE THREAD

**Issue by DianeDii** [zhuxb711/RX-Explorer#9]
在RX中点击一个word文档，打开方式只有默认的一个记事本，我也不知道我的word启动程序在哪里，希望能优化。：）

**Comment by aunight** [comment]
如果你的電腦裡有word的話應該就能選擇開啟的軟件

**Comment by zhuxb711** [comment]
RX应当能够自动侦测关联程序。若此处不存在Microsoft Word，则说明您可能未将其设置默认关联。

**Comment by DianeDii** [comment]
谢谢，第一次打开的时候没有显示，然后我关闭RX，再次尝试打开文件的时候就出来了。作者很棒:)

**Comment by zhuxb711** [comment]
ok😉那我关这个Issue了
