### ISSUE TITLE
tar.gz文件无右键解压菜单

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#91]
![image](https://user-images.githubusercontent.com/41459054/105964382-10b03180-60bd-11eb-9a84-218c084d02c6.png)
tar.gz文件无右键解压菜单

**Comment by zhuxb711** [comment]
目前RX仅支持Zip格式，对于tar.gz的支持尚不清楚是否有合适的辅助组件可以用

**Comment by silentmoooon** [comment]
不如直接加载系统菜单得了,一般都会装第三方压缩工具

**Comment by zhuxb711** [comment]
其实可以右键选择打开方式，把第三方压缩文件设置为默认，然后你以后直接双击打开就行了
