### ISSUE TITLE
解压建议增加选项

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#92]
![image](https://user-images.githubusercontent.com/41459054/105964732-90d69700-60bd-11eb-94dd-e9ad09f4d628.png)
建议增加解压到当前文件夹解压和解压到目录的选项

**Comment by zhuxb711** [comment]
其实我不是很清楚这几个选项有什么区别

**Comment by FlyingDragon0420** [comment]
解压到当前文件夹直接解压内容至当前目录，不会创建文件夹，解压到“domain_count”会创建domain_count文件夹，再将内容解压至该目录
