### ISSUE TITLE
启动时能不能恢复标签？

### ISSUE THREAD

**Issue by klxq520** [zhuxb711/RX-Explorer#93]
平时使用会固定打开几个文件夹在不同标签里，每次启动都要重新打开这些文件夹有些繁琐，能不能下次更新下哈？

**Comment by zhuxb711** [comment]
这个可能没有那么快上线，我正在忙于其他优先级更高的底层变动

**Comment by zhuxb711** [comment]
此功能将于下一个版本中上线
