### ISSUE TITLE
右键拓展菜单的图标问题

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#94]
右键拓展菜单的图标倒过来了。

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/106078517-857f7c00-614e-11eb-9f41-3bd7b417c440.png)
就像这样

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/106078588-a051f080-614e-11eb-87c7-a523c8f93285.png)
就像这样

**Comment by zhuxb711** [comment]
这个问题就贼搞笑了，RX依赖的一个组件在某次更新之后把这些Icon颠倒过来了，并且RX自5.9.7版本采用了它的简化实现(在此之前RX自己实现了一套逻辑)，换装新的组件之后就翻车了233333，正在联系组件作者修复，并且RX也会推出临时的解决方案（再给它转180°）

**Comment by zhuxb711** [comment]
Fixed by 6.0.0
