### ISSUE TITLE
RX内置文本编辑器问题

### ISSUE THREAD

**Issue by XSH-Hero** [zhuxb711/RX-Explorer#96]
现在内置文本编辑器打开中文的文本文档时会出现乱码，切换编码格式也没用，希望修复。

**Comment by XSH-Hero** [comment]
![image](https://user-images.githubusercontent.com/69738882/106223923-54ba4800-621d-11eb-956a-7a855c3fb7d8.png)
![image](https://user-images.githubusercontent.com/69738882/106223976-68fe4500-621d-11eb-8ea6-e332658ea27f.png)

**Comment by XSH-Hero** [comment]
就像上面这样，怎么样都不能正常显示中文

**Comment by XSH-Hero** [comment]
我记得以前是可以显示的

**Comment by zhuxb711** [comment]
你编码格式都没调对，自然显示不出来中文啊。
自己在编码格式中手动输入GBK

**Comment by XSH-Hero** [comment]
哦哦，好的，但一般人并不一定知道要输入GBK，希望能加入GBK这个选项

**Comment by zhuxb711** [comment]
RX提供所有系统默认的选项，不能确保一定能够适配到编码(毕竟编码那么多)。
其实UTF8和Unicode编码可以解析中文，只是要求你文本必须是这两种编码才行。文本用GBK编码的话是无法自动探测到的，GBK是国标编码，不是国际通用编码，所以必须手动输入编码格式类型，如果可能，RX将根据您输入的编码来解析

**Comment by XSH-Hero** [comment]
哦，行吧
