### ISSUE TITLE
无法打开samba映射驱动器

### ISSUE THREAD

**Issue by chengl404** [zhuxb711/RX-Explorer#97]
无法在驱动器窗口中显示网络驱动器；
以文件夹方式添加到“文件夹和库”中后，打开后为空文件夹。

**Comment by zhuxb711** [comment]
由于RX所依赖的微软API不支持网络驱动器，故无法支持Smb网络驱动器，抱歉

**Comment by zhuxb711** [comment]
预计RX将于下一个版本中支持非本机文件夹，在本地映射为网络驱动器的盘符
