### ISSUE TITLE
目录侧边栏移动后，点击回收站再点击这台电脑，侧边栏无法恢复

### ISSUE THREAD

**Issue by FlyingDragon0420** [zhuxb711/RX-Explorer#98]
目录侧边栏移动后，点击回收站再点击这台电脑，侧边栏无法恢复
![bug](https://user-images.githubusercontent.com/41459054/106426685-04531c80-64a1-11eb-84b4-d0e329591b71.gif)

**Comment by zhuxb711** [comment]
此问题已于6.0.0版本中解决
