### ISSUE TITLE
切换标签栏动画

### ISSUE THREAD

**Issue by taooceros** [zhuxb711/RX-Explorer#99]
想问一下，切换标签栏（及第一次打开文件夹）的时候会有一个景深的动画，但是会先停顿一下，再放大。
个人感觉这样有一些延迟，是否可以取消掉这个延迟直接放大？
同时，这个动画不可以被设置里的动画禁用给关掉

**Comment by zhuxb711** [comment]
此效果已经过优化并已纳入动画设置的管辖范围

**Comment by taooceros** [comment]
感谢

**Comment by zhuxb711** [comment]
版本6.0.1已发布
